type Spec={slug:string;title:string;excerpt:string;keyword:string;scene:string;record:string;owner:string;check:string};
const date='2026-09-08' as const;
const thumbnails:Record<string,string>={
  'ap-invoice-version-control-log':'/blog-thumbnails/ap-invoice-receipt-index.svg',
  'ap-credit-memo-resolution-ownership-queue':'/blog-thumbnails/ap-credit-memo-follow-up-workflow.svg',
  'ap-vendor-statement-balance-bridge':'/blog-thumbnails/ap-vendor-statement-open-items.svg',
  'ap-tax-code-exception-register':'/blog-thumbnails/invoice-coding-review-checklist.svg',
  'ap-approval-delegation-expiry-review':'/blog-thumbnails/ap-finance-support-access-review.svg',
  'ap-payment-file-transmission-log':'/blog-thumbnails/payment-run-preparation-controls.svg',
  'ap-receiving-unit-of-measure-check':'/blog-thumbnails/ap-receiving-report-follow-up.svg',
  'ap-invoice-split-allocation-workpaper':'/blog-thumbnails/ap-invoice-coding-exception-log.svg',
  'ap-supplier-refund-tracking-register':'/blog-thumbnails/ap-cash-application-support.svg',
  'ap-recurring-invoice-variance-review':'/blog-thumbnails/ap-invoice-data-quality-checks.svg',
  'ap-closed-period-posting-exception-log':'/blog-thumbnails/ap-monthly-close-checklist.svg',
  'ap-queue-reassignment-handoff-note':'/blog-thumbnails/ap-remote-ap-handoff-checklist.svg',
};
const specs:Spec[]=[
{slug:'ap-invoice-version-control-log',title:'Keep invoice versions from becoming silent replacements',excerpt:'Preserve the original invoice, every corrected copy, and the reason one version moved forward.',keyword:'invoice version control log',scene:'A supplier sends a corrected invoice under the same number after the first copy has entered approval',record:'file hashes, received times, sender, invoice number, changed fields, workflow status, linked credit, reviewer response, and chosen version',owner:'invoice approval owner',check:'replay unchanged resends, corrected totals, new bank text, replaced attachments, credits, and disputed versions'},
{slug:'ap-credit-memo-resolution-ownership-queue',title:'Build a credit memo resolution queue finance can replay',excerpt:'Match credits to open items without letting queue maintenance become an accounting decision.',keyword:'credit memo resolution ownership queue',scene:'A supplier credit names an old invoice while the statement points to a different open balance',record:'credit document, supplier and entity, currency, referenced invoices, open items, correspondence, proposed match, decision, posting, and residual balance',owner:'accounting owner',check:'include exact references, partial credits, cross-entity items, disputed invoices, refunds, duplicates, and unapplied balances'},
{slug:'ap-vendor-statement-balance-bridge',title:'Explain statement-to-ledger differences with a balance bridge',excerpt:'Turn a supplier statement mismatch into named reconciling items, evidence, and next actions.',keyword:'vendor statement balance bridge',scene:'The supplier statement is higher than the AP ledger even though every visible invoice appears entered',record:'statement cutoff and balance, ledger extract, opening balance, invoices, credits, payments, timing items, disputed lines, owner, and closing reconciliation',owner:'reconciliation reviewer',check:'test missing invoices, payments in transit, unapplied credits, prior-period items, currency differences, and duplicate lines'},
{slug:'ap-tax-code-exception-register',title:'Route invoice tax-code exceptions without guessing',excerpt:'Give AP preparers a clear stop point when source documents and configured tax treatment do not align.',keyword:'invoice tax-code exception register',scene:'An invoice line carries tax wording that conflicts with the purchase order and the normal supplier setup',record:'source invoice, entity, jurisdiction fields, PO, supplier record, configured code, observed conflict, questions, tax-owner response, posting, and correction history',owner:'tax or accounting policy owner',check:'cover missing tax, mixed lines, exemptions, credits, foreign suppliers, changed registrations, and unclear place-of-supply evidence'},
{slug:'ap-approval-delegation-expiry-review',title:'Review invoice approval delegations before they linger',excerpt:'Track who may approve, why the delegation exists, and when temporary authority must end.',keyword:'approval delegation expiry review',scene:'A holiday delegation remains active weeks after the original approver returned',record:'delegator, delegate, scope, authority source, start and end dates, system role, approvals used, review result, revocation event, and exceptions',owner:'approval-policy or system owner',check:'sample active, expired, overlapping, emergency, departed-user, unlimited, and unused delegations'},
{slug:'ap-payment-file-transmission-log',title:'Make payment-file transmission separately auditable',excerpt:'Connect the approved proposal, exported file, secure transfer, bank receipt, and final acceptance without exposing credentials.',keyword:'payment file transmission log',scene:'A bank portal shows two uploads while the payment-run folder contains only one approved export',record:'proposal ID, file hash and count, export time, transmitter, approved channel, upload event, bank acknowledgment, rejection, replacement file, and final status',owner:'treasury payment owner',check:'include accepted files, rejected formats, repeated uploads, changed totals, partial acceptance, timeouts, and cancelled runs'},
{slug:'ap-receiving-unit-of-measure-check',title:'Check unit-of-measure mismatches before invoice routing',excerpt:'Show when quantities cannot be compared cleanly across the invoice, PO, and receipt.',keyword:'receiving unit-of-measure check',scene:'The invoice bills cases, the purchase order uses eaches, and the receipt records pallets',record:'invoice line, PO line, receipt, displayed units, approved conversion source, quantities, calculation, variance, requester response, and reviewer decision',owner:'procurement or receiving owner',check:'test exact units, approved conversions, missing factors, pack-size changes, partial receipts, service lines, and rounding'},
{slug:'ap-invoice-split-allocation-workpaper',title:'Document split invoice allocations as a reviewable workpaper',excerpt:'Keep allocation inputs, calculations, evidence gaps, and accounting approval in one traceable packet.',keyword:'invoice split allocation workpaper',scene:'A shared-service invoice must be divided across entities but the current headcount file is incomplete',record:'invoice and period, allocation rule source, population, excluded records, calculation version, entity results, rounding, exception, accounting approval, and posting references',owner:'management accounting owner',check:'cover complete inputs, missing entities, changed drivers, credits, rounding, prior-period adjustments, and rejected allocations'},
{slug:'ap-supplier-refund-tracking-register',title:'Track supplier refunds until cash and ledger agree',excerpt:'Separate a supplier promise, bank receipt, cash application, and final AP closure.',keyword:'supplier refund tracking register',scene:'A supplier says a duplicate payment was refunded, but the bank receipt has no useful remittance reference',record:'claim basis, supplier, entity, amount and currency, correspondence, promised date, bank evidence, receipt identification, application decision, posting, and remaining balance',owner:'cash or accounting owner',check:'test promised, overdue, partial, netted, misdirected, unidentified, disputed, and fully applied refunds'},
{slug:'ap-recurring-invoice-variance-review',title:'Review recurring invoice changes without treating history as approval',excerpt:'Compare repeat bills consistently while keeping contract and accounting decisions with named owners.',keyword:'recurring invoice variance review',scene:'A familiar monthly invoice rises slightly and adds a new service description',record:'current invoice, prior comparison set, contract or order, amount and line changes, frequency, entity, explanation, exception, owner response, and approval outcome',owner:'budget or invoice approval owner',check:'include stable bills, price increases, new lines, credits, skipped periods, duplicate months, and supplier changes'},
{slug:'ap-closed-period-posting-exception-log',title:'Keep a separate log for invoices touching closed periods',excerpt:'Preserve timing evidence and route period decisions without reopening or backdating work informally.',keyword:'closed-period posting exception log',scene:'A late invoice describes work completed in a period the ledger now shows as closed',record:'invoice receipt, service or delivery evidence, entity, amount, requested period, system status, prior accrual or estimate, accounting response, posting period, and correction',owner:'financial close owner',check:'sample late invoices, prior accruals, credits, immaterial items, disputed service dates, reopened periods, and rejected requests'},
{slug:'ap-queue-reassignment-handoff-note',title:'Use a handoff note when AP queue ownership changes',excerpt:'Prevent reassignment from stripping away source links, promises, aging context, and the next required action.',keyword:'AP queue reassignment handoff note',scene:'An analyst changes roles while supplier questions and approval chases remain open',record:'queue scope, item IDs, current facts, source links, last action, outstanding promise, exception age, next action, new owner acceptance, access gaps, and closure',owner:'AP operations manager',check:'cover planned leave, termination, workload balancing, entity transfer, urgent items, rejected ownership, and missing access'},
];
const sections=(s:Spec)=>[
 {title:`Define the evidence boundary for the ${s.keyword}`,paragraphs:[`${s.scene}. Start by naming the queue, entity, cutoff, authoritative systems, and the event that opens the record.`, `Retain ${s.record}. A blank or disputed field should stay visible; it should not be repaired from memory.`]},
 {title:'Give preparation and decision-making different owners',paragraphs:[`An outsourced AP specialist can gather approved evidence, compare observable fields, update factual status, and route the exception. The ${s.owner} retains policy, judgment, approval, system change, and payment authority.`, `Write the next action in ordinary language and preserve earlier states when the answer changes.`]},
 {title:'Test the awkward cases before calling it routine',paragraphs:[`Ask a second reviewer to rebuild the result from the retained packet, without an oral briefing. For acceptance, ${s.check}.`, `If two reviewers reach different classifications, repair the instruction, source hierarchy, access, example, or escalation rule before increasing volume.`]},
];
export const sep8BlogPosts=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:8}));
export const sep8BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,thumbnail:thumbnails[s.slug],shortAnswer:`Use a source-linked ${s.keyword}, preserve uncertainty, and leave decisions with the ${s.owner}.`,sections:sections(s),faqs:[{question:`What may outsourced AP do with this ${s.keyword}?`,answer:`Support may collect approved records, compare observable fields, maintain factual status, and route exceptions. The ${s.owner} keeps judgment and authorization.`},{question:'What proves the handoff works?',answer:`Retain ${s.record}, then ${s.check}.`}]}]));
