import type {Draft} from './blog-oct2-batch';
const oct5BlogPublicationDate = '2026-10-06';

type Input = {
  slug:string; title:string; excerpt:string; keyword:string; thumbnail:string;
  shortAnswer:string; headings:string[]; paragraphs:string[]; checklist:string[];
  links:{href:string;label:string}[]; faqs:{question:string;answer:string}[];
};

const sources = [
  {name:'GAO Standards for Internal Control in the Federal Government',url:'https://www.gao.gov/greenbook',note:'Authoritative framework for transaction evidence, assigned responsibility, review, and corrective action.'},
  {name:'NIST least privilege glossary',url:'https://csrc.nist.gov/glossary/term/least_privilege',note:'Supports limiting maintenance, approval, and payment actions to authorized roles.'}
];

const finalSections:Record<string,{title:string;paragraphs:string[]}> = {
  'service-entry-sheet-rejection-invoice-hold':{title:'Test the handoff on a realistic rejection',paragraphs:[
    'Use a worked case before making the lane routine. A supplier bills a monthly service, but the entry sheet covers five weeks and the owner rejects it with only "incorrect period." The packet should retain the rejected sheet, divide the contract schedule from the invoice demand, identify the four-week supported period, and ask whether the supplier must rebill or the owner should approve a corrected sheet. It should also show whether the fifth week belongs to the next cycle. This example tests period evidence, correction authority, invoice handling, and cutoff without letting AP declare that any week was performed.',
    'Review quality by inspecting whether another preparer can find the rejection reason, source agreement, service evidence, open decision, responsible owner, and final system result without private messages. Check that paragraphs and attachments describe the same dates and amounts. A long note is not useful when it buries the decision. The handoff is ready when it distinguishes an unsupported service from a routing defect, keeps both rejected and corrected records, and produces one traceable outcome for the invoice rather than several disconnected workflow attempts.'
  ]},
  'invoice-withholding-tax-evidence-handoff':{title:'Use an evidence matrix for mixed invoices',paragraphs:[
    'A mixed invoice is a useful test. Suppose it contains professional services, reimbursed travel, and separately stated indirect tax for one service period. The evidence matrix should preserve those lines, identify the contract basis and location facts for each, and show candidate calculations without deciding which amounts belong in the withholding base. It should point out missing supplier documentation and a prior specialist decision that covered services but not expenses. The tax owner then receives a bounded set of questions instead of a worksheet that quietly treats every line the same.',
    'Audit the handoff by comparing its facts with the source invoice and its approved result with the ERP. Every amount in the calculation must trace to a source line or a named owner decision. Every sensitive supplier document must remain in the controlled repository. Sample cases where the specialist changed the proposed base, rate, or entity, since those reveal whether AP preserved uncertainty honestly. A strong process reduces repeated fact gathering while avoiding the dangerous appearance that the preparation team issued tax advice.'
  ]},
  'supplier-legal-name-invoice-mismatch':{title:'Test identity controls with close variants',paragraphs:[
    'Use several realistic variants when reviewing the procedure: a trading name over the correct identifier, a missing corporate suffix, a branch with a different registration, a recent merger, and an invoice addressed to the wrong buyer entity. The expected action should differ for each case. The trading name may need documented acceptance, the branch may require another vendor record, and the wrong buyer may require a corrected invoice. If the workflow sends every variant to a simple master-name edit, it is not protecting entity identity.',
    'Measure completion by evidence quality rather than the number of names standardized. A reviewer should see the invoice fields, verified supplier response, controlled identity sources, vendor-owner decision, effective date, and final posting account. Compare the new record with open invoices and payment data so a name correction does not strand prior obligations or redirect them. Recheck any account that shares branding with the changed supplier. This final review helps ensure that a legitimate clarification does not become an undocumented merge or payment-data change.'
  ]},
  'supplier-credit-balance-refund-request':{title:'Test the packet against a partial refund',paragraphs:[
    'Consider a balance made of a duplicate payment, an unrelated credit memo, and a small open invoice. The supplier agrees to refund only the duplicate payment. The packet should prove that component independently, leave the credit memo available for its approved disposition, and avoid deducting the open invoice unless finance authorizes netting. When cash arrives short because the supplier deducted a bank fee, keep the fee as a residual with a finance decision. This example tests whether the roll-forward survives a resolution that does not clear the whole account.',
    'Review closed cases for false closure. Compare the requested refund, supplier remittance, bank receipt, ledger clearing, and ending account balance. Search for a second open item created when cash was posted to the wrong vendor or entity. Confirm that refund instructions came from the controlled treasury path and that the supplier contact was verified independently. The packet succeeds when each originating item has its own disposition and the final balance can be reproduced, even when the answer is not zero.'
  ]},
  'subscription-renewal-invoice-owner-review':{title:'Work through a departed-requester case',paragraphs:[
    'Suppose the employee who bought a yearly analytics tool has left, the invoice uses the reseller name, and six active users sit in two departments. The review should connect reseller, product, tenant, contract, and renewal date; identify the current system administrator; and ask the cost owners who can accept the next term. It should compare licensed seats with the approved renewal quantity without claiming that login activity proves need. If the cancellation window has passed, procurement or legal decides the response. AP still needs a valid owner decision before treating the bill as routine.',
    'After disposition, inspect the next operational event. A paid renewal should have a named owner and future review date. A cancellation should have supplier confirmation, access or transition ownership, and monitoring for a credit or later bill. A downsized renewal should match the corrected invoice and purchase record. Keep the old approval and new decision linked so next year’s reviewer does not infer perpetual authority. This turns an orphaned invoice into a controlled subscription record instead of another annual search through old email.'
  ]},
  'utility-invoice-site-account-mismatch':{title:'Reconcile a site transition case',paragraphs:[
    'A site transition may produce a final bill for the old meter, an opening bill for a replacement meter, and a landlord recharge covering common areas. Build three separate lines in the review even if one provider statement presents them together. Match service dates to occupancy, meter exchange evidence, and the approved lease responsibility. Show overlapping dates and prior balances explicitly. Facilities must confirm physical service, and finance must decide entity and allocation treatment. AP should not assign the full statement to the new cost center simply because that code is active today.',
    'Verify closure by checking the provider account after posting. The old account should show its supported final balance or credit, the new account should begin with the documented read, and the landlord charge should retain its allocation authority. Confirm that autopay or recurring invoice settings do not remain attached to a closed account. Review the next bill for continuity. This follow-through catches cases where the invoice was coded correctly once but the master, template, or provider record still points to the wrong site.'
  ]},
  'erp-migration-duplicate-invoice-screening':{title:'Challenge the screen with transition-window cases',paragraphs:[
    'Test the review on a legacy invoice paid after the conversion extract, a converted open item with a generated target number, a supplier rebill received in both inboxes, and a legitimate split by buyer entity. Each case needs a different result. The payment case relies on settlement evidence, the generated number relies on the crosswalk, the dual intake case relies on file and transaction identity, and the entity split relies on commercial source detail. A rule that blocks all four because amount and supplier match would suppress valid obligations as well as duplicates.',
    'At the end of stabilization, reconcile candidate dispositions to both systems and the target ledger. Confirm that every reversal or block has owner approval and that the surviving invoice retains its order, receipt, approval, and payment chain. Preserve the legacy lookup method for later supplier inquiries. Report unresolved crosswalk gaps to migration ownership with document-level evidence. The screen is effective when it explains why each candidate is the same or different obligation, not when it simply produces a large list of possible matches.'
  ]},
  'corporate-card-central-bill-allocation':{title:'Use a statement case with disputes and late reports',paragraphs:[
    'A useful test statement includes an employee report submitted after cutoff, a foreign-currency purchase, a returned item with a credit on the next cycle, a provisional dispute credit, and a cardholder who has left. Reproduce the issuer total first, then give each item its own evidence and owner. The late report becomes a timing item, the currency charge retains issuer conversion, the return stays linked across cycles, and the dispute remains open until final. Departure changes follow-up ownership but does not make the transaction disappear.',
    'Inspect the cycle after payment as well. Tie the bank settlement to the issuer account, confirm any direct debit did not create a second payment, and roll unresolved items to the next review with stable identifiers. Compare the expense-system posting with the issuer data to find duplicate imports or missing credits. Managers should see only the transactions within their scope. This final control keeps statement payment punctual without pretending that every employee exception was solved merely because treasury settled the central account.'
  ]},
  'invoice-approval-after-cost-center-reorganization':{title:'Test the route across the transition date',paragraphs:[
    'Use two invoices from the same supplier to test the boundary: one covers service completed before the reorganization, while the other covers the first full period after it. Add a third invoice that spans the effective date. The procedure should preserve the old owner and code where the transition rule requires them, use the new route where appropriate, and send the spanning case to finance for an approved allocation. If all three automatically follow the current manager, the process is ignoring economic period and effective-dated authority.',
    'Review the first close after reorganization for stranded work. Compare old and new cost-center queues, parked documents, open purchase orders, receipts, accruals, and approval tasks. Link each exception to an owner and do not reset age when it moves. Confirm that supplier communications use the same case reference after rerouting. This wider check proves that the organization update changed responsibility without losing obligations, duplicating workflow, or rewriting approvals that were valid under the former structure.'
  ]}
};

const minimumSupplements:Record<string,string> = {
  'service-entry-sheet-rejection-invoice-hold':'The queue record should also retain the invoice due date and close cutoff without using them as reasons to weaken acceptance. When timing becomes urgent, escalate the same complete packet to the authorized owner and record the response. This preserves urgency as an operational fact while keeping service evidence and approval as the basis for processing.',
  'invoice-withholding-tax-evidence-handoff':'When an approved decision changes later, add the new authority, effective date, affected population, and correction path instead of rewriting the earlier packet. Link amended returns, certificates, credits, or postings through the specialist-owned process. A versioned chain matters because the earlier treatment may have been valid on the facts and documents available at that time.',
  'supplier-legal-name-invoice-mismatch':'If payment timing becomes urgent, keep the hold reason and escalation visible. A rush request does not establish supplier identity. Send the authorized owner the complete comparison and due date, and record any approved exception with its limits. Never let an exception become a permanent vendor-master relationship without the normal onboarding and verification evidence.',
  'supplier-credit-balance-refund-request':'Include currency treatment in every request and receipt comparison. A supplier may refund in another currency or on a date that creates a difference from the ledger amount. Treasury confirms the cash received, and finance decides exchange or fee treatment. AP retains both source currency and posted result so the remaining balance is explained rather than silently written away.',
  'subscription-renewal-invoice-owner-review':'Keep security and access offboarding connected but separate from invoice approval. Cancelling payment does not automatically terminate user access, and disabling access does not settle a contractual renewal. Name the owner and completion evidence for each path. This prevents the AP disposition from being mistaken for technical cancellation or proof that company data is no longer held by the provider.',
  'utility-invoice-site-account-mismatch':'For month end, identify service already consumed but not yet supported by a correct bill. Finance decides whether and how to accrue it using the site and period evidence. Do not post a known wrong-entity invoice as a placeholder. Link any accrual reference to the open provider case so a corrected bill reverses or clears the right estimate instead of creating another charge.',
  'erp-migration-duplicate-invoice-screening':'Retain query dates and system access boundaries in the evidence. A no-match result is meaningful only when the reviewer can see which repositories, entities, date ranges, and normalized fields were searched. If legacy access expires, preserve approved reports or references before shutdown. This makes later duplicate inquiries reproducible without granting permanent broad access to the retired platform.',
  'corporate-card-central-bill-allocation':'Protect employee and card data throughout the review. Store full account numbers and receipts only in approved systems, use masked identifiers in follow-up, and limit managers to their authorized transactions. The central statement should not circulate as a convenient attachment. Evidence quality includes proving the allocation while keeping unrelated cardholder activity and personal information out of ordinary email.',
  'invoice-approval-after-cost-center-reorganization':'Update durable routing references after the first cases prove the transition rule. Supplier instructions, non-PO coding aids, approval matrices, and queue ownership should point to controlled sources with effective dates. Do not paste temporary manager lists into invoice notes. A maintained source reduces inconsistent routing while preserving the ability to explain which organization rule applied to an older invoice.'
};
const closingSupplements:Record<string,string> = {
  'supplier-credit-balance-refund-request':'Document who will review any balance still open after the refund and when. The original case should remain discoverable from that residual item.',
  'subscription-renewal-invoice-owner-review':'Record any portal auto-renew setting or saved payment method through the authorized administrator. A cancelled purchase order alone may not stop renewal. Verify the outcome.',
  'utility-invoice-site-account-mismatch':'Keep provider case numbers and promised correction dates in the aging queue. A pending corrected bill does not remove the service period from close review. Recheck it promptly and record the result.',
  'erp-migration-duplicate-invoice-screening':'Sample cleared candidates after payment runs to ensure a later interface or reload did not reintroduce a suppressed legacy obligation. Record the query and result with the stabilization report so recurrence has a named technical owner and does not become another manual AP workaround.',
  'corporate-card-central-bill-allocation':'For cards closed during the cycle, confirm final charges, trailing credits, recurring merchants, and issuer closure separately. A zero balance does not prove future merchant charges stopped. Preserve administrator closure evidence and carry expected credits until they post. Review the following statement for delayed items and link them to the closed-card case. If an issuer accepts charges after closure, the card-program owner decides the dispute or merchant action while AP preserves the accounting trail.',
  'invoice-approval-after-cost-center-reorganization':'When the hierarchy is stable, retire temporary delegations through controlled access review and verify that no broad approval role remains from the transition. Sample later invoices to confirm that normal routing now reaches the intended owners without manual forwarding. Record any persistent exception in the workflow backlog rather than extending emergency access indefinitely.'
};

const inputs:Input[] = [
  {
    slug:'service-entry-sheet-rejection-invoice-hold', title:'Resolve an invoice hold after a service-entry sheet is rejected', keyword:'service entry sheet rejection invoice hold', thumbnail:'/blog-thumbnails/ap-invoice-po-mismatch-notes.svg',
    excerpt:'Reconstruct the service period, entry sheet, rejection reason, contract line, and correction owner without creating acceptance evidence.',
    shortAnswer:'Keep the rejected entry sheet and invoice on one chronology. Identify whether the problem concerns performance, quantity, period, coding, or workflow, then route the correction to the service owner or purchasing role that can attest acceptance.',
    headings:['Preserve the rejected record and define the hold','Rebuild service performance from controlled evidence','Separate correction work from acceptance authority','Verify the resolution against the invoice and ledger'],
    paragraphs:[
      'A rejected service-entry sheet is not merely a missing receipt. It may show that the business owner disputes performance, that the submitted period is wrong, or that the document went to an owner who cannot attest the work. Preserve the invoice, entry-sheet number, rejection text, rejecter, timestamp, purchase-order line, service period, supplier reference, quantity, value, and currency before anyone resubmits. Capture the exact ERP hold reason as well. Do not summarize every case as "SES missing." That label erases the difference between work that has not been accepted and acceptance evidence that failed a technical workflow.',
      'Check whether another entry sheet, reversal, prior invoice, or credit already covers the same service. Service suppliers often bill milestones, hours, retainers, or consumption periods that resemble one another. Compare contract line, statement of work, milestone name, dates, personnel or site where relevant, quantity, rate, and earlier postings. A matching total is weak identity evidence. Keep rejected and replacement documents linked rather than deleting the first attempt. The sequence should show what changed and who supplied the corrected evidence, which protects against paying both a rejected draft and a later accepted version.',
      'Build the performance packet from records the company already recognizes: approved statement of work, purchase-order version, authorized change order, time record, deliverable acknowledgment, project log, or other service evidence specified by policy. A supplier invoice proves the supplier made a demand; it does not prove the service owner accepted performance. Ask the owner a narrow question tied to a period or milestone. Avoid asking AP to infer completion from email traffic or create a service date because the invoice is due. If evidence conflicts, retain both records and identify the decision owner.',
      'Reconcile commercial dimensions independently. Verify service dates against contract validity, quantity against the approved basis, rate against the applicable order version, and value against earlier consumption. Keep tax, expenses, and pass-through charges separate when the agreement treats them separately. A rejected sheet might contain the right total but the wrong service period, cost object, or unit. Show the proposed correction beside the original value. This lets purchasing decide scope, the service owner confirm performance, and finance review accounting without letting one approval silently answer all three questions.',
      'Determine whether the rejection concerns source evidence or system routing. A valid attestation sent to an inactive approver needs an ownership correction, not a new claim that the work occurred. A wrong quantity needs commercial review, not reassignment. Record the rejecter’s stated reason and any controlled workflow rule. If the wording is vague, obtain clarification from the rejecter or process owner. Do not repeatedly resubmit unchanged data to clear a queue. That behavior can create duplicate entry sheets and weakens the audit trail around who actually accepted the service.',
      'The AP support role can assemble the packet, compare records, monitor aging, and prepare a correction request. It should not attest that services were delivered, amend a contract, approve a rate, change a purchase-order commitment, or override the hold. Name the authorized owner for each missing decision. When temporary approval coverage applies, preserve the delegation and its effective dates. If the supplier must correct the invoice, use a verified channel and state the disputed field without sending internal approval details or unrelated account information.',
      'After an authorized owner corrects or replaces the entry sheet, compare it with the approval and source evidence. Confirm the service period, line, quantity, amount, tax treatment, cost object, acceptance owner, and timestamp. Then rerun the match and capture the resulting invoice status. A technically successful match is not enough if the system consumed the wrong sheet. Check for abandoned drafts or duplicate accepted sheets and route them for cleanup through the owner rather than deleting history from the AP case.',
      'Close the hold only when the invoice posting, accepted service record, and decision trail agree. Retain the rejected version, replacement or correction, reason, approval, invoice document, and remaining exception. In recurring outsourced support, review these holds by rejection cause, supplier, owner, contract type, and age. Repeated period errors may call for clearer supplier billing instructions, while repeated inactive approvers belong with workflow ownership. The useful measure is how often a complete packet reaches the correct decision maker, not how quickly AP can make the hold disappear.'
    ],
    checklist:['Original rejected sheet and reason are retained','Service period and contract line are proven','Performance acceptance has an authorized owner','Replacement sheet is checked for duplicates','Final posting uses the approved service record'],
    links:[{href:'/services/purchase-order-reconciliation',label:'purchase order reconciliation'},{href:'/contact-us',label:'scope service-invoice exception support'}],
    faqs:[{question:'Can AP create a replacement service-entry sheet?',answer:'Only if company policy grants that preparation role, and an authorized service owner must still attest performance and approve the record.'},{question:'Does a supplier invoice prove the service was completed?',answer:'No. It proves a billing demand. Use the company-approved service evidence and acceptance owner to support performance.'}]
  },
  {
    slug:'invoice-withholding-tax-evidence-handoff', title:'Prepare invoice withholding-tax evidence for specialist review', keyword:'invoice withholding tax evidence handoff', thumbnail:'/blog-thumbnails/tax-document-collection-ap-workflow.svg',
    excerpt:'Assemble supplier, jurisdiction, document, calculation, and approval evidence while reserving tax conclusions for the authorized specialist.',
    shortAnswer:'Give the tax specialist an unchanged invoice, supplier and entity identity, transaction facts, current tax documents, proposed arithmetic, prior decisions, and a precise question. AP can prepare evidence but should not select a rate or legal treatment.',
    headings:['Frame the tax question without answering it','Assemble identity and transaction facts','Show arithmetic and uncertainty separately','Carry the specialist decision through posting'],
    paragraphs:[
      'Withholding questions often arrive as a vague request to "check tax" while an invoice waits for payment. Start by defining the unresolved decision. The question may concern whether withholding applies, which jurisdiction or income type governs, whether documentation supports an exemption, which rate applies, or how the supplier invoice should be recorded. Preserve the invoice and record supplier legal name, vendor ID, buyer entity, billing and service locations, currency, invoice date, service period, line descriptions, gross amount, taxes, expenses, and contract reference. AP should not turn an uncertain fact pattern into a confident tax code.',
      'Collect the supplier documents required by the company’s process, including their document type, legal name, identifier, issuing jurisdiction, signature or certification status where relevant, receipt date, review status, expiry or refresh trigger, and storage reference. Do not declare a form valid because a file exists. Compare identity fields with the vendor master and invoice, then report differences to the tax or vendor owner. Restrict access because tax records can contain sensitive identifiers. The handoff should point to the controlled document location rather than copying protected data into an ordinary queue note.',
      'Describe the transaction in commercial terms before applying labels. State what the supplier delivered, where the work or goods relate, the covered period, whether expenses or reimbursements appear, and which contract line supports the charge. Separate facts from supplier descriptions and from internal coding. A phrase on an invoice may not determine the tax classification. If the service spans locations or includes several components, break out the amounts supported by the source rather than allocating them by convenience. The specialist needs to see what is known, what came from the supplier, and what remains unverified.',
      'Retrieve earlier specialist decisions only as context. A prior invoice from the same supplier may involve another entity, period, document status, or service. Record the earlier case reference, facts that match, and facts that differ. Do not copy the old rate into the current invoice merely because it produces an expected net amount. Also check credits, corrected invoices, and contract changes. A credit may need to reverse an earlier withholding treatment, but AP should link the events and ask the specialist rather than netting unrelated documents.',
      'Prepare transparent arithmetic for the specialist. Show gross line amounts, proposed base, excluded components, candidate rate supplied by the controlled source, withholding amount, supplier payable amount, currency, rounding, and any system-calculated result. Label every unapproved input as proposed. If the invoice includes tax, freight, or reimbursable expenses, display them separately so the specialist can decide whether they belong in the base. Never alter the source invoice to make the calculation look native. The worksheet should reproduce a possible result without presenting it as a legal conclusion.',
      'Turn uncertainty into specific questions: which entity and jurisdiction apply, whether current supplier documentation supports the treatment, which components enter the base, and whether an earlier decision remains applicable. Assign the review to the authorized tax or finance owner with the invoice due date and payment-run cutoff visible. AP may monitor the response, but urgency does not authorize it to choose a rate. If the supplier disputes the net amount, preserve the message and route it through a verified contact path without revealing internal tax advice beyond approved communication.',
      'When the specialist responds, record the decision, authority, date, affected invoice and entity, rate, base, rounding, certificate or reporting requirement, and any limitation. Compare the approved arithmetic with the ERP entry before posting. Confirm that the system did not apply another default code or calculate withholding twice. Keep preparation and approval roles separated where policy requires. If the invoice has already entered a payment proposal, alert the payment-run owner and follow the controlled removal or update process; never change released payment data from the evidence queue.',
      'Close with the posted document, approved calculation, specialist reference, supplier communication, and follow-up requirement. Preserve enough detail for later reporting or a corrected invoice without exposing sensitive identifiers in public notes. Track recurring cases by question type, document gap, supplier, and response age. Patterns may justify better intake fields or scheduled document refreshes, but they do not justify an AP-created tax policy. A sound outsourced handoff makes the factual record and arithmetic easy to inspect while leaving legal interpretation and final accounting with the designated specialists.'
    ],
    checklist:['Invoice and transaction facts remain unchanged','Supplier documents are referenced securely','Facts, assumptions, and proposed arithmetic are labeled','Tax decision has an authorized specialist','ERP result agrees with approved calculation'],
    links:[{href:'/services/tax-document-collection',label:'tax document collection'},{href:'/services/invoice-data-capture',label:'invoice data capture'}],
    faqs:[{question:'Can outsourced AP select the withholding rate?',answer:'The team can assemble facts and calculate an approved input, while the authorized tax or finance specialist chooses the applicable treatment.'},{question:'Should prior invoices control the current treatment?',answer:'No. Use them as context and compare entity, service, period, documents, and earlier decision scope.'}]
  },
  {
    slug:'supplier-legal-name-invoice-mismatch', title:'Investigate a supplier legal-name mismatch on an invoice', keyword:'supplier legal name invoice mismatch', thumbnail:'/blog-thumbnails/ap-vendor-master-review-checklist.svg',
    excerpt:'Distinguish a trading name, entity change, branch, typo, or wrong supplier account before coding the invoice or changing vendor master data.',
    shortAnswer:'Compare the invoice name with the vendor master, contract, order, tax record, and verified supplier evidence. Identify the reason for the difference and route any entity or master-data decision to its owner before processing.',
    headings:['Treat the name difference as an identity question','Compare controlled records without collapsing entities','Verify changes through established channels','Resolve the invoice and preserve the identity trail'],
    paragraphs:[
      'An invoice can display a brand, shortened name, branch, former legal name, or an entirely different entity from the vendor account selected in the ERP. Preserve the invoice and record the displayed supplier name, address, registration or tax identifier when present, remit name, bank beneficiary name if visible under approved access, purchase order, buyer entity, and internal vendor account. Do not "correct" the source image or assume a familiar logo proves identity. Define the mismatch exactly, including spelling, suffix, address, and identifier differences, so the vendor owner can assess a concrete record.',
      'Compare the invoice with the vendor master history, onboarding file, current tax documents, contract, purchase order, and earlier verified correspondence. Keep effective dates and entity scope visible. A trading name may legitimately appear on invoices while the legal entity remains unchanged. A merger or conversion may require a new vendor record rather than a name edit. A branch may share branding but use another registration. Similar addresses and contacts are supporting context, not enough to merge obligations. Record which controlled source supports each identity field and who owns that source.',
      'Search for duplicate or related vendor accounts using permitted fields. Look for exact identifiers, verified addresses, contract references, purchase orders, and documented parent relationships. Avoid broad searches that expose unrelated supplier data. If two accounts may represent the same entity, preserve both histories and route the comparison to vendor-master ownership. AP should not merge records, move open invoices, or reuse bank instructions simply because names resemble each other. Those actions can shift an obligation across legal entities and weaken payment controls.',
      'Use an established supplier channel to clarify the invoice identity. A reply from the address that sent the mismatched invoice is not independent verification. Follow the company’s approved portal, known phone record, contract contact, or buyer relationship. Ask for the legal invoicing entity and supporting corrected document when needed. Keep the time, channel, person contacted, question, and response. If the request also changes bank, tax, or remit details, split those changes into their dedicated controls rather than treating the name clarification as authority for every field.',
      'Check whether the mismatch originated inside the company. A purchase order may carry an outdated supplier name, the wrong vendor account may have been selected at intake, or an OCR process may have read the remit name as the legal name. Trace the captured field back to its source and retain the erroneous value with the correction. Do not silently edit extracted data until it agrees with master data. That would hide whether the invoice was wrong, capture failed, or the master needs approved maintenance. Each cause has a different owner and preventive action.',
      'Build a decision packet that states the supported supplier identity, conflicting fields, affected buyer entity, open invoice amount, records checked, verification result, and action requested. Vendor-master or procurement owners decide whether to update an account, create a new one, reject the invoice, or request a corrected document. Tax or legal review may be needed under company policy. AP can hold and monitor the invoice while those decisions remain open. It should not bypass the mismatch with a one-time vendor or miscellaneous account merely to meet a due date.',
      'After the owner decides, compare the approved identity with the final invoice and ERP document. Confirm vendor ID, legal name, buyer entity, order, currency, tax treatment, remit record, and approval path. If the supplier issues a corrected invoice, link it to the rejected version and check for duplicate entry. If master data changes, retain the prior value, effective date, approval, and system log. Verify that unrelated accounts under the same brand did not change. The final posting should point to the entity that actually made the supported demand.',
      'Close the case with source documents, verification evidence, identity decision, correction, posting reference, and any open follow-up. Review mismatch cases by cause: trading name, company change, branch, capture error, buyer setup, or suspicious request. A useful outsourced process reports recurring sources without declaring fraud or corporate relationships from appearance. The reader outcome is a traceable answer to three questions: who invoiced the company, which internal account represents that entity, and who authorized any change needed to process the obligation.'
    ],
    checklist:['Invoice identity fields are preserved','Master, contract, order, and tax records are compared','Verification uses an established channel','Related vendor accounts remain separate pending approval','Final posting uses the authorized supplier entity'],
    links:[{href:'/services/vendor-onboarding-administration',label:'vendor onboarding administration'},{href:'/services/invoice-data-capture',label:'invoice data capture'}],
    faqs:[{question:'Can AP change the vendor name to match the invoice?',answer:'Only through the approved vendor-master process. First establish whether the difference is a trading name, correction, or different legal entity.'},{question:'Does a familiar logo prove the supplier identity?',answer:'No. Compare controlled identifiers and verify through an established supplier or procurement channel.'}]
  },
  {
    slug:'supplier-credit-balance-refund-request',title:'Build a support packet for a supplier credit-balance refund request',keyword:'supplier credit balance refund request',thumbnail:'/blog-thumbnails/ap-credit-memo-follow-up-workflow.svg',
    excerpt:'Prove the credit origin, ownership, open-item history, verified contact path, and approval needed before asking a supplier to return cash.',
    shortAnswer:'Reconstruct every item that created the credit, confirm it belongs to the correct supplier and buyer entity, rule out valid future application, and obtain finance and treasury approval before sending verified refund instructions.',
    headings:['Prove how the credit balance arose','Reconcile ownership and application options','Control supplier contact and refund instructions','Track settlement without losing the ledger trail'],
    paragraphs:[
      'A credit balance can come from an unapplied credit memo, duplicate payment, overpayment, returned goods, cancelled prepayment, pricing correction, or a posting error. Start with the ledger balance at a stated cutoff and list every contributing document. Include vendor account, buyer entity, currency, invoice, credit, payment, clearing document, dates, amounts, and current status. Do not begin by asking the supplier to send money. The company first needs evidence that the balance is real, belongs to this entity, and is not already committed to an open invoice or valid supplier claim.',
      'Build a roll-forward from the event that created the balance. For a duplicate payment, connect both payment records to the invoice and bank-supported settlement. For a credit memo, identify the original invoice, return, price decision, or cancellation. Preserve reversals and rejected payments rather than netting them out of view. Reconcile the roll-forward total to the subledger and supplier statement. Differences should remain named exceptions with owners. A supplier statement supports the supplier’s view but does not replace internal posting and bank evidence.',
      'Confirm legal-entity and account ownership. A supplier group may offset balances across locations or affiliates on its statement even when the company cannot do so. Compare legal names, vendor IDs, currencies, contracts, and purchasing relationships. Search related accounts only with approved access and do not move a credit because similar names make the offset convenient. Ask finance whether cross-account or cross-entity application is allowed. Record that decision and the affected items. Until then, the packet should show the credit where it is actually recorded.',
      'Review legitimate application options before requesting cash. Identify open invoices, disputed amounts, expected rebills, replacement goods, and contractual netting provisions. Show due dates and currencies without implying that any open debit can consume the credit. Procurement or finance decides commercial application, and treasury controls cash movement. If the company chooses application, record the invoice and amount, supplier acknowledgment, and clearing evidence. If it chooses refund, retain why application was rejected so the request does not look like an arbitrary preference.',
      'Verify the supplier contact independently, especially when the refund request involves bank instructions. Use the approved portal, known contract contact, or previously verified phone record. Do not rely only on the email thread that introduced new payment details. Record channel, contact, time, and result. The company should provide refund instructions through its controlled treasury process, not through an AP spreadsheet attached to ordinary email. AP can prepare the balance evidence and contact history while treasury or another authorized owner releases account details and confirms expected funds.',
      'The request should state the buyer entity, supplier account, currency, refund amount, credit origin, supporting document references, approved disposition, and response deadline. Avoid sending unrelated invoices or protected banking information. Ask the supplier to reference a stable case or credit identifier on its remittance. If the supplier disputes the amount, preserve its reconciliation and compare events one by one. Do not split the difference without approval or reopen cleared invoices simply to make the external statement agree.',
      'Track the refund as an open receivable-like follow-up without manufacturing an AP invoice. Record supplier acknowledgment, promised date, payment reference, currency, actual receipt evidence from treasury, bank fees, short payments, and remaining balance. AP should not mark the credit resolved when the supplier says payment was sent. Link bank-supported receipt to the ledger clearing entry and preserve any foreign-exchange or fee decision made by finance. Escalate missed promises with the evidence already gathered rather than restarting the request.',
      'Close only when the original credit, approved disposition, supplier communication, cash receipt or application, and final ledger balance reconcile. Retain a residual if fees, currency, or another dispute remains. Review aged credits by origin and resolution path. Repeated duplicate payments point to payment controls; repeated unapplied credits may expose weak statement reconciliation. An outsourced AP team can maintain the packet and follow-up cadence, but finance and treasury retain authority over offset, refund destination, accounting, and settlement confirmation.'
    ],
    checklist:['Credit roll-forward reconciles to the ledger','Supplier and buyer entity ownership are proven','Application options have an owner decision','Contact and refund instructions use controlled channels','Receipt or application clears the exact credit'],
    links:[{href:'/services/vendor-statement-reconciliation',label:'vendor statement reconciliation'},{href:'/services/payment-run-preparation',label:'payment run preparation'}],
    faqs:[{question:'Can a supplier credit be applied to any open invoice?',answer:'Not automatically. Confirm entity, account, currency, contractual scope, and finance approval before application.'},{question:'When is a refund complete?',answer:'After treasury-supported receipt or approved application is posted and the contributing credit items reconcile to the final ledger balance.'}]
  },
  {
    slug:'subscription-renewal-invoice-owner-review',title:'Find the right owner for a subscription renewal invoice',keyword:'subscription renewal invoice owner review',thumbnail:'/blog-thumbnails/sep22-2026/recurring-invoice-price-change-review.svg',
    excerpt:'Use contract, requester, access, renewal, cancellation, and usage evidence to route a recurring charge without inventing approval.',
    shortAnswer:'Trace the subscription to its agreement, original requester, current users, cost center, renewal notice, and cancellation terms. Route commercial acceptance to the current service owner and preserve uncertainty instead of approving from prior payment history.',
    headings:['Identify the subscription behind the invoice','Find current ownership after organizational change','Test renewal, price, and service-period evidence','Record the decision and prevent orphaned renewals'],
    paragraphs:[
      'A recurring invoice may continue arriving after the original buyer leaves, the team reorganizes, or users stop recognizing the product name. Preserve the invoice and record supplier, billed product, account or tenant identifier, service period, renewal date, amount, currency, purchase order, prior invoice, cost center, and delivery channel. Search the contract repository, purchasing system, prior approval, and vendor master using stable identifiers rather than the invoice title alone. A familiar monthly amount is evidence of history, not proof that the current renewal remains authorized.',
      'Distinguish supplier identity from product identity. Software resellers, payment processors, and parent companies can invoice under names that differ from the service users know. Connect the invoice to the controlled agreement, order, or account record and note any name changes. Avoid sending login or user data in a broad ownership search. If identity cannot be proven, ask the verified supplier contact for the customer account and contract reference, not for a copy of credentials or a list of employees.',
      'Reconstruct the ownership chain. Start with the original requester and approver, then review current cost-center ownership, contract owner, system administrator, security register, and known user team. Record departures and effective-dated transfers. An IT administrator may confirm that an account exists without owning the commercial decision. A manager may own budget without knowing whether the service is still used. Route each factual question to the role that can answer it and identify who has authority to accept renewal under company policy.',
      'Inspect cancellation and renewal terms from the approved agreement. Record notice window, automatic-renewal rule, term length, seat or usage basis, and price adjustment method. Do not make a legal interpretation from supplier marketing copy. If the cancellation deadline passed, show the dates and obtain procurement or legal direction. If the invoice covers a future term, keep that distinct from evidence that the current service is active. AP should not approve because cancellation appears difficult or reject because usage seems low.',
      'Compare price and quantity with the prior approved term. Show added seats, removed modules, usage bands, credits, taxes, and currency changes separately. A small total increase can hide a larger unit-price change offset by fewer licenses. Locate the purchase-order amendment or approval supporting the current configuration. If the supplier combined renewal and implementation charges, separate them in the review. The owner needs to see the commercial change, not only whether the invoice arithmetic is correct.',
      'Use available access or asset evidence carefully. A current administrator can confirm active tenant status, assigned seats, or last controlled review, but AP should not infer business value from raw login data. Record what the source actually shows and its date. If no owner responds, follow the documented escalation path through procurement, finance, IT, or the cost-center hierarchy. Do not forward the invoice randomly across departments or approve it to avoid a late fee. The queue should show every attempted owner and the next accountable decision point.',
      'Once an owner decides, preserve approval, rejection, cancellation action, corrected invoice request, or transition plan. Compare the decision with the actual posting and future renewal record. If payment proceeds under a limited exception, state its scope and do not treat it as standing approval for the next term. If cancelled, record supplier confirmation and monitor for credits or later invoices. Keep disputed charges visible until resolved rather than deleting the vendor or closing the mailbox thread.',
      'Close with the agreement reference, ownership trail, renewal facts, price comparison, decision, posting or rejection, and next renewal date. Add a review trigger early enough for the commercial owner to act before the next notice deadline. Analyze orphaned renewals by cause, such as departed requester, renamed product, missing contract, or cost-center move. Outsourced AP can maintain this evidence and cadence; business owners retain service need decisions, procurement controls terms, and finance controls accounting and payment treatment.'
    ],
    checklist:['Invoice is tied to a controlled subscription record','Current commercial and system owners are distinguished','Renewal and cancellation dates are documented','Price and quantity changes are explained','Next review occurs before the notice deadline'],
    links:[{href:'/services/ap-inbox-management',label:'AP inbox management'},{href:'/services/aging-report-preparation',label:'aging report preparation'}],
    faqs:[{question:'Does payment of last year’s invoice approve this renewal?',answer:'No. It provides history, while the current term, ownership, price, and service need still require the company’s current approval.'},{question:'Who owns a subscription invoice?',answer:'The answer may involve separate commercial, budget, system, and procurement owners. The approval policy determines who can accept renewal.'}]
  },
  {
    slug:'utility-invoice-site-account-mismatch',title:'Review a utility invoice with a site or account-number mismatch',keyword:'utility invoice site account mismatch',thumbnail:'/blog-thumbnails/sep18-2026/utility-invoice-account-verification.svg',
    excerpt:'Tie the bill to a meter, service address, billing period, legal entity, and verified provider account before processing.',
    shortAnswer:'Use the provider account, meter or service identifier, physical site, billing period, occupancy records, and prior verified bills to establish ownership. Hold unexplained differences for the facilities and finance owners.',
    headings:['Anchor the invoice to a physical service point','Reconcile account history and billing periods','Investigate moves, meter changes, and shared sites','Post only the supported obligation'],
    paragraphs:[
      'Utility invoices can look routine even when they belong to another site, former tenant, landlord account, or company entity. Preserve the bill and record provider legal name, customer account, meter or service identifier, service address, mailing address, billing period, read dates, usage, tariff or service class, prior balance, current charges, taxes, fees, due date, and buyer entity selected at intake. Do not route by mailing address alone. A centralized AP address may appear on every bill while the underlying service point determines ownership.',
      'Compare the bill with the approved site register, lease or facilities record, vendor master, prior verified invoice, purchase order where used, and utility portal under controlled access. Keep each identifier in its original format. Leading zeros, meter replacements, and provider migrations can make related accounts look different, while neighboring suites can have similar addresses. Record which field links the bill to the site and which fields conflict. Avoid changing the vendor account or cost center until the facilities or finance owner resolves identity.',
      'Build an account chronology covering opening, occupancy, provider changes, meter exchanges, transfers, closures, and earlier bills. Include effective dates and final reads. A new account number may be legitimate after a provider conversion, but the old account may still carry a final bill or credit. Link both without assuming the balance moved correctly. If the invoice contains a prior balance, trace it to earlier documents and payments. A current amount can be valid while an inherited arrears balance belongs to a predecessor or another entity.',
      'Check billing-period continuity. Compare previous ending read with current starting read, estimated and actual indicators, usage units, adjustment lines, and overlapping dates. AP does not need to judge engineering consumption, but it can identify a duplicated period, unexplained gap, reversed estimate, or meter mismatch. Send facilities the exact service point, dates, readings, and charge at issue. A seasonal increase by itself is not proof of error, and a total close to last month does not prove the account is correct.',
      'Site changes require commercial context. Review lease start and end dates, responsibility clauses, move-in documentation, landlord allocations, and facility closure records through the appropriate owners. If several entities share a building, identify the approved allocation basis rather than dividing the invoice by headcount or square footage on AP’s initiative. Record common-area charges separately. Facilities confirms the served location; procurement or legal interprets the agreement; finance decides coding, accrual, and entity treatment.',
      'Verify provider contact through a known portal, published account channel, or established record before discussing the account. Do not call a number added to a suspicious invoice without checking it. Ask for confirmation of account ownership, meter, service period, and corrected billing when needed. Keep the case reference and response. A provider representative’s verbal statement should be documented but does not authorize internal entity or coding changes. Route bank or autopay changes through separate controls.',
      'After resolution, compare the supported bill with the ERP document. Confirm provider account, buyer entity, service address, period, amount, tax, cost object, approval, and due date. Link a corrected bill to the rejected version and screen for duplicate entry. If only part is supported, follow company policy for dispute or partial processing and keep the residual visible. Check that a final bill does not leave an automatic recurring template active and that a new account does not bypass normal owner approval.',
      'Close with the source bill, site and account evidence, chronology, provider communication, owner decisions, posting reference, and remaining credit or dispute. Track exceptions by provider, location, cause, and age. Repeated site mismatches may reflect weak site-master maintenance; repeated estimated-read disputes may need facilities review. Outsourced AP can prepare the record and follow up, but it should not decide occupancy responsibility, allocate shared utilities, or accept a new provider account without authorized evidence.'
    ],
    checklist:['Provider account and service point are captured','Site and entity ownership are proven','Billing periods and readings do not overlap unexplained','Moves and meter changes appear in chronology','ERP posting matches the supported site obligation'],
    links:[{href:'/services/invoice-data-capture',label:'invoice data capture'},{href:'/services/month-end-ap-close-support',label:'month-end AP close support'}],
    faqs:[{question:'Is the invoice mailing address enough to identify the site?',answer:'No. Use the provider account, meter or service identifier, service address, site register, and ownership dates.'},{question:'Can AP allocate a shared-site utility bill?',answer:'AP can calculate an approved basis, while facilities and finance must establish the responsibility and allocation rule.'}]
  },
  {
    slug:'erp-migration-duplicate-invoice-screening',title:'Screen for duplicate invoices after an ERP migration',keyword:'ERP migration duplicate invoice screening',thumbnail:'/blog-thumbnails/duplicate-invoice-review-process.svg',
    excerpt:'Compare legacy and new-system identifiers, normalized invoice fields, conversion records, and payment history without collapsing legitimate splits.',
    shortAnswer:'Search both systems and the migration crosswalk using supplier identity, invoice variants, amounts, dates, purchase orders, credits, and payment evidence. Treat migrated records and re-entered invoices as one transaction history.',
    headings:['Define the migration duplicate population','Normalize identity without losing source values','Trace converted, re-entered, and paid documents','Clear candidates with evidence and controlled ownership'],
    paragraphs:[
      'Migration creates a special duplicate risk because the same obligation can appear as a converted open item, a historical reference, and a newly entered invoice. Define the cutoff, legacy system, target system, entities, suppliers, document types, and migration loads in scope. Preserve the new invoice and capture its supplier, invoice number, date, amount, currency, purchase order, receipt, file hash where available, entry channel, and target document ID. Do not assume the target system’s ordinary duplicate warning can see records that were summarized or stored outside its searchable invoice table.',
      'Obtain the approved migration crosswalk and load reports. Record legacy document ID, target ID, conversion status, open or closed state, balance, and exception result. A missing target invoice may have become an opening-balance line, while a visible target item may carry a generated number rather than the supplier reference. Treat the crosswalk as evidence, not infallible truth. Reconcile counts and values to the migration control report and report gaps to the migration or finance owner instead of creating a replacement invoice from memory.',
      'Normalize invoice references in a review layer while retaining original values. Compare case, spaces, punctuation, leading zeros, prefixes, suffixes, credit indicators, and common OCR substitutions. Also compare supplier legal identity, entity, currency, gross amount, tax, order, receipt, service period, and attachment. A normalized number match can be false when suppliers reuse sequences across accounts. A number mismatch can still be a duplicate after a manual prefix or migration transformation. Explain which fields create the candidate and which contradict it.',
      'Search payment and clearing history in both environments. A legacy invoice may be closed because it was paid before cutoff, yet its target historical record may not carry searchable settlement detail. Obtain the payment reference, value date, bank-supported status, clearing event, and any return or void. A converted open item might also have been paid during a transition window outside the final extract. Do not approve the target invoice because its local status says unpaid. Build one chronology across systems through the stabilization period.',
      'Distinguish duplicates from legitimate splits, recurring charges, corrections, and rebills. Compare line detail and covered periods, not only totals. A supplier may replace one invoice with two entity-specific documents, or issue a corrected invoice under the same reference. Link credits and cancellations. If the migration split one document by entity or currency, preserve the controlled mapping and ensure the combined balance matches the source. Do not merge target records simply to reduce candidate counts.',
      'For each candidate, assign a disposition supported by named evidence: confirmed duplicate, distinct obligation, corrected replacement, migrated reference only, payment already made, or unresolved. Finance or the designated process owner approves write-off, reversal, blocking, or release actions. AP can prepare the comparison and hold the newest entry. Keep the candidate pair and decision together. Deleting one side of the comparison removes evidence and makes later supplier or audit questions harder to answer.',
      'Before release, test the final target posting against order, receipt, approval, and payment history. Confirm that a duplicate block or reversal did not remove the valid invoice. Search staging tables, workflow queues, and permitted archives for another pending copy. If the supplier asks for status, communicate the supported invoice and dispute reference through a verified channel. Never reveal migration weaknesses or other suppliers’ records. Record the target document that will continue as the company’s operational source.',
      'Monitor duplicate cases through at least the defined stabilization window. Report causes such as crosswalk gap, late legacy posting, dual intake, reference transformation, missing payment history, or supplier rebill. Reconcile confirmed duplicate value as well as count. An outsourced AP team should receive read-only legacy evidence and explicit escalation routes rather than broad migration administration. Success means each paid or payable obligation has one traceable operational record, not that every similar record was automatically suppressed.'
    ],
    checklist:['Migration cutoff and system population are explicit','Crosswalk and load controls are referenced','Original and normalized invoice identifiers remain visible','Legacy and target payment histories are searched','Final disposition has evidence and owner approval'],
    links:[{href:'/services/duplicate-invoice-review',label:'duplicate invoice review'},{href:'/services/three-way-match-support',label:'three-way match support'}],
    faqs:[{question:'Will the new ERP duplicate check find migrated invoices?',answer:'Not always. Confirm how historical and opening items were loaded, then search the crosswalk and both transaction histories.'},{question:'Should a suspected duplicate be deleted?',answer:'Preserve both records, document the comparison, and let the authorized owner approve blocking, reversal, or release.'}]
  },
  {
    slug:'corporate-card-central-bill-allocation',title:'Reconcile a corporate-card central bill to employee transactions',keyword:'corporate card central bill allocation',thumbnail:'/blog-thumbnails/sep18-2026/corporate-card-receipt-invoice-match.svg',
    excerpt:'Bridge the issuer total to cardholder charges, credits, fees, disputes, and missing reports while keeping payment release separate.',
    shortAnswer:'Roll the issuer statement from prior balance through purchases, credits, fees, payments, and disputes. Match cardholder transactions individually, keep missing support visible, and route release to the authorized payment owner.',
    headings:['Reproduce the issuer balance before allocation','Match cardholder activity without hiding gaps','Handle credits, disputes, and timing differences','Reconcile posting and payment as separate controls'],
    paragraphs:[
      'A central bill combines many cardholders into one amount due, so matching only the statement total can conceal unsupported employee activity. Preserve the issuer statement and record corporate account, billing cycle, currency, opening balance, purchases, cash or special transactions, credits, fees, interest, payments, adjustments, closing balance, minimum or full amount due, and due date. Capture card-level subtotals and the issuer’s stable transaction IDs. Do not distribute the total across employees before reproducing the issuer’s own roll-forward.',
      'Tie the opening balance to the prior closing balance and trace payments to bank-supported settlement and issuer application. A payment in transit can appear on the company ledger but not the statement cutoff. Record value and application dates separately. Investigate unexplained prior balances rather than spreading them across current cardholders. Fees and interest need their own coding and owner review. AP should show the arithmetic and evidence; finance decides accounting and the card-program owner addresses preventable charges.',
      'Match each issuer transaction to the cardholder feed, approved expense report, receipt, business purpose, date, amount, currency, and cost allocation. Preserve foreign-currency source amount and issuer conversion where shown. Similar merchant names or amounts do not prove identity. If employees combine several transactions in one report, retain the line mapping. If one transaction is split across cost centers, use the approved allocation and keep the source total visible. Missing support remains an exception rather than a plug to make the central bill reconcile.',
      'Classify unmatched activity precisely: report not submitted, receipt missing, cardholder departed, merchant unrecognized, personal charge under review, duplicate feed item, timing cutoff, or system mapping error. Assign the next action to the employee, manager, card administrator, security team, or finance owner according to policy. Avoid asking every cardholder to review the whole statement. A focused request should include the transaction date, merchant, amount, and required evidence without exposing other employees’ purchases.',
      'Credits should link to the original charge and expected return. Show merchant credit date, issuer posting date, employee report treatment, and any amount difference. Do not net a credit against an unrelated expense merely because both belong to one card. Disputes also need separate states: reported, provisional credit, issuer investigation, final credit, denied, or withdrawn. A provisional credit is not final resolution. Keep the charge and dispute evidence visible until the issuer outcome and internal ledger agree.',
      'Account for timing between authorization, posting, statement cutoff, expense submission, and ledger import. A valid late-posting transaction may belong to the next statement even if the employee submitted it earlier. Conversely, a statement charge may be absent from the expense system because integration failed. Use transaction IDs and dates to locate it; do not create a second manual expense without checking staging and prior imports. Document the approved cutoff method so month-end reviewers understand what is accrued or carried forward.',
      'Reconcile the approved allocation to the ERP posting by account, cost object, tax treatment, currency, and total. Then treat statement payment as a separate control. AP may prepare the payment packet and identify due-date risk, while treasury or the designated owner releases funds. Confirm the payment proposal uses the correct issuer account and amount and that no duplicate direct debit is expected. After settlement, link the bank evidence and issuer application without erasing open employee exceptions.',
      'Close the cycle when statement roll-forward, cardholder allocation, ledger entry, payment, credits, and residual exceptions reconcile. Carry each residual with an owner and review date. Analyze patterns by exception cause and program rule, not by unsupported judgments about employees. An outsourced expense-review team can perform matching and follow-up with restricted card data. Program administration, disciplinary decisions, write-offs, and payment release remain with authorized company roles.'
    ],
    checklist:['Issuer roll-forward reproduces the amount due','Every allocation retains transaction identity','Credits and disputes link to original charges','Timing differences have a cutoff explanation','Ledger posting and payment release are reconciled separately'],
    links:[{href:'/services/expense-report-review',label:'expense report review'},{href:'/services/payment-run-preparation',label:'payment run preparation'}],
    faqs:[{question:'Can missing employee support be allocated temporarily?',answer:'Follow company policy, keep the item visible with an owner, and do not disguise it as a supported expense.'},{question:'Does a provisional dispute credit close the charge?',answer:'No. Track the issuer’s final outcome and reconcile both the original charge and credit to the ledger.'}]
  },
  {
    slug:'invoice-approval-after-cost-center-reorganization',title:'Reroute invoice approval after a cost-center reorganization',keyword:'invoice approval cost center reorganization',thumbnail:'/blog-thumbnails/invoice-approval-escalation-rules.svg',
    excerpt:'Preserve the original approval trail, effective-dated ownership, coding questions, and escalation clock when responsibility moves.',
    shortAnswer:'Map the invoice’s service period and cost ownership to the effective-dated organization, preserve prior workflow events, and obtain authorized coding and approval updates instead of forwarding blindly or restarting history.',
    headings:['Freeze the current workflow and organization facts','Map economic ownership across the effective date','Reroute approval without rewriting history','Verify the final coding, approval, and aging record'],
    paragraphs:[
      'A cost-center reorganization can strand invoices with inactive approvers or create pressure to code everything to the new structure. Preserve the invoice, current coding, workflow status, original requester, approvers, timestamps, rejection or delegation notes, purchase order, service period, amount, currency, and due date. Record the old and new cost-center identifiers and the reorganization effective date from a controlled source. Do not cancel the workflow or overwrite the old owner until the transition rule and invoice population are understood.',
      'Determine what changed: manager ownership, cost-center code, legal entity, department hierarchy, budget responsibility, approval threshold, or all of them. These changes have different control effects. A new manager may approve an old code, while a retired code may require finance mapping. A legal-entity move cannot be treated as a simple routing update. Capture the approved organization map, effective dates, delegation records, and system configuration owner. AP prepares the evidence; finance and business owners decide coding and authority.',
      'Compare the invoice’s delivery or service period, order date, invoice date, receipt date, and posting period with the reorganization date. A service spanning the change may need allocation, but AP should not invent a proration rule. Show the amounts and periods available from the supplier or contract and ask finance for the approved basis. For goods, receipt site and purchasing entity may control different questions from budget ownership. Keep commercial acceptance, coding, and approval authority distinct in the packet.',
      'Review purchase-order and non-PO paths separately. A purchase order may retain its original cost center until formally amended, even when the manager changed. A non-PO invoice may rely on an effective-dated coding matrix. Identify open commitments, receipts, accruals, and prior invoices under the same agreement. Do not change an order reference to force new routing. Purchasing owns amendments; the service or goods owner confirms acceptance; finance owns accounting mapping. Record the answer for this invoice without assuming it applies to every transition item.',
      'Map the authorized approval route using the current matrix and any documented transition rule. If the former approver is inactive, use approved delegation or reassignment rather than forwarding the task informally. Preserve completed approvals when policy allows; do not make the history appear as if the new owner approved earlier events. If thresholds changed, identify which rule applies to the invoice and cite the owner decision. A backup approver’s authority should include scope and dates, not merely a manager’s name in chat.',
      'Keep the aging clock factual. Record invoice receipt, first complete packet, each owner handoff, response, and current blocker. A reorganization may explain delay but should not reset the invoice’s age. Send one structured request containing the document, affected period, proposed mapping, prior approvals, and decision needed. Avoid parallel requests to several managers that can produce conflicting approvals. Escalate through the defined ownership chain, and tell the supplier only the supported status through an approved contact channel.',
      'After rerouting, compare the final ERP coding and workflow with the approved mapping. Confirm buyer entity, cost center, account, tax, order, service period, approval threshold, approvers, and posting date. Check for duplicate workflow instances or an abandoned parked document created during reassignment. If the invoice was split, the parts must sum to the source and retain the allocation authority. Preserve the original route and the reason for change so the audit trail shows a transition, not unexplained editing.',
      'Close with the organization source, effective-date analysis, coding decision, delegation or reassignment, approval record, posting, and remaining transition issue. Review cases by old cost center, new owner, exception type, and time to decision. Repeated stranded invoices may reveal incomplete workflow maintenance or supplier routing instructions. Outsourced AP can manage the queue and evidence, while company owners retain budget authority, coding policy, organizational design, and payment release. The result should show why this invoice reached this approver and this cost object.'
    ],
    checklist:['Original workflow and coding are preserved','Organization changes use controlled effective dates','Service period and ownership are compared','Delegation or reassignment has documented authority','Final posting matches approved mapping'],
    links:[{href:'/services/aging-report-preparation',label:'aging report preparation'},{href:'/services/month-end-ap-close-support',label:'month-end AP close support'}],
    faqs:[{question:'Should all old invoices move to the new cost center?',answer:'Not automatically. Apply the approved effective-date and transition rule to the invoice’s service, order, and entity facts.'},{question:'Can AP restart approval with the new manager?',answer:'Use the controlled reassignment or delegation process and preserve valid prior workflow history rather than silently restarting it.'}]
  }
];

export const remainingOct5BlogDrafts:Draft[] = inputs.map((x) => ({
  slug:x.slug,title:x.title,excerpt:x.excerpt,minutes:12,
  detail:{thumbnail:x.thumbnail,shortAnswer:x.shortAnswer,published:oct5BlogPublicationDate,modified:null,mainKeyword:x.keyword,
    sections:[...x.headings.map((title,i)=>({title,paragraphs:x.paragraphs.slice(i*2,i*2+2)})),...(finalSections[x.slug]?[{...finalSections[x.slug],paragraphs:[...finalSections[x.slug].paragraphs,minimumSupplements[x.slug],...(closingSupplements[x.slug]?[closingSupplements[x.slug]]:[])]}]:[])],
    checklistTitle:`Review the ${x.keyword} record`,checklist:x.checklist,bodyLinks:x.links,faqs:x.faqs,sources}
}));
