type Spec={slug:string;title:string;excerpt:string;keyword:string;scene:string;record:string;owner:string;check:string};
const date='2026-09-04' as const;
const specs:Spec[]=[
{slug:'ap-invoice-email-attachment-control',title:'Control invoice attachments arriving by email',excerpt:'Give the AP inbox a practical way to retain the original message, choose the right attachment, and quarantine unclear files.',keyword:'invoice email attachment control',scene:'A supplier sends a PDF invoice, a spreadsheet backup, and an old invoice in one reply chain.',record:'message ID, sender, received time, attachment names and hashes, selected invoice, duplicate search, queue receipt, and exception note',owner:'AP inbox owner',check:'replay ordinary messages, forwarded threads, missing files, password-protected files, and two invoices in one email'},
{slug:'ap-credit-memo-application-queue',title:'Run an AP credit memo application queue',excerpt:'Keep supplier credits visible until the right invoice, entity, and accounting treatment have been confirmed.',keyword:'credit memo application queue',scene:'A credit memo names an invoice that has already been paid by a different company entity.',record:'credit identifier, supplier, entity, currency, amount, referenced invoice, open balance, correspondence, proposed match, decision, and posting reference',owner:'accounting owner',check:'sample full, partial, unapplied, disputed, cross-entity, and already-used credits'},
{slug:'ap-purchase-order-price-variance-log',title:'Keep a purchase order price variance log',excerpt:'Record line-level price differences without allowing the exception list to become an unofficial approval channel.',keyword:'purchase order price variance log',scene:'Freight on the invoice raises one line above the purchase order while the goods price still agrees.',record:'invoice and PO lines, descriptions, quantities, unit prices, charges, taxes, tolerance source, variance, buyer response, and disposition',owner:'buyer or finance approver',check:'test price, quantity, freight, tax, rounding, currency, and amended-PO differences'},
{slug:'ap-vendor-statement-missing-invoice-queue',title:'Build a missing-invoice queue from vendor statements',excerpt:'Turn statement-only items into traceable requests instead of entering liabilities from a supplier list alone.',keyword:'vendor statement missing-invoice queue',scene:'A month-end statement lists two documents that never reached the AP inbox.',record:'statement date, supplier, account, listed document, amount, currency, ledger and inbox searches, request history, received file, and resolution',owner:'AP or accounting owner',check:'cover genuinely missing invoices, credits, paid items, wrong entities, duplicates, and statement errors'},
{slug:'ap-payment-file-preparation-checklist',title:'Use an AP payment file preparation checklist',excerpt:'Define what a preparer may assemble before an authorized employee reviews and releases a payment file.',keyword:'payment file preparation checklist',scene:'One approved invoice changes after the proposal is prepared but before the bank file is released.',record:'proposal version, included items, exclusions, approval evidence, supplier account reference, totals, control total, preparer, reviewer, release owner, and timestamps',owner:'treasury payment owner',check:'reconcile the source proposal, exported file, late changes, rejected items, control totals, and final bank acceptance'},
{slug:'ap-tax-document-expiration-tracker',title:'Maintain an AP tax document expiration tracker',excerpt:'Track dated supplier documents and requests while keeping tax interpretation with the company’s qualified owner.',keyword:'tax document expiration tracker',scene:'A supplier record has an older tax form while a recent address-change request is still under review.',record:'supplier and entity, document type, received and effective dates, stored source, status, request history, reviewer, decision, and next review date',owner:'tax or vendor-master owner',check:'include current, missing, replaced, conflicting, illegible, and out-of-scope documents'},
{slug:'ap-approver-absence-escalation-routine',title:'Set an invoice approval reminder cadence',excerpt:'Prompt the right approvers without flooding inboxes or turning silence into assumed approval.',keyword:'invoice approval reminder cadence',scene:'An invoice is due soon, but the assigned approver is away and no delegate appears in the workflow.',record:'invoice, approver assignment, received and due dates, reminder schedule, messages, replies, delegate evidence, escalation, and final action',owner:'approval process owner',check:'review normal, urgent, absent-owner, reassigned, disputed, and already-decided invoices'},
{slug:'ap-supplier-refund-receipt-log',title:'Create a supplier refund receipt log',excerpt:'Connect expected supplier refunds to bank evidence and accounting closure without treating a promise as cash.',keyword:'supplier refund receipt log',scene:'A supplier promises one refund for two overpayments but sends a different amount without references.',record:'claim, supplier, entity, expected amount and currency, promise, bank receipt, remittance detail, variance, application, accounting decision, and closure',owner:'cash or accounting owner',check:'trace promised, late, partial, combined, unidentified, rejected, and fully applied receipts'},
{slug:'ap-shared-services-entity-routing-table',title:'Maintain an AP entity routing table for shared services',excerpt:'Route invoices to the correct company queue using approved evidence and a clear path for ambiguous entities.',keyword:'shared-services entity routing table',scene:'A supplier sends one invoice to a group mailbox with a trading name used by two legal entities.',record:'source address, invoice addressee, tax identifier, PO entity, supplier account, approved routing rule, selected queue, exception, and owner response',owner:'entity accounting owner',check:'test clear entities, shared names, missing addressees, wrong inboxes, cross-entity POs, and corrected invoices'},
{slug:'ap-bank-change-callback-evidence-log',title:'Document vendor bank-change callback evidence',excerpt:'Preserve independent verification steps while restricting sensitive data and final master-record changes.',keyword:'bank-change callback evidence log',scene:'An urgent bank-change email includes a phone number that differs from the approved supplier contact record.',record:'request source, supplier, changed fields, approved contact source, callback initiator, time, outcome, unresolved differences, reviewer, and master-change reference',owner:'vendor-master or fraud-control owner',check:'test known contacts, unavailable contacts, failed calls, conflicting answers, withdrawals, and suspected impersonation'},
{slug:'ap-invoice-scan-quality-exception-queue',title:'Create an invoice scan quality exception queue',excerpt:'Catch unreadable and incomplete invoice images before weak OCR output enters approval or matching work.',keyword:'invoice scan quality exception queue',scene:'A phone photo cuts off the remittance section and turns one digit in the total into another.',record:'source file, sender, page count, image checks, OCR output, uncertain fields, comparison, replacement request, received revision, and queue status',owner:'invoice intake owner',check:'include clean files, cropped pages, skew, handwriting, low contrast, duplicates, and mixed-document scans'},
{slug:'ap-weekly-exception-aging-review',title:'Run a weekly AP exception aging review',excerpt:'Review stalled items by cause and next owner instead of using age alone as a performance verdict.',keyword:'weekly AP exception aging review',scene:'A young high-value bank-change exception needs faster attention than an older invoice awaiting a routine receipt.',record:'exception ID, opened time, category, value context, last evidence, dependency, current owner, next action, target date, escalation, and closure',owner:'AP operations owner',check:'sample new, aging, blocked, reassigned, reopened, high-risk, and closed exceptions'},
];
const sections=(s:Spec)=>[
 {title:`Put the ${s.keyword} around a real queue`,paragraphs:[`Start with the work as it arrives, not an idealized diagram. ${s.scene} Write down the source systems, cutoff, company entity, and the person accountable for the queue.`, `Keep ${s.record}. Leave blanks visible. A missing field is useful evidence; a guessed value is not.`]},
 {title:'Give the preparer a firm stopping point',paragraphs:[`An outsourced AP specialist can collect records, compare fields, update the queue, and ask for missing support. The ${s.owner} keeps policy interpretation, approval, accounting judgment, master-data authority, and payment authority.`, `Status labels should describe what happened: received, checked, waiting for evidence, with owner, decided, or closed. Record who moved the item and when.`]},
 {title:'Try the awkward cases before launch',paragraphs:[`A tidy example rarely finds a weak handoff. Use the scenario above and ask a second reviewer to reach the same conclusion from the retained record alone.`, `For acceptance, ${s.check}. When reviewers disagree, fix the rule, example, or source access before adding more volume.`]},
];
export const sep4BlogPosts=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:8}));
export const sep4BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,shortAnswer:`Build a source-linked ${s.keyword}, make missing evidence visible, and send decisions to the ${s.owner}.`,sections:sections(s),faqs:[{question:`What can outsourced support do in this ${s.keyword}?`,answer:`Support can gather approved records, compare observable fields, update status, and route exceptions. The ${s.owner} retains decisions and authorization.`},{question:'What proves the routine works?',answer:`Retain ${s.record}, then ${s.check}.`}]}]));
