import type {Draft} from './blog-oct2-batch';

type Stage={title:string;evidence:string;work:string;example:string;decision:string};
type Input={slug:string;title:string;excerpt:string;keyword:string;image:string;service:string;serviceLabel:string;question:string;boundary:string;stages:Stage[]};
const sources=[
  {name:'GAO Standards for Internal Control in the Federal Government',url:'https://www.gao.gov/products/gao-14-704g',note:'Authoritative framework supporting documented transactions, review, and assigned responsibility.'},
  {name:'NIST least privilege glossary',url:'https://csrc.nist.gov/glossary/term/least_privilege',note:'Supports narrow preparation access and retained decision authority.'},
  {name:'CISA guidance on phishing',url:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing',note:'Supports verified communication paths when a message, sender, or request changes.'},
];
const renderers=[
  (input:Input,stage:Stage,index:number)=>[
    `${stage.evidence} ${stage.work} Tie the entry to the proposal version and sequence number so the reviewer can see exactly when the population changed. State what the evidence establishes and what is still awaiting authorization. ${input.boundary}`,
    `${stage.example} ${stage.decision} Add the amount, currency, actor, timestamp, reason, and next checkpoint. Keep the prior version beside the corrected one. ${index%2===0?'Reperform the proposal bridge after the change and investigate any unexplained difference.':'Confirm the change appears in the final approved population and assign any carryover.'}`
  ],
  (input:Input,stage:Stage,index:number)=>[
    `${stage.evidence} ${stage.work} The queue entry should identify the supplier record, document version, governing instruction, secure location, and specialist question. Do not infer a tax requirement from age alone. Note whether the record affects one payee or several linked supplier accounts, since the answer may differ by entity. ${input.boundary}`,
    `${stage.example} ${stage.decision} Preserve the received file and the reviewer response as separate records. Note the outreach channel, effective date, unresolved field, and permitted next action. ${index%2===0?'A second reviewer should be able to trace the status without opening unrelated supplier data.':'Any hold or release remains a separately approved company action.'}`
  ],
  (input:Input,stage:Stage,index:number)=>[
    `${stage.evidence} ${stage.work} Build the explanation around the employee transaction and merchant event, then compare it with the card or reimbursement record. Avoid netting the expected credit against another expense. Keep statement-cycle timing visible. ${input.boundary}`,
    `${stage.example} ${stage.decision} Show the original charge, expected refund, actual settlement, difference, and current owner. Retain the employee statement and financial evidence in their approved systems. ${index%2===0?'Check the following statement cycle before treating a delayed credit as missing.':'If the merchant changes its answer, add a milestone instead of rewriting the first account.'}`
  ],
  (input:Input,stage:Stage,index:number)=>[
    `${stage.evidence} ${stage.work} Connect the technical response to the invoice, statement, or supplier case affected by the failure. Preserve headers and diagnostics without copying protected attachments into an informal channel. Distinguish a temporary retry from a permanent contact correction, and record why the chosen alternate route is trusted. ${input.boundary}`,
    `${stage.example} ${stage.decision} Log the route attempted, verified alternative, delivery result, business deadline, and person now responsible. ${index%2===0?'Do not retry blindly because repeated sends can create noise or trigger another control.':'When the alternate path works, update the case and test the permitted routing change.'}`
  ],
  (input:Input,stage:Stage,index:number)=>[
    `${stage.evidence} ${stage.work} Keep receipt, invoice, return, and supplier-search evidence at line level so finance can reproduce the close population. State the extraction timestamp and the period under review. Compare the line with earlier close packets only as history; a prior accrual does not prove that the current quantity or value remains valid. Show reversals, late postings, and corrections as new events. Keep operational receipt confirmation separate from the finance conclusion about cutoff. ${input.boundary}`,
    `${stage.example} ${stage.decision} Quantify the supported quantity, value, currency, missing document, and remaining uncertainty. ${index%2===0?'Compare the conclusion with later invoices and reversals so the packet can be cleared in the next close.':'An unresolved item stays visible with an owner and response date rather than dropping from the schedule.'}`
  ],
  (input:Input,stage:Stage,index:number)=>[
    `${stage.evidence} ${stage.work} Explain the dispute as a chain of dated events rather than a single age number. The note should make the present blocking question and missed commitment easy to find. Identify whether the latest delay sits with the supplier, an internal owner, or an evidence handoff, but do not assign blame beyond the records. A useful escalation asks for one decision and states the operational effect of waiting. ${input.boundary}`,
    `${stage.example} ${stage.decision} Record the milestone date, source, disputed amount, answer requested, escalation rule, and next review point. ${index%2===0?'Keep invoice age, dispute age, and time since the last meaningful event as separate measures.':'Close only the resolved branch when an invoice still has another live issue.'}`
  ]
];
const build=(input:Input,topicIndex:number):Draft=>({
  slug:input.slug,title:input.title,excerpt:input.excerpt,minutes:12,
  detail:{
    thumbnail:input.image,shortAnswer:`${input.excerpt} ${input.boundary}`,published:null,modified:null,mainKeyword:input.keyword,
    sections:input.stages.map((stage,index)=>({title:stage.title,paragraphs:renderers[topicIndex](input,stage,index)})),
    checklistTitle:'Review the case before handoff',
    checklist:['Source records and identifiers remain intact','Conflicts and missing evidence are stated precisely','The next decision and owner are named','Corrections preserve the earlier state','Preparation, approval, and release authority remain separate'],
    bodyLinks:[{href:`/services/${input.service}`,label:input.serviceLabel},{href:'/contact-us',label:'scope the AP support role'}],
    faqs:[
      {question:`What question should this ${input.keyword} answer?`,answer:input.question},
      {question:'Which authority stays with the company?',answer:input.boundary},
      {question:'How should the workflow begin?',answer:'Start with a bounded sample, named source systems, explicit stop conditions, and review by the company owner before expanding the queue.'}
    ],sources
  }
});

const inputs:Input[]=[
  {
    slug:'payment-proposal-cutoff-exception-log',title:'Maintain a cutoff exception log for payment proposal preparation',keyword:'payment proposal cutoff exception log',service:'payment-run-preparation',serviceLabel:'payment run preparation',image:'/blog-thumbnails/sep18-2026/payment-run-cutoff-calendar.svg',
    excerpt:'Document additions, removals, holds, timing changes, approvals, and final inclusion without giving the preparer release authority.',
    question:'Why did an invoice enter, leave, or change in the proposal after the stated cutoff, and who authorized that treatment?',
    boundary:'AP support may prepare the proposal and exception evidence; treasury or finance approves exceptions, controls bank access, and releases payment.',
    stages:[
      {title:'Freeze a reviewable cutoff snapshot',evidence:'Save the proposal ID, entity, bank account alias, currency, scheduled date, cutoff timestamp, invoice population, total, and extraction source before late changes begin.',work:'Compare later versions with this snapshot rather than relying on a total written in chat.',example:'A 4:00 p.m. snapshot contains 138 invoices. The 4:37 version contains 140, so the log identifies the two added document IDs and their values.',decision:'The finance owner confirms which snapshot is the authorized starting population.'},
      {title:'Log additions as separate decisions',evidence:'For every late addition, retain the invoice, due date, discount date, approval status, hold status, supplier verification state, requestor, reason, and time received.',work:'Check ordinary readiness controls even when the request is urgent.',example:'A manager asks to add a utility invoice after cutoff. The invoice is approved, but a vendor hold remains, so it stays outside the proposal pending an owner decision.',decision:'The authorized exception owner decides whether timing justifies inclusion and documents the control treatment.'},
      {title:'Explain every removal and hold',evidence:'Capture the proposal line, removal time, actor, reason code, related case, and whether the invoice returns to a later run.',work:'Distinguish a deliberate removal from a system filter or failed validation.',example:'One invoice disappears because its supplier was placed on hold after the first extract; another drops because its payment method is not supported by the selected run.',decision:'Treasury or finance confirms the disposition and prevents the item from becoming an unowned overdue balance.'},
      {title:'Reconcile totals after each approved change',evidence:'Show opening total, additions, removals, credits, discounts, currency adjustments, and closing total with document-level references.',work:'Make the bridge arithmetic reproducible and keep currencies separate.',example:'Three approved additions increase the run by $18,250, one removal reduces it by $4,100, and a $600 credit produces a net change of $13,550.',decision:'A reviewer compares the bridged total with the payment system before approval.'},
      {title:'Protect the release boundary',evidence:'Record preparer, reviewer, approver, file creator, bank submitter, and releaser as the company process defines them.',work:'Stop when a role conflict, missing approval, or unexplained file difference appears.',example:'The preparer can export the approved list but cannot submit it to the bank. A changed file hash after approval sends the run back for review.',decision:'Only the designated company users authorize and release funds.'},
      {title:'Verify the final run and carryovers',evidence:'After release, retain the approved proposal, final file or platform reference, bank result, failures, exclusions, and next-run assignments.',work:'Trace each cutoff exception to settlement, rejection, or a named carryover.',example:'A late invoice approved for inclusion fails account validation. The log keeps the failed result and assigns it to the remediation queue instead of marking it paid.',decision:'The run owner signs off the final population and every unresolved item.'}
    ]
  },
  {
    slug:'vendor-tax-document-expiry-queue',title:'Build a vendor tax-document expiry and refresh queue',keyword:'vendor tax document expiry queue',service:'tax-document-collection',serviceLabel:'tax document collection',image:'/blog-thumbnails/tax-document-collection-ap-workflow.svg',
    excerpt:'Track document type, receipt, review owner, expiry trigger, outreach, and unresolved status while leaving tax conclusions to authorized specialists.',question:'Which supplier record needs a current document, what triggered the review, and which authorized specialist decides whether the evidence is acceptable?',boundary:'AP support collects and tracks documents; the company tax, legal, or finance owner determines requirements, validity, classification, and payment consequences.',
    stages:[
      {title:'Define the document population',evidence:'List supplier ID, legal entity, company relationship, document type, issuing jurisdiction, received date, version, storage location, and review status.',work:'Use the company policy or specialist instruction to identify which records belong in the queue.',example:'A supplier profile holds two tax forms for different legal entities. The queue treats them as separate records instead of using the newest file for both.',decision:'The tax owner confirms the required document type and population.'},
      {title:'Record the actual refresh trigger',evidence:'Capture an explicit expiry date, policy review date, legal-name change, address change, classification change, notice, or other approved trigger.',work:'Do not invent annual expiry when the source document has none.',example:'One record enters the queue because a certificate states an end date; another enters because the supplier changed its legal name and the company policy requires review.',decision:'The specialist owner decides whether the trigger requires replacement, confirmation, or no action.'},
      {title:'Request documents through a verified path',evidence:'Use an approved portal or established supplier contact and retain the request date, requested document, secure submission method, response, and failed deliveries.',work:'Avoid collecting sensitive identifiers through an unapproved mailbox.',example:'A supplier replies from a new domain with a form and changed bank instructions. The form enters controlled review while the bank request follows a separate verification process.',decision:'Security and vendor-master owners handle channel or identity concerns.'},
      {title:'Check completeness without making a tax ruling',evidence:'Confirm the file is legible, names the expected supplier, includes required pages or fields identified by policy, and can be tied to the vendor record.',work:'Log blanks, conflicting names, and uncertain scope as review questions.',example:'The form is signed but names a parent entity that is not the payee. AP records the mismatch and routes it instead of selecting the parent record.',decision:'The tax or legal reviewer determines acceptability and classification.'},
      {title:'Control access and version history',evidence:'Store the document in the approved system with receipt time, reviewer, decision, effective date, superseded version, and access group.',work:'Link versions instead of overwriting the prior evidence.',example:'A corrected file replaces a blurred scan. Both remain traceable, and ordinary AP users see the status without receiving unnecessary sensitive fields.',decision:'The access owner approves permissions and retention treatment.'},
      {title:'Close outreach with a documented outcome',evidence:'Use outcomes such as accepted, replacement requested, supplier declined, unable to contact, duplicate record, or specialist review pending.',work:'Retain the next action and owner for unresolved suppliers.',example:'Three unanswered requests do not become an automatic payment hold unless the authorized policy owner directs that result.',decision:'Finance or tax owners approve any hold, release, or other consequence.'}
    ]
  },
  {
    slug:'employee-expense-merchant-credit-follow-up',title:'Follow up a merchant credit on an employee expense report',keyword:'employee expense merchant credit follow-up',service:'expense-report-review',serviceLabel:'expense report review',image:'/blog-thumbnails/expense-report-review-workflow.svg',
    excerpt:'Link the original charge, return evidence, expected credit, card statement, and employee response without netting unrelated expenses.',question:'Did the merchant issue the expected credit, did it reach the correct card or account, and how should the company resolve any difference?',boundary:'AP support traces evidence and maintains the follow-up; the employee confirms the purchase event, card administrators trace card activity, and finance approves accounting treatment.',
    stages:[
      {title:'Open the case from the original charge',evidence:'Record employee, card or reimbursement method, merchant, transaction date, posted date, currency, amount, report ID, business purpose, receipt, and approval.',work:'Keep the original expense unchanged while the credit is investigated.',example:'An employee returns a $740 monitor after the report was approved. The case links the approved charge rather than deleting it from the submitted report.',decision:'The expense owner confirms the original transaction and return reason.'},
      {title:'Document the return or cancellation',evidence:'Collect the return receipt, cancellation notice, merchant case, shipment tracking, refund promise, expected amount, destination, and promised timing.',work:'Separate merchant acceptance from the employee shipping an item.',example:'Tracking shows delivery on Monday, but the merchant accepts the return on Thursday with a stated restocking fee.',decision:'The employee or purchasing owner resolves commercial disputes about the accepted amount.'},
      {title:'Search the correct settlement record',evidence:'Compare pending and posted card transactions, statement periods, processor references, reimbursement records, and cash receipts using approved access.',work:'Check both the original card and any replacement account identified by the card administrator.',example:'The refund does not appear on the current statement because it posted on the first day of the next cycle under a shortened merchant name.',decision:'The card administrator confirms where the credit settled.'},
      {title:'Reconcile partial and foreign-currency credits',evidence:'Show original amount, refunded amount, fees, exchange effects, tax, and residual in their source currencies.',work:'Do not call a difference employee owed without owner review.',example:'A hotel refunds the room charge but keeps a cancellation fee; a foreign-currency credit also converts at a different rate from the original purchase.',decision:'Finance determines the accounting for fees and currency differences.'},
      {title:'Prevent double recovery',evidence:'Search employee repayments, payroll deductions, expense offsets, merchant credits, card disputes, and prior journals before proposing action.',work:'Link every recovery path to the same case.',example:'The employee already repaid the company while the merchant credit was pending. When the credit posts, finance must decide how to return or apply the excess.',decision:'Finance approves any reimbursement, clearing entry, or payroll correction.'},
      {title:'Close against the ledger and statement',evidence:'Retain the posted credit, statement reference, approved treatment, system entry, employee communication, and any residual owner.',work:'Reopen the case if a provisional credit reverses later.',example:'A card dispute creates a temporary credit that disappears after merchant evidence is reviewed, so the case stays open until the outcome is final.',decision:'The finance owner confirms that the expense and credit are fully reconciled.'}
    ]
  },
  {
    slug:'ap-mailbox-delivery-failure-triage',title:'Triage bounced and undeliverable messages from the AP mailbox',keyword:'AP mailbox delivery failure triage',service:'ap-inbox-management',serviceLabel:'AP inbox management',image:'/blog-thumbnails/ap-inbox-labels-and-routing.svg',
    excerpt:'Distinguish address errors, security rejections, supplier-domain changes, and closed cases while using verified contact paths.',question:'Why did the message fail, which business case is affected, and what verified channel should AP use next?',boundary:'AP support classifies the failure and follows approved contact procedures; security and system owners diagnose controls, while business owners decide the underlying invoice or supplier action.',
    stages:[
      {title:'Preserve the delivery evidence',evidence:'Keep the original outbound message ID, recipient, timestamp, subject, related case, bounce code, diagnostic text, and sending mailbox.',work:'Store headers in the approved location and avoid forwarding sensitive attachments for convenience.',example:'A 550 unknown-user response differs from a temporary  mailbox-full response and should not receive the same retry schedule.',decision:'The mailbox owner confirms which diagnostics may be handled by AP.'},
      {title:'Classify the failure before retrying',evidence:'Separate invalid address, blocked domain, authentication failure, attachment rejection, quota, policy filter, routing loop, and temporary service errors.',work:'Use the exact server response rather than guessing from the display text.',example:'A PDF message fails because of attachment policy while a plain-text status request succeeds, pointing to a channel constraint rather than an inactive supplier.',decision:'The system or security owner resolves technical controls outside the AP runbook.'},
      {title:'Connect the bounce to business risk',evidence:'Identify the invoice, statement, dispute, remittance, document request, due date, promised response, and current owner affected by the failed message.',work:'Prioritize by documented consequence instead of message age alone.',example:'A failed routine statement request can wait for normal follow-up, while a bounced correction request blocks an invoice approaching an approved payment cutoff.',decision:'The AP manager sets the business priority and escalation time.'},
      {title:'Find a contact through trusted records',evidence:'Check the supplier portal, verified vendor master, contract, prior confirmed correspondence, or named internal relationship owner.',work:'Do not trust replacement details contained only in an unexpected auto-reply.',example:'An auto-response names a new billing address and bank account. AP verifies the contact separately and routes the bank change through its own control.',decision:'Vendor-master or security owners approve changed contact paths.'},
      {title:'Retry without duplicating the case',evidence:'Record channel, recipient, time, content scope, delivery result, and response for each attempt under one case ID.',work:'Send only the information needed through the approved alternate channel.',example:'A portal message succeeds after email failure, so the queue links the portal receipt instead of creating a second unresolved supplier request.',decision:'The case owner decides when another channel satisfies the notice requirement.'},
      {title:'Close with a tested routing update',evidence:'Update permitted contact fields, mailbox rules, runbook notes, and open cases with the verified outcome and effective date.',work:'Preserve the former address and failure reason for history.',example:'A supplier domain migration affects five open cases; each is linked to the verified new contact and checked for a missed response.',decision:'The access or process owner approves any routing-rule change.'}
    ]
  },
  {
    slug:'goods-received-not-invoiced-close-packet',title:'Prepare a goods-received-not-invoiced review packet for close',keyword:'goods received not invoiced close packet',service:'month-end-ap-close-support',serviceLabel:'month-end AP close support',image:'/blog-thumbnails/ap-month-end-open-invoice-review.svg',
    excerpt:'Reconcile receipts, returns, expected invoices, service evidence, supplier follow-up, and finance ownership for cutoff decisions.',question:'Which open receipt represents an unbilled obligation at close, what evidence supports it, and what decision must finance make?',boundary:'AP support reconciles records and gathers evidence; receiving and purchasing confirm operational events, while finance owns cutoff, accrual, posting, reversal, and materiality decisions.',
    stages:[
      {title:'Define the close population',evidence:'Extract open receipts by entity, order, line, supplier, receipt date, quantity, value, currency, location, and close period at a recorded time.',work:'Retain the source snapshot so later receipts and invoices do not rewrite the population.',example:'A receipt posted after the extract belongs to the next review version, while a backdated receipt requires separate finance attention.',decision:'Finance confirms the cutoff and population rules.'},
      {title:'Prove the receipt event',evidence:'Link delivery documents, system receipts, service entries, inspection results, return records, and the employee who confirmed receipt.',work:'Distinguish physical arrival, acceptance, and system posting.',example:'Goods arrived before close but failed inspection and were returned after a provisional receipt; the packet shows all three events.',decision:'Receiving or the service owner confirms what was actually accepted.'},
      {title:'Search for invoices beyond the matched queue',evidence:'Check approved inboxes, portals, rejected submissions, blocked workflows, wrong-entity queues, statements, and supplier correspondence.',work:'Record search scope and extraction time.',example:'The invoice exists in a rejected OCR queue because its order number was truncated, so it is unprocessed rather than missing.',decision:'AP management assigns the correct intake and exception path.'},
      {title:'Reconcile quantity and value',evidence:'Show ordered, received, reversed, returned, invoiced, credited, and remaining quantities and values by line and unit.',work:'Keep price, currency, tax, freight, and unit conversions explicit.',example:'Ten cases were received but the order and expected invoice use individual units; the pack conversion explains the apparent overstatement.',decision:'Purchasing resolves commercial differences and finance decides the close amount.'},
      {title:'Ask the supplier a bounded question',evidence:'Use a verified contact and request invoice status, reference, amount, service period, or reason no invoice is expected.',work:'Avoid sharing unrelated receipt or pricing data.',example:'The supplier confirms that a shipment was a free replacement, while another open receipt awaits a consolidated month-end invoice.',decision:'The business owner validates any claim that no liability remains.'},
      {title:'Deliver a reproducible close disposition',evidence:'Classify each line as invoice located, expected, returned, duplicate receipt, wrong entity, no charge supported, or unresolved with an owner.',work:'Preserve the source evidence and decision reference.',example:'An unresolved service entry stays in the packet with the project owner and response date rather than disappearing from the aging total.',decision:'Finance approves the accrual, exclusion, posting, and later reversal treatment.'}
    ]
  },
  {
    slug:'invoice-aging-dispute-milestone-review',title:'Review dispute milestones before escalating an aged invoice',keyword:'invoice aging dispute milestone review',service:'aging-report-preparation',serviceLabel:'aging report preparation',image:'/blog-thumbnails/ap-aging-report-preparation.svg',
    excerpt:'Measure age from meaningful events, identify the current decision owner, and avoid escalating invoices that await a documented supplier correction.',question:'What happened since receipt, which party owns the next answer, and does the invoice need escalation or a different follow-up?',boundary:'AP support reconstructs milestones and manages the queue; business, purchasing, legal, tax, or finance owners decide the dispute, accounting, approval, and payment outcome.',
    stages:[
      {title:'Separate invoice age from dispute age',evidence:'Keep invoice date, company receipt, due date, first exception, dispute opening, last evidence, owner response, and supplier promise as distinct fields.',work:'State the timezone and whether elapsed days are calendar or business days.',example:'A 70-day-old invoice may have a five-day-old dispute after a late price exception was discovered; both ages belong in the review.',decision:'The AP owner selects the measures used for queue priority.'},
      {title:'Rebuild the milestone chain',evidence:'Link intake, validation, match, approval, rejection, correction request, supplier reply, credit promise, and reopened review in time order.',work:'Preserve gaps and conflicting accounts instead of forcing a smooth story.',example:'The supplier says it answered two weeks ago, but the reply went to an inactive employee and never reached the case.',decision:'The process owner determines where the handoff failed and who now responds.'},
      {title:'Name the present blocking question',evidence:'Write the disputed field, amount, source conflict, evidence already checked, requested answer, and owner in one case note.',work:'Split unrelated issues that need different authorities.',example:'A price difference belongs with purchasing, while a tax-line question on the same invoice requires a specialist review.',decision:'Each named owner decides only the part within that role.'},
      {title:'Use escalation for action, not visibility',evidence:'Select the escalation path from amount, due status, operational effect, broken commitment, security concern, and owner response target.',work:'Avoid copying senior staff when the case lacks an answerable request.',example:'A supplier collection notice does not bypass the purchasing owner; the escalation packet includes the contract line, invoice variance, and overdue decision.',decision:'The AP manager applies the company escalation rule.'},
      {title:'Reset milestones when evidence changes',evidence:'Add corrected invoices, credits, approvals, partial resolutions, and new promises as events without erasing the first dispute.',work:'Recalculate only the measures whose starting event truly changed.',example:'A corrected invoice resolves quantity but retains the original disputed freight fee, so one branch closes and the freight branch continues.',decision:'The owner confirms which issue is resolved and which remains open.'},
      {title:'Close with a reason and monitor recurrence',evidence:'Record approved, corrected, credited, rejected, duplicate, withdrawn, paid, or unresolved transfer outcomes with system references.',work:'Group later cases by actual cause and missed milestone.',example:'Repeated supplier delays after promised credits point to a different remedy than repeated internal approval gaps.',decision:'Finance and process owners choose corrective action while AP maintains the evidence.'}
    ]
  }
];

export const remainingOct2BlogDrafts=inputs.map(build);
