type Spec={slug:string;title:string;excerpt:string;keyword:string;focus:string;records:string;owner:string};
const date='2026-08-31' as const;
const specs:Spec[]=[
{slug:'ap-invoice-intake-completeness-gate',title:'Build an AP invoice intake completeness gate',excerpt:'Stop incomplete invoices from disappearing into the approval queue with a visible, owner-led intake check.',keyword:'AP invoice intake completeness gate',focus:'decide whether a newly received invoice has the evidence required to enter the working queue',records:'the original message, readable invoice, supplier identity, invoice number, date, entity, amount, and required purchase evidence',owner:'the invoice process owner'},
{slug:'ap-vendor-duplicate-identity-check',title:'Check duplicate vendor identities before invoice entry',excerpt:'Compare supplier records without merging, changing, or approving vendor master data from the support desk.',keyword:'AP duplicate vendor identity check',focus:'identify possible duplicate supplier records without treating similarity as permission to merge them',records:'legal name, vendor IDs, tax-document reference, remit address, approved contact, currency, and payment method',owner:'the vendor-master owner'},
{slug:'ap-po-balance-exception-register',title:'Create an AP purchase order balance exception register',excerpt:'Make invoices that exceed or conflict with purchase order balances easy to investigate and route.',keyword:'AP PO balance exception register',focus:'show exactly why an invoice line conflicts with an available purchase order balance',records:'ordered, received, previously invoiced, and newly invoiced values plus unit, currency, freight, and tax',owner:'the purchasing or finance owner'},
{slug:'ap-payment-hold-release-packet',title:'Prepare an AP payment hold release packet',excerpt:'Give finance owners the evidence needed to review a hold without letting support staff release funds.',keyword:'AP payment hold release packet',focus:'preserve the reason a payment was held and show what evidence changed afterward',records:'the original hold, invoice and supplier identifiers, verification results, corrections, approvals, and chronology',owner:'the authorized payment owner'},
{slug:'ap-shared-inbox-chain-of-custody',title:'Document chain of custody in a shared AP inbox',excerpt:'Track how invoice emails and attachments move from receipt through review without losing the original source.',keyword:'AP inbox chain of custody',focus:'trace an invoice from its original message through every classification and queue handoff',records:'sender, recipients, subject, receipt time, original attachments, stable file reference, routing actions, and current owner',owner:'the AP operations owner'},
{slug:'ap-approval-delegation-coverage-plan',title:'Plan AP approval coverage without informal delegation',excerpt:'Keep invoices moving during leave while preserving the company approval matrix and audit trail.',keyword:'AP approval delegation coverage',focus:'map planned absences to valid backup approvers before invoices become stranded',records:'entity, cost center, amount limit, invoice type, delegate, effective dates, and system authorization',owner:'the approval-matrix owner'},
{slug:'ap-supplier-statement-cutoff-review',title:'Run a supplier statement cutoff review',excerpt:'Compare statement activity with the AP ledger at a defined cutoff and route missing items before close.',keyword:'AP supplier statement cutoff review',focus:'reconcile supplier and ledger documents without mixing activity from different reporting times',records:'statement and ledger timestamps, entity, currency, invoices, credits, payments, remittances, and residual differences',owner:'the close or reconciliation owner'},
{slug:'ap-urgent-payment-request-triage',title:'Triage urgent AP payment requests safely',excerpt:'Respond to urgency with a repeatable evidence path instead of bypassing approval and verification controls.',keyword:'urgent AP payment request triage',focus:'turn an urgent request into verified facts and an attributable company decision',records:'requester, channel, invoice, deadline, stated consequence, supplier verification, duplicate status, approval, and hold status',owner:'the finance and payment owners'},
{slug:'ap-invoice-coding-confidence-notes',title:'Use confidence notes for AP invoice coding',excerpt:'Help reviewers focus on uncertain coding without allowing support staff to make accounting judgments.',keyword:'AP invoice coding confidence notes',focus:'explain why a code was proposed and expose evidence that needs accounting judgment',records:'the purchase order, contract, chart guidance, prior approved example, proposed code, differences, and owner question',owner:'the accounting owner'},
{slug:'ap-remittance-confirmation-workflow',title:'Build an AP remittance confirmation workflow',excerpt:'Prepare accurate remittance notices while keeping payment authorization and bank details under company control.',keyword:'AP remittance confirmation workflow',focus:'create notices only from final authorized payment results and verified supplier contacts',records:'payment date, amount, currency, reference, applied documents, recipient, delivery time, result, and response',owner:'the payment operations owner'},
{slug:'ap-close-open-item-owner-map',title:'Map owners for AP close open items',excerpt:'Turn month-end AP questions into a bounded queue with evidence, decisions, and deadlines.',keyword:'AP close open item owner map',focus:'make every close item state the missing evidence, next decision, accountable employee, and checkpoint',records:'report scope, source timestamp, entity, document, amount, first-seen date, requests, responses, and close impact',owner:'the authorized accounting owner'},
{slug:'ap-quality-sample-correction-loop',title:'Create an AP quality sample and correction loop',excerpt:'Review a transparent sample of prepared AP work and turn corrections into clearer operating rules.',keyword:'AP quality sample correction loop',focus:'review a reproducible sample and convert recurring corrections into owned rule improvements',records:'population, sampling method, exclusions, source evidence, working record, correction type, remediation, and review date',owner:'the AP control owner'},
];
const sections=(s:Spec)=>[
 {title:`Define the ${s.keyword} record`,paragraphs:[`Start by stating the population, source system, review time, legal entity, and employee owner. The purpose is to ${s.focus}.`, `Keep ${s.records} linked to the working item. Record a missing value as missing instead of filling it from memory or a convenient prior example.`]},
 {title:'Separate preparation from authority',paragraphs:[`Outsourced AP support may gather approved sources, compare fields, document conflicts, request missing evidence, and update factual status. ${s.owner} retains the decision that changes company records, accounting treatment, approval, or payment.`, `Use clear states such as preparing, waiting for evidence, held for verification, waiting for owner, approved by owner, or closed after a recorded response. A prepared packet is not an approval.`]},
 {title:'Preserve chronology and test the handoff',paragraphs:[`Retain receipt, review, follow-up, response, and decision times. If evidence changes, keep the earlier version and describe the difference rather than silently replacing history.`, `Test an ordinary item, an incomplete item, a conflicting item, and an urgent item. Another reviewer should be able to reproduce the checks, identify the outstanding question, and find ${s.owner} without asking the original operator.`]},
];
export const aug31BlogPublicationDates=Object.fromEntries(specs.map(s=>[s.slug,date])) as Record<string,typeof date>;
export const aug31BlogPosts=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:9}));
export const aug31BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,shortAnswer:`Use a controlled evidence packet to ${s.focus}, then route the decision to ${s.owner}.`,sections:sections(s),faqs:[{question:`What can outsourced support do with ${s.keyword}?`,answer:`It can prepare evidence, document gaps, follow up through approved channels, and maintain status. ${s.owner} retains approval and judgment.`},{question:'What should the handoff retain?',answer:`Retain ${s.records}, the checks performed, the unresolved question, and the authorized response.`}]}]));
