type Section = {title: string; paragraphs: string[]};
type Spec = {slug: string; title: string; keyword: string; excerpt: string; sections: Section[]};

const source = {name: 'NIST, Least Privilege', url: 'https://csrc.nist.gov/glossary/term/least_privilege', note: 'Limit access to the minimum resources needed for assigned AP work.'};

// Each August 17 route has its own literal source-date binding.
export const aug17BlogPublicationDates: Record<string, string> = {
  'ap-invoice-receipt-discrepancy-review': '2026-08-17',
  'ap-invoice-service-period-checks': '2026-08-17',
  'ap-invoice-remittance-account-checks': '2026-08-17',
  'ap-invoice-unit-price-exception-notes': '2026-08-17',
  'ap-invoice-tax-field-review': '2026-08-17',
  'ap-invoice-currency-mismatch-workflow': '2026-08-17',
  'ap-invoice-legal-entity-review': '2026-08-17',
  'ap-invoice-contract-reference-checks': '2026-08-17',
  'ap-invoice-credit-balance-review': '2026-08-17',
  'ap-invoice-approval-commentary-guide': '2026-08-17',
  'ap-invoice-queue-aging-buckets': '2026-08-17',
  'ap-invoice-requester-follow-up': '2026-08-17',
  'ap-invoice-early-receipt-review': '2026-08-17',
  'ap-invoice-vendor-name-variation-checks': '2026-08-17',
  'ap-invoice-attachment-completeness-rules': '2026-08-17',
  'ap-invoice-approval-deadline-map': '2026-08-17',
  'ap-invoice-payment-proposal-review': '2026-08-17',
  'ap-invoice-coding-memo-fields': '2026-08-17',
  'ap-invoice-reopened-item-control': '2026-08-17',
  'ap-invoice-duplicate-vendor-email-review': '2026-08-17',
  'ap-invoice-close-exception-summary': '2026-08-17',
  'ap-invoice-reviewer-backup-handoff': '2026-08-17',
};

const specs: Spec[] = [
  {slug:'ap-invoice-receipt-discrepancy-review',title:'How AP teams should review invoice and receipt discrepancies',keyword:'invoice and receipt discrepancies',excerpt:'A practical review path for separating missing receiving evidence from genuine quantity or service disputes.',sections:[{title:'Start with the two source records',paragraphs:['Compare the invoice line, purchase order, and receiving record before describing a discrepancy. Record the identifiers and the exact field that does not agree.','Do not label an invoice “wrong” because a receipt is absent. Missing evidence and a confirmed mismatch require different next actions.']},{title:'Route the question to the right owner',paragraphs:['Ask the requester or receiving owner to confirm delivery, quantity, or service completion. Keep the invoice paused while that evidence is gathered.','The AP support role can prepare the comparison and follow up; it should not accept a substitute receipt or approve an exception.']},{title:'Make the note reusable',paragraphs:['Write one sentence stating what agrees, what differs, and what evidence is still needed. Link the note to the packet rather than burying it in an email thread.','A useful note lets a reviewer resume the item without repeating the entire search.']}]},
  {slug:'ap-invoice-service-period-checks',title:'Invoice service-period checks for outsourced AP support',keyword:'invoice service-period checks',excerpt:'Use service dates and source evidence to flag period questions before an invoice reaches approval.',sections:[{title:'Capture the period evidence',paragraphs:['Record the invoice service dates, contract or order reference, and the person who can confirm completion. A date on the invoice alone may not explain the accounting period.','Separate an incomplete packet from a disagreement about when the service occurred.']},{title:'Keep period judgment with finance',paragraphs:['Prepare the comparison and ask a named owner to decide how the item should be handled. Do not alter dates to make a queue appear complete.','If the owner requests a change, retain the original source and the reason for the approved correction.']},{title:'Review recurring questions',paragraphs:['Track repeated service-period questions by vendor or process. The pattern may call for clearer purchase requests or a better close checklist.','Measure whether evidence arrives before the cutoff, not just whether a message was sent.']}]},
  {slug:'ap-invoice-remittance-account-checks',title:'Remittance-account checks before AP payment preparation',keyword:'remittance-account checks',excerpt:'A bounded control for comparing remittance information without accepting a payment-detail change in the support queue.',sections:[{title:'Compare approved sources',paragraphs:['Use the approved vendor record and the invoice remittance details as separate sources. Record an agreement or mismatch without overwriting either source.','A new account, changed contact, or urgent instruction is a stop signal, not a routine data-cleaning task.']},{title:'Use independent verification',paragraphs:['Route a mismatch to the company’s approved verification process using a known contact path. Never rely solely on the message that requested the change.','The support role can log the request and assemble evidence; an authorized employee decides whether any record may change.']},{title:'Close the loop safely',paragraphs:['Keep the request, verification evidence, decision, and date together. If verification fails, leave the payment preparation item blocked.','Review access to vendor records regularly and remove permissions that are no longer needed.']}]},
  {slug:'ap-invoice-unit-price-exception-notes',title:'Invoice unit-price exception notes that finance owners can act on',keyword:'invoice unit-price exception notes',excerpt:'Turn a unit-price difference into a factual question with the source line, owner, and next action visible.',sections:[{title:'Describe the exact difference',paragraphs:['State the invoice quantity, unit price, order value, and any receipt evidence. Avoid conclusions such as “vendor error” until the owner reviews the source records.','Use the same units and currency shown in the documents so the reviewer can reproduce the comparison.']},{title:'Ask one decision question',paragraphs:['Send the discrepancy to the requester, buyer, or finance owner who can explain the approved terms. Keep unrelated invoice fields out of the question.','AP support should not edit the order, approve the variance, or promise the supplier an outcome.']},{title:'Track resolution evidence',paragraphs:['When the owner responds, attach the response to the packet and record whether the invoice proceeds, waits, or needs a corrected document.','Sample resolved notes for clarity and completeness rather than rewarding the fastest closure.']}]},
  {slug:'ap-invoice-tax-field-review',title:'AP invoice tax-field review before finance approval',keyword:'invoice tax-field review',excerpt:'Check visible tax fields and source completeness while keeping tax treatment decisions with the responsible finance owner.',sections:[{title:'Check what the invoice actually shows',paragraphs:['Record the billed amount, tax label, jurisdiction shown, and whether the supporting document is readable. A missing field is different from an incorrect tax treatment.','Use the approved entity and vendor records as context, not as permission to invent a tax answer.']},{title:'Escalate uncertainty',paragraphs:['Route questions about classification, exemption, or treatment to the named finance or tax owner. Keep the original document unchanged.','The support role can request a corrected invoice or missing certificate when instructed, but cannot certify the result.']},{title:'Protect the review trail',paragraphs:['Keep the question, source, owner response, and final disposition in the packet. This makes later review possible without relying on memory.','Add recurring gaps to vendor communication guidance or intake requirements.']}]},
  {slug:'ap-invoice-currency-mismatch-workflow',title:'Invoice currency mismatch workflow for AP support teams',keyword:'invoice currency mismatch workflow',excerpt:'Handle currency differences by documenting the invoice, order, and approved record before anyone decides how to post or pay.',sections:[{title:'Identify the competing currencies',paragraphs:['Write down the currency on the invoice, purchase order, contract, and vendor record. Also capture the invoice number and source dates.','Do not convert an amount in the support queue unless the written process specifies the source and rate for that preparation step.']},{title:'Separate data from accounting judgment',paragraphs:['Ask the finance owner whether the difference reflects an approved term, a vendor correction, or an accounting question. Leave the item clearly stopped.','A support specialist may prepare a comparison but should not choose the posting currency or payment amount.']},{title:'Make future intake clearer',paragraphs:['Record the rule that would have prevented the mismatch, such as a required currency field on the purchase request.','Review unresolved currency items at close so they do not disappear in a general exception list.']}]},
  {slug:'ap-invoice-legal-entity-review',title:'Legal-entity review for invoices in multi-entity AP',keyword:'legal-entity invoice review',excerpt:'A source-led checklist for flagging entity mismatches before invoice coding or approval.',sections:[{title:'Match the entity evidence',paragraphs:['Compare the bill-to entity, purchase order entity, vendor record, and requester. Record each source even when the mismatch looks obvious.','A familiar vendor name does not prove that the invoice belongs to the same entity as a prior invoice.']},{title:'Pause unexpected changes',paragraphs:['Route an entity mismatch to the finance owner or requester who can confirm the obligation. Do not recode or approve the invoice to clear the queue.','Keep the original packet and the owner’s decision together.']},{title:'Use patterns to improve intake',paragraphs:['If the same entity is repeatedly unclear, add an entity field or approval check to the purchase request.','Review the exception log during close planning and assign one owner to unresolved items.']}]},
  {slug:'ap-invoice-contract-reference-checks',title:'Contract-reference checks for recurring AP invoices',keyword:'contract-reference checks',excerpt:'Help finance teams verify recurring invoices against the right agreement without interpreting contract terms beyond the assigned role.',sections:[{title:'Locate the reference',paragraphs:['Capture the contract or order identifier, invoice period, billed service, and the source location used for the comparison.','If no reference exists, mark the evidence gap plainly rather than guessing which agreement applies.']},{title:'Ask for the owner’s confirmation',paragraphs:['The business owner should confirm that the service was received and that the charge follows the approved terms. AP support can prepare the question and follow up.','Do not interpret renewal, termination, or disputed terms as an approval decision.']},{title:'Keep recurring packets consistent',paragraphs:['Use a stable packet order for the reference, invoice, confirmation, and approval evidence. Consistency makes sampling more useful.','When a contract changes, request an updated source before continuing the recurring queue.']}]},
  {slug:'ap-invoice-credit-balance-review',title:'Credit-balance review when an AP invoice is already open',keyword:'invoice credit-balance review',excerpt:'Connect open credits, invoices, and owner decisions without applying a credit automatically.',sections:[{title:'Gather the open-item picture',paragraphs:['List the invoice, credit memo, vendor statement, and relevant ledger identifiers. Note dates and amounts exactly as shown in source records.','Do not assume the oldest invoice is the correct application target.']},{title:'Route application decisions',paragraphs:['Ask the finance owner to confirm whether the credit is valid and how it should be applied. AP support can prepare the match and request clarification.','Keep disputed or duplicate-looking credits outside the routine application queue.']},{title:'Review aged credits',paragraphs:['Use an aged open-credit list to identify items needing owner attention. Include the last action and next review date.','A credit is not resolved merely because an email was sent; retain the disposition evidence.']}]},
  {slug:'ap-invoice-approval-commentary-guide',title:'Useful approval commentary for AP invoice packets',keyword:'invoice approval commentary',excerpt:'Write concise packet notes that give an approver context without turning support commentary into an approval.',sections:[{title:'State the evidence',paragraphs:['Open with the invoice identifier, source documents checked, and any missing or conflicting field. Avoid adjectives that imply a conclusion.','A reviewer should be able to tell what the support role observed and what remains for the owner.']},{title:'Keep the request narrow',paragraphs:['Ask one approval question and name the person responsible. If there are multiple risks, list them separately rather than hiding them in a long paragraph.','Do not write “approved,” “safe to pay,” or similar language on behalf of an employee.']},{title:'Standardize without flattening judgment',paragraphs:['Use a short template for identifiers, evidence, exception, owner, and due date. Leave room for the owner’s actual decision.','Sample commentary for missing evidence and resolved exceptions to ensure the template does not encourage shortcuts.']}]},
  {slug:'ap-invoice-queue-aging-buckets',title:'How to use AP invoice queue aging buckets',keyword:'invoice queue aging buckets',excerpt:'Create aging buckets that reveal waiting time and ownership without confusing age with risk or approval.',sections:[{title:'Define the clock',paragraphs:['Choose a clear start point such as receipt or complete-packet date, and record it on every item. Do not mix message age with invoice age.','Separate waiting for evidence, waiting for approval, and ready-for-payment preparation.']},{title:'Add ownership and reason',paragraphs:['Each bucket should show the current owner, the blocked reason, and the next action. An old item without an owner is a control gap.','Use risk or cutoff flags separately from age so urgent new work is not hidden.']},{title:'Review movement, not just totals',paragraphs:['At a recurring review, compare items entering, moving, and leaving each bucket. Investigate items that remain unchanged.','Use the results to improve handoffs and escalation rules rather than setting a volume target alone.']}]},
  {slug:'ap-invoice-requester-follow-up',title:'Requester follow-up for incomplete AP invoice packets',keyword:'requester follow-up',excerpt:'Ask for missing purchase, receipt, or approval evidence in a way that makes the next action unambiguous.',sections:[{title:'Name the missing item',paragraphs:['Reference the invoice and state exactly what is absent: a receipt, purchase order, business purpose, or approval. Avoid asking for “more information” without a field.','Include the source location and the date the invoice entered the queue.']},{title:'Set a clear stop point',paragraphs:['Explain that the packet remains paused until the missing evidence arrives or the named owner provides a documented decision.','Do not promise a payment date or suggest that the requester bypass a normal approval.']},{title:'Escalate repeated gaps',paragraphs:['Track unanswered requests with an owner and review date. Repeated gaps may indicate an intake or purchasing problem.','Keep the follow-up in the packet so the next reviewer can see the full history.']}]},
  {slug:'ap-invoice-early-receipt-review',title:'Early receipt review for AP month-end readiness',keyword:'early receipt review',excerpt:'Use open receipts to identify likely invoice or accrual questions before the close deadline.',sections:[{title:'Compare receipt and invoice queues',paragraphs:['List open receipts with requester, order, vendor, date, and known invoice status. Treat the list as a prompt for evidence, not proof that an expense must be recorded.','Reconcile identifiers before combining records from different systems.']},{title:'Ask the business owner',paragraphs:['Request confirmation of delivery or service completion and whether an invoice is expected. Leave accounting treatment with the finance owner.','Record “no response” as a status rather than assuming the receipt is invalid.']},{title:'Prepare the close handoff',paragraphs:['Summarize open receipts by owner, evidence status, and next action. Include the cutoff date used for the review.','Keep the source report and the follow-up trail available for the close reviewer.']}]},
  {slug:'ap-invoice-vendor-name-variation-checks',title:'Vendor-name variation checks in AP invoice intake',keyword:'vendor-name variation checks',excerpt:'Flag name differences without creating duplicate vendors or changing master data in the intake queue.',sections:[{title:'Compare identifiers beyond the name',paragraphs:['Check the vendor record, invoice remit-to details, tax identifier where permitted, and known source references. A punctuation difference may be harmless; a changed account is not.','Record the exact fields that support the comparison.']},{title:'Separate review from maintenance',paragraphs:['Route uncertain matches to the vendor-master owner. AP support may prepare evidence but should not create, merge, or edit a vendor record without authorized review.','Keep a new or changed payment instruction paused until independent verification is complete.']},{title:'Reduce repeated ambiguity',paragraphs:['Add a controlled alias or required reference only through the approved master-data process. Do not maintain an informal shadow list as the source of truth.','Sample name-variation cases to confirm the escalation path is working.']}]},
  {slug:'ap-invoice-attachment-completeness-rules',title:'Attachment-completeness rules for AP invoice packets',keyword:'attachment completeness rules',excerpt:'Define what a reviewable packet contains and how to stop incomplete attachments from moving forward.',sections:[{title:'Define “complete” by invoice type',paragraphs:['A purchase-order invoice may need the order and receipt evidence; a non-PO invoice may need a business owner and approval trail. Write the rule for each lane.','Check page count, readability, and whether the attachment belongs to the invoice identifier.']},{title:'Record missing evidence precisely',paragraphs:['Name the missing page or source and send one focused request. Do not mark a packet complete because a file exists if it cannot be read or tied to the invoice.','Keep the item stopped until an owner resolves the gap.']},{title:'Review packet quality',paragraphs:['Sample complete packets for source traceability and stopped packets for clear next actions.','If the same attachment problem recurs, improve the intake instruction or vendor request.']}]},
  {slug:'ap-invoice-approval-deadline-map',title:'Mapping invoice approval deadlines for AP teams',keyword:'invoice approval deadlines',excerpt:'Turn close and payment-run dates into a visible approval map while preserving the approver’s decision.',sections:[{title:'Start from real cutoff dates',paragraphs:['List the payment run, close cutoff, review lead time, and backup coverage. Explain which date is operational and which is a finance decision.','Do not turn an internal target into a promise to a vendor.']},{title:'Show waiting ownership',paragraphs:['For each pending invoice, show the current approver, last follow-up, evidence status, and escalation date.','A reminder is useful only when it reaches the correct owner and leaves a record.']},{title:'Handle missed deadlines honestly',paragraphs:['If a date passes, flag the item and route the decision; do not silently change the due date or remove the exception.','Review missed deadlines for process causes such as incomplete packets or unclear backup rules.']}]},
  {slug:'ap-invoice-payment-proposal-review',title:'Payment-proposal review before an AP run',keyword:'payment-proposal review',excerpt:'Prepare a reviewable payment proposal with source checks and clear exclusions before authorized employees approve and release it.',sections:[{title:'Build from approved records',paragraphs:['Use the approved invoice queue, vendor record, due-date evidence, and exception list. Record the source date for the proposal.','Do not add an item because a vendor asks for urgency or remove one to make totals convenient.']},{title:'Make exclusions visible',paragraphs:['List invoices held for missing evidence, changed bank details, duplicate risk, or owner decision. An exclusion should have a reason and next action.','Keep preparation separate from approval, bank verification, and release.']},{title:'Require owner sign-off',paragraphs:['The authorized employee reviews the proposal against company policy and makes the payment decision. Preserve that approval evidence with the run.','After the run, reconcile the result and document any item that changed status.']}]},
  {slug:'ap-invoice-coding-memo-fields',title:'Fields to include in an AP invoice coding memo',keyword:'invoice coding memo fields',excerpt:'Use a coding memo to show source evidence and questions without turning a preparer into the final accounting decision-maker.',sections:[{title:'Capture the source context',paragraphs:['Include invoice identifier, entity, supplier, line description, order or contract reference, and the source used for each proposed field.','Mark uncertain fields rather than filling them with a familiar default.']},{title:'State what needs review',paragraphs:['Ask the finance owner to confirm account, department, project, tax, or allocation questions. Keep proposed values visibly separate from approved values.','A memo supports review; it does not replace approval evidence.']},{title:'Learn from corrections',paragraphs:['Track recurring corrections and update examples only after the owner confirms the rule.','Review a mix of straightforward and exception memos to test whether the fields reveal uncertainty.']}]},
  {slug:'ap-invoice-reopened-item-control',title:'Controls for reopened AP invoice items',keyword:'reopened invoice item control',excerpt:'Keep reopened invoices traceable when new evidence or an owner decision changes a previously closed item.',sections:[{title:'Preserve the prior state',paragraphs:['Record why the item was reopened, who requested it, and what prior evidence or decision remains valid. Never overwrite the earlier trail.','Assign a new next action and review date.']},{title:'Recheck changed fields',paragraphs:['Compare the new document or message with the prior packet and identify the exact changed field.','Route approval, vendor, or payment-impacting changes to the proper owner instead of treating the item as routine rework.']},{title:'Close with a fresh decision',paragraphs:['Document the owner’s updated disposition and retain both versions of relevant source records.','Review reopened items periodically; a high rate may indicate weak intake checks or unclear close rules.']}]},
  {slug:'ap-invoice-duplicate-vendor-email-review',title:'Duplicate risk checks for vendor email invoice submissions',keyword:'duplicate vendor email submissions',excerpt:'Detect repeated invoice submissions from vendor email without deleting evidence or assuming that similar messages are duplicates.',sections:[{title:'Compare the meaningful fields',paragraphs:['Check vendor, invoice number, amount, date, line description, attachment hash or filename, and related order. Similar subjects alone are not enough.','Keep both messages available until the comparison is complete.']},{title:'Route ambiguous matches',paragraphs:['If a credit, corrected invoice, or split billing explains the similarity, ask the finance or vendor owner to confirm. Do not discard the second record.','Mark one record as a possible duplicate and link the evidence.']},{title:'Improve inbox handling',paragraphs:['Use consistent labels for original, correction, duplicate risk, and owner review.','Sample the queue to ensure labels reflect evidence and not just the first impression.']}]},
  {slug:'ap-invoice-close-exception-summary',title:'AP close exception summaries that support decisions',keyword:'AP close exception summaries',excerpt:'Summarize open invoice exceptions so finance owners can make close decisions from evidence rather than scattered messages.',sections:[{title:'Group by decision needed',paragraphs:['Separate missing source evidence, approval delay, vendor correction, duplicate risk, and accounting questions. Similar-looking items may need different owners.','Include invoice identifier, amount as shown, age, source status, and cutoff relevance.']},{title:'Make ownership explicit',paragraphs:['Every row needs a named owner, last action, next action, and review date. Avoid a generic “finance” queue.','The support role prepares the summary; owners decide treatment, approval, and escalation.']},{title:'Keep the summary bounded',paragraphs:['Link each row to its source packet and preserve the underlying evidence. A summary should help review, not become the only record.','After close, record which rules or intake fields would reduce repeat exceptions.']}]},
  {slug:'ap-invoice-reviewer-backup-handoff',title:'Reviewer-backup handoffs for AP invoice approvals',keyword:'reviewer-backup handoffs',excerpt:'Document temporary reviewer coverage so an AP support lane knows who can answer questions without inventing authority.',sections:[{title:'Define the coverage window',paragraphs:['Record the primary reviewer, backup, dates, scope, and the source of the delegation. Coverage should be time-bounded and easy to verify.','Do not infer authority from an out-of-office reply or a copied email.']},{title:'Route decisions carefully',paragraphs:['Send routine packets through the documented backup path and escalate items outside its scope. Payment release and vendor changes may require separate authority.','Keep the delegation evidence with the affected approvals.']},{title:'Return to normal ownership',paragraphs:['When the window ends, update the queue and remove obsolete backup access. Review any items that crossed the coverage boundary.','A short post-coverage check prevents temporary arrangements from becoming permanent exceptions.']}]},
  {slug:'ap-invoice-work-queue-reconciliation',title:'Reconciling the AP work queue to source records',keyword:'AP work-queue reconciliation',excerpt:'Compare queue status with inbox, ledger, and approval sources so missing or stale invoice items become visible.',sections:[{title:'Choose the population',paragraphs:['Define the date range and systems included in the reconciliation. Record the extraction time because queues change during the day.','Use stable identifiers to match records; do not rely on supplier name alone.']},{title:'Classify differences',paragraphs:['Separate missing queue items, stale statuses, duplicates, and legitimate timing differences. Each class needs a different owner or follow-up.','Preserve the comparison file or evidence needed to reproduce the result.']},{title:'Turn findings into actions',paragraphs:['Assign each difference a next action and date. A reconciliation is not complete when the counts match if exceptions remain unexplained.','Review repeated differences with the system or process owner.']}]},
  {slug:'ap-invoice-support-scope-review',title:'Quarterly AP support-scope review checklist',keyword:'AP support-scope review',excerpt:'Review whether an outsourced AP support lane still has the right tasks, access, examples, and escalation boundaries.',sections:[{title:'Compare work with the written scope',paragraphs:['List actual queues handled, exceptions encountered, approvals touched, and systems accessed. Compare that list with the role’s approved scope.','Unexpected work should be paused and reviewed, not normalized by habit.']},{title:'Check access and evidence',paragraphs:['Confirm permissions still match assigned tasks and that completed packets retain the required source and decision evidence.','Review who can view vendor, invoice, and payment information and remove stale access.']},{title:'Decide what changes',paragraphs:['The finance owner should approve any scope, access, or escalation change and update the written procedure.','Keep the review record with the role documentation so the next review starts from facts.']}]},
];

function detail(spec: Spec) {
  return {mainKeyword: spec.keyword, published: aug17BlogPublicationDates[spec.slug], modified: aug17BlogPublicationDates[spec.slug], shortAnswer: spec.excerpt + ' The support role prepares evidence and routes decisions to the finance owner.', sections: spec.sections, bodyLinks:[{href:'/services/ap-inbox-management',label:'AP inbox management'},{href:'/services/invoice-data-capture',label:'invoice data capture support'}], relatedLinks:[{href:'/services/three-way-match-support',label:'three-way match support'},{href:'/services/payment-run-preparation',label:'payment-run preparation'}], sources:[source], faqs:[{question:`What should support do with ${spec.keyword}?`,answer:`Support can gather source records, check required fields, and document exceptions. The finance owner keeps approval, accounting judgment, vendor changes, and payment release.`},{question:'What should happen when evidence is missing?',answer:'Pause the item, name the missing evidence, and route a dated request to the responsible owner.'}]};
}

export const aug17BlogPosts = specs.map((spec, index) => ({slug: spec.slug, title: spec.title, excerpt: spec.excerpt, minutes: 11 + (index % 5)}));
export const aug17BlogDetails = Object.fromEntries(specs.map(spec => [spec.slug, detail(spec)]));
