type Spec={slug:string;title:string;excerpt:string;keyword:string;goal:string;evidence:string;owner:string;scenario:string;review:string};
const date='2026-09-02' as const;
const specs:Spec[]=[
{slug:'ap-invoice-number-normalization-routine',title:'Set an AP invoice number normalization routine',excerpt:'Preserve supplier invoice identifiers while creating consistent matching keys for search and duplicate review.',keyword:'AP invoice number normalization routine',goal:'make formatting differences searchable without replacing the identifier shown on the source invoice',evidence:'source invoice number, supplier, entity, captured value, normalized comparison key, transformation rule, operator, timestamp, and exceptions',owner:'invoice-data owner',scenario:'the same supplier alternates between spaces, dashes, and leading zeroes in invoice numbers',review:'compare the source value and normalized key across clean, reformatted, blank, and ambiguous identifiers'},
{slug:'ap-duplicate-payment-recovery-register',title:'Build an AP duplicate payment recovery register',excerpt:'Track suspected duplicate payments from evidence review through supplier contact, recovery, and ledger disposition.',keyword:'AP duplicate payment recovery register',goal:'separate a duplicate signal from a confirmed recovery and preserve every owner decision',evidence:'payments, invoices, supplier, entity, amounts, dates, duplicate signal, review result, supplier correspondence, recovery evidence, and accounting disposition',owner:'controller or recovery owner',scenario:'two payments share an amount and invoice reference but were released from different entities',review:'sample open suspicions, rejected matches, promised refunds, received funds, and closed accounting entries'},
{slug:'ap-payment-hold-release-record',title:'Create an AP payment hold release record',excerpt:'Document why a supplier or invoice was held, who reviewed the issue, and what authorized its release.',keyword:'AP payment hold release record',goal:'prevent a status change from erasing the reason, evidence, and authority behind a payment hold',evidence:'hold scope, reason, source, applied time, operator, affected items, review evidence, decision maker, release time, and residual exceptions',owner:'authorized payment owner',scenario:'a supplier hold is cleared after documents arrive while one disputed invoice remains unresolved',review:'trace active, partially resolved, expired, rejected-release, and fully released cases'},
{slug:'ap-vendor-portal-invoice-intake-log',title:'Maintain an AP vendor portal invoice intake log',excerpt:'Record invoice retrieval from supplier portals with stable provenance, cutoff times, and exception ownership.',keyword:'AP vendor portal invoice intake log',goal:'show which approved portal was checked, what population was available, and what entered the AP queue',evidence:'portal, supplier, account, access role, retrieval time, covered period, document IDs, file references, queue receipts, gaps, and owner',owner:'invoice intake owner',scenario:'a portal displays three invoices but only two files download successfully before cutoff',review:'reconcile ordinary retrievals, missing files, access failures, revised documents, and repeated portal IDs'},
{slug:'ap-early-payment-discount-review-list',title:'Prepare an AP early-payment discount review list',excerpt:'Surface discount terms and deadlines without letting support staff choose cash priorities or release payments.',keyword:'AP early-payment discount review list',goal:'give treasury and finance owners timely, source-linked options without presenting discounts as guaranteed savings',evidence:'invoice, supplier, entity, terms source, eligible base, stated discount, deadline, approval state, exceptions, cash owner, and decision',owner:'treasury or finance owner',scenario:'an invoice offers a discount date that conflicts with the purchase order terms',review:'include eligible, ineligible, disputed, expired, and owner-declined opportunities'},
{slug:'ap-invoice-currency-validation-check',title:'Run an AP invoice currency validation check',excerpt:'Compare invoice currency with approved purchasing and supplier records before coding or payment preparation.',keyword:'AP invoice currency validation check',goal:'expose currency conflicts early while reserving accounting and commercial decisions for authorized owners',evidence:'invoice currency, amount, supplier record, purchase order, contract reference, entity, comparison result, exchange-rate source if required, and owner decision',owner:'accounting or procurement owner',scenario:'a supplier invoice is denominated in euros while the purchase order is recorded in US dollars',review:'test matching, conflicting, missing, multi-currency, and corrected source records'},
{slug:'ap-unmatched-receipt-follow-up-queue',title:'Create an AP unmatched receipt follow-up queue',excerpt:'Route receipt gaps with line-level evidence so purchasing owners can resolve blocked three-way matches.',keyword:'AP unmatched receipt follow-up queue',goal:'identify the exact receipt evidence missing from an invoice match without inventing delivery confirmation',evidence:'invoice, purchase order, line, quantity, amount, receipt search result, delivery evidence, requester, buyer, follow-up history, and resolution',owner:'purchasing or receiving owner',scenario:'an invoice bills five units while the system shows a receipt for only three',review:'sample timing gaps, partial receipts, wrong-PO references, disputed deliveries, and confirmed corrections'},
{slug:'ap-vendor-name-variation-review',title:'Review vendor name variations in AP records',excerpt:'Compare supplier names across invoices and approved master data without making unreviewed identity changes.',keyword:'AP vendor name variation review',goal:'distinguish harmless display differences from identity, entity, or master-data exceptions',evidence:'invoice name, remittance name, supplier ID, legal name, tax-document name, purchase order, prior approved alias, difference type, and reviewer',owner:'vendor-master owner',scenario:'an invoice uses a trading name that is not listed on the approved supplier record',review:'test punctuation changes, known aliases, legal-entity conflicts, new remittance names, and duplicate candidates'},
{slug:'ap-invoice-due-date-calculation-log',title:'Keep an AP invoice due date calculation log',excerpt:'Show how invoice dates, receipt dates, and approved terms produce a proposed due date for owner review.',keyword:'AP invoice due date calculation log',goal:'make due-date preparation reproducible without letting an operator resolve disputed contractual terms',evidence:'invoice date, receipt date, approved terms, terms source, calculation rule, proposed due date, conflicts, owner response, and change history',owner:'procurement or accounting owner',scenario:'the invoice states net 15 while the approved purchase order states net 30',review:'cover standard terms, receipt-based terms, conflicts, missing terms, and approved overrides'},
{slug:'ap-recurring-invoice-monitoring-calendar',title:'Build an AP recurring invoice monitoring calendar',excerpt:'Track expected recurring invoices and escalate missing or unusual items without creating unsupported accruals.',keyword:'AP recurring invoice monitoring calendar',goal:'make expected receipt windows and follow-up ownership visible while separating expectation from liability',evidence:'supplier, service period, entity, expected window, basis, prior invoice reference, receipt status, variance note, follow-up, and accounting owner',owner:'close or accounting owner',scenario:'a monthly service invoice has not arrived by the normal close cutoff',review:'sample received-on-time, late, missing, changed-amount, stopped-service, and duplicate cases'},
{slug:'ap-vendor-inquiry-response-log',title:'Use an AP vendor inquiry response log',excerpt:'Answer supplier status questions from approved records while retaining requests, responses, and escalation limits.',keyword:'AP vendor inquiry response log',goal:'create a consistent record of what was asked, which facts were checked, and what response was authorized',evidence:'supplier, authenticated contact, inquiry time, invoice references, approved status source, response template, sent time, attachments, exceptions, and owner',owner:'vendor-relations or AP owner',scenario:'a supplier asks for a payment date while its invoice is still waiting for internal approval',review:'inspect routine status replies, unknown contacts, disputed invoices, payment promises, and sensitive-data requests'},
{slug:'ap-month-end-cutoff-exception-log',title:'Maintain an AP month-end cutoff exception log',excerpt:'Document invoices and receipts that cross close boundaries so accounting owners can make attributable cutoff decisions.',keyword:'AP month-end cutoff exception log',goal:'separate observed document timing from the accounting decision about period treatment',evidence:'entity, close period, invoice date, receipt timestamp, service or delivery evidence, amount, source system, exception reason, accounting decision, and reviewer',owner:'close accounting owner',scenario:'an invoice received after cutoff relates to services completed before month end',review:'include late invoices, disputed service periods, missing receipts, reversals, and owner-approved treatments'},
];
const sections=(s:Spec)=>[
 {title:`Define the ${s.keyword}`,paragraphs:[`Start with a named population, cutoff, legal entity, authoritative systems, and accountable reviewer. The routine should ${s.goal}.`, `Retain ${s.evidence}. Keep original values beside any comparison field, and mark missing evidence explicitly instead of filling gaps from memory.`]},
 {title:'Separate evidence work from authority',paragraphs:[`Outsourced AP support can gather approved records, compare observable fields, maintain chronology, and route exceptions. The ${s.owner} retains approval, policy interpretation, accounting judgment, master-data authority, and payment decisions.`, `Use bounded states such as received, evidence check, waiting, owner review, owner decided, and closed. Each transition should identify its actor, time, source, and next required action.`]},
 {title:'Test the handoff before scaling it',paragraphs:[`Use this scenario: ${s.scenario}. The record should expose the conflict, preserve both sources, name the decision owner, and prevent a preparer from turning an assumption into an approved fact.`, `For acceptance, ${s.review}. A second authorized reviewer should be able to reproduce the comparison and explain why the final state follows from attributable evidence.`]},
];
export const sep2BlogPosts=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:9}));
export const sep2BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,shortAnswer:`Create a source-linked record to ${s.goal}, then route any judgment or authorization to the ${s.owner}.`,sections:sections(s),faqs:[{question:`What may outsourced support do with a ${s.keyword}?`,answer:`Support may assemble approved evidence, compare observable facts, record chronology, and route exceptions. The ${s.owner} keeps decisions and authorization.`},{question:'How should the routine be accepted?',answer:`Retain ${s.evidence}; then ${s.review}.`}]}]));
