type Spec={slug:string;title:string;excerpt:string;keyword:string;goal:string;evidence:string;owner:string;scenario:string};
const date='2026-09-01' as const;
const specs:Spec[]=[
{slug:'ap-invoice-receipt-acknowledgment-log',title:'Build an AP invoice receipt acknowledgment log',excerpt:'Confirm invoice receipt without implying approval, acceptance, or a promised payment date.',keyword:'AP invoice receipt acknowledgment log',goal:'show when an invoice arrived, what was received, and which queue owns the next check',evidence:'source channel, sender, receipt timestamp, attachment names, supplier, invoice number, entity, and acknowledgment result',owner:'AP operations owner',scenario:'an invoice email arrives with two attachments but only one readable invoice'},
{slug:'ap-credit-balance-investigation-queue',title:'Create an AP credit balance investigation queue',excerpt:'Organize supplier credits and overpayments into reviewable cases without making unsupported ledger changes.',keyword:'AP credit balance investigation queue',goal:'separate documented credits from balances that still need accounting or supplier evidence',evidence:'supplier, entity, currency, ledger balance, credit memo, payment history, statement, correspondence, and last review date',owner:'accounting or reconciliation owner',scenario:'a supplier statement shows a credit that is absent from the current ledger extract'},
{slug:'ap-invoice-approval-reminder-cadence',title:'Set an AP invoice approval reminder cadence',excerpt:'Follow up on pending approvals with predictable timing, complete context, and a named escalation route.',keyword:'AP invoice approval reminder cadence',goal:'move approval requests without turning repeated reminders into an informal authorization path',evidence:'invoice identity, amount, due date, requested approver, request timestamp, reminder history, response, and escalation state',owner:'approval-matrix owner',scenario:'an invoice is nearing its due date and the assigned approver has not responded'},
{slug:'ap-vendor-contact-directory-control',title:'Maintain a controlled AP vendor contact directory',excerpt:'Keep supplier contacts useful for routine follow-up while protecting verification routes from unreviewed changes.',keyword:'AP vendor contact directory control',goal:'distinguish routine correspondence contacts from independently approved verification contacts',evidence:'supplier ID, contact purpose, name, address, source, verification status, effective date, change history, and reviewer',owner:'vendor-master owner',scenario:'a supplier asks that all future payment questions go to a new email address'},
{slug:'ap-invoice-rejection-reason-register',title:'Create an AP invoice rejection reason register',excerpt:'Record why invoices leave the normal workflow and what suppliers or internal owners must provide next.',keyword:'AP invoice rejection reason register',goal:'make every rejected or returned invoice traceable to a factual reason and next action',evidence:'invoice, supplier, reason code, supporting note, decision source, notification, response, resubmission link, and final state',owner:'invoice process owner',scenario:'an invoice names the wrong legal entity and must be returned for correction'},
{slug:'ap-payment-batch-readiness-checklist',title:'Prepare an AP payment batch readiness checklist',excerpt:'Assemble a review packet that exposes holds, duplicates, approvals, and totals before authorized payment release.',keyword:'AP payment batch readiness checklist',goal:'give the payment owner a reproducible view of what is proposed and what remains excluded',evidence:'batch ID, cutoff, entities, currencies, invoice list, approvals, duplicate checks, holds, totals, exceptions, and preparer',owner:'authorized payment owner',scenario:'a proposed batch contains an approved invoice whose supplier record is on hold'},
{slug:'ap-vendor-statement-request-calendar',title:'Run an AP vendor statement request calendar',excerpt:'Request supplier statements on a planned cadence and retain delivery, cutoff, and follow-up evidence.',keyword:'AP vendor statement request calendar',goal:'collect comparable supplier statements before reconciliation deadlines',evidence:'supplier, contact, requested period, cutoff date, request time, delivery status, file reference, follow-up, and exception',owner:'reconciliation owner',scenario:'a key supplier sends a current balance report without transaction-level detail'},
{slug:'ap-invoice-attachment-quality-review',title:'Review AP invoice attachment quality before entry',excerpt:'Catch unreadable, incomplete, and mismatched invoice files before their data reaches downstream queues.',keyword:'AP invoice attachment quality review',goal:'verify that source documents are readable, complete, and tied to the correct message or portal event',evidence:'file name, format, page count, readability, invoice identifiers, missing pages, related attachments, and source reference',owner:'invoice intake owner',scenario:'a scanned invoice omits the page containing tax and remittance details'},
{slug:'ap-open-purchase-order-follow-up-list',title:'Build an AP open purchase order follow-up list',excerpt:'Route invoice-blocking PO questions with precise evidence while leaving purchasing decisions with employees.',keyword:'AP open purchase order follow-up list',goal:'explain which PO fact blocks invoice processing and which employee response is required',evidence:'purchase order, supplier, entity, line, ordered and received quantities, prior invoices, current invoice, variance, and request history',owner:'purchasing owner',scenario:'an invoice references an open PO line with no recorded receipt'},
{slug:'ap-supplier-refund-tracking-workflow',title:'Track supplier refunds in an AP workflow',excerpt:'Follow expected refunds from request through receipt without treating a promise as settled cash.',keyword:'AP supplier refund tracking workflow',goal:'preserve the basis, expected amount, ownership, and actual settlement evidence for supplier refunds',evidence:'supplier, entity, reason, supporting credit, amount, currency, request, supplier response, expected date, receipt, and application',owner:'cash or accounting owner',scenario:'a supplier promises a refund after a duplicate payment is documented'},
{slug:'ap-invoice-tax-field-review-notes',title:'Use review notes for AP invoice tax fields',excerpt:'Expose missing or conflicting invoice tax information without asking support staff to make tax judgments.',keyword:'AP invoice tax field review notes',goal:'compare observable invoice tax fields with approved source records and route judgment separately',evidence:'legal entity, supplier record, jurisdiction, taxable base, tax type, rate, amount, exemption evidence, purchase order, and discrepancy',owner:'tax or accounting owner',scenario:'the tax amount on an invoice does not reconcile to its stated rate and taxable subtotal'},
{slug:'ap-daily-queue-reconciliation-routine',title:'Run a daily AP queue reconciliation routine',excerpt:'Compare inbox, workflow, and ledger populations so received invoices do not vanish between systems.',keyword:'daily AP queue reconciliation routine',goal:'identify items that exist in one controlled population but not in the next expected queue',evidence:'source system, extraction timestamp, stable item ID, receipt state, workflow state, ledger state, difference reason, owner, and resolution',owner:'AP operations owner',scenario:'an acknowledged invoice appears in the inbox register but not in the workflow queue'},
];
const sections=(s:Spec)=>[
 {title:`Define the ${s.keyword}`,paragraphs:[`Begin with a named population, cutoff time, legal entity, source system, and review owner. The routine should ${s.goal}.`, `Retain ${s.evidence}. Use stable references and record an absent field as missing; do not reconstruct it from memory or an unrelated prior transaction.`]},
 {title:'Keep preparation separate from decisions',paragraphs:[`Outsourced AP support may collect approved records, compare observable fields, document discrepancies, send approved follow-ups, and maintain factual status. The ${s.owner} retains any approval, accounting judgment, master-data change, or payment decision.`, `Use explicit states such as new, checking evidence, waiting for response, held for owner, decided by owner, and closed. A complete-looking packet does not itself authorize a change or release.`]},
 {title:'Test the routine with a real exception',paragraphs:[`Walk through this case: ${s.scenario}. The record should expose the source evidence, the exact gap, the current owner, and the response required without relying on a private message thread.`, `Review one ordinary item, one incomplete item, one conflict, and one aged item. A second reviewer should be able to reproduce the work, follow its chronology, and identify the retained company decision.`]},
];
export const sep1BlogPublicationDates=Object.fromEntries(specs.map(s=>[s.slug,date])) as Record<string,typeof date>;
export const sep1BlogPosts=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:9}));
export const sep1BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,shortAnswer:`Create a controlled record to ${s.goal}, then send any judgment or authorization to the ${s.owner}.`,sections:sections(s),faqs:[{question:`What can outsourced support do with a ${s.keyword}?`,answer:`Support can assemble evidence, compare observable facts, maintain chronology, and route exceptions. The ${s.owner} retains decisions and authorization.`},{question:'What evidence should the handoff preserve?',answer:`Preserve ${s.evidence}, plus the unresolved question and the attributable owner response.`}]}]));
