type Topic = {
  slug:string; title:string; excerpt:string; keyword:string; service:string; serviceLabel:string;
  scenario:string; owner:string; records:string; example:string; image:string; steps:[string,string][];
};

const topics: Topic[] = [
  {slug:'invoice-line-item-unit-price-variance',title:'Review an invoice line-item unit-price variance',excerpt:'Reproduce the ordered and invoiced unit prices, quantities, currency, and commercial evidence before routing a price exception.',keyword:'invoice unit price variance review',service:'three-way-match-support',serviceLabel:'three-way match support',scenario:'an invoice line whose unit price differs from the purchase order',owner:'purchasing or finance owner',records:'invoice, purchase order versions, contract, quote, receipt, tolerance result, supplier message, and approval history',example:'A supplier invoices 240 units at $18.60 while the approved order shows $18.10. The AP specialist records the $120 line variance and the two sources instead of changing either price or splitting the invoice.',image:'po-tolerance-exception-packet.svg',steps:[['Normalize the comparison','Put ordered and invoiced quantity, unit of measure, unit price, currency, discounts, freight, tax, and extensions in separate fields.'],['Check order history','Identify which controlled order version was active and whether an authorized amendment predates the invoice.'],['Recalculate the variance','Show the unit and extended difference and reproduce any configured tolerance result without treating it as approval.'],['Separate likely causes','Distinguish price change, quantity basis, unit conversion, currency, rounding, or a charge placed on the wrong line.'],['Route one decision','Ask the owner to confirm a correction, amendment, exception, hold, or supplier query using the attached evidence.'],['Retain the outcome','Link the authorized response and any corrected document to the original comparison and system result.']]},
  {slug:'vendor-tax-form-renewal-review',title:'Run a vendor tax-form renewal review',excerpt:'Track requested, received, reviewed, superseded, and missing supplier tax forms without letting collection become a tax decision.',keyword:'vendor tax form renewal review',service:'tax-document-collection',serviceLabel:'tax document collection',scenario:'a periodic review of supplier tax-document records',owner:'tax or vendor-master owner',records:'current and prior tax forms, request history, supplier identity, approved contact, receipt date, review status, and retention record',example:'A supplier sends a newly signed W-9 after changing its mailing address. Support records both changes and routes them separately rather than assuming the form authorizes every master-data update.',image:'vendor-address-change-evidence.svg',steps:[['Define the population','List supplier entity, company entity, document type, current status, last review, and the policy event that triggered follow-up.'],['Request through an approved channel','Use the controlled supplier contact or portal and avoid asking for sensitive records in an unprotected message.'],['Preserve each version','Keep receipt timestamps and the superseded record so a reviewer can see what changed and when.'],['Compare identity fields','Flag legal name, business name, address, classification, and identifier differences without selecting tax treatment.'],['Route specialist review','A designated company owner decides validity, withholding, reporting, and required system changes.'],['Close accurately','Use statuses such as requested, received-unreviewed, clarification pending, accepted by owner, or replaced.']]},
  {slug:'partial-delivery-invoice-match',title:'Match an invoice after a partial delivery',excerpt:'Compare ordered, delivered, accepted, returned, and invoiced quantities by line before an AP owner resolves a partial-delivery exception.',keyword:'partial delivery invoice match',service:'three-way-match-support',serviceLabel:'three-way match support',scenario:'an invoice covering goods or services delivered in stages',owner:'receiving, purchasing, or finance owner',records:'purchase order, delivery records, service acceptance, receipts, returns, invoice lines, prior billings, and match result',example:'An order covers 100 units, the warehouse accepts 60, and the supplier invoices 80. AP shows the 20-unit unsupported difference while receiving confirms the physical event.',image:'receipt-reversal-invoice-review.svg',steps:[['Build the line history','Record every order, delivery, acceptance, return, invoice, credit, and prior payment by line and timestamp.'],['Respect units of measure','Keep packs, cases, hours, milestones, and individual units explicit before comparing quantities.'],['Separate delivery from acceptance','A carrier event may prove arrival without proving that the company accepted the billed quantity or service.'],['Check cumulative billing','Compare this invoice with earlier billings so an apparently valid partial quantity does not exceed the order overall.'],['Assign the evidence gap','Receiving owns physical facts, purchasing owns commercial changes, and finance retains accounting and approval decisions.'],['Re-run after response','Preserve the failed match and attach the corrected receipt, invoice, credit, approved exception, or hold.']]},
  {slug:'freight-charge-invoice-validation',title:'Validate freight charges on a supplier invoice',excerpt:'Trace freight lines to the purchase terms, shipment evidence, order, and approved exception before proposing how the invoice should proceed.',keyword:'freight charge invoice validation',service:'purchase-order-reconciliation',serviceLabel:'purchase order reconciliation',scenario:'a supplier invoice containing an unexpected or changed freight charge',owner:'purchasing or finance owner',records:'invoice, purchase order, contract terms, quote, shipping document, delivery record, tax detail, prior invoices, and approvals',example:'The order says freight included, but the invoice adds a $475 delivery line after an expedited shipment. AP links the expedite request and asks the commercial owner whether that charge was authorized.',image:'invoice-service-period-validation.svg',steps:[['Identify each freight component','Separate base freight, fuel surcharge, handling, insurance, accessorial charge, tax, and credit instead of reviewing one net amount.'],['Read the controlled terms','Capture the relevant order or contract wording and version without supplying legal interpretation.'],['Connect shipment evidence','Match carrier, tracking reference, route, weight or quantity, delivery date, and the invoiced service.'],['Check prior and duplicate charges','Look across supplier and carrier invoices so the same shipment is not billed twice through different channels.'],['Prepare the commercial question','State the amount, source conflict, due date, and exact confirmation needed from the authorized owner.'],['Record the disposition','Retain any supplier correction, order amendment, owner approval, dispute, or credit with the original line.']]},
  {slug:'supplier-entity-relationship-check',title:'Check the supplier entity before processing an invoice',excerpt:'Compare legal entity, trading name, order, tax record, remit-to data, and vendor account before an invoice moves forward.',keyword:'supplier entity invoice check',service:'vendor-onboarding-administration',serviceLabel:'vendor onboarding administration',scenario:'an invoice issued by an entity related to, but different from, the vendor on the order',owner:'vendor-master, purchasing, tax, or finance owner',records:'invoice, vendor master, purchase order, contract, tax form, supplier communication, corporate relationship evidence, and approval',example:'The contract names a parent company, the purchase order names a regional subsidiary, and the invoice comes from a shared-services entity. Support maps the three names and pauses the item for owner review.',image:'vendor-contact-ownership-register.svg',steps:[['Capture names exactly','Keep legal name, trading name, identifier, address, account, and source separate rather than normalizing away differences.'],['Map each business role','Show which entity contracted, ordered, supplied, invoiced, receives payment, and appears on tax documentation.'],['Avoid assumed relationships','A shared domain, address, bank, or brand is a clue, not authorization to merge supplier records.'],['Verify through known contacts','Use approved directories and channels when the supplier explains a restructuring or billing-entity change.'],['Route dependent decisions','Company owners decide master-data changes, tax treatment, contracting, invoice acceptance, and payment authority.'],['Preserve the approved mapping','Link the decision to affected accounts and effective dates while retaining the earlier record.']]},
  {slug:'invoice-exchange-rate-evidence-review',title:'Review exchange-rate evidence on a foreign-currency invoice',excerpt:'Separate invoice currency, order currency, system rate, conversion date, and payment currency so finance can resolve an exchange-rate question.',keyword:'invoice exchange rate evidence review',service:'invoice-data-capture',serviceLabel:'invoice data capture',scenario:'an invoice whose entered base-currency value does not match an expected conversion',owner:'controller, treasury, or finance owner',records:'invoice, order, contract, currency fields, system-rate record, rate date, posting proposal, payment instruction, and approval',example:'A EUR invoice is entered using the receipt-date rate while the company procedure may require a different date. AP documents both calculations and sends the policy question to finance.',image:'invoice-capture-confidence-review.svg',steps:[['Keep currencies explicit','Record document, order, ledger, functional, settlement, and reporting currencies without replacing one with a converted value.'],['Capture the rate source','Name the controlled system or approved reference, rate type, date, time, timezone, and precision used.'],['Reproduce the calculation','Show source amount, rate direction, multiplication or division, rounding, and resulting amount.'],['Separate policy from arithmetic','Support can test a calculation but should not choose the accounting date, rate type, or gain-and-loss treatment.'],['Watch for payment-detail changes','A request to settle in another currency or account needs its own trusted-channel verification and authority.'],['Retain the finance answer','Store the authorized rate basis, corrected entry, and effective date beside the original proposal.']]},
  {slug:'supplier-credit-review-calendar',title:'Build a supplier-credit review calendar',excerpt:'Give open credits an evidence-based owner and review date without inventing an expiration or applying value without authority.',keyword:'supplier credit review calendar',service:'vendor-statement-reconciliation',serviceLabel:'vendor statement reconciliation',scenario:'open supplier credits that may be overlooked between statement cycles',owner:'AP, purchasing, or finance owner',records:'credit memo, original invoice or payment, supplier statement, ledger balance, correspondence, application proposal, refund evidence, and owner decision',example:'A two-year-old credit remains on the ledger, but no source says it expires. AP schedules review and requests supplier confirmation instead of calling the balance lost or applying it arbitrarily.',image:'duplicate-credit-memo-detection.svg',steps:[['Inventory open credits','Record supplier, entity, currency, amount, source event, document date, ledger date, statement status, and current owner.'],['Use truthful time fields','Distinguish document age, last supplier response, promised refund date, policy review date, and any documented contractual deadline.'],['Trace the originating event','Link return, pricing correction, duplicate payment, overpayment, rebate, or disputed invoice evidence.'],['Choose a review cadence','Prioritize material, disputed, old, cross-entity, or supplier-unconfirmed items using company-defined rules.'],['Route the disposition','Finance decides application, refund, write-off, transfer, accounting, and closure; support prepares evidence.'],['Carry forward visibly','Retain the original date, latest action, unanswered question, owner, and next review point.']]},
  {slug:'purchase-order-closure-invoice-check',title:'Check invoices before a purchase order is closed',excerpt:'Reconcile ordered, received, invoiced, credited, committed, and disputed values before an authorized owner closes a purchase order.',keyword:'purchase order closure invoice check',service:'purchase-order-reconciliation',serviceLabel:'purchase order reconciliation',scenario:'a purchase order proposed for closure while AP activity may remain open',owner:'purchasing or finance owner',records:'purchase order and changes, receipts, invoices, credits, commitments, disputes, supplier statement, and closure authorization',example:'A project order appears fully invoiced, but a rejected invoice and expected credit remain in separate queues. AP links both exceptions before purchasing decides whether closure is appropriate.',image:'po-tolerance-exception-packet.svg',steps:[['Define the closing population','State entity, order, lines, currencies, extraction time, included statuses, and systems searched.'],['Reconcile each line','Compare ordered, received, returned, invoiced, credited, paid, and open values without relying only on header totals.'],['Search adjacent queues','Include rejected invoices, unmatched inbox items, blocked documents, disputes, pending credits, and unprocessed receipts.'],['Confirm future commitments','Ask the business owner about remaining delivery, service, retainage, price adjustment, or cancellation evidence.'],['Keep closure authority separate','Support prepares the comparison; purchasing and finance authorize commercial and accounting outcomes.'],['Retain the final state','Record who closed or retained the order, when, why, and which unresolved items remain linked.']]},
  {slug:'returned-payment-recovery-packet',title:'Prepare a returned-payment recovery packet',excerpt:'Connect the authorized payment, bank return, supplier record, open invoices, verification, and next decision without retrying funds automatically.',keyword:'returned vendor payment recovery',service:'payment-run-preparation',serviceLabel:'payment run preparation',scenario:'a supplier payment returned or rejected after release',owner:'treasury or payment approver',records:'payment proposal, approvals, bank result, return code, remittance, supplier account, invoices, verification evidence, and retry authorization',example:'A payment is returned with an account-closed code and the supplier emails new banking details. AP holds the retry and routes the change through independent verification.',image:'payment-proposal-removal-log.svg',steps:[['Confirm the bank event','Record payment ID, amount, currency, value date, beneficiary, bank status, return code, and retrieval time.'],['Protect the original authorization','Link the approved proposal and release record; a return does not authorize a changed beneficiary or second payment.'],['Reopen affected invoices carefully','Show ledger and supplier-account status without duplicating liabilities or erasing the failed attempt.'],['Verify changed information','Use the company-approved independent process for new bank, contact, legal-entity, or remittance details.'],['Prepare the retry decision','Treasury decides whether, when, how, and to whom funds may be sent again.'],['Reconcile the resolution','Link the authorized retry, cancellation, hold, supplier response, bank result, and final invoice status.']]},
  {slug:'vendor-portal-invoice-rejection-triage',title:'Triage an invoice rejected by a vendor portal',excerpt:'Capture the submitted file, portal response, rejection reason, source invoice, and correction owner before resubmission.',keyword:'vendor portal invoice rejection triage',service:'ap-inbox-management',serviceLabel:'AP inbox management',scenario:'an invoice upload or portal submission that did not enter the customer workflow',owner:'billing, purchasing, supplier, or finance owner',records:'source invoice, submission file, portal account, upload timestamp, response, rejection code, order, correction, and resubmission result',example:'A portal rejects an invoice because its PO field is blank, while the source invoice references a contract instead. AP preserves the rejection and asks the commercial owner which controlled reference applies.',image:'invoice-approval-delegation-handoff.svg',steps:[['Preserve the failed attempt','Keep file hash, filename, invoice ID, portal, account, actor, timestamp, response, and screenshot or export where permitted.'],['Translate the reason cautiously','Quote the portal state and separate it from a diagnosis until source records support the cause.'],['Compare required fields','Check entity, supplier, order, invoice number, dates, currency, tax, attachments, and permitted file format.'],['Assign the correction','Route source-document changes to the supplier and commercial or setup issues to the designated company owner.'],['Prevent duplicate resubmission','Use one queue record and mark every attempt so repeated uploads do not become duplicate invoices.'],['Verify acceptance','Retain the new portal reference and status while recognizing that acceptance is not invoice approval or payment.']]},
  {slug:'invoice-supporting-document-completeness-check',title:'Check invoice supporting-document completeness',excerpt:'Use a scoped document checklist to identify missing support without treating a complete packet as approval.',keyword:'invoice supporting document checklist',service:'ap-inbox-management',serviceLabel:'AP inbox management',scenario:'an invoice that needs specified evidence before review can continue',owner:'requester, purchasing, receiving, or finance owner',records:'invoice, order, receipt, contract, approval request, timesheet or milestone record, tax support, correspondence, and policy checklist',example:'A services invoice includes a manager email but lacks the milestone acceptance named in the purchase record. AP requests that exact evidence instead of sending a generic “more support needed” reply.',image:'invoice-capture-confidence-review.svg',steps:[['Select the right checklist','Base requirements on the entity, invoice type, purchasing path, risk, and controlled procedure.'],['Index received evidence','Name document, version, issuer, date, stable reference, and source location rather than relying on attachments in a thread.'],['State each gap precisely','Identify the missing field or record and why the workflow expects it, without asking for unrelated sensitive data.'],['Keep quality separate from presence','An attached document may be unreadable, inconsistent, expired, or unrelated; record that observation explicitly.'],['Route to the evidence owner','Ask the person or supplier able to provide the record while finance retains approval and accounting decisions.'],['Close the preparation step honestly','A complete packet is ready for review, not approved, posted, or scheduled for payment.']]},
  {slug:'month-end-invoice-cutoff-handoff',title:'Prepare a month-end invoice cutoff handoff',excerpt:'Separate received, missing, disputed, unapproved, and post-cutoff invoices so the close owner gets a reproducible decision queue.',keyword:'month end invoice cutoff handoff',service:'month-end-ap-close-support',serviceLabel:'month-end AP close support',scenario:'the AP queue approaching a financial close cutoff',owner:'controller or close owner',records:'inbox and workflow extracts, invoices, receipts, approvals, disputes, late-arrival timestamps, prior-period items, and close instructions',example:'An invoice arrives after the AP processing cutoff but describes services from the closing month. Support records both dates and routes the period decision rather than backdating receipt or choosing accounting treatment.',image:'invoice-service-period-validation.svg',steps:[['Freeze the population','Record extraction times, systems, entities, currencies, included statuses, and the close instruction version.'],['Classify operational state','Separate unentered, unmatched, waiting for receipt, waiting for approval, disputed, rejected, and received after cutoff.'],['Keep dates distinct','Preserve invoice, service, delivery, receipt, workflow, approval, posting, and payment dates with their sources.'],['Prepare owner questions','State amount, supplier, evidence, possible period, missing record, and the exact decision required.'],['Protect accounting authority','Support maintains the queue and evidence; finance decides accrual, posting period, materiality, and close treatment.'],['Carry unresolved items forward','Retain original arrival, latest action, close disposition, owner, and next review date across periods.']]},
];

const sources = [
  {name:'NIST glossary: least privilege',url:'https://csrc.nist.gov/glossary/term/least_privilege',note:'Definition supporting limited access for AP systems and records.'},
  {name:'CISA: Recognize and Report Phishing',url:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing',note:'Government guidance supporting trusted-channel verification for suspicious requests.'},
  {name:'IRS: About Form W-9',url:'https://www.irs.gov/forms-pubs/about-form-w-9',note:'First-party context for a common supplier tax record; tax decisions remain with the company.'},
];

const companion = [
  'Keep source observations and reviewer conclusions in separate fields. When records disagree, preserve both values and their retrieval times.',
  'Use stable identifiers for the supplier, entity, document, line, currency, and source system. Similar names are not reliable joins.',
  'Give every exception one accountable owner, one answerable question, and a next review date. A generic follow-up status hides the actual stop.',
  'Apply least privilege: preparation access may support reading, comparison, notes, and routing while approval and release remain separate.',
  'Retain the original record when a correction arrives. Link the replacement, responder, time, reason, and authority instead of overwriting history.',
  'Test an ordinary item, an incomplete item, and a conflicting item. A backup reviewer should reproduce the result without an oral explanation.',
];

const paragraph = (t:Topic, guidance:string, i:number) => `${i % 2 ? `For ${t.scenario}, begin with the ${t.records}.` : `The practical goal is a reviewable decision packet, not a faster unsupported conclusion.`} ${guidance} ${companion[i % companion.length]} The outsourced AP specialist may gather, compare, document, and follow up, while the ${t.owner} keeps authority over accounting, supplier changes, approval, and movement of funds.`;

export const sep25BlogPosts = topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:12}));
export const sep25BlogDetails = Object.fromEntries(topics.map(t=>[t.slug,{
  thumbnail:`/blog-thumbnails/sep24-2026/${t.image}`,shortAnswer:t.excerpt,published:'2026-09-25',modified:'2026-09-25',mainKeyword:t.keyword,
  sections:[
    {title:'A practical AP example',paragraphs:[paragraph(t,t.example,0),paragraph(t,'Agree on authoritative sources, required fields, permitted actions, stop conditions, and escalation owners before processing begins. This makes the lane trainable and protects finance decisions from being buried inside routine data entry.',1)]},
    ...t.steps.map(([title,guidance],i)=>({title,paragraphs:[paragraph(t,guidance,i+2),paragraph(t,companion[(i+2)%companion.length],i+3)]})),
    {title:'Pilot the control with real exceptions',paragraphs:[paragraph(t,`Choose a small sample that includes routine records plus missing, conflicting, late, and security-sensitive evidence. Review each packet with the ${t.owner} and correct unclear statuses before increasing volume.`,10),paragraph(t,'Measure aged exceptions, returned packets, correction reasons, and owner response time only after the company defines each measure, source, and review purpose. Activity volume alone does not prove a good AP outcome.',11)]},
    {title:'Create a bounded outsourced handoff',paragraphs:[paragraph(t,`Document intake channels, expected volume, peak periods, system access, retention, backup coverage, and escalation timing. The ${t.serviceLabel} service page frames this work as a controlled preparation lane.`,12),paragraph(t,'Use the contact and scoping page after inputs, outputs, owners, evidence, and stop conditions are explicit. A narrow lane is easier to inspect and improve than an instruction to handle whatever arrives.',13)]},
  ],
  checklistTitle:'Review the packet before handoff',
  checklist:['Original evidence and stable identifiers retained','Missing or conflicting information stated plainly','Authorized company owner named','Status, next action, and review date recorded','Approval, vendor-master authority, and payment release remain with the company'],
  bodyLinks:[{href:`/services/${t.service}`,label:t.serviceLabel},{href:'/contact-us',label:'contact and scoping page'}],
  faqs:[
    {question:'What can outsourced AP support prepare?',answer:`Support can gather and compare the ${t.records}, maintain the exception queue, and send a focused question to the ${t.owner}.`},
    {question:'Which decisions stay with the company?',answer:'Employees retain invoice approval, accounting and tax judgment, supplier-master authorization, access ownership, security verification, and payment release.'},
    {question:'How should the workflow begin?',answer:'Start with a small controlled sample and expand only after sources, statuses, owners, permissions, and escalation paths are clear.'},
  ],sources,
}]));
