type Spec = {
  slug: string; title: string; excerpt: string; keyword: string;
  focus: string; owner: string; source: string; risk: string;
  sections: {title: string; notes: string[]}[];
};

const specs: Spec[] = [
  {slug:'invoice-split-allocation-evidence',title:'Prepare evidence for a split invoice allocation',excerpt:'Separate the billed facts from the employee decision when one invoice must be divided across departments, projects, or entities.',keyword:'split invoice allocation evidence',focus:'a proposed split of one invoice',owner:'finance or budget owner',source:'invoice, purchase request, contract, receipt, and approved allocation instruction',risk:'a convenient percentage can become an unsupported accounting entry',sections:[
    {title:'Begin with the obligation as billed',notes:['Keep the original total, currency, supplier, entity, invoice number, service period, and line descriptions visible before discussing a split. The proposed allocation must always reconcile to that unchanged source.','Identify why a split is being considered. Shared use, separate projects, several cost centers, or more than one legal entity require different evidence and may involve different decision owners.']},
    {title:'Build a calculation another reviewer can repeat',notes:['Show each proposed destination, basis, input, rounding treatment, and subtotal. Link headcount, usage, purchase, or owner records when the approved method relies on them.','Do not treat last month\'s percentages as standing authority. Retain them as a comparison, then ask whether the same method and population apply to the current invoice.']},
    {title:'Keep entity and tax questions outside routine coding',notes:['A split across legal entities may require intercompany, tax, or contractual judgment. The outsourced specialist should stop at a factual packet and route those decisions.','If one line lacks an owner, hold that line visibly rather than hiding it in a general overhead category. The finance owner decides whether partial processing is permitted.']},
    {title:'Close the allocation trail',notes:['Record the authorized response, calculation version, preparer, reviewer, timestamp, and system reference. A corrected split should preserve the earlier proposal and the reason it changed.','Sample allocations that use different bases. A total that reconciles is necessary, but it does not prove that the destinations or method were authorized.']}]},
  {slug:'supplier-merger-transition-record',title:'Build an AP transition record for a supplier merger',excerpt:'Track old and new supplier identities without merging records or payment instructions on assumption.',keyword:'supplier merger AP transition',focus:'a supplier identity transition',owner:'vendor-master, procurement, legal, or finance owner',source:'approved supplier notices, contracts, tax records, vendor master, open invoices, and payment history',risk:'a name change can conceal an unauthorized bank or legal-entity change',sections:[
    {title:'Treat the notice as evidence, not authorization',notes:['Preserve the merger, acquisition, or name-change notice with its source and receipt time. Extract the stated effective date, old name, new name, affected entities, and contact details without editing the vendor record.','Separate a trading-name change from a change in contracting party. Similar branding does not establish which legal entity owns an invoice or receives payment.']},
    {title:'Map open documents across the transition',notes:['List open invoices, credits, statements, purchase orders, disputes, and pending payments under the old record. Link candidate new records without combining them.','Check invoice dates and service periods against the authorized effective date. When the documents cross that date, ask the named owner which record and approval path apply.']},
    {title:'Verify sensitive changes independently',notes:['Route tax identifiers, remit addresses, bank details, portal domains, and payment methods through the company\'s separate verification process. Do not use contact information introduced by the change request as the trusted check.','Keep ordinary invoice review paused where the identity or payment destination remains unresolved. Urgency from either supplier name does not expand the specialist\'s authority.']},
    {title:'Retain a reversible history',notes:['Record who authorized each master-data action, when it became effective, and which open documents moved or remained. Preserve old identifiers for searches and duplicate review.','After transition, sample statements and invoices under both names. Confirm that credits, disputes, and payment results still trace to the obligation that created them.']}]},
  {slug:'vendor-debit-balance-review',title:'Review a vendor debit balance without guessing its cause',excerpt:'Assemble invoices, payments, credits, and refunds so an employee can decide how a supplier debit balance should be handled.',keyword:'vendor debit balance review',focus:'a supplier account showing a debit balance',owner:'finance, treasury, or supplier relationship owner',source:'vendor ledger, invoices, payments, credits, statements, refund messages, and approved adjustments',risk:'a debit can reflect overpayment, misapplication, timing, or an unsupported posting',sections:[
    {title:'Define the balance and its date',notes:['Capture the entity, supplier identifier, currency, ledger source, report timestamp, debit amount, and periods included. Do not combine currencies or entities into one unexplained figure.','A current debit is not proof that the supplier owes a refund. List the transactions that compose it and distinguish posted records from messages about future action.']},
    {title:'Trace the sequence behind the balance',notes:['Order invoices, payments, credit memos, reversals, and adjustments by date while retaining their accounting and source identifiers. A payment may precede a later credit without being erroneous.','Compare the supplier statement when available, but keep it separate from the company ledger. Differences may arise from timing, application, missing documents, or different account scope.']},
    {title:'Route the decision, not a conclusion',notes:['Ask whether the owner expects invoice application, refund pursuit, correction, write-off review, or further evidence. The outsourced specialist must not choose treatment or instruct a supplier to send money.','Changed refund or banking instructions require verified channels. Do not place company bank details in an uncontrolled message or accept a proposed offset without authorization.']},
    {title:'Monitor the chosen next action',notes:['Use states such as evidence pending, owner review, supplier response pending, refund received, credit applied, or correction authorized. Record the next review date and accountable role.','Close only after the authorized system record and supporting evidence agree. A supplier promise, proposed credit, or initiated refund is not the same as a completed result.']}]},
  {slug:'partial-payment-instruction-packet',title:'Prepare a partial-payment instruction packet for AP review',excerpt:'Show what would be paid, held, and left open while reserving the decision and release for authorized employees.',keyword:'partial payment instruction packet',focus:'a proposed partial payment of an invoice',owner:'finance approver and payment releaser',source:'invoice, dispute record, approval, contract or order, credit evidence, and payment proposal',risk:'an informal partial amount can imply settlement or bypass invoice controls',sections:[
    {title:'State why the full invoice is not moving',notes:['Identify the disputed, unsupported, or held amount beside the uncontested amount. Preserve the supplier\'s invoice total rather than editing the document to match the proposal.','Record whether the proposal comes from an authorized owner, a supplier request, or AP preparation. These sources do not carry the same authority.']},
    {title:'Reconcile the proposed components',notes:['Show invoice total, prior payments, credits, proposed payment, retained balance, currency, and calculation. Explain rounding and tax treatment only from authorized instructions.','Link the approval that covers the amount to be paid. Approval of the original invoice may not automatically authorize a changed or partial disposition.']},
    {title:'Protect dispute and settlement boundaries',notes:['Do not tell a supplier that accepting a partial payment resolves the dispute unless an authorized employee supplies approved wording. Legal and commercial consequences stay outside outsourced AP judgment.','Keep bank-detail changes in the independent verification lane. A legitimate dispute conversation does not authenticate a new destination for funds.']},
    {title:'Follow both sides after payment',notes:['After release, link the result to the exact approved proposal. Keep the unpaid balance visible with its dispute owner, evidence request, and next review date.','If the payment fails or the supplier rejects it, create a new event rather than rewriting the original instruction. Preserve the chronology for the next decision.']}]},
  {slug:'zero-value-invoice-handling',title:'Handle zero-value invoices without dropping the document trail',excerpt:'Decide where no-charge invoices, replacements, and informational documents belong before they distort the AP queue.',keyword:'zero value invoice handling',focus:'an invoice or invoice-like document with a zero total',owner:'finance, purchasing, or receiving owner',source:'document, purchase order, receipt, prior invoice, credit, contract, and supplier correspondence',risk:'zero amount can hide quantity, tax, inventory, replacement, or duplicate implications',sections:[
    {title:'Classify what the document claims to be',notes:['Capture the document title, number, date, supplier, entity, lines, quantities, taxes, total, and references. Do not assume that zero means the file has no accounting or operational purpose.','Separate a no-charge shipment, replacement, sample, warranty item, pro forma document, corrected invoice, and netted invoice-credit pair. Each can require a different owner.']},
    {title:'Connect it to the underlying event',notes:['Look for the order, receipt, return, prior charge, credit, or service record using stable identifiers. Keep missing relationships visible rather than filing the document as complete.','If positive and negative lines net to zero, show each line and its source. A zero header total can still affect quantity records, tax review, or duplicate checks.']},
    {title:'Keep decisions with the designated employee',notes:['The specialist may index the document and prepare comparisons. An employee decides whether it should be recorded, attached to another transaction, rejected, or retained as non-posting evidence.','Do not invent nominal values, coding, or tax treatment so the system will accept the document. Route system limitations to the process owner.']},
    {title:'Prevent repeated intake confusion',notes:['Record the disposition and linked transaction so a resent copy does not reenter as a new mystery. Preserve the original channel and receipt timestamp.','Review recurring zero-value documents by supplier and reason. Update intake examples only after the authorized owner confirms a repeatable rule.']}]},
  {slug:'purchase-order-amendment-trace',title:'Trace purchase order amendments during invoice review',excerpt:'Keep original and revised order terms visible when an invoice relies on a changed purchase commitment.',keyword:'purchase order amendment trace',focus:'an invoice matched to an amended purchase order',owner:'purchasing, receiving, or finance owner',source:'original order, amendment, approval history, receipt, invoice, contract, and system audit log',risk:'the latest total can obscure when, why, and by whom the commitment changed',sections:[
    {title:'Anchor the original order first',notes:['Record the original order number, entity, supplier, currency, lines, quantities, prices, dates, requester, and approval reference. Preserve that version even when the system displays only current values.','Identify every amendment event with its timestamp, author, approval, affected field, and effective date. A note that an order was updated is not enough.']},
    {title:'Match the invoice to the applicable version',notes:['Compare invoice service or shipment dates with amendment timing. A later amendment may not govern an earlier delivery, and the outsourced specialist should not decide that interpretation.','Show line-level differences across versions. A higher overall ceiling can coexist with an unchanged line that still fails the match.']},
    {title:'Separate evidence gaps from approval gaps',notes:['Missing amendment documentation needs a source request. An amendment that exists but lacks required approval needs the designated purchasing or finance owner.','Do not backdate a reference, edit receipt evidence, or treat requester confirmation as formal amendment authority unless the controlled process says it is.']},
    {title:'Preserve the post-decision lineage',notes:['Record which order version the employee authorized for the invoice and link any system correction. Keep the comparison packet with the invoice.','Sample amendments made near invoice receipt or close cutoff. These cases reveal whether version timing and authority remain visible across teams.']}]},
  {slug:'translated-invoice-review-handoff',title:'Build a review handoff for an invoice in another language',excerpt:'Capture visible invoice facts and translation uncertainty without turning outsourced AP support into a tax or legal interpreter.',keyword:'translated invoice review handoff',focus:'an invoice that requires language support',owner:'finance, tax, legal, purchasing, or approved language reviewer',source:'original invoice, approved translation output, purchase record, contract, vendor master, and reviewer response',risk:'a fluent-looking translation can conceal uncertainty or change the meaning of regulated fields',sections:[
    {title:'Keep the original document primary',notes:['Retain every page in its received form and record language, supplier, entity, invoice number, date, currency, total, and source channel where visible.','A translated working copy should point back to page and field locations. It must never replace the original or present uncertain text as exact.']},
    {title:'Mark the kind of language support used',notes:['State whether text came from an approved tool, bilingual employee, supplier-provided copy, or authorized service. Record the time and person responsible for review.','Separate transcription from translation and interpretation. Copying a number is different from deciding what a tax, legal, or commercial term means.']},
    {title:'Route high-consequence fields',notes:['Send unclear legal entity, tax, bank, payment-term, or contract wording to the designated employee. The specialist may highlight the source but cannot settle its meaning.','Changed bank information still requires independent verification. Translation confidence does not authenticate the supplier or payment destination.']},
    {title:'Make later correction possible',notes:['Preserve earlier translations when a reviewer corrects them, with the affected field and reason. Update the queue only from the authorized response.','Test the handoff using numbers, dates, negative amounts, multi-page references, and similar supplier names. These expose errors that smooth prose can hide.']}]},
  {slug:'late-arriving-invoice-close-register',title:'Maintain a close register for late-arriving invoices',excerpt:'Separate receipt timing, service evidence, and accounting decisions when invoices arrive around period close.',keyword:'late arriving invoice close register',focus:'an invoice received after a close checkpoint',owner:'controller or designated finance owner',source:'authoritative receipt event, invoice, service or receipt record, close calendar, approval state, and ledger extract',risk:'queue pressure can turn a timing observation into an unauthorized period decision',sections:[
    {title:'Define late against one controlled checkpoint',notes:['Record the close rule, time zone, entity, and authoritative receipt channel. Supplier sent time, mailbox receipt, capture, and approval answer different questions.','Do not call an invoice late solely because AP reviewed it after cutoff. Preserve outage, quarantine, forwarding, or portal events that explain the sequence.']},
    {title:'Prepare the period evidence',notes:['Capture invoice date, service period, delivery or receipt evidence, purchase reference, amount, currency, and current approval. State which sources are missing or conflicting.','The specialist can organize this packet but cannot choose an accrual, posting period, reversal, or materiality treatment. Route one explicit question to finance.']},
    {title:'Keep the register connected to ordinary processing',notes:['Show whether the invoice awaits evidence, owner decision, approval, posting, or later-period handling. Do not let the close register become a second unlinked queue.','Retain the authorized decision and system reference. If the invoice later changes, add an event and reconsider only through the approved route.']},
    {title:'Review boundary cases after close',notes:['Sample invoices just before and after cutoff, plus those delayed by systems. Check the original timestamp and the decision trail rather than relying on reported averages.','Repeated late arrivals may call for supplier, purchasing, or intake changes. Assign those improvements to employees without rewriting historical receipt dates.']}]},
  {slug:'remittance-advice-reconciliation',title:'Reconcile remittance advice with the AP payment record',excerpt:'Connect supplier-facing remittance details to the authorized payment result without exposing or changing sensitive data.',keyword:'remittance advice reconciliation',focus:'a remittance advice and its related payment',owner:'treasury or finance owner',source:'approved payment batch, bank result, remittance record, invoice ledger, supplier account, and delivery status',risk:'an advice can be sent, duplicated, or altered without proving funds moved',sections:[
    {title:'Treat advice and payment as separate records',notes:['Capture remittance identifier, supplier, entity, currency, listed invoices, deductions, payment reference, issue time, and delivery channel. Link the exact authorized batch.','A sent email is not evidence of settlement. Use the controlled bank or payment-system result for status and retain failures or rejections separately.']},
    {title:'Reconcile invoice application detail',notes:['Compare each invoice and credit listed on the advice with the ledger and released payment. Show omissions, extra lines, amount differences, and currency conflicts.','Do not correct supplier application or resend revised advice without the designated employee response. A difference may involve cash, ledger, or supplier-account judgment.']},
    {title:'Protect destinations and disclosures',notes:['Use approved supplier contacts and reveal only the information allowed by company policy. Do not include unrelated vendor or bank data in a combined message.','A request to change the remittance address or bank destination enters independent verification. The prior advice thread is not sufficient authentication.']},
    {title:'Close delivery and reconciliation separately',notes:['Record delivered, bounced, portal-posted, or supplier-query states apart from payment success. Assign an owner and next action to each failure.','Sample multi-invoice, partial, credit-netted, and returned payments. Confirm that the advice points to the result that actually occurred.']}]},
  {slug:'returned-payment-investigation',title:'Prepare the evidence for a returned supplier payment',excerpt:'Trace the released payment, return event, vendor record, and next decision without automatically resubmitting funds.',keyword:'returned supplier payment investigation',focus:'a supplier payment returned after release',owner:'treasury, vendor-master, security, or finance owner',source:'payment approval, bank result, return code, vendor record, invoice state, and verified supplier communication',risk:'automatic correction can repeat fraud, duplicate payment, or master-data errors',sections:[
    {title:'Freeze the chronology before changing anything',notes:['Record batch, payment reference, supplier, entity, amount, currency, destination reference, release time, releaser, return time, and bank message. Preserve the original result.','Do not mark invoices unpaid or resubmit solely from an email report. Confirm the event through the company\'s controlled payment source.']},
    {title:'Translate the return code into a question',notes:['Retain the code and source wording exactly, then route its interpretation to the authorized owner. Similar codes can require different operational responses.','Compare the destination used with the approved vendor record at release time. Do not overwrite that historical value with the current record.']},
    {title:'Verify every proposed correction',notes:['Changed account details, contact instructions, or payment methods need independent verification. Never use new contact details contained in the correction request as the trusted path.','The specialist can prepare evidence and place a hold. Employees decide master-data changes, invoice reopening, cash treatment, and any second release.']},
    {title:'Link the final outcome to both attempts',notes:['If a new payment is authorized, give it a distinct reference and connect it to the return and renewed approval. Prevent both attempts from appearing as unrelated obligations.','If funds settle elsewhere or remain unresolved, preserve that state with an owner. Close only from controlled evidence, not supplier assurance.']}]},
  {slug:'vendor-portal-access-custody',title:'Define custody for vendor portal access used by AP',excerpt:'Assign named access owners, recovery paths, and evidence boundaries for invoice portals used by outsourced support.',keyword:'vendor portal access custody',focus:'access to a supplier invoice or statement portal',owner:'system, security, procurement, or finance owner',source:'approved access request, user roster, portal role, authentication method, activity evidence, and removal confirmation',risk:'shared or orphaned accounts erase accountability and can expose payment data',sections:[
    {title:'Name the company owner before granting access',notes:['Record the portal purpose, supplier, entity, permitted tasks, data visible, employee sponsor, outsourced user, start date, and review date. Avoid access based only on a forwarded invitation.','Use individual accounts and approved authentication where the portal permits them. Shared passwords or borrowed employee identities undermine custody.']},
    {title:'Limit the role to the assigned work',notes:['Document whether support may download invoices, retrieve statements, view status, or upload approved records. Payment changes and supplier-master actions require separate authority.','If portal permissions are bundled, record the excess capability and compensating owner review. The specialist should not test privileged actions.']},
    {title:'Control recovery and unusual events',notes:['Keep recovery contacts, devices, and reset routes with authorized employees. Do not route codes through personal channels or store secrets in the AP procedure.','Escalate unexpected prompts, changed domains, new bank requests, lockouts, or unfamiliar activity. Preserve the evidence without bypassing security controls.']},
    {title:'Review and remove access visibly',notes:['Compare the current roster with assigned work, leave dates, supplier relationships, and portal roles. Record the reviewer and response for every retained account.','When access ends, capture removal or disablement evidence from the owner. The outsourced user should not certify their own access termination.']}]},
  {slug:'intercompany-invoice-routing-evidence',title:'Prepare routing evidence for an intercompany invoice',excerpt:'Identify both company sides and preserve source records while employees decide intercompany accounting and settlement.',keyword:'intercompany invoice routing evidence',focus:'an invoice between related company entities',owner:'controller, intercompany accountant, tax, or treasury owner',source:'invoice, entity directory, agreement, service evidence, intercompany identifiers, approval, and counterparty record',risk:'familiar group names can hide wrong-entity, currency, tax, or settlement assumptions',sections:[
    {title:'Identify both legal entities',notes:['Capture issuer and recipient legal names, identifiers, addresses, currency, invoice number, dates, and source systems. Do not route from brand or department name alone.','Link the controlled entity directory and any intercompany account mapping, including effective dates. Conflicts remain visible for employee resolution.']},
    {title:'Separate service evidence from accounting treatment',notes:['Gather the agreement, allocation support, service or delivery record, and approvals. State what each source proves and which evidence is missing.','Outsourced AP support must not decide transfer pricing, tax, elimination, account mapping, foreign exchange, or netting treatment.']},
    {title:'Coordinate the two queues without merging them',notes:['Record the counterpart identifier and status on each side so teams can compare invoice, receivable, payable, and dispute events. Preserve each system as its own source.','A posting on one side does not authorize the other. Route mismatched periods, currencies, amounts, or approvals to the named intercompany owner.']},
    {title:'Close with reciprocal references',notes:['Retain the employee decision, system records, settlement reference if applicable, and open differences. Do not mark matched because totals happen to offset elsewhere.','Sample cross-border, multi-currency, allocated, and corrected invoices. The evidence should let reviewers reconstruct both sides without relying on group familiarity.']}]},
];

function expand(spec: Spec, note: string, index: number) {
  const sequence = `For ${spec.focus}, the outsourced AP specialist should preserve the ${spec.source}. The record must name the ${spec.owner} who can decide the unresolved point. ${note} Note the legal entity, document identifier, amount and currency, source location, observation time, current state, and next review date. Keep copied values beside their original evidence, and describe a missing value as missing rather than filling it from habit. If sources conflict, retain both and ask a narrow question. This matters because ${spec.risk}. Support may collect records, compare visible fields, prepare a factual question, update the queue, and follow the approved escalation. It may not approve an obligation, choose accounting or tax treatment, alter vendor master data from an unverified request, promise a payment date, or release funds. Preserve earlier versions and the authorized response so another reviewer can reconstruct why the item moved.`;
  const endings = [
    `Test this step with an ordinary record and a difficult exception. The result should prove traceability and ownership, not a promised processing outcome.`,
    `At handoff, another person should be able to identify the next action without an oral retelling or a search through personal messages.`,
    `When the owner responds, record who answered, when, what was decided, and which source supports the change in status.`,
    `Review recurring gaps with the process owner, but update the operating rule only through an authorized and dated change.`,
  ];
  return `${sequence} ${endings[index % endings.length]}`;
}

export const sep3BlogPosts = specs.map(spec => ({slug:spec.slug,title:spec.title,excerpt:spec.excerpt,minutes:10}));
export const sep3BlogDetails = Object.fromEntries(specs.map(spec => [spec.slug, {
  shortAnswer: spec.excerpt,
  published:'2026-09-03',
  modified:'2026-09-03',
  mainKeyword: spec.keyword,
  sections: spec.sections.map((section, sectionIndex) => ({title:section.title, paragraphs:section.notes.map((note, noteIndex) => expand(spec,note,sectionIndex+noteIndex))})),
  checklistTitle:'Review the handoff record',
  checklist:['Controlled sources retained','Uncertainty stated plainly','Employee decision owner named','Next action and date recorded'],
  faqs:[
    {question:'What can outsourced AP support prepare?',answer:`Support can assemble and compare the records for ${spec.focus}, document exceptions, and route a factual question.`},
    {question:'Which decisions stay with the company?',answer:`The ${spec.owner} retains the relevant approval, accounting, vendor-data, security, tax, and payment authority.`},
  ],
}]));
