type Spec={slug:string;title:string;excerpt:string;keyword:string;scene:string;records:string;owner:string;tests:string;thumbnail:string};
const date='2026-09-09' as const;
const specs:Spec[]=[
['ap-invoice-hold-release-register','Make every invoice hold—and every release—explainable','Keep the evidence, owner, aging, and release decision together when an invoice cannot move forward.','invoice hold release register','An invoice is on hold, but the queue does not say whether the cause is a dispute, missing receipt, or payment concern.','invoice ID, entity, hold category, source evidence, placed-by event, owner, review date, correspondence, release evidence, approver, and history','invoice or payment control owner','new, aged, released, disputed, duplicate-risk, and unexplained holds','/blog-thumbnails/ap-invoice-exception-log-template.svg'],
['ap-remittance-advice-delivery-log','Close the gap between payment and remittance advice','Track whether usable remittance reached the right supplier contact without treating delivery as proof of application.','remittance advice delivery log','A supplier reports an unpaid invoice even though the bank shows a completed payment.','payment reference, paid items, currency, advice version, approved recipient, send event, delivery response, supplier reply, follow-up, and resolution','treasury or supplier-relationship owner','delivered, bounced, wrong-contact, partial, consolidated, resent, and disputed advice','/blog-thumbnails/ap-payment-status-inquiry-process.svg'],
['ap-purchase-order-closure-review','Review purchase orders before AP treats them as closed','Separate invoice matching facts from the business decision to close an order or release its remaining commitment.','purchase order closure review','A buyer asks AP to clear an old purchase order while an invoice and unused balance remain visible.','PO version, receipts, invoices, credits, open commitments, requester statement, supplier correspondence, proposal, owner decision, and system event','procurement or budget owner','fully invoiced, partial, overbilled, returned, cancelled, disputed, and service orders','/blog-thumbnails/ap-purchase-request-review.svg'],
['ap-vendor-portal-access-inventory','Inventory vendor-portal access before it becomes invisible','Document who can enter supplier portals, what they can see or change, and when access must be reviewed.','vendor portal access inventory','An analyst leaves a queue while shared and named supplier-portal accounts remain active.','portal, supplier, user, account type, approved purpose, privileges, credential owner, MFA method, last review, exception, and revocation','security or application owner','active, dormant, shared, privileged, departed-user, recovery, and unowned accounts','/blog-thumbnails/ap-finance-support-access-review.svg'],
['ap-prepayment-amortization-handoff','Hand off supplier prepayments without losing the future schedule','Connect the original approval and cash event to delivery evidence, recognition dates, exceptions, and reconciliation.','supplier prepayment amortization handoff','A supplier deposit is paid now, but later invoices and service periods must be matched against it.','agreement, approval, payment, supplier balance, delivery evidence, schedule basis, periodic entries, applications, variance, and remaining amount','accounting policy owner','full delivery, partial delivery, delay, cancellation, refund, currency change, and disputed schedules','/blog-thumbnails/ap-reconciliation-evidence-pack.svg'],
['ap-supplier-contact-authority-record','Record which supplier contacts may answer which AP questions','Distinguish routine correspondence from instructions that require independent company verification.','supplier contact authority record','A familiar contact sends new bank instructions in an email thread used for invoice questions.','supplier and entity, contact identity, approved channels, permitted topics, verification source, effective dates, changes, restrictions, and revocation','vendor-master or treasury owner','invoice queries, statements, bank changes, ownership changes, urgent demands, substitutes, and stale contacts','/blog-thumbnails/ap-vendor-change-request-workflow.svg'],
['ap-invoice-accrual-source-packet','Build invoice-accrual packets that survive the close','Preserve how an expected liability was identified, estimated, approved, posted, and later cleared.','invoice accrual source packet','Services were received before close, but the invoice has not arrived and the estimate depends on several emails.','entity, period, contract, receipt evidence, service dates, estimate source, calculation, exclusions, approval, journal, invoice receipt, and reversal','financial close owner','invoice-later, estimate-change, partial-service, disputed, recurring, reversed, and unmatched accruals','/blog-thumbnails/ap-month-end-open-invoice-review.svg'],
['ap-duplicate-payment-recovery-file','Treat duplicate-payment recovery as a case file','Link the suspected duplicate, validated payment events, supplier response, recovery method, and final ledger result.','duplicate payment recovery file','Two payments share an amount and supplier, but their references and bank dates differ.','candidate invoices, payment IDs, bank evidence, rationale, validation, supplier contact, credit or refund promise, cash event, application, and closure','cash or accounting owner','confirmed duplicates, false positives, partial recovery, credits, refunds, offsets, and unrecovered cases','/blog-thumbnails/ap-invoice-duplicate-controls.svg'],
['ap-foreign-currency-invoice-rate-evidence','Keep foreign-currency invoice rate evidence with the posting','Show which date, source, rate, calculation, and policy owner support a converted invoice amount.','foreign currency invoice rate evidence','An invoice, purchase order, and ledger each display a different functional-currency amount.','document and functional currencies, dates, approved rate source, retrieved rate, calculation, rounding, system result, variance, and correction','treasury or accounting policy owner','spot, contractual, period-end, credit, prepayment, missing-rate, and rounding cases','/blog-thumbnails/invoice-coding-review-checklist.svg'],
['ap-service-entry-evidence-check','Check service-entry evidence without inventing receipt','Identify missing service confirmation and route it to the accountable business owner.','service entry evidence check','A service invoice matches the order value, but no record explains which period or milestone was accepted.','invoice, contract, service period, milestone, requester, approved evidence, system entry, missing fields, response, and match result','requester or procurement owner','recurring, milestone, time-based, disputed, partial, cancelled, and no-PO services','/blog-thumbnails/ap-unmatched-invoice-follow-up.svg'],
['ap-small-balance-writeoff-queue','Route small AP balances without turning thresholds into permission','Prepare aged residuals and evidence while leaving write-off policy and accounting approval with named owners.','AP small balance write-off queue','A supplier account retains a minor debit or credit after payment and no open document explains it.','supplier, entity, currency, balance, aging, source transactions, reconciliation, correspondence, policy, proposal, approver, and posting','controller or accounting owner','debit, credit, foreign-currency, active-supplier, inactive-supplier, disputed, and aggregated balances','/blog-thumbnails/ap-invoice-status-dashboard.svg'],
['ap-invoice-approval-return-reasons','Use approval-return reasons that lead to a next action','Replace vague rejections with factual categories, retained comments, ownership, and a traceable resubmission.','invoice approval return reasons','An approver sends an invoice back as “incorrect,” and AP cannot tell what must change.','invoice and workflow IDs, approver, return time, reason, comment, missing evidence, owner, response, resubmission, outcome, and aging','invoice approval owner','coding, receipt, price, entity, duplicate, budget, disputed, and unclear returns','/blog-thumbnails/invoice-approval-escalation-rules.svg'],
].map(x=>({slug:x[0],title:x[1],excerpt:x[2],keyword:x[3],scene:x[4],records:x[5],owner:x[6],tests:x[7],thumbnail:x[8]} as Spec));
const sections=(s:Spec)=>[
 {title:`Start the ${s.keyword} with observable facts`,paragraphs:[`${s.scene} Define the event that opens the record, the entity, the queue, and the authoritative source before classifying the exception.`,`Retain ${s.records}. Leave gaps visible so a reviewer can distinguish missing evidence from a negative answer.`]},
 {title:'Keep preparation separate from authority',paragraphs:[`Outsourced AP support may collect approved evidence, compare fields, update factual status, and route the case. The ${s.owner} keeps judgment, approval, system configuration, and payment authority.`,`Record each handoff. Preserve earlier facts and decisions when the case changes direction.`]},
 {title:'Replay awkward cases before scaling',paragraphs:[`Ask a second reviewer to rebuild the outcome from the retained packet. Include ${s.tests}.`,`If reviewers disagree, improve the source hierarchy, category definition, access, example, or escalation rule before adding volume.`]},
];
export const sep9BlogPosts=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:8}));
export const sep9BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,thumbnail:s.thumbnail,shortAnswer:`Maintain a source-linked ${s.keyword}, keep uncertainty visible, and leave decisions with the ${s.owner}.`,sections:sections(s),faqs:[{question:`What can outsourced AP prepare in this ${s.keyword}?`,answer:`Support may gather approved records, compare observable facts, track status, and route exceptions. The ${s.owner} retains judgment and authorization.`},{question:'What should a reviewer reproduce?',answer:`The chronology and outcome from ${s.records}, including missing or disputed evidence.`}]}]));
