import type {Draft} from './blog-oct2-batch';

export const oct8BlogPublicationDate = '2026-10-08';

type Spec = {slug:string;title:string;excerpt:string;subject:string;owner:string;decision:string;evidence:string[]};

const sources = [
  {name:'GAO Standards for Internal Control in the Federal Government',url:'https://www.gao.gov/greenbook',note:'Authoritative framework for responsibility, control activities, quality information, and monitoring.'},
  {name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Authoritative control catalog supporting least privilege, attributable events, and retained audit evidence.'},
  {name:'IRS recordkeeping guidance',url:'https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping',note:'Government guidance on retaining records that support business transactions.'}
];

const specs: Spec[] = [
  {slug:'vendor-remittance-email-bank-change-conflict',title:'Resolve a vendor remittance email and bank-change conflict',excerpt:'Separate a routine remittance request from changed payment instructions, preserve the evidence, and route each decision to its authorized owner.',subject:'a remittance-email request that also introduces different bank details',owner:'vendor-master, treasury, and payment-approval owners',decision:'whether the supplier identity and proposed payment destination satisfy the company verification process',evidence:['original email and headers','previously verified supplier contact','masked bank-detail tokens','vendor-master history','payment proposal version','verification and approval events']},
  {slug:'invoice-duplicate-after-supplier-legal-name-change',title:'Review a possible duplicate invoice after a supplier legal-name change',excerpt:'Compare identities, invoice versions, credits, and postings without assuming that a new supplier name creates a new obligation.',subject:'a duplicate signal spanning old and new supplier legal names',owner:'vendor-master and finance owners',decision:'whether the records represent one obligation, a valid rebill, or separate transactions',evidence:['invoice images','vendor identifiers','legal-name change record','purchase order and receipt','posting history','credits and cancellations']},
  {slug:'purchase-order-line-closure-late-invoice',title:'Handle a late invoice after its purchase-order line was closed',excerpt:'Reconstruct the order, receipt, closure, and invoice chronology before asking purchasing or finance for a bounded decision.',subject:'a supplier invoice received after the related purchase-order line closed',owner:'purchasing, receiving, and finance owners',decision:'whether the late demand is supported and which authorized process should address the closed commitment',evidence:['original purchase order','order revisions and closure event','receipts or service acceptance','supplier invoice','prior invoices and credits','owner correspondence']},
  {slug:'goods-receipt-timezone-cutoff-review',title:'Review a goods-receipt timezone conflict at period cutoff',excerpt:'Preserve original timestamps, normalize timezones, and let finance decide the cutoff treatment using a reproducible chronology.',subject:'a goods receipt whose local and system timestamps cross the accounting cutoff',owner:'receiving, system, and close owners',decision:'which controlled event and timezone govern the company cutoff treatment',evidence:['delivery or service evidence','receiver event','system receipt log','timezone configuration','invoice and order','close policy and disposition']},
  {slug:'vendor-credit-memo-allocation-conflict',title:'Resolve a vendor credit-memo allocation conflict',excerpt:'Trace the credit to the correct invoices, entities, and open balances without forcing an allocation merely to clear the supplier account.',subject:'a credit memo that could apply to several invoices or company entities',owner:'purchasing and finance owners',decision:'which obligation the credit legally and operationally offsets',evidence:['credit memo','referenced invoices','supplier statement','returns or dispute record','entity and vendor accounts','ledger allocation history']},
  {slug:'invoice-tax-amount-mismatch-evidence-packet',title:'Build an evidence packet for an invoice tax-amount mismatch',excerpt:'Reproduce source amounts and calculations while keeping tax interpretation and posting approval with the responsible finance owner.',subject:'an invoice whose tax amount differs from order, receipt, or system calculation',owner:'tax and finance owners',decision:'which approved tax treatment and posting amount apply',evidence:['invoice tax lines','order tax terms','receipt or service location','system tax calculation','supplier tax record','owner decision']},
  {slug:'payment-run-hold-owner-transfer',title:'Transfer ownership of a payment-run hold without losing control',excerpt:'Keep the hold reason, evidence, authority, and next action intact when responsibility moves between reviewers.',subject:'an unresolved payment hold moving from one owner to another',owner:'the outgoing reviewer, incoming reviewer, and payment approver',decision:'whether the hold remains, changes, or is released under company policy',evidence:['payment proposal','hold event and reason','invoice packet','open exception','handoff acknowledgement','final disposition']},
  {slug:'supplier-statement-missing-page-review',title:'Review a supplier statement with a missing page',excerpt:'Prove the statement sequence, isolate unavailable balances, and avoid treating an incomplete document as a full reconciliation.',subject:'a supplier statement whose page sequence or account section is incomplete',owner:'supplier-contact and reconciliation owners',decision:'whether additional source evidence is required before the account can be reconciled',evidence:['original statement file','page numbers and totals','prior statement','open-invoice ledger','supplier request and response','reconciliation worksheet']},
  {slug:'expense-receipt-identity-mismatch',title:'Investigate an expense receipt identity mismatch',excerpt:'Compare employee, merchant, card, date, and claim records while protecting sensitive data and preserving approval boundaries.',subject:'an expense receipt whose purchaser, cardholder, or claimant identity does not align',owner:'expense-policy, employee, and reimbursement owners',decision:'whether the claim is adequately supported or needs correction or escalation',evidence:['receipt image','expense claim version','employee identity','approved card token','merchant record','review and approval events']},
  {slug:'recurring-invoice-price-amendment-gap',title:'Resolve a recurring invoice price-amendment gap',excerpt:'Connect contract versions, effective dates, service periods, and prior invoices before presenting the variance for approval.',subject:'a recurring supplier invoice that uses a price not found in the current contract record',owner:'contract, purchasing, and finance owners',decision:'which documented rate applies to the billed service period',evidence:['contract and amendments','invoice and service period','purchase order versions','prior invoices','supplier explanation','owner approval']},
  {slug:'vendor-onboarding-beneficial-owner-evidence-route',title:'Route beneficial-owner evidence during vendor onboarding',excerpt:'Collect, protect, and route ownership information without letting an AP preparation role make legal, tax, or compliance decisions.',subject:'beneficial-owner information submitted during supplier onboarding',owner:'legal, compliance, tax, and vendor-master owners',decision:'whether the evidence satisfies the company onboarding requirements',evidence:['supplier application','ownership declaration','approved identity evidence','entity registry reference','review status','activation decision']},
  {slug:'ap-offboarding-saved-payment-template-review',title:'Review saved payment templates during AP offboarding',excerpt:'Inventory template access, ownership, destinations, and recent use before removing a departing support user.',subject:'saved payment templates accessible to a departing AP support user',owner:'system administration, treasury, and security owners',decision:'which templates remain valid, require reassignment, or must be disabled',evidence:['user access export','template inventory','masked destinations','creation and change logs','recent use','removal and review evidence']}
];

function makeBlog(s:Spec):Draft {
  const e=s.evidence;
  const sections=[
    {title:'Frame the exception before touching the record',paragraphs:[`Open one controlled case for ${s.subject}. Record the company entity, supplier or employee identifier, amount, currency, dates, systems involved, queue status, and the precise question that remains unanswered. The support analyst should describe the observed conflict without predicting the outcome. Preserve ${e[0]} and ${e[1]} in their received form, including timestamps and identifiers. A copied value in a message or worksheet is useful for indexing, but it does not replace the source record. This opening snapshot prevents a later system refresh, edited attachment, or urgent follow-up from erasing the facts that first triggered review.`,`State the authority boundary in the case. The accountable decision belongs to ${s.owner}; the decision is ${s.decision}. AP support can gather, compare, label, and route evidence. It should not create missing approval, edit a source to make fields agree, remove a hold, interpret policy beyond the written rule, or release payment. Naming that boundary at intake makes the remaining work more efficient because every request can be directed to the person who can actually answer it.`]},
    {title:'Build a source register and identity map',paragraphs:[`List every source with its system, record owner, retrieval time, effective time, stable identifier, and version. Include ${e[2]}, ${e[3]}, ${e[4]}, and ${e[5]}. Keep original display values beside any normalized values. Similar names, amounts, or references are signals for comparison, not proof that two records describe the same event. Map the legal entity, supplier account, purchase order, invoice, receipt, credit, employee, proposal, or access identity that applies so the reviewer can see where one identifier changes into another.`,`For documents received by email or portal, retain the file and the delivery context. For system records, capture an export, event identifier, or approved screenshot when audit history is unavailable. Mark evidence that came from an unverified contact or from a report that can later change. Sensitive bank, tax, personal, or ownership data should remain masked in the working queue and stored only in the approved location. The objective is a complete lineage, not a convenient bundle of copied values.`]},
    {title:'Reconstruct the chronology in original and normalized time',paragraphs:[`Arrange creation, receipt, change, approval, hold, posting, transmission, rejection, and correction events in sequence. Retain each original timestamp and timezone, then add a normalized UTC value when comparison requires it. Record the actor or automated process and the resulting state. A current screen shows only what exists now; it cannot establish which evidence or instruction was available when an earlier action occurred. Chronology separates a genuine contradiction from an expected lag, later correction, or superseding decision.`,`Do not backdate an explanation to fill a gap. If a source lacks a reliable time, label the limitation and ask the system owner for an event log or the business owner for a dated disposition. Preserve reversals and unsuccessful attempts. They explain why the latest status changed and may prove that an earlier record was never effective. Where two clocks differ, show both and quantify the difference instead of silently choosing the timestamp that produces the cleaner result.`]},
    {title:'Compare fields without manufacturing agreement',paragraphs:[`Create a line-by-line matrix for the identifiers, parties, amounts, currencies, dates, quantities, destinations, approval states, and document versions relevant to the case. Cite the source beside each value. Classify a row as aligned, different, missing, superseded, or awaiting owner interpretation. Recalculate totals using visible arithmetic and preserve both the source precision and the applied rounding. Never overwrite a supplier value with an internal value merely because the internal record is easier to process.`,`Use the matrix to distinguish clerical variation from a decision. Punctuation, leading zeros, or display formatting can often be normalized while keeping the originals. A different legal entity, bank token, tax basis, service period, quantity, authority window, or payment state is substantive and needs the named owner. When prior transactions are consulted, label them as historical examples rather than policy. Repetition can reveal a control defect, but it cannot authorize the same treatment for the current item.`]},
    {title:'Route one bounded question with a complete packet',paragraphs:[`Summarize what agrees, what conflicts, what has been checked, and what remains unavailable. Ask ${s.owner} the bounded question: ${s.decision}? Attach or link the source register, identity map, chronology, comparison matrix, and the minimum sensitive evidence required. Include the due date and operational consequence without using urgency as authority. A good handoff lets the owner answer without repeating the investigation and lets a second reviewer reproduce the support analyst's conclusion.`,`Use evidence-based queue states such as source missing, identity unresolved, amount conflict, policy interpretation pending, verification pending, owner decision pending, correction expected, or disposition recorded. Avoid labels such as handled or approved unless the record identifies who performed that action and when. If ownership changes, require acknowledgement and retain the old and new owner, transfer time, open question, and next review date. This protects the exception from disappearing between inboxes.`]},
    {title:'Verify the implemented outcome',paragraphs:[`After an authorized decision, compare it with the system action. Record the decision owner, timestamp, reason, affected records, approved value or state, and the user or process that implemented it. Confirm that the invoice, vendor, credit, receipt, proposal, reimbursement, template, or access record now reflects the intended outcome. A successful status alone is not proof: the change may have affected a different entity, version, line, or payment cycle.`,`Retain the pre-change and post-change evidence. Link any corrected document, replacement record, reversal, renewed approval, or verification result rather than deleting the earlier version. Check adjacent risks: duplicate drafts, residual balances, unused receipts, old access, pending proposals, or unresolved supplier messages. Close only when the original question has an attributable disposition and every remaining item has an owner and next action.`]},
    {title:'Measure quality without rewarding unsafe speed',paragraphs:[`Sample these cases by cause, entity, supplier, age, value, owner, and outcome. Useful measures include source completeness, time to named ownership, evidence gaps, repeated conflict types, reopened cases, implementation mismatches, and second-review agreement. Do not rank analysts by the number of holds released or exceptions cleared. A well-supported stop can be the correct result, while a fast clearance can hide missing authority or evidence.`,`Review recurring gaps with process owners. Repeated missing timestamps may require system logging; repeated identity conflicts may require master-data cleanup; repeated late evidence may require a supplier or receiving workflow change. AP support can quantify and illustrate patterns, but management owns control design and risk acceptance. The durable result is a reproducible packet that preserves sources, makes responsibility visible, and supports a decision without transferring approval authority to the preparer.`]},
    {title:'Make the control durable for the next reviewer',paragraphs:[`Before adopting the workflow, test it with an ordinary case, a missing-source case, a conflicting-identity case, an urgent request, and a case that changes after approval. Give a backup reviewer only the retained packet and ask that person to reconstruct the source, chronology, difference, owner question, disposition, and implemented result. Record where private message history or undocumented system knowledge was required, then repair the checklist or evidence route. A process is not repeatable merely because its original analyst remembers what happened.`,`Publish the final procedure with field definitions, approved systems, access limits, stop conditions, escalation owners, response expectations, and sample evidence. Review permissions and ownership whenever scope changes. Preserve a version history so later cases can be evaluated against the procedure that actually applied. This final step turns one resolved ${s.subject} case into a controlled handoff that can be reviewed, trained, sampled, and improved without weakening the separation between preparation and authorized decision-making.`]}
  ];
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:12,detail:{thumbnail:'/blog-thumbnails/sep22-2026/goods-receipt-reversal-review.svg',shortAnswer:`For ${s.subject}, preserve the sources, reconstruct the chronology, compare each controlled field, and route ${s.decision} to ${s.owner}. Verify the implemented outcome without letting the preparation role approve or release it.`,published:oct8BlogPublicationDate,modified:null,mainKeyword:s.slug.replaceAll('-',' '),sections,checklistTitle:'Check the exception packet before handoff',checklist:['Original sources and versions are retained','Identifiers and entities are mapped','Original and normalized timestamps remain visible','Differences are classified without forced agreement','The decision has a named authorized owner','Implementation is verified against the disposition'],bodyLinks:[{href:'/services',label:'accounts payable support services'},{href:'/contact-us',label:'scope a controlled AP workflow'}],faqs:[{question:'Can outsourced AP support decide this exception?',answer:`Support can assemble and compare evidence, but ${s.owner} must decide ${s.decision}.`},{question:'What should remain in the case?',answer:`Retain ${e.join(', ')}, plus the final owner decision and implementation evidence.`},{question:'When is the case complete?',answer:'Close it only after the authorized disposition is implemented, verified against the correct record, and any residual item has a named owner.'}],sources}};
}

export const oct8BlogDrafts:Draft[]=specs.map(makeBlog);
export const oct8BlogPosts=oct8BlogDrafts.map(({slug,title,excerpt,minutes})=>({slug,title,excerpt,minutes}));
export const oct8BlogDetails=Object.fromEntries(oct8BlogDrafts.map(post=>[post.slug,post.detail]));
