type Spec={slug:string;title:string;excerpt:string;keyword:string;scene:string;record:string;owner:string;check:string};
const date='2026-09-07' as const;
const specs:Spec[]=[
{slug:'ap-invoice-receipt-timestamp-log',title:'Keep an invoice receipt timestamp log',excerpt:'Preserve when an invoice first reached the business so queues, due dates, and handoffs can be reviewed from evidence.',keyword:'invoice receipt timestamp log',scene:'A supplier resends an overdue invoice and the forwarded copy obscures when the original message arrived.',record:'original message ID, sender, recipient inbox, received time, attachment identity, forwarding history, queue entry, and correction notes',owner:'invoice intake owner',check:'test direct mail, forwarded mail, portal downloads, duplicates, delayed sync, and missing headers'},
{slug:'ap-po-closure-evidence-checklist',title:'Use an evidence checklist before closing purchase orders',excerpt:'Give AP a bounded way to identify open invoice questions without deciding whether procurement should close a purchase order.',keyword:'purchase order closure evidence checklist',scene:'The final invoice appears paid, but one receipt was reversed after the buyer requested closure.',record:'PO version, lines, receipts, reversals, invoices, credits, open commitments, buyer response, closure decision, and system event',owner:'procurement or purchasing owner',check:'cover fully used, partially used, over-invoiced, credited, reversed-receipt, cancelled, and disputed orders'},
{slug:'ap-duplicate-supplier-record-review',title:'Review possible duplicate supplier records',excerpt:'Compare supplier identities and activity while keeping merge, disablement, and master-data decisions with authorized employees.',keyword:'duplicate supplier record review',scene:'Two supplier IDs share a tax name but use different remit addresses and bank records.',record:'supplier IDs, legal and trading names, addresses, identifiers, approved contacts, payment history, active documents, comparison, and decision',owner:'vendor-master owner',check:'sample exact matches, trading names, related entities, address changes, inactive records, and false positives'},
{slug:'ap-invoice-coding-reference-table',title:'Maintain an invoice coding reference table',excerpt:'Document approved recurring coding patterns without turning old postings into automatic accounting conclusions.',keyword:'invoice coding reference table',scene:'A recurring software invoice adds a new service line that was not present in the approved example.',record:'supplier, entity, invoice type, approved coding example, effective dates, source policy, changed fields, exception, reviewer, and decision',owner:'accounting policy owner',check:'include stable invoices, new lines, changed entities, credits, allocations, taxes, and expired guidance'},
{slug:'ap-vendor-portal-access-review',title:'Run a vendor portal access review',excerpt:'Keep supplier-portal access attributable, limited, and removable as AP assignments and personnel change.',keyword:'vendor portal access review',scene:'A former contractor still appears as an administrator in a supplier billing portal.',record:'portal, supplier, user, role, access purpose, approval source, last use, authentication method, review result, and removal evidence',owner:'system or security owner',check:'review active, dormant, shared, privileged, terminated-user, emergency, and unknown accounts'},
{slug:'ap-payment-return-triage-queue',title:'Build a payment return triage queue',excerpt:'Separate bank-return facts, supplier follow-up, master-data concerns, and authorized repayment decisions.',keyword:'payment return triage queue',scene:'A bank rejects a supplier payment after a recent remittance-detail change.',record:'payment ID, bank status and code, amount, supplier, invoice population, master-record version, contacts, hold status, owner decision, and outcome',owner:'treasury payment owner',check:'test closed accounts, invalid details, sanctions holds, duplicates, partial returns, fees, and unexplained codes'},
{slug:'ap-unmatched-receipt-followup-log',title:'Track unmatched receipt follow-up',excerpt:'Route invoice-to-receipt gaps to the right operational owner while preserving what AP checked and what remains unknown.',keyword:'unmatched receipt follow-up log',scene:'An invoice references delivered goods, but the receiving system has no matching event.',record:'invoice line, PO line, expected location, receiving search, delivery evidence, requester, messages, owner response, and resolution',owner:'receiving or business owner',check:'cover late receipts, wrong locations, partial deliveries, services, reversals, missing POs, and supplier errors'},
{slug:'ap-small-balance-writeoff-review-queue',title:'Create a small-balance write-off review queue',excerpt:'Present aging and evidence consistently without letting a dollar threshold replace accounting approval.',keyword:'small-balance write-off review queue',scene:'A minor residual balance may be rounding, a short payment, or an unapplied credit.',record:'supplier, entity, currency, open item, age, source documents, payment and credit history, correspondence, proposed cause, decision, and posting',owner:'accounting owner',check:'include rounding, fees, credits, disputes, currency differences, duplicate items, and recoverable balances'},
{slug:'ap-early-payment-discount-calendar',title:'Maintain an early-payment discount calendar',excerpt:'Make discount opportunities visible while leaving cash, approval, and payment-timing decisions with authorized owners.',keyword:'early-payment discount calendar',scene:'An invoice offers a discount date before its normal approval cycle can finish.',record:'invoice, terms source, receipt date, discount date and amount, approval status, exceptions, cash owner response, payment proposal, and outcome',owner:'treasury or finance owner',check:'test valid terms, ambiguous terms, late receipt, disputed invoices, credits, weekends, and missed discounts'},
{slug:'ap-intercompany-invoice-routing-log',title:'Keep an intercompany invoice routing log',excerpt:'Identify entity and ownership questions early without allowing AP preparation to determine intercompany treatment.',keyword:'intercompany invoice routing log',scene:'A shared-services charge names one entity in the file and another in the email instructions.',record:'source file, sender, named entities, agreement reference, period, currency, receiving queue, conflicts, accounting owner, decision, and posting reference',owner:'intercompany accounting owner',check:'cover clear charges, conflicting entities, missing agreements, duplicates, reversals, allocations, and wrong periods'},
{slug:'ap-supplier-contact-change-log',title:'Document supplier contact changes separately from bank changes',excerpt:'Retain who requested a contact update, how it was verified, and which communications the new contact may receive.',keyword:'supplier contact change log',scene:'A new billing contact asks to replace every prior supplier contact and receive remittance notices.',record:'request source, supplier, fields changed, old and proposed contacts, independent source, verification attempts, authorization, system event, and notices',owner:'vendor-master owner',check:'test additions, removals, domain changes, bounced mail, disputed authority, urgent requests, and withdrawals'},
{slug:'ap-month-end-invoice-cutoff-register',title:'Run a month-end invoice cutoff register',excerpt:'Carry late and unresolved invoices into close with visible evidence, ownership, and accounting decisions.',keyword:'month-end invoice cutoff register',scene:'An invoice arrives after the operational cutoff but relates to services completed before month end.',record:'invoice source, receipt time, service or delivery evidence, entity, amount, PO and receipt status, exception, accounting response, close treatment, and posting',owner:'financial close owner',check:'sample pre-cutoff, late-arriving, disputed, recurring, missing-receipt, corrected, and subsequent-period invoices'},
];
const sections=(s:Spec)=>[
 {title:`Start the ${s.keyword} with source evidence`,paragraphs:[`${s.scene} Define the queue, period, company entity, source systems, and the event that starts the clock before assigning work.`, `Retain ${s.record}. Keep missing or conflicting fields visible instead of filling them from memory.`]},
 {title:'Separate preparation from authority',paragraphs:[`An outsourced AP specialist may gather approved records, compare observable fields, update factual status, and route questions. The ${s.owner} retains policy, approval, accounting judgment, master-data changes, and payment authority.`, `Use plain states such as received, checked, waiting for evidence, with owner, decided, and closed. Record every correction and handoff.`]},
 {title:'Test exceptions and replay the result',paragraphs:[`Choose awkward cases before launch and ask a second reviewer to reconstruct the outcome from the retained packet without an oral explanation.`, `For acceptance, ${s.check}. If the reviewers differ, repair the rule, example, access, or escalation path before scaling the queue.`]},
];
export const sep7BlogPosts=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:8}));
export const sep7BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,shortAnswer:`Build a source-linked ${s.keyword}, show missing evidence, and reserve decisions for the ${s.owner}.`,sections:sections(s),faqs:[{question:`What can outsourced AP support do with this ${s.keyword}?`,answer:`Support can collect approved records, compare observable fields, maintain factual status, and route exceptions. The ${s.owner} keeps decisions and authorization.`},{question:'How should the routine be tested?',answer:`Retain ${s.record}, then ${s.check}.`}]}]));
