type Topic = {
  slug: string; title: string; excerpt: string; keyword: string;
  service: string; serviceLabel: string; scenario: string; owner: string;
  records: string; example: string; steps: [string, string][];
};

const steps = (...items: [string, string][]) => items;

const topics: Topic[] = [
  {slug:'invoice-service-period-validation',title:'Validate an invoice service period before coding',excerpt:'Separate invoice date, service period, receipt evidence, and posting proposal so AP can route a period question without making the accounting decision.',keyword:'invoice service period validation',service:'invoice-data-capture',serviceLabel:'invoice data capture',scenario:'an invoice whose service dates are missing, ambiguous, or inconsistent with the purchase record',owner:'controller or finance owner',records:'invoice, contract, purchase order, acceptance record, prior invoice, receipt timestamp, and close instruction',example:'A consulting invoice dated September 22 says only “monthly services,” while the statement of work began August 15. The processor records the ambiguity and asks the owner which dated evidence governs instead of inferring a September service period.',steps:steps(['Preserve every relevant date','Capture invoice, receipt, service, delivery, approval, and proposed posting dates as separate fields with their source.'],['Read the commercial description','Compare line descriptions, contract milestones, subscription terms, and acceptance records without treating one vague label as proof.'],['Check for overlaps and gaps','Place adjacent invoices on a timeline and flag days billed twice or not represented; do not conclude that either pattern is wrong.'],['Prepare the close question','State the amount, entity, possible periods, missing evidence, and exact decision needed from finance.'],['Retain the authorized answer','Link the decision, responder, timestamp, supporting source, and any corrected supplier document to the original packet.'],['Review recurring suppliers','Sample repeat invoices for consistent periods and escalate patterns to the process owner before changing a standing rule.'])},
  {slug:'duplicate-credit-memo-detection',title:'Detect duplicate credit memos before they distort AP',excerpt:'Compare credit references, amounts, invoice links, applications, and supplier statements before treating similar credits as separate value.',keyword:'duplicate credit memo detection',service:'duplicate-invoice-review',serviceLabel:'duplicate invoice review',scenario:'two credit records that may represent the same supplier adjustment',owner:'AP or finance owner',records:'credit documents, original invoices, supplier statement, ledger applications, return records, emails, and audit history',example:'A supplier emails credit CM-841 twice, once as a PDF and once through its portal, while the filenames differ. AP matches the supplier reference, amount, currency, and original invoice, then parks the second intake for owner review.',steps:steps(['Normalize without deleting evidence','Create a comparison key while retaining punctuation, leading zeros, filenames, and original channel data.'],['Trace the business event','Link the return, price correction, duplicate payment, rebate, or disputed invoice that produced each credit.'],['Compare applications','Show where each credit has been posted, proposed, applied, reversed, or left open by entity and currency.'],['Use the supplier statement carefully','Treat the statement as a separate source and investigate timing or scope differences instead of overwriting the ledger.'],['Route the disposition','Present the likely duplicate and affected balance to the authorized owner; support does not delete or apply value.'],['Close both records visibly','Link the retained credit and rejected, voided, or corrected record so a later copy does not reenter the queue.'])},
  {slug:'vendor-address-change-evidence',title:'Build evidence for a vendor address change',excerpt:'Distinguish mailing, remit-to, ordering, legal, and tax addresses before an authorized employee changes a supplier record.',keyword:'vendor address change evidence',service:'vendor-onboarding-administration',serviceLabel:'vendor onboarding administration',scenario:'a supplier asking the company to change one or more addresses',owner:'vendor-master, tax, or finance owner',records:'change request, current vendor record, contract, tax form, invoice, approved contact directory, verification result, and authorization',example:'A supplier invoice shows a new remit-to address, but the email asks to replace the legal address too. The specialist separates both requests and sends each through the required ownership and verification path.',steps:steps(['Name the address type','Record whether the request concerns legal, tax, physical, mailing, ordering, remit-to, or return details.'],['Keep old and proposed values','Show field-by-field differences, effective date, supplier entity, company entity, and the source that introduced each value.'],['Verify through a trusted path','Use the company-approved contact or portal rather than phone numbers and links supplied only in the change message.'],['Separate related controls','Route bank, tax, legal-entity, and payment-method changes through their own checks even when bundled with the address.'],['Require recorded authority','The specialist prepares the packet; the designated vendor-master or finance employee authorizes the system change.'],['Test downstream records','After approval, confirm invoices, orders, tax records, statements, and correspondence use the intended address without rewriting history.'])},
  {slug:'po-tolerance-exception-packet',title:'Prepare a purchase order tolerance exception packet',excerpt:'Show the exact price or quantity variance, configured tolerance, receipts, and commercial evidence before an owner decides whether an invoice may proceed.',keyword:'purchase order tolerance exception packet',service:'three-way-match-support',serviceLabel:'three-way match support',scenario:'an invoice that exceeds a configured purchase-order match tolerance',owner:'purchasing or finance owner',records:'invoice, order versions, receipts, tolerance configuration, contract, prior invoices, exception history, and approval',example:'An invoice line is 2.4 percent above the order price while the system tolerance is 2 percent. AP records the $84 difference and configuration result rather than splitting the line or changing the order.',steps:steps(['Reproduce the system result','Record ordered, received, invoiced, prior-billed, and remaining values at line level using the active tolerance rule.'],['Identify the variance dimension','Separate unit price, quantity, freight, tax, currency, rounding, and cumulative-value exceptions.'],['Confirm the rule version','Capture the tolerance name, threshold, entity, effective date, and system timestamp without treating configuration as approval.'],['Attach commercial evidence','Link amendments, quotes, delivery records, and supplier explanations while preserving conflicts and missing sources.'],['Ask for one disposition','Give the owner the line, variance, policy result, deadline, and available paths without recommending an unauthorized bypass.'],['Re-run the match','After a controlled correction or approval, repeat the comparison and retain both the original exception and final outcome.'])},
  {slug:'receipt-reversal-invoice-review',title:'Review an invoice after a goods receipt reversal',excerpt:'Reconstruct receipt, reversal, return, correction, and invoice events so AP does not match against inventory evidence that no longer stands.',keyword:'goods receipt reversal invoice review',service:'purchase-order-reconciliation',serviceLabel:'purchase order reconciliation',scenario:'an invoice linked to a purchase-order receipt that was later reversed',owner:'receiving, purchasing, or finance owner',records:'invoice, purchase order, receipt, reversal audit log, return record, warehouse note, credits, and approval history',example:'A warehouse received 40 units, reversed the receipt the next day, then entered 36 units under a new reference. AP builds the sequence and matches only against the controlled final evidence after owner review.',steps:steps(['Build the event chronology','Record each receipt, reversal, return, re-receipt, invoice, and credit with actor, timestamp, quantity, line, and identifier.'],['Preserve the reason code','Capture the system reason and any supporting note, but do not treat a generic code as proof of what physically happened.'],['Reconcile quantities by line','Compare ordered, accepted, returned, invoiced, credited, and open quantities without netting away the individual events.'],['Check invoice timing','Show whether the invoice preceded or followed the reversal and whether a corrected receipt or supplier document exists.'],['Route the operational question','Receiving confirms physical acceptance; purchasing or finance decides the approved processing path.'],['Link the final match','Retain the superseded records and point the invoice to the authorized receipt, correction, hold, rejection, or credit.'])},
  {slug:'invoice-approval-delegation-handoff',title:'Control an invoice approval delegation handoff',excerpt:'Document who is absent, who may act, which invoices are covered, and when authority ends before routing approvals to a delegate.',keyword:'invoice approval delegation handoff',service:'ap-inbox-management',serviceLabel:'AP inbox management',scenario:'invoice approvals moving temporarily from one employee to another',owner:'approval-policy or finance owner',records:'delegation authorization, approval matrix, dates, entity and amount scope, invoice queue, system access, actions, and revocation',example:'A manager is away for a week and names a colleague in chat, but the colleague has no recorded authority for capital invoices. AP holds those invoices while the policy owner confirms scope and system access.',steps:steps(['Verify the delegation source','Use the controlled authorization path and do not convert an informal out-of-office message into approval authority.'],['Define scope precisely','Record entities, cost centers, invoice types, amount limits, excluded vendors, start time, end time, and timezone.'],['Check conflicts and access','Confirm that system rights, segregation rules, and substitute-review requirements match the documented delegation.'],['Prepare the open-queue handoff','List pending invoices, ages, due dates, exceptions, prior comments, and the next action without implying approval.'],['Record every delegated action','Keep the approver identity, delegation reference, timestamp, decision, and system event linked to each invoice.'],['End authority on time','Remove or expire temporary rights, return open work to the normal owner, and review actions completed during the period.'])},
  {slug:'payment-proposal-removal-log',title:'Maintain a log when invoices leave a payment proposal',excerpt:'Record why an approved invoice was removed, who authorized the change, and what happens next without silently rewriting the payment run.',keyword:'payment proposal removal log',service:'payment-run-preparation',serviceLabel:'payment run preparation',scenario:'an invoice removed from a payment proposal after the list was prepared',owner:'treasury or payment approver',records:'payment proposal versions, invoice approval, removal request, hold evidence, funding decision, release result, and next-run status',example:'An approved invoice is removed after a buyer raises a delivery dispute. AP records the proposal version, amount, authorized requester, dispute owner, and review date instead of deleting the row from the working file.',steps:steps(['Freeze the original proposal','Store the run ID, version, timestamp, entity, bank account reference, currencies, invoice list, and total.'],['Capture the removal reason','Use specific states such as new dispute, duplicate concern, legal hold, data change, funding decision, or owner request.'],['Confirm decision authority','The support role can prepare the change record but cannot choose which approved debts to delay or release.'],['Recalculate visibly','Show item count and total before and after removal, with separate currency totals and no hidden spreadsheet rows.'],['Keep the invoice active','Assign an owner, question, status, and next review or run date so removal does not make the liability disappear.'],['Reconcile the released run','Link bank and system results to the final authorized proposal and explain every difference from the original version.'])},
  {slug:'supplier-account-hold-inquiry',title:'Investigate a supplier account hold without promising payment',excerpt:'Organize invoices, disputes, payments, credits, and supplier claims so the right owner can resolve an account hold.',keyword:'supplier account hold inquiry',service:'vendor-statement-reconciliation',serviceLabel:'vendor statement reconciliation',scenario:'a supplier saying the company account is on hold',owner:'supplier relationship, purchasing, or finance owner',records:'supplier notice, statement, open invoices, disputes, payment results, credits, purchase commitments, and correspondence',example:'A supplier pauses new shipments because it says two invoices are overdue. One was paid but appears unapplied and the other lacks receiving evidence, so AP routes two distinct actions instead of promising a payment date.',steps:steps(['Confirm the claim safely','Record the supplier account, legal entities, hold scope, notice time, contact source, and operational impact.'],['Reconcile the stated balance','Match statement lines to ledger invoices, credits, payments, disputes, and unapplied items by currency and entity.'],['Separate causes','Classify missing invoice, missing receipt, approval delay, dispute, payment failure, unapplied cash, and genuine scheduled payment.'],['Avoid unauthorized promises','Provide only approved status language; staff should not commit payment timing, credit treatment, or commercial concessions.'],['Route parallel actions','Send each exception to its named owner while maintaining one consolidated supplier-facing status record.'],['Close from evidence','Remove the inquiry only after the supplier and company records show the authorized resolution or an owner accepts the remaining difference.'])},
  {slug:'recurring-invoice-contract-renewal-trace',title:'Trace a recurring invoice through contract renewal',excerpt:'Compare the old and renewed term, price, service period, supplier entity, and approval before accepting a changed recurring invoice.',keyword:'recurring invoice contract renewal review',service:'invoice-data-capture',serviceLabel:'invoice data capture',scenario:'a subscription or repeating invoice that changes near a contract renewal',owner:'contract, purchasing, or budget owner',records:'current and prior contracts, renewal notice, invoice series, order, approval, service evidence, and supplier record',example:'A software invoice rises 8 percent at renewal and adds five users. AP separates the stated price change from the seat change and asks the contract owner to confirm both against the signed renewal.',steps:steps(['Anchor the prior term','Record old dates, price, quantity, billing frequency, entity, currency, and approved source before reviewing the change.'],['Identify every new term','Compare renewal dates, notice period, indexation, quantity, tier, tax, credits, discounts, and supplier identity field by field.'],['Map invoice coverage','Show which service days or units the new invoice covers and detect overlap with the last invoice or a prepaid period.'],['Confirm the commitment record','Link the signed renewal, purchase-order amendment, or owner authorization; a supplier notice alone is not company approval.'],['Route unresolved differences','Present the amount, relevant clause, missing evidence, and due date without interpreting legal terms for the company.'],['Set the new baseline carefully','After authorization, retain both terms and note the effective date so future recurring checks use the approved record.'])},
  {slug:'unapplied-vendor-payment-investigation',title:'Investigate an unapplied vendor payment',excerpt:'Connect the bank result, remittance, supplier account, invoice set, and ledger posting before anyone reallocates cash or closes open items.',keyword:'unapplied vendor payment investigation',service:'vendor-statement-reconciliation',serviceLabel:'vendor statement reconciliation',scenario:'a supplier payment that cannot be matched cleanly to invoices',owner:'treasury, cash, or finance owner',records:'bank result, payment batch, remittance advice, supplier statement, invoices, credits, vendor accounts, and ledger applications',example:'A $14,820 payment cleared the bank, but the supplier posted it to a similarly named account. AP assembles the remittance and account identifiers while an authorized employee handles reapplication.',steps:steps(['Confirm the payment event','Record amount, currency, value date, bank reference, beneficiary, company entity, batch, and release authorization.'],['Rebuild the intended application','List invoice and credit references from the approved proposal and remittance without inventing a split for missing detail.'],['Compare supplier accounts','Check legal names, account numbers, locations, currencies, and parent-child relationships without merging accounts on similarity.'],['Protect sensitive information','Share only the minimum payment reference through approved channels and do not expose bank credentials or unrelated invoices.'],['Assign correction authority','The specialist tracks evidence and responses; treasury or finance authorizes ledger and supplier-account changes.'],['Verify both sides','Close only when bank, company ledger, supplier statement, and affected invoices reflect the recorded resolution.'])},
  {slug:'invoice-capture-confidence-review',title:'Review low-confidence invoice capture fields',excerpt:'Turn uncertain OCR or extraction results into a focused human review without presenting machine confidence as accounting evidence.',keyword:'invoice capture confidence review',service:'invoice-data-capture',serviceLabel:'invoice data capture',scenario:'an invoice extraction tool marking important fields as uncertain',owner:'AP quality or finance owner',records:'original invoice, extracted fields, confidence indicators, validation rules, vendor record, order, correction history, and reviewer result',example:'OCR reads a total of 18,600 from a scanned invoice, while the printed value may be 16,600. The reviewer checks the source image, subtotal, tax, and purchase record, then records the corrected value and reason.',steps:steps(['Keep the source primary','Retain the original file and page coordinates; extracted text and confidence scores are aids, not replacements.'],['Prioritize consequential fields','Review entity, supplier, invoice number, dates, currency, bank cues, line amounts, tax, and total before low-risk descriptive text.'],['Use cross-checks transparently','Compare arithmetic, master data, purchase records, and prior patterns while labeling each source and avoiding automatic overwrites.'],['Handle unreadable evidence','Request a clearer document or owner review when the source cannot support a value; do not guess from context.'],['Record correction lineage','Store original extraction, corrected value, reviewer, time, reason, and source location for quality analysis.'],['Improve the queue from samples','Track repeated error classes by layout or field, but require controlled approval before changing capture rules.'])},
  {slug:'vendor-contact-ownership-register',title:'Create a vendor contact ownership register for AP',excerpt:'Document which supplier contacts are approved for invoices, statements, disputes, and sensitive changes without treating every email sender as trusted.',keyword:'vendor contact ownership register',service:'vendor-onboarding-administration',serviceLabel:'vendor onboarding administration',scenario:'an AP team receiving messages from several contacts at the same supplier',owner:'vendor-master, purchasing, or supplier relationship owner',records:'vendor record, contract, onboarding evidence, approved contacts, role and channel, verification result, correspondence, and review history',example:'A salesperson sends invoices, a shared mailbox sends statements, and a new person requests a bank change. The register clarifies routine channels while the bank request still follows independent verification.',steps:steps(['Define contact purpose','Separate invoice delivery, statement, dispute, order, tax, security, and sensitive-change contacts by supplier entity.'],['Record provenance','Capture who approved the contact, when, from which controlled source, and how the identity or channel was verified.'],['Limit trust by task','An approved statement sender is not automatically authorized to change bank details, legal identity, or commercial terms.'],['Handle shared mailboxes','Document ownership, backup route, domain, expected message types, and escalation without relying on a personal relationship.'],['Review changes independently','Use a known channel when contacts, domains, phone numbers, portals, or responsibilities change.'],['Expire stale entries','Set review dates, retain history, and disable obsolete contacts only through the designated owner and controlled system.'])},
];

const sources = [
  {name:'NIST glossary: least privilege',url:'https://csrc.nist.gov/glossary/term/least_privilege',note:'Definition supporting limited access for AP systems and records.'},
  {name:'CISA: Recognize and Report Phishing',url:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing',note:'Government guidance supporting trusted-channel verification for suspicious requests.'},
  {name:'IRS: About Form W-9',url:'https://www.irs.gov/forms-pubs/about-form-w-9',note:'First-party context for a common supplier tax record; tax decisions remain with the company.'},
];

const expand = (topic: Topic, guidance: string, index: number) => {
  const openings = [
    `For ${topic.scenario}, start with a packet another reviewer can reproduce. Keep the ${topic.records} connected by stable identifiers, not by a familiar filename or email subject.`,
    `The outsourced specialist prepares the evidence and maintains the queue. The ${topic.owner} retains decisions that change accounting, supplier data, access, contractual treatment, or the movement of money.`,
    `Use labeled timestamps for issue, receipt, review, approval, change, and completion. Sequence matters, and a later event must not silently rewrite an earlier source.`,
    `Describe the exception as a comparison: what each source says, which record or amount is affected, what is missing, and which named owner can answer.`,
    `Apply least-privilege access to the work. Preparation rights should cover only the fields and records needed, while authorization and release stay with employees.`,
    `Treat new links, contacts, bank details, domains, and urgent instructions as security signals. Verification must use a channel the company already trusts.`,
  ];
  const endings = [
    `Keep the prior value after any authorized correction and link the responder, time, reason, and controlled source. That lineage supports duplicate review, close work, and later audit questions.`,
    `Finish the queue entry with a factual status, named next owner, due or review date, and source link. “Done” is not adequate when the underlying business event remains unresolved.`,
    `Quality review should include an ordinary item and a difficult exception. A second person should be able to repeat the comparison without an oral explanation from the preparer.`,
    `Never fill an evidence gap from a prior invoice simply because the supplier looks familiar. Preserve the received document, flag uncertainty, and ask one answerable question.`,
  ];
  return `${openings[index % openings.length]} ${guidance} ${endings[index % endings.length]}`;
};

const companion = [
  'Record the source location and the observation in separate fields. If sources disagree, keep the item in the exception queue instead of selecting the convenient value.',
  'Put the proposed next action beside the evidence. Missing access, an absent document, and pending authorization are different states and need different owners.',
  'The handoff should identify the affected record, amount or quantity, deadline, and exact response needed. Link evidence instead of copying an unlabeled value into chat.',
  'Name who can authorize the next move. Until that response arrives, preserve the last confirmed state and prevent downstream work from implying approval.',
  'Use a status that describes the actual stop. Preparation can be complete while the invoice, supplier record, or payment remains unresolved.',
  'Before handoff, verify entity, supplier, identifiers, currency, dates, and source links. These details stop a general reply from being mistaken for a decision.',
];

export const sep24BlogPosts = topics.map(topic => ({slug:topic.slug,title:topic.title,excerpt:topic.excerpt,minutes:12}));
export const sep24BlogDetails = Object.fromEntries(topics.map(topic => [topic.slug, {
  thumbnail:`/blog-thumbnails/sep24-2026/${topic.slug}.svg`, shortAnswer:topic.excerpt,
  published:'2026-09-24', modified:'2026-09-24', mainKeyword:topic.keyword,
  sections:[
    {title:'A practical AP example',paragraphs:[expand(topic,topic.example,0),expand(topic,'Before work begins, agree on authoritative sources, required fields, stop conditions, permitted system actions, and employee owners. Test those rules with records from the company’s real workflow.',1)]},
    ...topic.steps.map(([title,guidance],i)=>({title,paragraphs:[expand(topic,guidance,i+2),expand(topic,companion[i],i+3)]})),
    {title:'Start with a controlled sample',paragraphs:[expand(topic,`Choose a small set with ordinary records and at least two realistic exceptions. Review every packet with the ${topic.owner}, correct unclear statuses and escalation wording, and confirm that each step leaves evidence before increasing volume.`,9),expand(topic,'Measure the underlying result rather than emails sent or fields touched. Useful signals may include aged exceptions, returned packets, correction reasons, and owner response time when the company defines each measure and source.',10)]},
    {title:'Turn the routine into a scoped handoff',paragraphs:[expand(topic,`Document intake channels, volume, busy periods, system access, review cadence, retention, and backup ownership. The ${topic.serviceLabel} service page helps frame a bounded work lane without transferring company decisions.`,11),expand(topic,'Use the contact and scoping page once the lane has real inputs, outputs, owners, and stop conditions. A narrow and reviewable handoff is easier to train, inspect, and improve than an open instruction to handle AP.',12)]},
  ],
  checklistTitle:'Review the packet before handoff',
  checklist:['Original source and stable identifiers retained','Conflict or missing evidence stated plainly','Authorized employee owner named','Status, next action, and review date recorded','Approval, master-data authority, and payment release remain with the company'],
  bodyLinks:[{href:`/services/${topic.service}`,label:topic.serviceLabel},{href:'/contact-us',label:'contact and scoping page'}],
  faqs:[
    {question:'What can an outsourced AP specialist prepare?',answer:`The specialist can collect and compare the ${topic.records}, document exceptions, maintain the queue, and send a focused question to the ${topic.owner}.`},
    {question:'Which decisions stay with the company?',answer:'Employees retain invoice approval, accounting and tax judgments, vendor-master authorization, security verification, access ownership, and payment release.'},
    {question:'How should the team begin?',answer:'Start with a small sample, review routine and exception cases, and expand only after sources, statuses, owners, and escalation paths are clear.'},
  ], sources,
}]));
