type Section = {title: string; paragraphs: string[]};
type Topic = readonly [string,string,string,string,string,readonly string[]];

// August 18, 2026 publication batch. Each record carries its own literal date.
const topics: Topic[] = [
  ['ap-invoice-intake-channel-map','AP invoice intake channel map for outsourced support','invoice intake channel map','Map every invoice entry point before an AP support lane begins so documents do not disappear between inboxes, portals, and employee forwarding.','channel ownership',['email forwarding','supplier portal exports','purchase-system handoffs','scanned exceptions','daily reconciliation']],
  ['ap-invoice-approval-owner-roster','AP invoice approval owner roster that stays current','invoice approval owner roster','Build an owner roster that helps AP support route questions without guessing who can approve an invoice or cover an absence.','approval ownership',['primary approvers','time-bounded backups','entity and threshold scope','response evidence','stale-owner review']],
  ['ap-vendor-statement-reconciliation-notes','AP vendor statement reconciliation notes for finance review','vendor statement reconciliation notes','Write statement notes that distinguish missing invoices, credits, disputes, and timing differences for a finance owner.','reconciliation notes',['opening balance','invoice and credit matching','unexplained items','supplier follow-up','review sign-off']],
  ['ap-invoice-business-purpose-check','Business-purpose checks for non-PO AP invoices','business-purpose invoice check','Use a factual business-purpose check for non-PO invoices while leaving coding, policy, and approval judgments with the responsible owner.','business purpose',['requester identity','receipt or contract','service description','policy question','owner disposition']],
  ['ap-invoice-received-date-log','AP invoice received-date log for cutoff control','invoice received-date log','Keep the date an invoice entered the process visible so month-end cutoff questions can be reviewed from evidence.','received dates',['source timestamp','duplicate messages','late arrivals','cutoff grouping','close handoff']],
  ['ap-invoice-approval-rejection-notes','Invoice approval rejection notes that support clean rework','invoice rejection notes','Turn a rejected invoice into a specific rework item with a reason, owner, evidence request, and preserved prior decision.','rejection rework',['rejection reason','source preservation','correction request','re-review gate','history']],
  ['ap-invoice-supplier-portal-export-checks','Supplier portal export checks for AP support','supplier portal export checks','Check portal exports for completeness and identity before they enter an invoice review queue.','portal exports',['export scope','invoice identity','attachment pairing','duplicate risk','handoff record']],
  ['ap-invoice-line-description-review','AP invoice line-description review before coding','invoice line description review','Use line descriptions to flag unclear goods or services without inventing coding or accepting an unsupported invoice.','line descriptions',['line clarity','order reference','service evidence','question design','owner review']],
  ['ap-invoice-approver-response-log','Approver response log for distributed AP teams','approver response log','Create a response log that shows reminders, decisions, unanswered questions, and the next escalation point.','response logging',['request timestamp','response type','decision evidence','aging','escalation']],
  ['ap-invoice-attachment-version-control','AP invoice attachment version control','invoice attachment version control','Keep corrected invoices and supporting files distinguishable so a reviewer can tell which source was used and why.','file versions',['original source','corrected copy','naming rule','superseded evidence','review trail']],
  ['ap-invoice-po-quantity-variance-review','Purchase-order quantity variance review for AP support','purchase-order quantity variance','Prepare quantity comparisons that help a receiving owner resolve a variance without allowing support staff to approve it.','quantity variance',['ordered quantity','received quantity','billed quantity','partial receipt','resolution']],
  ['ap-invoice-recurring-charge-review','Recurring AP charge review checklist','recurring invoice review','Review recurring charges for expected period, source reference, and owner confirmation before the packet moves to approval.','recurring charges',['period comparison','contract reference','scope change','missing confirmation','renewal boundary']],
  ['ap-invoice-urgent-escalation-log','Urgent AP escalation log for deadline pressure','urgent AP escalation log','Make urgent requests visible without letting urgency erase approval, verification, or evidence controls.','urgent escalation',['request source','deadline claim','risk cue','owner decision','closure evidence']],
  ['ap-invoice-closed-period-question','AP invoice questions that touch a closed period','closed-period invoice question','Route closed-period invoice questions with the original dates and evidence intact while finance decides the accounting treatment.','closed periods',['invoice date','service period','system status','owner question','record retention']],
  ['ap-invoice-employee-expense-evidence','Employee expense evidence checks for AP review','employee expense evidence','Check expense evidence for identity, date, purpose, and receipt completeness without making a policy exception decision.','expense evidence',['employee identity','receipt','business purpose','duplicate claim','policy owner']],
  ['ap-invoice-payment-run-exclusion-log','Payment-run exclusion log for AP preparation','payment-run exclusion log','Document why an invoice was left out of a payment proposal and who must resolve the hold.','payment exclusions',['proposal population','hold reason','source evidence','owner','next run']],
  ['ap-invoice-vendor-inquiry-record','AP vendor inquiry record for repeat questions','vendor inquiry record','Record vendor questions in a way that separates routine status answers from payment changes and disputed records.','vendor inquiries',['question type','approved source','reply boundary','change request','follow-up']],
  ['ap-invoice-approval-threshold-check','Invoice approval threshold checks for support roles','approval threshold check','Compare an invoice with the approved threshold rule and route uncertainty without deciding whether an exception is acceptable.','threshold checks',['amount basis','entity rule','split risk','approver','exception authority']],
  ['ap-invoice-reconciliation-break-log','AP reconciliation break log for open items','reconciliation break log','Use a break log to show what did not reconcile, which evidence is missing, and who owns the decision.','reconciliation breaks',['source population','matching rule','break reason','owner','aging review']],
  ['ap-invoice-document-access-review','AP document access review for shared finance work','document access review','Review who can reach invoice evidence and remove unnecessary access when an AP support scope changes.','document access',['approved users','shared links','least privilege','change event','removal check']],
  ['ap-invoice-month-end-evidence-index','Month-end AP evidence index for close review','month-end evidence index','Create an index that connects open invoices, receipts, approvals, exceptions, and sign-off evidence during close.','close evidence',['population','cutoff','open items','owner notes','sign-off']],
  ['ap-invoice-correction-request-workflow','AP invoice correction request workflow','invoice correction request','Request supplier corrections with enough detail to be actionable while preserving the original invoice and finance decision path.','correction requests',['incorrect field','source comparison','supplier message','replacement record','re-review']],
];

const paragraph = (topic: Topic, item: string, n: number) => `${topic[1]} requires a clear record of ${item}, not a vague status label. Begin with the invoice identifier, supplier, entity, date received, and source location. Compare the relevant document or report without overwriting the original. State what the AP support role observed, what the evidence does not establish, and which person owns the unresolved judgment. For ${item}, preserve the message, line, file, or report that caused the review and note the exact field that needs attention. This keeps preparation separate from approval, accounting treatment, vendor-master maintenance, tax judgment, and payment release. A reviewer should be able to open the packet later and understand why the item was routed, what was checked, and what still needs an answer. ${n % 2 ? 'Record a named next action and review date; “follow up” is not a control unless someone owns the response.' : 'Keep both agreement and disagreement visible; hiding clean fields makes the eventual exception harder to explain.'} If the source is incomplete, pause the item and request the missing evidence through the approved channel. If the request is urgent, preserve the urgency claim but do not let it bypass the normal control path. Repeated questions belong in a process review, where the finance owner can decide whether the intake rule, access boundary, or escalation route should change.`;

export const aug18BlogPublicationDates: Record<string,string> = {
  'ap-invoice-intake-channel-map':'2026-08-18','ap-invoice-approval-owner-roster':'2026-08-18','ap-vendor-statement-reconciliation-notes':'2026-08-18','ap-invoice-business-purpose-check':'2026-08-18','ap-invoice-received-date-log':'2026-08-18','ap-invoice-approval-rejection-notes':'2026-08-18','ap-invoice-supplier-portal-export-checks':'2026-08-18','ap-invoice-line-description-review':'2026-08-18','ap-invoice-approver-response-log':'2026-08-18','ap-invoice-attachment-version-control':'2026-08-18','ap-invoice-po-quantity-variance-review':'2026-08-18','ap-invoice-recurring-charge-review':'2026-08-18','ap-invoice-urgent-escalation-log':'2026-08-18','ap-invoice-closed-period-question':'2026-08-18','ap-invoice-employee-expense-evidence':'2026-08-18','ap-invoice-payment-run-exclusion-log':'2026-08-18','ap-invoice-vendor-inquiry-record':'2026-08-18','ap-invoice-approval-threshold-check':'2026-08-18','ap-invoice-reconciliation-break-log':'2026-08-18','ap-invoice-document-access-review':'2026-08-18','ap-invoice-month-end-evidence-index':'2026-08-18','ap-invoice-correction-request-workflow':'2026-08-18',
};
export const aug18BlogPosts = topics.map(([slug,title,,excerpt])=>({slug,title,excerpt,minutes:14}));
export const aug18BlogDetails = Object.fromEntries(topics.map((topic, index) => {
  const [slug,title,keyword,excerpt,angle,items] = topic;
  const sections: Section[] = [
    {title:`Define the ${angle} boundary`,paragraphs:[paragraph(topic,items[0],index),paragraph(topic,items[1],index+1)]},
    {title:`Build the ${items[2]} evidence path`,paragraphs:[paragraph(topic,items[2],index+2),paragraph(topic,items[3],index+3)]},
    {title:`Use the ${items[4]} review point`,paragraphs:[paragraph(topic,items[4],index+4),paragraph(topic,'next review date',index+5)]},
    {title:'Keep the role boundary visible',paragraphs:[paragraph(topic,'owner decision',index+6),paragraph(topic,'escalation record',index+7)]},
    {title:'Turn the record into a repeatable AP routine',paragraphs:[paragraph(topic,'sample review',index+8),paragraph(topic,'handoff improvement',index+9)]},
  ];
  return [slug,{mainKeyword:keyword,published:'2026-08-18',modified:'2026-08-18',shortAnswer:`Prepare the ${keyword} record from approved source documents, then route any judgment or exception to the named finance owner.`,sections,faqs:[{question:`What is the support role’s job in ${keyword}?`,answer:'It gathers and compares source evidence, records gaps, and follows the documented escalation path. It does not approve, release payment, alter master data, or invent a missing decision.'},{question:'What should remain in the packet?',answer:'Keep the original source, comparison note, owner, action date, response evidence, and final disposition together so another reviewer can resume the item.'}]}];
}));
