type Spec={slug:string;title:string;excerpt:string;keyword:string;opening:string;packet:string;owner:string;checks:string;thumbnail:string};
const date='2026-09-11' as const;
const specs=[
['ap-invoice-number-normalization-control','Normalize invoice numbers without erasing the supplier record','Make invoice searches and duplicate checks consistent while retaining the value printed on the document.','invoice number normalization rules','The same invoice can appear as INV-00421, INV 00421, or 421 after email capture, OCR, and manual entry.','the supplier value, normalized value, transformation rule, source image, system field, operator, timestamp, and any exception','AP process owner','leading zeros, spaces, punctuation, prefixes, credit notes, handwritten values, and blank numbers','/blog-thumbnails/ap-invoice-data-quality-checks.svg'],
['supplier-credit-balance-evidence-workbook','Investigate supplier credit balances before choosing a remedy','Build a source-linked worksheet for credits, overpayments, refunds, offsets, and unresolved supplier balances.','supplier credit balance investigation','An aging report shows a supplier credit, but it does not say whether the cause was a credit memo, duplicate payment, or unapplied cash.','entity, supplier, currency, open items, bank events, credit documents, correspondence, proposed treatment, reviewer, and final posting','controller or accounting owner','valid credits, overpayments, duplicate recoveries, refunds in transit, offsets, foreign currency, and unsupported balances','/blog-thumbnails/ap-credit-memo-follow-up-workflow.svg'],
['split-invoice-allocation-evidence-review','Review split-coded invoices line by line','Keep allocation support, coding logic, approver responsibility, and later corrections traceable.','split invoice coding review','A service invoice is allocated across departments, but the file contains percentages and no explanation of the basis.','invoice lines, allocation basis, source schedule, entities, accounts, cost centers, tax treatment, preparer, approvers, and corrections','accounting policy or budget owner','fixed percentages, headcount, usage, project, multi-entity, tax, rounding, and revised allocations','/blog-thumbnails/invoice-coding-review-checklist.svg'],
['supplier-statement-period-alignment-check','Anchor supplier-statement reviews to a clear cutoff','Keep a reconciliation from mixing statement dates, ledger extracts, later invoices, and payments in transit.','supplier statement cutoff check','A month-end supplier statement is compared with a ledger report downloaded several days later.','statement date, ledger cutoff, extraction time, included entities, open documents, payments in transit, later activity, reconciling items, and reviewer','financial close owner','late invoices, post-cutoff payments, backdated entries, disputed items, credits, cross-entity items, and missing statements','/blog-thumbnails/ap-vendor-statement-open-items.svg'],
['payment-file-custody-handoff-log','Log the payment-file handoff without widening AP authority','Record what AP prepared, what treasury received, and which checks remain before upload and release.','payment file transfer log','A payment proposal leaves the AP queue, but its version, recipient, and transmission status are unclear.','batch ID, source report, item count, total by currency, exclusions, file hash or version, approved channel, sender, recipient, receipt, and rejection history','treasury or payment owner','accepted, rejected, corrected, partial, duplicate transfer, wrong recipient, expired batch, and out-of-band requests','/blog-thumbnails/ap-payment-support-segregation.svg'],
['invoice-date-source-comparison','Validate invoice dates without guessing what the supplier meant','Separate printed dates, receipt dates, service periods, posting dates, and policy decisions.','invoice date validation guide','An invoice has a printed date after the stated service period and before the AP inbox received it.','source image, printed invoice date, receipt timestamp, service period, purchase terms, posting proposal, discrepancy, supplier response, and owner decision','accounting policy owner','future dates, ambiguous formats, missing dates, reissued invoices, credits, time-zone edges, and altered documents','/blog-thumbnails/ap-invoice-cutoff-checklist.svg'],
['urgent-payment-evidence-intake','Give rush payment requests a controlled intake lane','Capture the business reason, evidence, timing, requester authority, and exceptions without promising payment.','rush payment request intake','A requester labels an invoice urgent and asks AP to bypass the normal queue before a supplier deadline.','invoice, due date, terms, receipt, approval status, reason, business impact, requester, supplier contact, exceptions, escalation, and outcome','treasury or finance owner','genuine deadlines, missing approvals, changed bank details, duplicates, first-time suppliers, weekends, and repeated rush requests','/blog-thumbnails/ap-urgent-invoice-request-controls.svg'],
['purchase-order-change-evidence-trace','Keep purchase order versions visible during invoice matching','Make quantity, price, terms, and closure changes inspectable instead of matching only against the latest screen.','purchase order version history','An invoice seems to match the current purchase order, but the order changed after the supplier issued it.','PO versions, change timestamps, requester, approval, lines, quantities, prices, receipts, invoice date, match result, and override evidence','procurement owner','price changes, quantity changes, cancelled lines, reopened orders, after-invoice amendments, currency changes, and migrated orders','/blog-thumbnails/purchase-order-reconciliation-checklist.svg'],
['supplier-identity-alias-evidence-register','Use a vendor alias register without merging distinct suppliers','Connect trading names and payment descriptors to approved master records while keeping uncertain matches open.','vendor name alias register','A bank descriptor, invoice header, and vendor master use three similar names for what may be the same supplier.','observed name, source, vendor ID, legal name, entity, tax record reference, payment descriptor, validation evidence, effective date, and status','vendor-master owner','DBAs, abbreviations, acquisitions, shared service centers, spelling differences, subsidiaries, and false matches','/blog-thumbnails/ap-vendor-master-review-checklist.svg'],
['invoice-attachment-readiness-triage','Check invoice file readiness before data entry','Define what to do with incomplete, unreadable, protected, altered, or mismatched invoice files.','invoice file readiness check','The email subject names one invoice while its attachment has missing pages and a different supplier reference.','message ID, sender, attachment name, type, page count, readability, invoice fields, mismatch notes, safe-handling result, replacement request, and disposition','AP intake or security owner','missing pages, corrupted files, password protection, duplicate attachments, renamed files, unexpected formats, and suspicious links','/blog-thumbnails/ap-invoice-attachment-naming.svg'],
['returned-payment-resolution-record','Build a case file for returned supplier payments','Trace a returned payment through the bank event, supplier verification, correction, reapproval, and ledger outcome.','returned supplier payment case file','The bank returns a supplier payment, but the reason code alone does not show whether a master-data change is appropriate.','payment ID, bank event, return code, amount, currency, supplier, original instructions, verification, correspondence, proposed action, approvals, retry, and accounting result','treasury or vendor-master owner','closed accounts, invalid details, bank review, currency issues, partial returns, fees, duplicate retries, and unresolved returns','/blog-thumbnails/ap-payment-status-inquiry-process.svg'],
['recurring-billing-receipt-monitor','Maintain a recurring invoice expectation list that catches gaps','Compare expected invoices with received documents without treating a forecast as proof of liability.','recurring invoice expectation list','Rent, software, and utility invoices arrive on different schedules, and a missing document is noticed only during close.','supplier, entity, agreement, expected period, cadence, usual channel, expected range, receipt event, variance, follow-up, owner, and resolution','close or contract owner','late, skipped, duplicate, variable, cancelled, renewed, disputed, and new recurring charges','/blog-thumbnails/ap-month-end-open-invoice-review.svg'],
].map(x=>({slug:x[0],title:x[1],excerpt:x[2],keyword:x[3],opening:x[4],packet:x[5],owner:x[6],checks:x[7],thumbnail:x[8]} as Spec));
const sections=(s:Spec)=>[
 {title:`Write the rule around the evidence`,paragraphs:[`${s.opening} Start the ${s.keyword} with the source event and the exact population it covers.`,`Keep ${s.packet}. Leave a field blank until an approved source resolves it.`]},
 {title:'Make the handoff explicit',paragraphs:[`An outsourced AP specialist can gather documents, copy observable fields, apply a written rule, and route exceptions. The ${s.owner} decides policy questions and authorizes changes or payments.`,`Record who received the packet and what happened next. Keep the earlier version when a correction arrives.`]},
 {title:'Test the awkward examples',paragraphs:[`Before using the routine at scale, replay ${s.checks}. Ask a reviewer who did not prepare the case to reach the same classification from the retained record.`,`A disagreement usually points to a weak source hierarchy, an undefined exception, or an unclear owner. Fix that part of the routine and test the case again.`]},
];
export const sep11BlogPosts=specs.map(s=>({slug:s.slug,title:'September 11: '+s.title,excerpt:s.excerpt,minutes:8}));
export const sep11BlogDetails=Object.fromEntries(specs.map(s=>[s.slug,{mainKeyword:s.keyword,published:date,modified:date,sourceDate:date,thumbnail:s.thumbnail,shortAnswer:`Use a source-linked ${s.keyword}, preserve uncertainty, and send decisions to the ${s.owner}.`,sections:sections(s),faqs:[{question:`What may outsourced AP staff do with this ${s.keyword}?`,answer:`They may collect approved records, apply written checks, document gaps, and route the packet. The ${s.owner} keeps policy and authorization.`},{question:'What evidence should the reviewer see?',answer:`The reviewer should be able to rebuild the chronology from ${s.packet}.`}]}]));
