import type {ResearchPost} from './research-batch';
const date='2026-08-23';
const links=[{label:'AP services',href:'/services'},{label:'AP inbox management',href:'/services/ap-inbox-management'},{label:'Research library',href:'/research'}];
const gao={label:'GAO Green Book',href:'https://www.gao.gov/greenbook'};
const nist={label:'NIST Least Privilege',href:'https://csrc.nist.gov/glossary/term/least_privilege'};
const cisa={label:'CISA Verification Guidance',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'};
const sba={label:'SBA Financial Records',href:'https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances'};
const irs={label:'IRS Form W-9',href:'https://www.irs.gov/forms-pubs/about-form-w-9'};
const make=(x:{slug:string,title:string,excerpt:string,thumbnail:string,citations:ResearchPost['citations'],body:string}):ResearchPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,published:date,modified:date,thumbnail:x.thumbnail,keywords:['accounts payable outsourcing','AP research','finance operations'],body:[x.body],citations:x.citations,internalLinks:links,cta:'Use this research to define a controlled AP support lane.'});
const controls=`Campaign date: 2026-08-23. Methodology: this bounded qualitative study compares source documents, timestamps, field values, exceptions, and owner decisions. The sample must contain ordinary items as well as incomplete, corrected, urgent, conflicting, and unresolved items. Define the population, entity, period, systems searched, fields compared, exclusions, and inaccessible records before reviewing results. Ask an independent reviewer to reproduce the preparation from the retained packet without oral explanation. Record reviewer disagreements because they show where a policy, source, or packet is unclear. Evidence scope is limited to the declared sample and controlled records.

External evidence: the analysis uses https://www.gao.gov/greenbook for documented control activity, https://csrc.nist.gov/glossary/term/least_privilege for limiting access to assigned work, and https://www.cisa.gov/secure-our-world/recognize-and-report-phishing for independent verification of risky requests. These are reputable public sources for control principles. They do not provide a market benchmark, detection rate, staffing ratio, accounting answer, legal conclusion, tax answer, fraud finding, payment promise, or universal AP precedence rule. Facts remain tied to a source field, document, timestamp, recorded response, or system event. Analysis explains the relationship among facts. A recommendation proposes a next step. An authorized owner’s disposition is a decision.

Role boundary: an outsourced Philippines-based AP specialist may collect approved records, compare visible fields, request missing evidence, prepare a factual note, maintain a queue, and route a question. The specialist must not invent evidence, certify a business event, approve spend, change vendor-master data, select tax or accounting treatment, override an exception, promise payment, accuse a supplier, or release funds. Least privilege means access matches the preparation lane. Keep sensitive supplier and payment information in approved systems. Preserve the preparer’s observation when an owner later decides; append the owner, date, source considered, and disposition rather than erasing history.

Operational test: give a second reviewer the same packet and ask what is known, inferred, absent, and undecided. Ask the reviewer to locate every source, explain each stop condition, identify the next owner, and distinguish preparation from authorization. Measure reproducibility, evidence visibility, and clear escalation rather than speed or a convenient status. Test only in a non-production review set. A useful handoff names the population, records checked, fields compared, factual result, unresolved question, next owner, and review date. A label such as approved, matched, clean, or duplicate is not a substitute for that information.

Limitations: this report does not establish legal compliance, fraud, tax treatment, accounting treatment, contractual obligation, platform performance, staffing ratios, savings, market benchmarks, retention requirements, or payment outcomes. Records can be stale, overwritten, incomplete, unavailable, privacy-restricted, or governed by different entity policies. External guidance informs evidence and access discipline but cannot make an organization’s decision. The conclusion below is therefore an evidence-led workflow conclusion, not professional advice. A reviewer should record whether a source arrived through an approved channel, whether it was available at review time, whether a later correction changed the factual picture, and whether a named employee accepted the remaining question. Those details make the packet useful across shifts and prevent a support lane from presenting a missing document as a clean result. Research findings are bounded observations from the declared sample, not claims about every supplier, entity, system, or accounting policy. When reviewers disagree, retain both interpretations, return to the source records, and escalate the unresolved decision. A controlled process can improve visibility without claiming that every exception has the same risk. The proper outcome is a clear evidence packet, a stop condition where needed, and a decision owner who can act within policy.`;
export const aug23ResearchBatch:ResearchPost[]=[
make({slug:'ap-invoice-approval-evidence-chain-research',title:'What evidence chain lets an AP approval survive review?',excerpt:'A bounded study of the records that connect invoice intake, review, approval, and payment preparation in outsourced accounts payable.',thumbnail:'/research-thumbnails/ap-invoice-approval-evidence-chain-research.svg',citations:[gao,nist,cisa],body:controls+`Campaign date: 2026-08-23. Route-local methodology and evidence scope. Sources: https://www.gao.gov/greenbook; https://csrc.nist.gov/glossary/term/least_privilege; https://www.cisa.gov/secure-our-world/recognize-and-report-phishing. Route-local limitations and evidence-led conclusion follow.

Research question: what evidence chain lets a finance reviewer reconstruct an invoice approval without relying on memory or an unverified message? An approval event proves that an employee recorded an action; it does not prove invoice identity, legal entity, amount, receipt, terms, exception resolution, or payment authority. Preserve receipt, preparation, questions, responses, approval, and handoff as separate events with source, actor, and timestamp.

Evidence analysis: retain the original invoice, intake event, purchase-order and receipt evidence, prepared fields, exception history, and approval record. A forwarded email may be context but should not replace the original decision record. A bank-detail request or urgent message requires independent verification and is not evidence of its own authorization. If a source is unavailable, record unavailable. If a reply conflicts with an invoice, preserve both values and route the question.

Test ordinary, incomplete, corrected, urgent, and exception invoices. Ask whether the independent reviewer can find each source, explain the preparation, identify the authorized approver, and locate the final owner disposition. The support lane can organize and compare; finance retains approval, override, vendor-master, tax, and payment-release decisions. Conclusion: an AP approval survives review when its source chain and employee authorization remain visible rather than being collapsed into a status label.`}),
make({slug:'ap-vendor-statement-cutoff-uncertainty-research',title:'When does a vendor statement match become evidence?',excerpt:'Research on separating statement lines, ledger records, credits, timing differences, and owner decisions in outsourced AP reconciliation.',thumbnail:'/research-thumbnails/ap-vendor-statement-cutoff-uncertainty-research.svg',citations:[gao,sba,nist],body:controls+`Campaign date: 2026-08-23. Route-local methodology and evidence scope. Sources: https://www.gao.gov/greenbook; https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances; https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final. Route-local limitations and evidence-led conclusion follow.

Research question: when does a vendor-statement match provide enough evidence for an AP reviewer to close an open item? A statement proves what a supplier lists for a named period; it does not automatically prove that each line is owed, posted, unpaid, associated with the same entity, or free of an unapplied credit. Preserve statement date, period, page, currency, retrieval event, supplier identifier, invoice reference, credit reference, and source location.

Evidence analysis: classify each line as matched, statement-only, ledger-only, both with a difference, timing-related, credit pending application, duplicate candidate, disputed, or not comparable. A missing identifier is a fact, not permission to infer one from a nearby amount. Keep the old statement and original open-item note when a later reply explains a difference. Do not net a credit or call a balance resolved without finance-owner disposition.

Test ordinary lines, a credit, a payment near cutoff, a shared supplier across entities, an apparent duplicate, and an unanswered request. The support lane can request statements, compare records, maintain the open-item register, and draft factual follow-up. Finance decides write-offs, disputes, posting, credit application, materiality, and closure. Conclusion: a statement match is evidence only when another reviewer can reproduce it from dated sources and see every remaining uncertainty.`}),
make({slug:'ap-payment-terms-conflict-research',title:'Which AP payment term should a reviewer trust?',excerpt:'A source-led study of conflicting invoice, purchase-order, vendor-master, and agreement terms before an outsourced AP payment run.',thumbnail:'/research-thumbnails/ap-payment-terms-conflict-research.svg',citations:[gao,nist,sba],body:controls+`Campaign date: 2026-08-23. Route-local methodology and evidence scope. Sources: https://www.gao.gov/greenbook; https://csrc.nist.gov/glossary/term/least_privilege; https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances. Route-local limitations and evidence-led conclusion follow.

Research question: which term should an AP reviewer trust when invoice, purchase order, vendor master, and agreement values disagree? A printed due date, a net-term phrase, a master value, and a contract clause can describe different clocks based on receipt, acceptance, delivery, or an approved exception. Preserve exact wording, source date, supplier, entity, currency, effective date, owner, and calculation basis instead of silently selecting the newest value.

Evidence analysis: “wrong terms” is analysis; “invoice says X while the purchase order says Y” is fact. If policy permits a draft calculation, label it draft and show inputs. Stop for a conflict, unclear acceptance, missing purchase order, accelerated request, or unapproved master-data change. The support role can compare records and route the question, but cannot interpret contract language, edit master data, waive approval, promise a payment date, or release funds.

Test ordinary terms, a conflict, missing evidence, an early-payment request, and an urgent bank instruction. Ask two reviewers to preserve the same source values and identify the same owner question. Append the owner’s decision without deleting earlier values. Conclusion: the trustworthy record preserves competing terms and routes interpretation to finance, procurement, or the contract owner rather than choosing a convenient processing date.`}),
make({slug:'ap-invoice-entity-routing-evidence-research',title:'Can AP intake evidence identify the right legal entity?',excerpt:'A bounded study of entity clues in invoices, purchase orders, tax records, and inbox routes for distributed AP support.',thumbnail:'/research-thumbnails/ap-invoice-entity-routing-evidence-research.svg',citations:[gao,irs,nist],body:controls+`Campaign date: 2026-08-23. Route-local methodology and evidence scope. Sources: https://www.gao.gov/greenbook; https://www.irs.gov/forms-pubs/about-form-w-9; https://csrc.nist.gov/glossary/term/least_privilege. Route-local limitations and evidence-led conclusion follow.

Research question: can an AP intake packet identify the responsible legal entity without relying on vendor familiarity or a prior invoice? Compare supplier name, legal name, bill-to wording, billing address, purchase-order entity, contract, receiving location, tax-document reference, currency, and intake channel. These clues have different authority. “Wrong entity” is a conclusion; “invoice names X while the purchase order names Y” is a reviewable fact.

Evidence analysis: preserve exact text, source location, missing fields, conflicts, and redirections. A shared address does not prove a shared legal entity, and a taxpayer identifier does not authorize vendor creation or determine tax treatment. A support specialist may collect an approved Form W-9 from https://www.irs.gov/forms-pubs/about-form-w-9, compare identifiers, mark missing evidence, and route a conflict. Finance, tax, procurement, or the entity owner decides liability, coding, master-data action, and intercompany treatment.

Test clean records, shared addresses, parent-subsidiary mismatches, cross-entity orders, missing tax fields, and redirected inbox items. Ask another reviewer what is known, inferred, absent, and undecided. Restrict sensitive identifiers to approved systems. Conclusion: intake evidence can make routing reviewable when it preserves conflicts and ownership, but ambiguous clues are not authority to assign an entity.`}),
make({slug:'ap-duplicate-invoice-signal-research',title:'Which signals make an AP duplicate candidate worth review?',excerpt:'Research on combining invoice identifiers, amounts, dates, attachments, and supplier context without treating a candidate as a confirmed duplicate.',thumbnail:'/research-thumbnails/ap-duplicate-invoice-signal-research.svg',citations:[gao,nist,sba],body:controls+`Campaign date: 2026-08-23. Route-local methodology and evidence scope. Sources: https://www.gao.gov/greenbook; https://csrc.nist.gov/glossary/term/least_privilege; https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances. Route-local limitations and evidence-led conclusion follow.

Research question: which combination of invoice signals makes a duplicate candidate worth human review? A candidate is a relationship among records, not a verdict. Compare supplier, legal entity, invoice number, invoice date, service period, currency, amount, purchase order, attachment content, source channel, receipt event, and correction history. Same amount can be recurring service; same number can occur across entities; a replacement can correct a tax field; a credit can resemble a negative invoice.

Evidence analysis: preserve both original files and describe differences rather than deleting a resubmission. “Duplicate” is analysis; “same supplier and number, different entity and service period” is fact. The support lane can search a declared period, prepare a side-by-side packet, link records, and route a candidate. It cannot reject an invoice, accuse a supplier, clear a hold, merge records, infer intent, or approve payment from a flag.

Test ordinary non-duplicates, recurring charges, corrections, same-number cross-entity records, credits, and unresolved pairs. Ask two reviewers to apply the same search fields, explain false alarms, retain excluded sources, and identify the owner decision. Conclusion: a duplicate signal warrants a preserved comparison when independent fields make it reproducible; it never substitutes for the authorized owner’s disposition.`})
];
