type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-09-02';
const links=[{label:'Month-end cutoff exception log',href:'/blog/ap-month-end-cutoff-exception-log'},{label:'Payment hold release record',href:'/blog/ap-payment-hold-release-record'},{label:'Vendor portal invoice intake log',href:'/blog/ap-vendor-portal-invoice-intake-log'}];
const serviceHandoff={heading:'Translate the evidence into a bounded AP role',body:'Define source records, preparation steps, exception ownership, review timing, and retained employee decisions before granting access.',href:'/contact-us',label:'Discuss an AP support scope'};
const sources={nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},gao:{label:'GAO Green Book',href:'https://www.gao.gov/greenbook'},cisa:{label:'CISA Identity and Access Management',href:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'},fbi:{label:'FBI Business Email Compromise',href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'},coso:{label:'COSO Internal Control resources',href:'https://www.coso.org/internal-control'}};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,evidence:string,boundary:string,test:string,interpretation:string,citations:Post['citations']):Post=>({slug,title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks:links,serviceHandoff,body:[
`This evidence review asks ${question}. It maps public control guidance to a bounded accounts payable workflow; it does not establish a legal conclusion, universal benchmark, or promised outcome. The method compares guidance on reliable information, attributable action, restricted access, and monitoring.`,
`The proposed evidence population includes ${evidence}. Original records, operator observations, external replies, and company decisions remain separate so a reviewer can identify the source and authority of every material fact.`,
`The useful measurement is reproducibility, not raw volume. Each sample needs a declared population, cutoff, inclusion rule, exclusions, stable identifiers, exception definition, and owner. Rates and aging figures should be interpreted only after missing and disputed records are visible.`,
`In an outsourced AP model, ${boundary}. Least-privilege access and separation between preparation, approval, master-data change, accounting judgment, and payment release protect the meaning of the record.`,
`A practical test should ${test}. Include ordinary, incomplete, conflicting, corrected, and urgent examples, and retain chronology rather than overwriting the initial observation when new evidence arrives.`,
`The evidence should be read with this caution: ${interpretation}. Management should set its own thresholds, retention rules, review cadence, and escalation owners, then revisit them when systems or responsibilities change.`,
]});
export const sep2ResearchBatch:Post[]=[
make('ap-payment-hold-governance-research','Payment hold governance in accounts payable: an evidence review','Research on hold reasons, authority, release evidence, and residual exceptions in outsourced AP workflows.','/research-thumbnails/aug21-payment-hold.png','which records make the creation, review, and release of an AP payment hold independently reproducible','hold scope, reason source, affected suppliers and invoices, timestamps, preparer actions, reviewer evidence, release decision, residual exceptions, and history','support may log, monitor, and assemble hold evidence, but only an authorized company owner may decide whether a hold is applied or released','reconstruct a supplier-wide hold, a single-invoice exception, a rejected release request, and a partial release without losing prior states','a short hold can still indicate weak control if its authority is missing, while a long hold may be appropriate when a documented exception remains unresolved',[sources.gao,sources.nist,sources.coso]),
make('ap-invoice-currency-control-research','Invoice currency controls for outsourced AP operations','A source-backed synthesis of currency evidence, conflict routing, and decision separation before invoice coding.','/research-thumbnails/ap-invoice-coding-control-research.svg','how invoice currency can be checked against purchasing and supplier evidence without delegating commercial or accounting judgment','invoice amount and currency, purchase order, contract or terms source, supplier record, entity, system configuration, comparison result, exception chronology, and owner response','support may transcribe currency, compare approved sources, and flag conflicts while procurement, accounting, and treasury owners retain decisions','present matching, conflicting, absent, corrected, and multi-currency records to two reviewers and compare their classifications','a match between two fields does not prove contractual validity, and a mismatch is an exception signal rather than evidence that either source is correct',[sources.gao,sources.nist,sources.coso]),
make('ap-duplicate-payment-recovery-research','Duplicate payment recovery evidence: a control synthesis','Research on confirming duplicate signals, documenting supplier recovery, and closing accounting dispositions.','/research-thumbnails/ap-duplicate-invoice-detection-research.svg','what evidence distinguishes a suspected duplicate payment from a confirmed duplicate, promised refund, recovered cash, and completed ledger treatment','invoice and payment identifiers, entities, currencies, dates, amounts, duplicate rules, review result, supplier communications, authorization, bank receipt, credit application, and closure review','support may assemble comparisons and follow-up records but cannot declare a duplicate, direct recovery funds, or approve an accounting disposition','trace a false positive and a confirmed duplicate through different outcomes, requiring independent evidence at confirmation, recovery, and closure','recovery counts can overstate performance when promised refunds are treated as cash received or when recovered funds remain unapplied',[sources.gao,sources.coso,sources.nist]),
make('ap-vendor-inquiry-authentication-research','Vendor inquiry authentication in AP service workflows','An evidence review of contact validation, disclosure limits, and escalation for supplier payment-status questions.','/research-thumbnails/ap-vendor-inquiry-response-research.svg','how an AP team can answer legitimate supplier inquiries without exposing payment information to unverified contacts','incoming channel, supplier identity, approved contact source, authentication steps, requested invoice references, permitted disclosure, source status, response, attachments, and escalation','support may use approved verification and response procedures but must not authenticate a contact with details supplied only in the same unsolicited request','test a known contact, a lookalike domain, a forwarded thread, a changed address, and a request for sensitive remittance data','fast response time is not evidence of quality if authentication or disclosure boundaries are skipped, and repeated escalation may reveal unclear contact governance',[sources.fbi,sources.cisa,sources.nist]),
make('ap-month-end-cutoff-evidence-research','Month-end AP cutoff evidence for distributed teams','A research synthesis of invoice timing, service-period evidence, exception logs, and attributable close decisions.','/research-thumbnails/ap-close-evidence-handoff-research.svg','which records let distributed AP and accounting teams review items that cross a month-end cutoff','close calendar and cutoff, entity, invoice and receipt timestamps, service or delivery period, purchase and receiving evidence, amount, exception reason, accounting decision, posting reference, and review history','support may collect timing evidence and maintain exceptions while the accounting owner determines recognition, accrual, posting period, and reversal treatment','sample pre-cutoff receipts, late invoices, disputed service periods, missing receiving evidence, corrections, and approved period treatments','receipt time alone may not determine the accounting period, while a complete-looking invoice packet may still lack the evidence required for an owner decision',[sources.gao,sources.coso,sources.nist]),
];
