import type {ResearchPost} from './research-batch';

const date='2026-09-23', checked='September 23, 2026';
const sources={
  gao:{label:`U.S. GAO Green Book, checked ${checked}`,href:'https://www.gao.gov/greenbook'},
  nist:{label:`NIST SP 800-53 Rev. 5, checked ${checked}`,href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  paymentIntegrity:{label:`GAO Payment Integrity report GAO-26-108694, checked ${checked}`,href:'https://www.gao.gov/products/gao-26-108694'},
  cisa:{label:`CISA Recognize and Report Phishing, checked ${checked}`,href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'},
};
const links=[
  {label:'Invoice data capture',href:'/services/invoice-data-capture'},
  {label:'Purchase order reconciliation',href:'/services/purchase-order-reconciliation'},
  {label:'Payment run preparation',href:'/services/payment-run-preparation'},
];
type Seed={slug:string;title:string;excerpt:string;thumbnail:string;question:string;population:string;method:string;tests:string;boundary:string;limits:string;finding:string;citations:ResearchPost['citations']};

const make=(x:Seed):ResearchPost=>({...x,published:date,modified:date,keywords:['accounts payable research','AP evidence controls',x.slug],internalLinks:links,cta:'Discuss a bounded AP support scope',serviceHandoff:{heading:'Turn the evidence method into a bounded AP routine',body:'Define the population, source hierarchy, access, preparer, reviewer, decision owner, retention rule, and stop conditions before assigning recurring work.',href:'/contact-us',label:'Discuss an AP support scope'},body:[
`Research question and decision context. ${x.question} This report examines how an accounts-payable support team can prepare decision-grade evidence without taking authority that belongs to procurement, receiving, treasury, accounting, tax, information security, or an authorized finance employee. It is a control-design study, not legal, accounting, tax, cybersecurity, or fraud advice. The unit of analysis is one traceable payable event within a named legal entity, system boundary, policy version, and UTC reporting cutoff. Facts, calculations, inferences, uncertainties, and owner decisions remain distinct throughout the record.`,
`Population and scope. ${x.population} The population definition records included entities, business units, suppliers, currencies, intake channels, systems, document types, date fields, policy version, and reporting cutoff. It also records excluded records and why they are excluded. Each row keeps a stable transaction identifier, source location, source title, event timestamp, retrieval timestamp, preparer, reviewer, decision owner, and disposition. Empty values remain labelled missing rather than being converted to zero, not applicable, matched, accepted, or approved. That discipline prevents an apparently complete spreadsheet from concealing inaccessible evidence.`,
`Methodology. ${x.method} The preparer freezes a dated population and retains the source extracts needed to reproduce it. A reviewer receives the packet without an oral explanation and repeats the source tracing, calculation, exception classification, and routing decision. Disagreements are recorded as a missing source, ambiguous rule, timing difference, calculation error, classification difference, or unsupported conclusion. Agreement supports reproducibility only; it does not prove that an invoice, receipt, supplier identity, contract interpretation, accounting treatment, bank instruction, or payment is valid.`,
`Challenge cases. ${x.tests} The test set includes one item that proceeds under an identified written rule, one stopped because a required source is absent, one with conflicting sources, one altered after the reporting cutoff, and one requiring an employee decision. Later evidence is appended using its actual receipt time and never backdated into the original packet. This tests whether the routine preserves uncertainty and chronology instead of rewarding a clean-looking status. A stopped item is an informative control result when evidence or authority is genuinely absent.`,
`Evidence language. A fact is a value or event visible in a named retained source, such as an invoice field, purchase-order version, receipt event, approval record, bank status, or supplier communication. Analysis is a disclosed comparison or calculation made from those facts. An inference is a plausible explanation that the sources do not directly establish. A decision is an action attributed to an authorized company owner. Repetition, urgency, similarity, system labels, reviewer confidence, and supplier assertions do not convert an inference into a fact. The packet labels these categories so a later reviewer can identify where judgment entered.`,
`Authority boundary. ${x.boundary} Outsourced AP support can collect approved records, transcribe visible values, perform a documented comparison, maintain an exception register, request missing evidence through an approved channel, and route a factual packet. It should not invent evidence, alter source documents, change supplier or banking data, choose accounting or tax treatment, certify delivery, approve its own work, waive an exception, promise a payment date, or create and release funds. Technical access must fit the preparation lane. Excess access is a condition to document and remediate, not implied business authority.`,
`Source interpretation. The 2025 GAO Green Book informs responsibility, quality information, documentation, control activities, and monitoring. NIST SP 800-53 contributes least-privilege, separation-of-duties, and attributable audit-record concepts. GAO's 2026 payment-integrity report provides current context on payments made in incorrect amounts and documentation limitations. CISA guidance informs independent-channel caution when messages or account details change. These government sources support the method but do not settle a private contract, supplier identity, materiality threshold, accounting conclusion, tax position, receipt dispute, or payment decision. Current company policy and authorized owners govern those questions.`,
`Security and communication. Messages, attachments, portal labels, caller familiarity, and urgency are evidence inputs rather than proof of authority. A new contact route or payment-detail request should be verified using the company’s independently approved process. Preparers should not move invoices, tax records, employee data, or banking details into personal tools for convenience. Shared accounts weaken attribution and must be disclosed. When a source cannot be accessed, the result is source unavailable with a named owner and recovery action. It is not a finding about evidence nobody inspected.`,
`Quality review. The reviewer confirms each conclusion cites a retained source or is labelled analysis, inference, uncertainty, or owner decision. Every calculation exposes inputs, formula, precision, rounding, and residual. Every timeline identifies its clock, timezone, and event meaning. Every exception names the current owner and next action. Review also searches for overwritten versions, unexplained state changes, inaccessible sources, duplicate identifiers across entities, and conclusions based only on absence. Corrections preserve the earlier value, correction time, reason, actor, and downstream effect rather than silently replacing history.`,
`Measures and retesting. Useful measures include population coverage, packets containing required sources, reproducible classifications, unresolved cases with named owners, elapsed time between evidence events, retained corrections, and items reopened after new evidence. Each rate discloses numerator, denominator, cutoff, and exclusions. This report does not claim savings, productivity, accuracy, compliance, loss prevention, or market benchmarks because those claims require a defensible reference standard and study design. Retest after a material policy, workflow, system, access role, integration, source hierarchy, or supplier-channel change, preserving both rounds and explaining any changed method.`,
`Handoff and closure. Unresolved items name both the evidence task and the person authorized to decide the business question. Procurement may interpret an order or contract, receiving may confirm a physical or service event, accounting or tax may determine treatment, treasury may confirm cash movement, information security may investigate suspicious contact, and finance may approve the final disposition. Closure requires more than a matched flag, zero balance, successful upload, or completed ticket. The record links source evidence, comparison, conflicts, authorized decision, effective time, downstream action, and follow-up. Reopened cases append the reason and new evidence.`,
`Limitations. ${x.limits} A bounded sample can overrepresent visible exceptions and cannot estimate hidden events or financial effect. Exports may omit unposted or archived items. Timestamps may represent intake, user action, processing, posting, extraction, display refresh, or settlement and cannot be compared without context. Supplier and company records can use different cutoffs. Public guidance may not match the company’s contracts, jurisdictions, reporting framework, materiality, software, or risk appetite. Findings apply only to the tested entities, systems, records, period, sources, and policy. Missing evidence remains missing.`,
`Evidence-led conclusion. ${x.finding} The useful output is a narrower supported question delivered to the person who can decide it, with sources, chronology, calculations, conflicts, assumptions, and access limits intact. A preparer should show what was observed, calculated, uncertain, and authorized; why work stopped or proceeded; and who supplied authority. Management retains policy, procurement, accounting, tax, supplier-master, access, exception, remediation, treasury, and payment authority. A durable packet lets a new reviewer reconstruct the path without depending on memory or an undocumented conversation.`,
]});

export const sep23ResearchBatch:ResearchPost[]=[
make({slug:'invoice-freight-surcharge-evidence-research',title:'Invoice freight surcharges: an AP evidence study',excerpt:'Research on freight terms, carrier records, supplier charges, receipt evidence, allocation, and exception ownership.',thumbnail:'/research-thumbnails/ap-invoice-coding-control-research.svg',question:'What evidence lets AP prepare a freight-surcharge exception without interpreting commercial terms or approving the charge?',population:'Include supplier-delivered, buyer-arranged, prepaid-and-add, third-party, expedited, fuel, accessorial, and minimum-order freight charges across goods, services, credits, and returns.',method:'Trace the invoice charge to the order and contract version, shipping term, shipment or carrier record, receipt, supplier calculation, tax treatment source, prior credits, and authorized disposition; show the charge separately from goods value.',tests:'Test an unlisted surcharge, changed fuel rate, split shipment, expedited delivery requested after order, freight-only invoice, returned goods, duplicate carrier charge, and cross-entity allocation.',boundary:'A shipment record proves movement, not who owes freight or whether a supplier surcharge is contractually valid. Procurement and accounting owners decide terms, allocation, and treatment.',limits:'Carrier data may be held by another party, shipping terms can be amended informally, consolidated freight may span invoices, and invoice labels may not identify the underlying calculation.',finding:'Keep commercial term, shipment event, surcharge basis, calculation, invoice presentation, receipt context, conflicts, and owner decision in one reproducible bridge.',citations:[sources.gao,sources.nist,sources.paymentIntegrity]}),
make({slug:'supplier-statement-opening-balance-provenance-research',title:'Supplier statement opening balances: tracing AP provenance',excerpt:'A source-backed method for testing opening balances, prior-period items, credits, disputed invoices, and cutoff differences.',thumbnail:'/research-thumbnails/ap-vendor-statement-reconciliation-research.svg',question:'How should AP trace a supplier statement opening balance before treating the current-period reconciliation as complete?',population:'Include statements with prior-period invoices, unapplied credits, payments in transit, disputed lines, account mergers, currency changes, entity changes, and balances carried across calendar or fiscal cutoffs.',method:'Bridge the opening balance to the prior closing statement and item-level ledger population; retain subsequent applications, reversals, credits, write-offs, disputes, and supplier responses with their actual effective dates.',tests:'Test an unexplained forward balance, missing prior statement, credit carried under another account, payment posted after supplier cutoff, old dispute, merged supplier account, currency conversion, and later reversal.',boundary:'AP may reconcile records and request support but cannot infer that an aged amount is valid, waive a dispute, net legal entities, approve a write-off, or alter accounting treatment.',limits:'Supplier statements can omit history, apply different cutoffs, combine accounts, or restate prior balances; ledger extracts may exclude archived, unposted, or migrated items.',finding:'Treat the opening balance as a population requiring its own source bridge, not as an accepted input to the current reconciliation.',citations:[sources.gao,sources.nist,sources.paymentIntegrity]}),
make({slug:'invoice-cancellation-rebill-chain-research',title:'Invoice cancellation and rebill chains: an evidence study',excerpt:'Research on original invoices, cancellation status, replacement documents, credits, approvals, and duplicate-risk controls.',thumbnail:'/research-thumbnails/ap-duplicate-invoice-detection-research.svg',question:'What evidence distinguishes a valid cancellation-and-rebill chain from two payable claims or an unsupported replacement?',population:'Include voids, supplier cancellations, credit-and-rebill sequences, corrected tax invoices, portal replacements, partial credits, changed entities, changed currencies, and documents crossing reporting periods.',method:'Preserve every original document and system state; link supplier references, amounts, taxes, service periods, cancellation or credit authority, replacement reason, approval, posting, and payment status without overwriting the first record.',tests:'Test a replacement without credit, partial rebill, changed invoice number, corrected entity, changed bank details, paid original, cancellation after cutoff, and two replacements for one source.',boundary:'AP can assemble the chain and flag duplicate exposure, but accounting and tax owners determine document validity, posting, period, recovery, and whether a replacement may proceed.',limits:'Supplier portals may remove cancelled documents, status labels may not create a legal credit, system voids can differ from supplier cancellation, and references are often inconsistent.',finding:'A valid-looking replacement remains an exception until the original claim, cancellation or credit, replacement scope, posting state, and payment exposure are linked.',citations:[sources.gao,sources.nist,sources.cisa,sources.paymentIntegrity]}),
make({slug:'payment-proposal-exclusion-reason-research',title:'Payment proposal exclusions: a reproducible AP review method',excerpt:'Research on excluded invoices, hold codes, due-date logic, cash decisions, master data, and payment-run handoffs.',thumbnail:'/research-thumbnails/ap-payment-run-preparation-research.svg',question:'How can AP explain why an approved invoice did not enter a payment proposal without assuming the exclusion was correct?',population:'Include due and overdue invoices excluded for holds, payment-method gaps, bank-data status, cash direction, entity, currency, minimum thresholds, netting, dispute, system configuration, and manual deselection.',method:'Freeze the eligible invoice population and proposal parameters; reproduce rule evaluation; record system reason, underlying source, manual action, proposal version, reviewer, decision owner, and later outcome.',tests:'Test a valid hold, stale hold, missing payment method, future baseline date, manual exclusion, supplier netting, blocked bank record, currency restriction, and invoice added after the cutoff.',boundary:'AP may reproduce proposal logic and route exceptions but cannot decide cash priority, waive a hold, change bank data, override policy, select a payment account, or release funds.',limits:'Payment engines may expose only generic reason codes, parameters can change between runs, cash decisions may sit outside the system, and a technically eligible invoice may still require an owner decision.',finding:'Separate invoice approval, technical eligibility, proposal inclusion, cash prioritization, payment authorization, release, and settlement so each exclusion has a truthful owner and reason.',citations:[sources.gao,sources.nist,sources.paymentIntegrity]}),
make({slug:'supplier-credit-reapplication-history-research',title:'Supplier credit reapplication history: preserving AP evidence',excerpt:'A study of credits moved between invoices, unapplied balances, reversals, entity boundaries, and closure evidence.',thumbnail:'/research-thumbnails/ap-credit-memo-reconciliation-research.svg',question:'What history should AP retain when a supplier credit is applied, reversed, and reapplied to a different invoice?',population:'Include credit memos, overpayments, returns, rebates, pricing credits, unapplied cash, partial applications, cross-currency proposals, disputed invoices, and activity spanning entities or periods.',method:'Preserve the originating claim, credit authority, original application, reversal reason and actor, each later application, currency and amount, ledger references, supplier statement effect, approval, and residual balance.',tests:'Test a partial reapplication, application to a disputed invoice, reversal after close, credit under a merged account, cross-entity request, expired credit assertion, duplicate application, and remaining residual.',boundary:'AP may prepare an application history and reconcile balances but cannot decide legal setoff, move value across entities, approve write-offs, choose accounting treatment, or conceal a reversal.',limits:'Supplier and buyer systems may assign different references, net balances can hide item movement, historical applications may be archived, and supplier assertions may conflict with ledger state.',finding:'Closure requires a transaction-level chain from credit origin through every application and reversal to the residual balance and authorized disposition.',citations:[sources.gao,sources.nist,sources.paymentIntegrity]}),
];
