import type {ResearchPost} from './research-batch';
import {supplierTaxIdCollisionResearch} from './research-sep28-supplier-tax-id';
import {beneficiaryNameMismatchResearch} from './research-sep28-beneficiary-name';
import {ocrTableBoundaryResearch} from './research-sep28-ocr-table-boundary';
import {dormantVendorInvoiceResearch} from './research-sep28-dormant-vendor';
import {paymentFileRejectionResearch} from './research-sep28-payment-file';
ocrTableBoundaryResearch.body.push(`Correction review should follow the captured field downstream. After a row boundary is repaired, retest the line extension, document total, duplicate check, order comparison, coding proposal, approval packet, and any export that consumed the earlier value. The correction log names every dependent record inspected and whether it changed. A harmless description-wrap correction may have no monetary effect; a duplicated carry-forward subtotal may require the invoice to be removed from a payment proposal. The capture specialist can identify those affected records but does not decide their accounting disposition. This downstream trace is necessary because correcting the OCR screen alone can leave an earlier wrong amount in another queue. It also supplies evidence that the repair addressed the actual propagation path rather than merely improving the appearance of the source record.`);
dormantVendorInvoiceResearch.body.push(`The exception queue should expose the precise next owner question. Reactivate vendor is too broad. A better entry might ask procurement to confirm whether service occurred before termination, request receiving evidence for a stated invoice line, ask vendor-master staff to explain a security block, or ask accounting whether an open credit belongs to the same entity. The queue links that question to the evidence already gathered and prevents redundant supplier contacts. It also distinguishes a missing answer from a rejected request. When an owner responds, the preparer records the source and time, updates the chronology, and routes any consequential action through its normal approval path. This design lets AP move the investigation forward without making reactivation the default remedy for every open item.`);
export const sep28ResearchBatch:ResearchPost[]=[supplierTaxIdCollisionResearch,beneficiaryNameMismatchResearch,ocrTableBoundaryResearch,dormantVendorInvoiceResearch,paymentFileRejectionResearch];
