type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-09-07';
const sources={gao:{label:'GAO Green Book',href:'https://www.gao.gov/greenbook'},nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},cisa:{label:'CISA Identity and Access Management',href:'https://www.cisa.gov/topics/cybersecurity-best-practices/identity-and-access-management'},occ:{label:'OCC: Accounts Payable Operations',href:'https://www.occ.treas.gov/publications-and-resources/publications/comptrollers-handbook/files/accounts-payable/index-accounts-payable.html'},fbi:{label:'FBI: Business Email Compromise',href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'}};
const internalLinks=[{label:'Supplier contact change log',href:'/blog/ap-supplier-contact-change-log'},{label:'Payment return triage queue',href:'/blog/ap-payment-return-triage-queue'},{label:'Month-end invoice cutoff register',href:'/blog/ap-month-end-invoice-cutoff-register'}];
const serviceHandoff={heading:'Turn the finding into a bounded AP handoff',body:'Define sources, preparation steps, access, review timing, exception ownership, and decisions retained by employees before work begins.',href:'/contact-us',label:'Discuss an AP support scope'};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,population:string,method:string,limits:string,finding:string,citations:Post['citations']):Post=>({slug,title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks,serviceHandoff,body:[
`This review asks ${question}. It applies public control guidance to a bounded accounts payable workflow; it does not provide legal, tax, accounting, cybersecurity, or fraud assurance and does not establish a universal benchmark.`,
`The declared evidence population is ${population}. Source records, operator observations, supplier statements, system events, reviewer analysis, and management decisions remain separate so their provenance can be inspected.`,
`Method: ${method}. Selection rules are fixed before status cleanup. The test includes routine, incomplete, conflicting, corrected, urgent, and stopped cases, and a second reviewer attempts the classification from retained evidence alone.`,
`The GAO Green Book frames documentation, quality information, responsibility, and monitoring. NIST SP 800-53 frames least privilege, attributable actions, and review. Additional cited sources narrow the operational question; none determines the outcome of a particular invoice or supplier record.`,
`Scope and limitations: ${limits}. Results apply only to the named entities, systems, period, sample, access, policy, and records available. Missing evidence remains visible as a finding or a declared exclusion rather than being inferred.`,
`The supported conclusion is deliberately limited: ${finding}. Management still sets policy, materiality, access, retention, escalation, accounting treatment, approval, and payment authority, and should retest after workflow or system changes.`,
]});
export const sep7ResearchBatch:Post[]=[
make('ap-invoice-receipt-date-evidence-research','Evidence for determining invoice receipt dates','A bounded review of message provenance, portal events, forwarding, queue timestamps, and date corrections.','/research-thumbnails/ap-close-evidence-handoff-research.svg','which retained records let a reviewer determine when an invoice first reached the business','original email headers and message IDs, monitored mailboxes, portal download events, file identities, forwarding chains, intake logs, manual corrections, and queue timestamps','select invoices from email and portals across the declared period, preserve original metadata, compare each first-receipt event with its queue entry, and independently replay exceptions','mail retention, clock configuration, time zones, forwarding, portal history, synchronization delays, and manual uploads can limit reconstruction; a timestamp alone does not prove invoice validity or accounting period','receipt dating is more reviewable when original transport evidence and later workflow events stay distinct and corrections retain their history',[sources.gao,sources.nist]),
make('ap-supplier-master-duplicate-detection-research','Supplier-master duplicate detection as an evidence review','Research on identity fields, false positives, payment history, access boundaries, and authorized record decisions.','/research-thumbnails/ap-vendor-onboarding-controls-research.svg','what evidence supports review of possible duplicate supplier records without automating a merge decision','supplier IDs, names, identifiers, addresses, contacts, bank-record references, documents, status history, invoices, payments, candidate rules, reviewer notes, and master-data events','declare match fields and thresholds, stratify exact and fuzzy candidates, retain nonmatches, blind a second reviewer to the first conclusion, and trace authorized outcomes','shared addresses, trading names, group companies, recycled contacts, incomplete identifiers, localization, and stale records can produce both false positives and false negatives','candidate detection can organize review, but authorized owners must resolve identity, risk, retention, merge, and disablement decisions',[sources.gao,sources.nist,sources.occ]),
make('ap-vendor-portal-access-governance-research','Governance evidence for AP vendor-portal access','A source-led study of role purpose, least privilege, dormant users, authentication, review, and removal.','/research-thumbnails/ap-outsourced-ap-access-review-research.svg','which records demonstrate that supplier-portal access is attributable, bounded, reviewed, and removable','portal inventories, user lists, roles, access requests, approvals, business purpose, authentication settings, login history, employment or contract status, review decisions, and removal events','define the in-scope portals and review date, reconcile users to approved assignments, sample privileged and dormant accounts, and retest removal evidence independently','portal reporting differs, shared credentials defeat attribution, last-login data can be incomplete, and the study does not test every security control or prove compromise absence','an access register is useful only when responsibility, role purpose, exceptions, review decisions, and completed removals can be traced',[sources.nist,sources.cisa,sources.gao]),
make('ap-payment-return-root-cause-research','Payment-return root-cause evidence in accounts payable','Research on bank messages, file identity, supplier records, holds, remediation, and repeat-payment boundaries.','/research-thumbnails/aug21-payment-hold.png','what evidence supports classification of returned supplier payments before any repayment decision','bank acknowledgments and return codes, payment files, proposal versions, invoice populations, supplier-master versions, change requests, verification records, holds, correspondence, remediation, and final outcomes','sample return categories and unresolved codes, reconcile bank events to source files and master-record versions, separate initial classification from management action, and have a second reviewer replay each case','bank codes may be generic, intermediaries can alter messages, fees and partial returns complicate amounts, and the review cannot establish fraud, legal ownership, or the correct payment action','root-cause labels are defensible only when their source evidence, uncertainty, master-data history, hold status, and authorized outcome remain connected',[sources.fbi,sources.nist,sources.gao]),
make('ap-month-end-cutoff-evidence-research','Evidence design for AP month-end cutoff reviews','A bounded study of receipt timing, service periods, receiving records, unresolved invoices, and close decisions.','/research-thumbnails/ap-close-evidence-handoff-research.svg','how a close team can preserve the basis for reviewing invoices received near or after month end','invoice files and receipt metadata, purchase orders, receiving events, service-period support, corrections, disputes, materiality policy references, close registers, reviewer notes, posting events, and subsequent activity','fix the entity, close period, cutoff window, and sample rules; include pre-cutoff, late, corrected, disputed, missing-receipt, and subsequent-period items; then replay the documented decision trail','source timing does not by itself determine recognition, services may span periods, receiving records may lag, and the study does not prescribe accounting treatment or materiality','a cutoff register improves reviewability when observed dates, evidence gaps, preparer analysis, accounting decisions, posting outcomes, and later corrections are not collapsed into one status',[sources.gao,sources.occ,sources.nist]),
];
