import type {ResearchPost} from './research-batch';

const links=[{label:'AP services',href:'/services'},{label:'AP inbox management',href:'/services/ap-inbox-management'},{label:'Research library',href:'/research'}];
const gao={label:'GAO Green Book',href:'https://www.gao.gov/greenbook'};
const nist={label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'};
const cisa={label:'CISA Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'};
const treasury={label:'U.S. Treasury Office of Financial Research',href:'https://www.financialresearch.gov/financial-markets/'};
const sba={label:'SBA Manage Your Business Finances',href:'https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances'};
const date='2026-08-21' as const;

export const aug21ResearchRouteDates:Record<string,typeof date>={
  'ap-invoice-receipt-timestamp-research':date,
  'ap-approval-evidence-reconstruction-research':date,
  'ap-vendor-statement-cutoff-research':date,
  'ap-payment-run-hold-reason-research':date,
  'ap-ap-inbox-channel-integrity-research':date
};

export const aug21ResearchBatch:ResearchPost[]=[
{slug:'ap-invoice-receipt-timestamp-research',title:'Which AP receipt timestamp makes an invoice queue reviewable?',excerpt:'A bounded study of invoice arrival, document receipt, and queue-entry dates for outsourced accounts-payable support.',published:date,modified:date,thumbnail:'/research-thumbnails/aug21-receipt-timestamp.png',keywords:['accounts payable outsourcing','AP research','invoice intake'],citations:[gao,nist,sba],internalLinks:links,cta:'Use this research to define a controlled AP support lane.',body:[
'Campaign date: 2026-08-21. Research question: which timestamp should a finance owner trust when reviewing an AP queue? Invoice date, email arrival, attachment receipt, queue entry, and first human review answer different questions. This report examines those distinctions for a support lane that prepares invoice records without approving them. The evidence scope is a defined sample of intake messages and their linked invoice records. Facts are the timestamps present in the source systems; analysis explains what each timestamp can and cannot establish.',
'Methodology begins by naming the population. Select one inbox or portal feed, one entity or vendor group, and a fixed observation period. Preserve message identifiers, attachment names, system-created timestamps, and any later correction history. A queue export alone is insufficient if it omits the original message. The GAO Green Book supports using reliable information for control decisions, while NIST accountability principles support preserving who performed the intake step. Neither source supplies a universal AP timing standard.',
'The invoice date is a supplier-stated field. It may help interpret terms or a period, but it does not prove when the buyer received the document. Email arrival can establish when a message reached a mailbox, yet a delayed forward or unreadable attachment can make it a poor proxy for usable intake. Queue entry shows when a system record was created. First review shows when a person began preparation. Keep these fields separate instead of selecting the earliest date to make aging look worse or the latest date to make it look better.',
'A useful sample includes clean invoices, forwarded messages, duplicate attachments, unreadable scans, portal imports, and invoices that arrive near a close boundary. For each item, record which source supplied each timestamp and whether a human corrected it. A missing timestamp is itself a finding about evidence design. Do not infer receipt from the invoice date, and do not infer service period from receipt. Those interpretations require the policy and finance context of the organization.',
'The support role can capture source timestamps, link the original document, identify gaps, and ask the owner which event controls a particular decision. It should not rewrite a supplier field, backdate queue entry, classify an invoice as late, or promise that a payment will meet a deadline. A finance owner decides how the organization treats cutoffs, terms, and exceptions. The role boundary should appear in the SOP and in the permissions that allow note entry without source alteration.',
'For comparison, calculate descriptive counts only within the declared sample: items with all five fields, items missing queue history, items whose attachment arrived separately, and items corrected after intake. These counts describe the observed period; they are not productivity rates or market benchmarks. Treasury materials about financial-market information reinforce the value of clear observation boundaries, but they do not validate an AP sample. Label every denominator so a reader can reproduce the claim.',
'A second reviewer should receive the original message, invoice, queue record, and prepared timestamp table without the preparer’s narrative. Ask what can be proven, what is only a plausible explanation, and which owner must decide. Record disagreements by field. If reviewers repeatedly disagree about “received,” the process needs a definition and a source field, not a pressure to choose a faster date. This review also tests whether an outsourced team can hand over evidence without hiding uncertainty.',
'Limitations are material. Mail systems may use different time zones, imports may batch records, and a supplier may resend the same attachment. A short sample cannot establish a seasonal pattern or legal conclusion. Privacy and retention rules may restrict copying message content into a research sheet. Keep links and identifiers in approved systems, minimize sensitive data, and document excluded records. The study describes evidence quality; it does not determine liability for a missed cutoff or the correct accounting period.',
'Evidence-led conclusion: an AP queue becomes reviewable when receipt, usable-document, queue-entry, and review events are distinct and traceable to source records. Outsourced support can prepare that timeline and route missing evidence. Finance should decide which event governs policy, cutoff, and payment decisions. A truthful “unknown” timestamp is more useful than a guessed date because it tells the owner exactly which control or intake change needs attention.',
'The next test should be narrow: repeat the sample after one intake-field change and compare completeness by source channel. Preserve the old method, the new field definition, and the reviewer disagreements. If completeness improves only for one channel, keep the exception visible rather than claiming the whole inbox is fixed. This sequence turns timestamp research into a controlled AP improvement while keeping approval, accounting treatment, and payment release with authorized finance staff. Include a small set of records that arrived outside ordinary hours and note the time zone used by each system. That detail can explain an apparent sequence conflict without changing any source value. The owner can then decide whether the queue needs a display rule, a service window, or a policy clarification. Record who made that definition, when it took effect, and which historical records remain outside it. A dated rule is easier to review than an assumption that silently changes.'
]},
{slug:'ap-approval-evidence-reconstruction-research',title:'Can an AP approval packet be reconstructed after the decision?',excerpt:'Research on whether invoice approval evidence lets a later reviewer distinguish preparation, judgment, and authorization.',published:date,modified:date,thumbnail:'/research-thumbnails/aug21-approval-reconstruction.png',keywords:['accounts payable outsourcing','AP research','approval controls'],citations:[gao,nist,cisa],internalLinks:links,cta:'Use this research to define a controlled AP support lane.',body:[
'Campaign date: 2026-08-21. Research question: if a later reviewer sees an approved invoice, can they reconstruct what was known, compared, and authorized at the time? Approval evidence is more than a green status. This study examines invoice packets containing the source document, matching records, exception notes, approval identity, decision date, and any change after approval. The scope is evidence reconstruction, not a claim about whether a sampled approval was economically wise or legally sufficient.',
'The method uses a retrospective sample with three strata: ordinary matched invoices, invoices approved after an exception, and invoices changed after the first review. Select a period and entity before opening examples. Preserve immutable source links and approval history. GAO control principles frame the need for documented activities and reliable information. NIST guidance frames attribution and least privilege. These authorities support the test design; they do not dictate the organization’s thresholds or delegation matrix.',
'For each packet, distinguish source facts from preparation. The invoice states a supplier, amount, and date. A purchase order may state an order quantity. A receipt may show acceptance. A preparer may calculate a difference or highlight missing evidence. An approver decides whether the organization accepts the exception under its policy. If those layers are merged into one edited field, a later reviewer cannot tell whether an amount was sourced, calculated, or authorized.',
'Reconstruction should begin with a blank chronology. Ask a reviewer who did not prepare the item to identify intake, comparison, exception creation, approval request, approval response, and posting or payment handoff from the retained records. Record the first point at which the reviewer needs an explanation unavailable in the packet. That point is a practical evidence gap. It should not be repaired by asking the original worker to recreate a memory without labeling the reconstruction as retrospective.',
'The outsourced support boundary is central. A support role may assemble the packet, calculate a stated variance, route a question, and record the approver’s response. It should not approve its own preparation, alter source values to match an expected result, or treat a manager’s informal message as a formal delegation unless policy says it is valid. The finance owner remains responsible for judgment, unusual terms, entity treatment, and release authority.',
'CISA’s phishing guidance is relevant when approval arrives through an unusual or urgent message. The sample should ask whether identity and channel were trusted, whether a request to bypass normal review was preserved, and whether an independent confirmation was required. Tone is not evidence of fraud, and a missing control record is not proof of malicious intent. The research identifies whether the process maintained a safe route for doubt and escalation.',
'Measurements should stay descriptive: percentage of sampled packets with a source link, decision owner, decision date, exception rationale, and post-approval change history. Report the denominator and strata. Do not present the result as an approval accuracy rate or assurance of compliance. Compare the evidence pattern across ordinary and exception items only to guide the next control test. A high completion count can coexist with weak reconstruction if the decision rationale is absent.',
'A useful remediation may be a structured decision note with separate fields for question, evidence reviewed, decision, authority, date, and follow-up. The note should preserve the prior proposal if the owner changes it. Avoid a free-text box that says “approved” without identifying what was approved. Avoid broad access that lets preparation staff delete or overwrite the trail. The system should make the safe route easier while leaving the owner’s authority intact.',
'Limitations include missing historical records, platform migrations, delegated approvals that vary by entity, and policies that changed during the sample. A reconstruction test cannot prove that a person read every attachment or that a financial decision was correct. It can show whether the retained packet supports later review. Keep those claims separate. If the evidence cannot answer a question, report the gap and the responsible policy owner instead of inventing certainty.',
'Evidence-led conclusion: an approval is reviewable when the packet shows source facts, preparation, exception reasoning, authorized decision, and later changes as separate events. Outsourced AP can make that packet coherent and searchable. Finance must retain approval judgment and the authority to accept exceptions. The best result of the study may be a stopped or escalated item, because stopping preserves the distinction between evidence preparation and authorization.',
'Repeat the reconstruction with a small set of changed packets after the decision-note fields are introduced. Ask whether the second reviewer can identify what changed and why without contacting the preparer. Keep the before-and-after findings together. This gives the finance owner evidence about the control itself and prevents a new form from being mistaken for a working approval process. Include one packet that was stopped and one that was approved after an exception. A design that records only successful approvals may look complete because it excludes the moments where judgment and escalation matter most. The review should make those boundary cases legible. Also retain the original proposal when a reviewer changes a coding note, amount, or route. The change history should explain the decision without blaming the preparer for raising a reasonable question.'
]},
{slug:'ap-vendor-statement-cutoff-research',title:'What does a vendor statement cutoff actually prove?',excerpt:'A source-led study of statement period, issue date, retrieval date, and open-item evidence in AP reconciliation.',published:date,modified:date,thumbnail:'/research-thumbnails/aug21-statement-cutoff.png',keywords:['accounts payable outsourcing','AP research','vendor statements'],citations:[gao,treasury,sba],internalLinks:links,cta:'Use this research to define a controlled AP support lane.',body:[
'Campaign date: 2026-08-21. Research question: when an AP team says it reconciled a vendor statement “through” a date, which date does that statement actually describe? Statement period end, statement issue date, retrieval date, invoice receipt date, and payment clearing date are different evidence. This report studies how a support lane can preserve those distinctions while preparing an open-item comparison. It does not claim that a statement is complete, that a balance is correct, or that an old item should be paid or written off.',
'The evidence scope is a fixed sample of statements from selected vendors and a defined close period, with source invoices, credits, payments, and correspondence where available. The method records the original file, the statement’s stated period, issue date, retrieval event, and the date of each comparison. GAO principles support reliable information and documented review. SBA guidance supports keeping business-finance records organized. Neither establishes a universal reconciliation cutoff or aging rule.',
'Start with the statement itself. Preserve the vendor’s opening balance, listed transactions, closing balance, currency, entity, and period wording. A retrieval timestamp tells when the buyer obtained the file; it does not prove that the vendor included every transaction through that moment. A statement issued on the third may describe activity through the first. A portal download may have no clear issue date at all. Record absence rather than filling a blank from the retrieval time.',
'Build the comparison from both sides. Match statement lines to approved AP records by vendor, reference, amount, currency, and relevant date, while retaining the exact field used. Separate unmatched statement items, invoices in the buyer ledger but absent from the statement, credits, duplicate-looking lines, and timing differences. A support role can prepare these categories. It should not decide that an unmatched item is invalid, eligible for payment, or ready for a journal entry.',
'The close owner needs a question, not a pile of exceptions. For each unresolved line, state what source is missing, who can supply it, and what decision depends on it. If an invoice arrived after the statement period but before close, show both dates. If a credit appears on the statement but not in the ledger, preserve the vendor source and route the accounting treatment. This structure makes handoff practical without turning reconciliation support into an unapproved accounting function.',
'Use a two-part sample: ordinary statements selected across the period and deliberately selected cases with credits, foreign currency, late invoices, disputed services, or multiple entities. Keep the strata separate. A risk-focused sample is valuable for finding control questions but cannot produce a normal reconciliation rate. Treasury’s financial-information resources illustrate why period and source definitions matter, but they do not provide AP performance benchmarks.',
'Reviewers should reconstruct the cutoff claim from the source file and comparison sheet. Ask: what period did the vendor state, when did the buyer receive it, which ledger population was used, and which unresolved items could change the balance? Record disagreements. If a reviewer cannot answer one question, mark the evidence gap. Do not use a clean-looking closing balance as proof that all activity was captured; balances can agree while individual items remain misclassified or omitted.',
'Access and retention matter because statements can contain account details, contact data, and transaction history. Keep source files in the approved records system and limit the working comparison to necessary fields. NIST least-privilege concepts apply to the support lane, while the organization’s privacy, retention, and vendor policies control actual handling. Do not email a full statement to an unapproved address merely to accelerate follow-up. Route the missing evidence through the named owner.',
'Limitations include vendor-specific statement formats, delayed credits, different currencies, portal revisions, and incomplete historical records. A bounded study cannot establish a vendor’s reliability or prove a liability balance. It can show whether the organization’s cutoff language and comparison evidence are sufficient for review. State excluded vendors, missing statements, unmatched records, and the date the study was performed. Those disclosures prevent a local observation from becoming an unsupported financial conclusion.',
'Evidence-led conclusion: a vendor statement cutoff is useful only when its period wording, issue date, retrieval event, ledger population, and unresolved items remain visible together. Outsourced AP support can collect, compare, and route that evidence. Finance decides reconciliation disposition, accrual implications, disputes, and payment action. The honest outcome may be “statement received, balance not yet substantiated,” which is more actionable than a false completed status.',
'A follow-up study should compare one close cycle before and after adding explicit cutoff fields. Keep the vendor’s wording as the source of truth and label any internal cutoff as an organizational rule. Measure missing-field recurrence, not a promised reduction in open items. If the same ambiguity persists, escalate the policy question to finance rather than teaching the support lane to guess. Preserve a copy of the vendor’s original wording when the internal register uses a shorter label. A later reviewer should be able to distinguish “statement through June 30” from “reviewed on July 3” without asking why the dates differ. That simple separation protects both reconciliation quality and the support role’s boundary.'
]},
{slug:'ap-payment-run-hold-reason-research',title:'Which payment-run hold reason helps finance decide?',excerpt:'Research on making held invoices understandable without disguising approval, bank, or cash-management decisions as queue status.',published:date,modified:date,thumbnail:'/research-thumbnails/aug21-payment-hold.png',keywords:['accounts payable outsourcing','AP research','payment controls'],citations:[gao,cisa,treasury],internalLinks:links,cta:'Use this research to define a controlled AP support lane.',body:[
'Campaign date: 2026-08-21. Research question: does a payment-run hold reason tell a finance owner what must happen next, or merely explain why an invoice is absent from the run? This study examines held invoices across approval, evidence, vendor, bank, dispute, and scheduling conditions. The scope is the quality of the handoff record. It does not determine whether a hold is commercially wise, whether cash should be prioritized, or whether a payment should be released.',
'Define the population as one or more dated payment proposals and their excluded invoices. Preserve the proposal version, invoice identity, source status, hold field, owner, and later disposition. GAO control principles support documenting actions and information used in decisions. CISA guidance supports independent handling of suspicious payment requests. Treasury material provides context for financial-market information but does not set an organization’s payment calendar. The study maps principles to evidence, not policy to a universal answer.',
'A useful reason has three layers: observable condition, required evidence or decision, and named owner. “Missing approval” is a condition. “Obtain approval from the delegated owner” is the next action. “Controller” is the owner only if the organization’s matrix says so. “Not paid” is not a reason, and “urgent” is not authority. Keep a free-text explanation for unusual cases, but require the structured fields that prevent every hold becoming an opaque queue label.',
'Sample ordinary holds separately from risk-selected holds such as bank-detail changes, requests to bypass the run, duplicate signals, disputed invoices, and cross-entity questions. The risk sample tests escalation behavior; it cannot be used to state how often normal payments are held. For each item, ask whether the source record supports the reason, whether the owner is valid, and whether the next review event is dated. Do not infer risk from urgency alone or intent from a message’s tone.',
'The support role may prepare the excluded-invoice register, attach source evidence, identify a missing approval, and route a bank or fraud signal. It should not change a hold to make the run balance, select a replacement approver, modify bank details, approve the invoice, or release funds. A finance owner decides whether an exception is resolved and whether the item belongs in a payment proposal. Access should prevent the preparation lane from silently undoing its own stop.',
'When a hold persists, preserve each review event rather than resetting age. A new run date is not a new exception. Record what changed, which source was added, and who decided the disposition. This allows finance to distinguish a supplier delay, an approval delay, an internal evidence gap, and a deliberate cash-management choice. The distinction is operationally useful even when the final action is the same: remain held.',
'CISA’s independent-verification principle should be explicit for payment-detail changes and unusual release requests. A hold reason can state that verification is pending and identify the trusted channel required by policy. It should not include sensitive bank data in a broad report. The support worker routes the signal; an authorized employee verifies it. That boundary protects both the vendor relationship and the payment process from a request serving as its own confirmation.',
'Review quality with a reconstruction exercise. Give a second reviewer the proposal, held-invoice record, source packet, and history. Ask what caused the hold, what evidence would clear it, who can decide, and when it will be reviewed. Count the fields answered from source records. Report the denominator and run dates. Do not report a hold rate as a benchmark or promise that a new reason code will reduce payment delays.',
'Limitations include changing approval matrices, multiple payment systems, bank holidays, cash policy, and source records that are unavailable after a platform migration. A hold reason cannot establish a payment’s legality, liquidity impact, or supplier entitlement. It is a control artifact for a bounded workflow. State the systems reviewed, excluded runs, missing histories, and policy assumptions. Those limitations are part of the result, not an afterthought.',
'Evidence-led conclusion: a useful payment-run hold reason connects a source-backed condition to a next action, owner, and review event. Outsourced AP support can maintain that evidence without assuming release authority. Finance retains approval, bank verification, prioritization, and payment decisions. The strongest queue is not the one with the fewest holds; it is the one where every hold is understandable and cannot be cleared by an unauthorized shortcut.',
'After introducing the reason fields, repeat the reconstruction on a later run with the same vendor and entity mix. Compare clarity of the next action and owner, not the number of payments released. If a reason still requires private knowledge, improve the written rule or escalation route. Do not expand support permissions merely to make the payment list appear complete. Keep the held item visible across run versions and link each new review event to the previous one. That history lets a finance manager see whether evidence arrived, an approval changed, or the organization deliberately kept the item out of the run. It also prevents an outsourced preparer from being judged on a decision that belongs to finance. Include the person or role that can close each reason and the evidence they must attach. Without that close condition, a reason code simply moves uncertainty from one screen to another.'
]},
{slug:'ap-ap-inbox-channel-integrity-research',title:'Does the AP inbox preserve the channel an invoice arrived through?',excerpt:'A study of email, portal, forwarding, and attachment provenance for finance teams managing outsourced AP intake.',published:date,modified:date,thumbnail:'/research-thumbnails/aug21-inbox-channel.png',keywords:['accounts payable outsourcing','AP research','inbox controls'],citations:[cisa,gao,nist],internalLinks:links,cta:'Use this research to define a controlled AP support lane.',body:[
'Campaign date: 2026-08-21. Research question: can a later reviewer tell whether an AP document arrived through an approved channel, was forwarded, was imported from a portal, or was attached to an unrelated conversation? Channel provenance affects duplicate detection, independent verification, and the confidence a reviewer can place in the intake record. This report studies provenance as evidence, not as a judgment about a supplier or a message. The support lane’s task is to preserve signals and route uncertainty.',
'Methodology uses a defined sample from each allowed intake path: direct supplier email, shared mailbox forwarding, portal export, internal request, and manually uploaded attachment. Record message or export identifiers, received time, sender as displayed, attachment hash or filename where the system supports it, linked invoice record, and first route. GAO principles support reliable information; NIST supports traceable access; CISA supports treating suspicious requests with care. These sources do not certify a mailbox or establish fraud.',
'Provenance begins with the original container. An invoice attachment may be genuine while the surrounding email is not the approved request path. A forwarded message may preserve the file but obscure the original sender and arrival time. A portal export may establish the portal account and download event but not the supplier’s internal transmission process. Keep channel, sender evidence, and document content as separate fields. Do not collapse them into a green “received” status.',
'The sample should include duplicate files, replacement attachments, invoices arriving from a new address, payment-detail requests, and documents moved between queues. For each, ask whether the support worker can link the current record to the original channel without copying sensitive content into an uncontrolled sheet. If a link is unavailable, label the limitation. A missing provenance trail is an intake-control question, not proof that the invoice is invalid or that the sender acted improperly.',
'CISA guidance makes independent verification important when a message requests urgency, secrecy, or a bank change. The ordinary AP intake path should not be used to “verify” an unusual request by replying to the requesting address. The support role preserves the message, marks the risk signal, and routes it through the organization’s trusted procedure. The finance owner or security process decides what verification means. This distinction should be visible in both training examples and system permissions.',
'A support worker can classify the visible intake channel, attach the approved record, identify duplicate-looking documents, and request missing context. The worker should not create an exception-free path for familiar vendors, whitelist a new sender, alter the original document, or approve a vendor change. NIST least-privilege concepts support limiting access to the queue and fields needed for preparation. The organization’s policy determines actual access, retention, and escalation obligations.',
'Analyze the sample in separate strata. Report the number of records with complete channel provenance, unclear forwarding history, duplicate attachment signals, and escalation evidence. Do not combine risk-selected cases with ordinary cases to produce a normal error percentage. A second reviewer should try to reconstruct the source path from records alone. Disagreements reveal where intake labels or system integration need attention. They do not establish a vendor fraud rate or a production performance guarantee.',
'Channel integrity also involves retention. Keep the original message or portal reference under the approved records rule, restrict access to tax and bank documents, and avoid personal downloads. If a source system overwrites attachment history, record that limitation and ask the owner whether a controlled export is allowed. A research sheet should contain only the fields needed for the question. More copied data can make review harder and increase exposure without improving evidence.',
'The study cannot resolve all provenance questions. Email headers may be unavailable, portal permissions may change, vendor domains may use service providers, and attachments can be transformed by scanning or import. A bounded sample cannot prove that every invoice arrived through the approved channel. It can show what the current workflow preserves and where a reviewer must ask for confirmation. State the systems, period, exclusions, missing history, and reviewer disagreements clearly.',
'Evidence-led conclusion: AP channel integrity is reviewable when the record preserves the original intake path, document identity, sender context, duplicate signals, and escalation route. Outsourced support can perform that disciplined observation and preparation. Finance and security owners retain verification, vendor changes, approval, and payment authority. The right outcome for an uncertain source is a routed question, not a confident status that hides how little the record can prove.',
'The next experiment should alter one intake field or approved-channel rule, then repeat the same strata. Compare provenance completeness and reconstruction clarity. If forwarding remains the weak point, tighten the channel or require a linked original rather than asking workers to infer sender identity. Keep the change subject to owner approval, and preserve the initial sample so later improvements are measured against the same evidence boundary. A useful review also asks whether the new field creates unnecessary exposure. If it captures full message content when a stable identifier would do, narrow the design. Better provenance means a reviewer can find the source, not that every sensitive detail is copied into every queue.'
]}
];
