import type {ResearchPost} from './research-batch';

const gao={label:'GAO: Green Book Internal Control Standards',href:'https://www.gao.gov/greenbook'};
const nist={label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'};
const least={label:'NIST: Least Privilege Glossary',href:'https://csrc.nist.gov/glossary/term/least_privilege'};
const cisa={label:'CISA: Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-report-phishing'};
const irs={label:'IRS: About Form W-9',href:'https://www.irs.gov/forms-pubs/about-form-w-9'};
const ftc={label:'FTC: Data Breach Response Guide',href:'https://www.ftc.gov/business-guidance/resources/data-breach-response-guide-business'};
const links=[{label:'AP services',href:'/services'},{label:'AP inbox management',href:'/services/ap-inbox-management'},{label:'Research library',href:'/research'}];

const common=(title:string,focus:string)=>[
`Research question: how should an AP support team examine ${focus} without turning a preparation task into an accounting, approval, or payment decision? This report studies ${focus} as a bounded evidence problem. The unit of observation is one invoice, request, or related record in a defined queue and period. A result is useful only when a reviewer can trace it to the original source, see what was compared, and identify the person who owns the unresolved question.`,
`The control distinction matters because a clean-looking queue can conceal uncertainty. Preparation may include locating records, transcribing stated fields, comparing documents, labeling an exception, and requesting missing evidence. Review determines whether the evidence is sufficient. Approval, vendor-master change, tax interpretation, journal treatment, and payment release remain decisions for the organization’s authorized finance owners. The boundary should appear in both the written scope and the permissions granted to the person doing the preparation.`,
`For a practical observation, choose one entity or vendor group and a defined two-week period. Count complete items and exceptions separately. For each item, retain intake date, source location, fields checked, disposition, named owner, and date of the owner’s response. This design can show where evidence is missing or where handoffs stall. It cannot establish a universal error rate, staffing ratio, or policy for another company. Keep that limitation beside every conclusion.`,
`The evidence packet should preserve provenance rather than replace source values with a convenient summary. Record the exact field label, document name, page or system location, and whether the value was present, conflicting, or absent. If a prepared value is calculated, show the inputs and label it as a calculation. If an interpretation is needed, write a focused question instead of presenting the interpretation as a fact.`,
`A useful sample includes ordinary items and difficult cases. Ordinary items show whether the basic comparison is repeatable. Difficult cases show whether the stop condition works when dates, names, amounts, or supporting documents disagree. Do not remove stopped cases from the sample because they take longer. They reveal the handoff cost and tell the finance owner whether the proposed scope is narrow enough to supervise.`,
`The named owner should receive a short request: identify the mismatch, link the supporting records, state what is known, and ask one decision question. A queue status such as “pending” is not an escalation path. The owner may request more evidence, approve a documented exception, correct a source record, or keep the item stopped. The support role records that response and does not silently convert it into a new rule.`,
`Access should follow the smallest task that produces the packet. Read access may be enough for a comparison. Limited entry access may be needed for a draft field, but it should not include authority to approve invoices, change payment instructions, create vendors, or release funds. Access reviews should compare current permissions with the actual tested scope. A broader permission is a separate risk decision, not a convenience for clearing a queue.`,
`The external control principles cited here support reliable information, documented control activities, separation of responsibilities, and least privilege. They do not prescribe one AP workflow or prove that a particular sample is effective. Their role in this report is bounded: they provide a language for asking whether the source is reliable, whether the responsible owner is clear, and whether the person preparing evidence has more authority than the task requires.`,
`Interpretation must stay close to the observed period. If six of twenty items lacked a source field, the finding is that six sampled items lacked it during the selected period. It is not evidence that every vendor or future month will behave the same way. Segment findings by entity, vendor type, document type, and exception reason when the sample permits. A small sample can improve a question without becoming a market benchmark.`,
`Limitations include incomplete system history, inconsistent document naming, different policies across entities, and owner responses that arrive after the observation closes. A support team may also see only the queue assigned to it, not downstream accounting or bank records. These limits should be stated before results are used. The report is a research design for a controlled handoff, not a substitute for an organization’s accounting policy, legal advice, tax advice, or incident process.`,
`A manager can review the pilot through four questions: Did the packet retain the source? Did the comparison identify the actual issue? Did the item reach the correct owner? Did the final response remain visible? These questions are more diagnostic than a single throughput number. They distinguish missing evidence from slow approval and preparation quality from a decision that belongs elsewhere. Record corrections so recurring ambiguity can be addressed at the source.`,
`The record should also identify the cohort being studied. A queue containing domestic invoices, recurring services, purchase-order lines, and credit documents may require different evidence rules. Combining them can make a finding appear more stable than it is. Segmenting by document type and exception reason helps the owner decide whether the next change belongs in intake, source-data maintenance, reviewer guidance, or a separate specialist review.`,
`Time measurements need the same discipline. Measure from a named event, such as receipt of a complete source packet, to a named event, such as owner response. Do not describe a missing-document wait as preparation time. Report median or grouped observations only when the sample supports them, and preserve the raw dates for review. Elapsed time is a diagnostic signal; it is not permission to bypass an unresolved control.`,
`A stopped item is a valid research result. The purpose of the lane is not to make every record pass. A stop can protect the organization when a source is incomplete, a request is suspicious, or the decision depends on policy not available to the preparer. The quality test is whether the stop is legible, owned, and revisited through the approved channel, not whether the queue contains no exceptions.`,
`Before expanding the scope, the finance owner should compare the pilot’s ordinary examples with its stopped examples. Confirm that the source documents are available, that the prepared fields are reproducible, and that the escalation question reaches the right person. If the same ambiguity returns, narrow the lane or improve the source record first. Expansion should follow evidence about control fit, not pressure to process a larger population.`,
`The comparison should be repeatable by a second reviewer who was not present during preparation. Give that reviewer the source packet, the stated rule, and the prepared result, but do not rely on an oral explanation that disappears after the handoff. Agreement between reviewers does not prove the policy is correct; it does show whether the evidence and instruction are clear enough to inspect. Record disagreements as design findings rather than choosing the faster answer.`,
`When the source supports more than one plausible interpretation, preserve the alternatives and the reason for escalation. For example, a date may fit two service periods, or a contact may be valid for correspondence but not for payment changes. Stating the competing readings helps the owner answer the actual question. It also prevents a later reviewer from mistaking a preparer’s assumption for a fact supplied by the vendor or system.`,
`A follow-up review after the observation period can test whether the proposed control survives normal variation. Revisit a small selection of complete items, stopped items, and items with owner corrections. Compare the original packet with the final disposition and note whether the source, permission boundary, and escalation route remained intact. This retrospective is evidence about the design under test, not a claim that every future queue will behave identically.`,
`The conclusion is intentionally bounded. ${title} is safest when the support lane makes evidence easier to inspect and exceptions easier to own. It should not make an uncertain record look complete or move authority into an outsourced queue by implication. Start with a narrow sample, preserve complete and stopped examples, review the permissions, and expand only when the finance owner can explain both the ordinary path and the exception path.`,
];

type Seed={slug:string;title:string;excerpt:string;focus:string;specific:string[];citations:ResearchPost['citations'];thumbnail:string;serviceHandoff?:ResearchPost['serviceHandoff']};
const seeds:Seed[]=[
{slug:'ap-invoice-service-period-evidence-research',title:'Invoice service-period evidence research',excerpt:'How to separate service-period evidence from invoice and arrival dates before a close owner reviews an AP item.',focus:'invoice service-period evidence',specific:['A service period describes when goods or services relate to the business; it is not interchangeable with the supplier’s invoice date or the day an inbox received the file. Compare the stated period with the contract, purchase order, receipt, or service confirmation where those records exist.','A recurring monthly service can still have a missing or ambiguous period. Record the supplier wording and the supporting record rather than assigning a month because the invoice arrived near a close.','The support packet should show invoice date, arrival date, service-period wording, source location, and the close question. The finance owner decides accrual, posting period, reversal, or other accounting treatment.'],citations:[gao,nist],thumbnail:'ap-invoice-cutoff-research',serviceHandoff:{heading:'Set up a clear close-support lane',body:'A Philippines-based support role can collect the service-period record, label the gap, and send the close question to the right owner. Your finance team still decides the accounting treatment, then reviews the packet before the close is complete.',label:'Explore Month-End AP Close Support',href:'/services/month-end-ap-close-support'}},
{slug:'ap-invoice-billing-address-evidence-research',title:'Invoice billing-address evidence research',excerpt:'A bounded comparison of billing-address fields, legal entity records, and routing evidence for AP review.',focus:'invoice billing-address evidence',specific:['Billing address is a source field, not automatically proof of the legal entity that owes an invoice. Compare it with the entity on the purchase order, approved vendor record, tax document, and receiving evidence when available.','A shared office, lockbox, or third-party billing address can be legitimate. It can also be a sign that the packet lacks the field needed for routing. Preserve the exact address and ask the owner to resolve the relationship.','Do not edit the invoice or vendor record to make an address match. The preparation result should identify the compared records and distinguish a confirmed match from an unresolved entity question.'],citations:[gao,irs],thumbnail:'ap-invoice-entity-validation-research'},
{slug:'ap-invoice-number-normalization-research',title:'Invoice-number normalization research',excerpt:'How to improve duplicate review while preserving the supplier’s original invoice identifier and source record.',focus:'invoice-number normalization',specific:['Invoice numbers often contain spaces, punctuation, prefixes, or leading zeroes. A search form may help locate candidates, but it must remain separate from the identifier printed on the supplier document.','Test normalization against a dated sample of invoices and record false matches as well as useful matches. A shared number across entities or recurring invoices may be normal, so vendor, entity, amount, date, and source document remain relevant context.','The support role can record a candidate pair and explain the matching signals. It should not reject an invoice, merge records, or decide that two obligations are duplicates without the authorized review.'],citations:[gao,nist],thumbnail:'ap-invoice-duplicate-signals-research'},
{slug:'ap-invoice-currency-evidence-research',title:'Invoice currency evidence research',excerpt:'What an AP packet should preserve when invoice currency, entity, and conversion questions need finance review.',focus:'invoice currency evidence',specific:['Keep the currency code or wording exactly as shown on the invoice and separate it from the organization’s reporting currency. A numeric amount without its currency is incomplete evidence.','Compare the invoice currency with purchase-order terms and the entity context, but do not select an exchange rate merely because it produces a familiar total. If a conversion is prepared for review, record the source, date, and calculation inputs.','The finance owner decides recognition, conversion, settlement, and any policy exception. The support packet can make the question smaller by listing the source amount, currency, proposed basis, and unresolved field.'],citations:[gao,nist],thumbnail:'ap-cash-forecast-inputs-research'},
{slug:'ap-invoice-unit-price-variance-research',title:'Invoice unit-price variance evidence research',excerpt:'A research model for describing unit-price differences without labeling every variance an error.',focus:'invoice unit-price variance evidence',specific:['A unit-price comparison needs a common unit, quantity, currency, and source date. Compare the invoice line with the applicable order line and retain the wording that defines the unit.','A variance can reflect an approved change, freight, tax, partial delivery, a different unit of measure, or a source error. A single percentage does not explain which case occurred. Separate price, quantity, and description differences.','The support role prepares the comparison and routes the exact question to the buyer or finance owner. It should not alter an order, accept a price, approve an exception, or tell a supplier that payment will proceed.'],citations:[gao,least],thumbnail:'three-way-match-exception-research'},
{slug:'ap-vendor-statement-period-research',title:'Vendor statement period research',excerpt:'Why statement period, retrieval date, and open-item evidence need separate fields in AP reconciliation work.',focus:'vendor statement periods',specific:['A vendor statement is bounded by the period printed on the statement and the date it was retrieved. Those dates answer different questions and should not be collapsed into a single “current” label.','Compare statement lines with the organization’s invoice, payment, credit, and dispute records. Preserve unmatched lines and missing pages. An apparent balance may be caused by a timing difference rather than an unexplained obligation.','The support role can request a complete statement and prepare candidate matches. Finance decides whether an item is payable, disputed, duplicated, or subject to another reconciliation treatment.'],citations:[gao,nist],thumbnail:'ap-vendor-statement-reconciliation-research'},
{slug:'ap-approval-channel-evidence-research',title:'Invoice approval-channel evidence research',excerpt:'How to retain approval context while distinguishing a recorded decision from an informal message or status update.',focus:'invoice approval-channel evidence',specific:['Approval evidence should identify the invoice, decision, approver, date, and channel permitted by the organization’s policy. A forwarded message or chat excerpt may be context without being sufficient authority.','The packet should preserve the original approval record and distinguish “approved,” “reviewed,” “received,” and “please process.” These phrases have different implications and should not be normalized into one status.','The support role can link the packet and request clarification when the decision is ambiguous. It should not infer approval from silence, route around a threshold, or approve its own preparation.'],citations:[gao,nist,least],thumbnail:'ap-approval-separation-research'},
{slug:'ap-purchase-order-line-evidence-research',title:'Purchase-order line evidence research',excerpt:'A line-level approach to comparing invoices with purchase orders and routing unmatched details to the right owner.',focus:'purchase-order line evidence',specific:['Line-level evidence is more informative than a header-level match. Retain item description, quantity, unit, price, currency, and order reference when each is available. Mark absent fields rather than assuming the line is covered.','One invoice can contain matched and unmatched lines. Keep those outcomes separate so a clean line does not hide a disputed line. Partial receipts and approved change orders need their own source references.','The support lane prepares the comparison and identifies the requester, buyer, receiver, or finance owner who can answer the mismatch. It does not create receipts or rewrite purchase-order lines to force agreement.'],citations:[gao,least],thumbnail:'ap-purchase-order-reconciliation-research',serviceHandoff:{heading:'Turn this check into a Philippines role brief',body:'If your team needs help preparing purchase-order comparisons, start with the fields, source records, and stop rules in this report. The finance owner still decides how to handle a mismatch, while the support role keeps the evidence and follow-up clear.',label:'Plan purchase order reconciliation support',href:'/services/purchase-order-reconciliation'}},
{slug:'ap-invoice-receipt-date-evidence-research',title:'Invoice receipt-date evidence research',excerpt:'How to keep invoice receipt date distinct from invoice, service, approval, and posting dates in AP close support.',focus:'invoice receipt-date evidence',specific:['Receipt date means when the organization received the invoice through the defined channel. It can support a cutoff analysis, but it does not establish when the service occurred or when an invoice should be posted.','Use a consistent intake timestamp and preserve the original message or upload record where policy allows. Late forwarding, duplicate delivery, and replacement files should be identified rather than silently backdated.','The support role records the source and routes cutoff questions. The close owner decides the accounting response and should be able to see both the source date and any later correction.'],citations:[gao,nist],thumbnail:'ap-invoice-cutoff-research'},
{slug:'ap-vendor-contact-source-research',title:'Vendor-contact source verification research',excerpt:'A source-led method for following up on AP questions while reducing risk from changed channels and urgent requests.',focus:'vendor-contact source verification',specific:['A contact address in an invoice, approved vendor record, or prior verified correspondence has a different evidentiary role from a new message asking to change payment details. Record which source supplied the contact.','Follow-up can request a missing document or clarification through an approved channel. A new channel, urgent payment pressure, or changed bank instruction should be stopped and independently verified by an authorized owner.','The support packet should retain the message, source comparison, verification status, and escalation owner. It should not treat the requesting message as its own independent confirmation.'],citations:[cisa,gao],thumbnail:'ap-vendor-email-verification-research'},
];

export const aug14ResearchBatch:ResearchPost[]=seeds.map((s)=>({
  ...s,
  published:'2026-08-14',
  modified:'2026-08-14',
  thumbnail:`/research-thumbnails/${s.thumbnail}.svg`,
  keywords:['accounts payable outsourcing','AP research','finance operations'],
  body:[...s.specific,...common(s.title,s.focus)],
  internalLinks:links,
  cta:'Use this research to define a controlled AP support lane.'
}));
