import type {ResearchPost} from './research-batch';

export const oct9ResearchPublicationDate='2026-10-09';
const citations=[
  {label:'GAO: Standards for Internal Control in the Federal Government',href:'https://www.gao.gov/greenbook'},
  {label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {label:'NIST: Least Privilege Glossary',href:'https://csrc.nist.gov/glossary/term/least_privilege'},
  {label:'IRS: Recordkeeping',href:'https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping'}
];
type Spec={slug:string;title:string;excerpt:string;question:string;population:string;signals:string[]};
const specs:Spec[]=[
  {slug:'outsourceaccountspayable-queue-wait-state-evidence-study',title:'Outsourced Accounts Payable Queue Wait-State Evidence Study',excerpt:'A source-backed study for outsourced accounts payable teams to whether waiting reasons explain queue age.',question:'how long an adequately prepared exception waits for the authorized owner and which evidence gaps explain the delay',population:'invoice, credit, receipt, vendor, tax, and payment exceptions routed to named owners',signals:['packet-ready time','owner assignment','first review event','requests for added evidence','decision time','implementation time']},
  {slug:'outsourceaccountspayable-reviewer-agreement-reliability-study',title:'Outsourced Accounts Payable Reviewer Agreement Reliability Study',excerpt:'A source-backed study for outsourced accounts payable teams to whether reviewers reproduce the same conclusion.',question:'whether a second reviewer can reconstruct the invoice packet seen at approval after attachments or system fields change',population:'posted, held, corrected, rejected, and superseded invoice packets with later source changes',signals:['document version','file hash or stable ID','field extraction','approval event','later correction','final posting']},
  {slug:'outsourceaccountspayable-minimum-access-effectiveness-study',title:'Outsourced Accounts Payable Minimum Access Effectiveness Study',excerpt:'A source-backed study for outsourced accounts payable teams to whether permissions are sufficient but bounded.',question:'whether independent reviewers reach the same factual classification and routing decision from the same frozen evidence',population:'representative AP exceptions across invoice, receipt, credit, vendor, tax, and payment workflows',signals:['cause classification','missing source','risk flag','named owner','stop condition','requested decision']},
  {slug:'outsourceaccountspayable-handoff-completeness-observation',title:'Outsourced Accounts Payable Handoff Completeness Observation',excerpt:'A source-backed study for outsourced accounts payable teams to whether a receiving team can continue without private clarification.',question:'whether all payment-related access and reusable artifacts are removed or reassigned at the authorized offboarding time',population:'departing employees, contractors, service accounts, temporary roles, active sessions, and saved payment artifacts',signals:['identity inventory','role removal','session revocation','token rotation','template ownership','post-removal test']},
  {slug:'outsourceaccountspayable-control-change-traceability-research',title:'Outsourced Accounts Payable Control Change Traceability Research',excerpt:'A source-backed study for outsourced accounts payable teams to whether operating changes remain attributable and reversible.',question:'why closed AP exceptions reopen and which recurrence patterns point to evidence, ownership, system, or workflow defects',population:'exceptions reopened after recorded closure across invoices, credits, receipts, supplier records, approvals, and payments',signals:['original cause','closure basis','new trigger','same-record recurrence','owner transfer','corrective action']}
];

function makeResearch(s:Spec):ResearchPost{
 const sig=s.signals;
 const body=[
  `This study asks ${s.question}. It examines ${s.population}. The research is designed for finance leaders who need measurable process evidence without transferring approval, accounting judgment, vendor acceptance, access administration, or payment authority to an outsourced preparation role. The output is a reproducible register and owner-facing decision packet, not a declaration that a transaction is valid. GAO's Green Book provides the framework for responsibility, quality information, control activities, and monitoring. NIST SP 800-53 and the least-privilege definition support attributable events and restricted permissions. IRS recordkeeping guidance reinforces retaining records that support business activity. Company policy and accountable owners still determine the actual treatment.`,
  `The population register retains every in-scope item, including completed, held, rejected, corrected, superseded, and reopened cases. Core fields include entity, stable case ID, supplier or employee identity, transaction reference, amount and currency where relevant, intake time, source versions, queue state, assigned owner, reviewer, decision event, implementation event, and final disposition. The six primary observations are ${sig.join(', ')}. Excluding difficult or unresolved cases would bias the study toward clean outcomes, so selection rules are frozen before measurement and every exclusion receives a reason. Sensitive bank, tax, identity, and personnel values are masked in analytical files and remain in approved systems.`,
  `Time is treated as evidence. Each event retains its original display value, timezone, actor or process, system, and stable event identifier. A normalized UTC time is added for comparison without replacing the original. The protocol separates intake, packet-ready, routing, owner acknowledgement, evidence request, response, decision, implementation, and verification. That distinction prevents waiting for missing source evidence from being attributed to an owner and prevents post-decision implementation time from being attributed to the preparer. If system clocks or exports conflict, the variance is recorded as a limitation and routed to the system owner rather than silently resolved.`,
  `Source preservation is tested before analysis. Original documents, portal exports, workflow histories, approval records, master-data versions, and relevant correspondence receive stable identifiers or hashes where the approved platform supports them. Extracted values remain linked to the source and version from which they came. A current screen cannot prove what a reviewer saw earlier, and an edited attachment cannot retroactively replace the file used for a prior decision. The reconstruction packet therefore keeps both the historical and later record, explains the event connecting them, and marks evidence that was unavailable at the tested point in time.`,
  `The analytical method uses explicit classifications. For each signal, reviewers choose aligned, different, missing, superseded, not applicable, or owner interpretation required and cite the supporting record. Calculations show inputs, precision, rounding, and result. Identity comparisons retain legal entity, internal account, source-document name, and any approved relationship record. The protocol does not treat matching totals, familiar display names, a successful status, or a prior transaction as proof. Those observations can guide review, but an authorized owner must resolve substantive differences involving scope, validity, accounting, compliance, access, or release.`,
  `Quality is tested with a blinded second review. Two reviewers receive the same frozen packet and independently record ${sig.join(', ')}. Agreement is measured separately for factual fields, classification, missing evidence, named owner, and stop condition. A disagreement is adjudicated against the source and taxonomy; it is not settled by choosing the faster answer. The taxonomy and instructions are revised when wording, missing source structure, or system ambiguity causes recurring disagreement. The original reviewer responses remain in the research record so improvement does not erase evidence of the earlier measurement weakness.`,
  `Challenge cases are deliberately included: records spanning two entities; documents replaced under the same visible name; timestamps near a cutoff; an approval followed by a value change; an automated state without an attributable actor; overlapping owners; transferred queues; a supplier message introducing sensitive changes; a rejected action later retried; and closure followed by new evidence. The method passes when reviewers reconstruct the same sources, chronology, factual differences, and accountable decision point. It fails when current state substitutes for historical evidence, when missing records are treated as negative proof, or when the support role resolves a controlled decision to improve a metric.`,
  `Role boundaries are part of the study design. AP support may inventory sources, normalize timestamps, prepare comparisons, maintain an evidence-based queue, calculate documented measures, and route bounded questions. It may not approve invoices or vendors, choose accounting or tax treatment, verify sensitive changes through an unapproved channel, grant or remove privileged access unless assigned as the authorized administrator, override controls, approve payment, or release funds. Finance, purchasing, receiving, tax, compliance, treasury, security, human resources, and system owners retain their designated decisions. The register records those assignments so a missing owner is visible as a design defect rather than quietly absorbed by the analyst.`,
  `Useful measures include population completeness, source completeness, packet-ready rate, owner acknowledgement, decision time, implementation time, missing-evidence cycles, classification agreement, reopened items, repeated causes, and verified closure. Report medians and distributions rather than only averages, and stratify by cause, entity, owner role, risk, and workflow where sample sizes permit. Do not rank individual employees by raw speed or reward hold removal. A controlled stop can be the correct result. Counts are accompanied by definitions, numerator, denominator, exclusions, observation window, and known system gaps so management can distinguish a process signal from an attractive but unsupported benchmark.`,
  `Limitations include overwritten histories, inaccessible external systems, shared identities, clock drift, policy ambiguity, informal decisions, unrecorded supplier events, and small samples. The study cannot prove fraud, legal ownership, tax status, contract validity, or ultimate receipt of funds. It also cannot establish causation from a workflow correlation alone. Its defensible conclusion is narrower: ${s.question} can be evaluated when the population, source versions, chronology, roles, classifications, decision, implementation, and residual limitations are preserved. Management may use recurring evidence gaps to prioritize system or workflow changes, but the research packet does not authorize those changes.`,
  `The final handoff contains a methods note, frozen population, data dictionary, source register, exception taxonomy, event chronology, reviewer-agreement table, findings with denominators, challenge-case results, limitations, and an action register. Each proposed action names the accountable owner, required evidence, target review date, and verification method. A compact case summary shows ${sig.join(', ')} and links them to original records. Later corrections append a new version rather than rewriting the measured history. This structure lets another reviewer reproduce the result, lets leaders see where delay or recurrence actually arises, and keeps the outsourced support role focused on evidence preparation instead of policy interpretation or transaction approval.`
 ];
 return {slug:s.slug,title:s.title,excerpt:s.excerpt,published:oct9ResearchPublicationDate,modified:null,thumbnail:'/research-thumbnails/ap-approval-matrix-research.svg',keywords:[s.slug.replaceAll('-',' '),'accounts payable controls','AP evidence research'],body,citations,internalLinks:[{label:'Accounts payable services',href:'/services'},{label:'AP workflow guides',href:'/blog'},{label:'Contact the team',href:'/contact-us'}],cta:'Map this research method to a controlled AP workflow.',serviceHandoff:{heading:'Turn evidence into an owner-ready AP handoff',body:'Our support team can preserve sources, prepare comparisons, and maintain the review queue while your authorized owners retain policy, approval, access, and payment decisions.',href:'/services',label:'Review AP support services'}};
}

export const oct9ResearchBatch:ResearchPost[]=specs.map(makeResearch);

// This October 9 control starts from one bounded observation, preserves missing evidence as missing, and keeps the consequential decision with the named accountable owner.
