type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-09-04';
const links=[{label:'Bank-change callback evidence log',href:'/blog/ap-bank-change-callback-evidence-log'},{label:'Payment file preparation checklist',href:'/blog/ap-payment-file-preparation-checklist'},{label:'Weekly exception aging review',href:'/blog/ap-weekly-exception-aging-review'}];
const serviceHandoff={heading:'Turn the evidence into a bounded AP role',body:'Name the source records, preparation steps, review timing, exception owner, and decisions that remain with employees before granting access.',href:'/contact-us',label:'Discuss an AP support scope'};
const sources={nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},gao:{label:'GAO Green Book',href:'https://www.gao.gov/greenbook'},cisa:{label:'CISA: Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'},fbi:{label:'FBI: Business Email Compromise',href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'},irs:{label:'IRS: About Form W-9',href:'https://www.irs.gov/forms-pubs/about-form-w-9'}};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,population:string,method:string,limit:string,conclusion:string,citations:Post['citations']):Post=>({slug,title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks:links,serviceHandoff,body:[
`This review asks ${question}. It applies public guidance to a bounded accounts payable process. It does not produce a legal, tax, accounting, or fraud conclusion, and it does not claim a universal performance benchmark.`,
`The evidence population is ${population}. The study keeps source records, operator observations, third-party replies, and company decisions in separate fields so readers can see who knew what and when.`,
`Method: ${method}. The sample includes routine, incomplete, conflicting, corrected, and urgent cases. A second reviewer attempts the same classification without an oral explanation from the first reviewer.`,
`Access also matters. NIST's control catalog supplies principles for least privilege and attributable actions. The GAO Green Book supplies principles for documentation, quality information, and monitoring. Those sources frame the test; they do not decide a particular invoice or supplier outcome.`,
`Evidence limits: ${limit}. Results apply to the named systems, entities, date range, selection rules, and records that were actually available. Missing records stay in the denominator or appear as a stated exclusion.`,
`A defensible reading is modest: ${conclusion}. Management still chooses thresholds, access, retention, escalation, and decision owners, then retests the process when the workflow changes.`,
]});
export const sep4ResearchBatch:Post[]=[
make('ap-bank-change-verification-channel-research','Independent channels for vendor bank-change verification','A source-led review of contact provenance, callback evidence, access boundaries, and unresolved bank-change requests.','/research-thumbnails/ap-vendor-inquiry-response-research.svg','which evidence shows that a bank-change request was checked through a channel independent of the incoming request','bank-change requests, original supplier records, approved contact sources, callback attempts, replies, reviewer notes, master-data events, and payment holds','define the period and entities, stratify requests by channel and outcome, then test whether reviewers can trace the contact source without relying on details inside the request','a completed phone call does not prove the caller reached an authorized supplier representative, and a familiar email thread can still be compromised','the record is stronger when contact provenance, failed attempts, discrepancies, authority, and the final disposition remain visible',[sources.fbi,sources.cisa,sources.nist]),
make('ap-payment-file-change-control-research','Change control between AP payment proposal and release','Research on version identity, control totals, late edits, approval evidence, and separation of payment duties.','/research-thumbnails/aug21-payment-hold.png','what lets a reviewer reconstruct changes between an approved payment proposal and the released bank file','proposal versions, invoice population, exclusions, approvals, export logs, control totals, bank-file identity, late changes, release events, and rejection messages','select payment cycles with and without late edits, compare each source population to its exported file, and ask an independent reviewer to explain every difference','matching totals can conceal offsetting changes, while a changed total may be legitimate when the evidence and renewed approval are retained','versioned populations and attributable changes matter more than a single screenshot of a final total',[sources.gao,sources.nist]),
make('ap-credit-memo-application-evidence-research','Evidence for applying supplier credit memos','A bounded study of invoice references, entity conflicts, open balances, correspondence, and accounting disposition.','/research-thumbnails/ap-close-evidence-handoff-research.svg','which records support review of a proposed credit application without turning a supplier document into an automatic posting instruction','credit memos, referenced invoices, supplier accounts, entities, currencies, open-item reports, correspondence, proposed applications, approvals, and posting results','sample full, partial, unapplied, disputed, duplicate, and cross-entity credits, then reconcile proposal, owner decision, and ledger outcome','a supplier reference may be stale or ambiguous, and an open balance does not by itself establish the correct entity or accounting treatment','a reviewable queue separates the supplier claim, internal match analysis, authorized decision, and completed posting',[sources.gao,sources.nist]),
make('ap-invoice-image-quality-research','Invoice image quality and AP data reliability','Research on source-file defects, uncertain OCR fields, replacement requests, and the boundary between transcription and judgment.','/research-thumbnails/ap-invoice-coding-control-research.svg','how image defects affect the reliability of invoice data used in outsourced AP workflows','original files, page counts, image-quality checks, OCR output, operator corrections, uncertain fields, replacement requests, revised files, and downstream queue events','create a declared test set with clean, cropped, skewed, low-contrast, handwritten, duplicate, and mixed-document files, then compare field-level results and escalation choices','the study does not estimate every OCR system’s accuracy; file mix, language, layout, scan conditions, and human review can change results','teams should measure uncertainty at the field and document level and stop processing when required source evidence cannot be read',[sources.gao,sources.nist]),
make('ap-tax-document-status-evidence-research','Supplier tax-document status as an AP evidence problem','A source-backed review of document provenance, dates, conflicting supplier details, access, and escalation boundaries.','/research-thumbnails/ap-tax-document-collection-research.svg','what an AP support team can record about supplier tax documents without making a tax determination','supplier records, requested document types, received files, IRS form references, received and effective dates, name and identifier comparisons, conflicts, access logs, reviewer decisions, and replacement history','define the document population and company procedure, sample current, missing, replaced, illegible, and conflicting files, and test whether a reviewer can reproduce the recorded status','IRS materials describe federal forms and instructions, but they do not decide a specific supplier’s status from this workflow; jurisdiction, entity type, and company obligations may differ','support staff can track provenance and visible conflicts, while qualified company owners decide requirements, validity, tax treatment, and remediation',[sources.irs,sources.gao,sources.nist]),
];
