type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-09-09';
const sources={gao:{label:'GAO Green Book',href:'https://www.gao.gov/greenbook'},nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},occ:{label:'OCC Accounts Payable Operations',href:'https://www.occ.treas.gov/publications-and-resources/publications/comptrollers-handbook/files/accounts-payable/index-accounts-payable.html'},cisa:{label:'CISA Identity and Access Management',href:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'},fbi:{label:'FBI Business Email Compromise',href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'}};
const internalLinks=[{label:'Invoice hold release register',href:'/blog/ap-invoice-hold-release-register'},{label:'Supplier contact authority record',href:'/blog/ap-supplier-contact-authority-record'},{label:'Duplicate-payment recovery file',href:'/blog/ap-duplicate-payment-recovery-file'}];
const serviceHandoff={heading:'Turn the evidence into a bounded AP support lane',body:'Define the source population, permitted preparation, access, reviewer, exception owner, retained decisions, and retest trigger before assigning the work.',href:'/contact-us',label:'Discuss an AP support scope'};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,population:string,method:string,limits:string,finding:string,citations:Post['citations']):Post=>({slug,title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks,serviceHandoff,body:[
`Research question and scope: ${question}. This review applies public control guidance to a bounded accounts payable process. It is not legal, tax, accounting, cybersecurity, or fraud assurance and does not establish a universal benchmark.`,
`Evidence population: ${population}. The entity, systems, observation period, cutoff, inclusion criteria, exclusions, and unavailable records must be declared before analysis. Source facts, operator notes, supplier statements, reviewer inference, and management decisions remain separate.`,
`Methodology: ${method}. The review retains original chronology and requires a second reviewer to reproduce classifications from the same evidence packet. Reported counts describe only the declared sample.`,
`Control basis: the GAO Green Book addresses responsibility, documentation, quality information, and monitoring; NIST SP 800-53 addresses least privilege and attributable activity. The other cited sources refine the operating question but do not decide individual cases.`,
`Inference limits and limitations: ${limits}. Missing records are reported as missing or excluded rather than inferred. Results cannot be generalized beyond the stated population, policies, access model, workflow, and period.`,
`Bounded conclusion: ${finding}. Management retains policy, access, materiality, accounting treatment, vendor-master approval, payment release, retention, and the decision to remediate or retest.`,
]});
export const sep9ResearchBatch:Post[]=[
make('ap-invoice-hold-duration-research','How long invoice holds last—and what duration cannot explain','A reproducible review of hold causes, ownership, evidence age, release events, and unresolved AP work.','/research-thumbnails/ap-aging-handoff-research.svg','which retained events let a reviewer measure invoice-hold duration and distinguish waiting from unowned work','invoice and workflow identifiers, hold events and categories, source evidence, owner changes, correspondence, reviews, releases, approvals, cancellations, and unresolved items','select all holds opened or active in the period; stratify by reason and age; reconstruct start, review, and terminal events; then replay released and still-open cases','duration alone does not establish control failure, supplier fault, validity, materiality, or urgency; inconsistent codes, migrations, reopened items, and missing messages can distort elapsed time','hold aging is useful when cause, owner, evidence, next review, release authority, and history remain independently inspectable',[sources.gao,sources.occ,sources.nist]),
make('ap-remittance-delivery-evidence-research','Remittance delivery evidence after payment execution','Research on advice generation, recipient authority, delivery signals, supplier responses, and unresolved cash application.','/research-thumbnails/ap-remittance-advice-research.svg','what evidence supports a claim that remittance advice was prepared and delivered to an approved supplier contact','payment records, advice versions, paid-item detail, approved contacts, outbound events, bounce or delivery signals, portal access, replies, resend events, inquiries, and resolution status','sample completed payments across delivery channel and supplier type; compare advice with payment records; validate recipient authority; and separately classify send, delivery, acknowledgment, and application evidence','a sent or delivered message does not prove it was read, understood, or correctly applied; mail telemetry and supplier systems vary, and later reconciliation can hide the original gap','follow-up is reproducible when payment identity, advice content, recipient, delivery event, supplier response, and unresolved items are distinct facts',[sources.gao,sources.occ,sources.nist]),
make('ap-vendor-portal-access-research','Vendor-portal access patterns in outsourced AP work','A bounded evidence study of privileges, account ownership, review dates, shared access, and revocation events.','/research-thumbnails/ap-vendor-onboarding-controls-research.svg','which records let finance and security reviewers assess vendor-portal access used for AP preparation','portal inventory, supplier, named and shared accounts, approved purpose, privilege display, authentication setup, logs where available, attestations, role changes, reviews, and revocations','declare the portal population; compare approved purpose with observable privilege; stratify active, dormant, shared, privileged, and departed-user accounts; independently replay review decisions','portal logs and privilege labels vary; absence of an event does not prove non-use; the study does not test credential secrecy, supplier security, session integrity, or intent','least-privilege review is stronger when every portal has an owner, approved purpose, inspectable rights, review cadence, and attributable revocation path',[sources.nist,sources.cisa,sources.gao]),
make('ap-duplicate-payment-recovery-research','Evidence pathways for duplicate-payment recovery','Research on candidate detection, validation, supplier confirmation, credits, refunds, offsets, and ledger closure.','/research-thumbnails/ap-duplicate-payment-research.svg','what evidence allows a reviewer to follow a suspected duplicate payment through validation and recovery','invoice images and identifiers, duplicate signals, ledger and bank events, match rationale, validation, supplier correspondence, credits, refunds, offsets, postings, and open balances','include every candidate generated in the period; classify confirmed and rejected matches; stratify recovery route and age; reconcile outcomes to bank and ledger evidence; replay ambiguous cases','similar invoices or payments do not prove duplication; missing bank references, cross-entity activity, credits, foreign exchange, and supplier netting can produce false matches','reporting is credible when candidate logic, validation, supplier response, cash or credit event, application, remaining exposure, and closure authority stay separate',[sources.gao,sources.occ,sources.fbi]),
make('ap-service-receipt-evidence-research','Service-receipt evidence for non-physical purchases','A synthesis of service periods, milestones, requester confirmation, system entries, exceptions, and AP decision boundaries.','/research-thumbnails/ap-receipt-evidence-research.svg','which evidence supports invoice preparation when a service has no physical goods receipt','invoices, contracts, service periods, milestone terms, time or delivery records, requester confirmations, system entries, disputes, credits, approvals, and corrections','define eligible service categories; sample routine, partial, milestone, recurring, disputed, cancelled, and missing-receipt cases; compare required with retained evidence; replay routing outcomes','requester confirmation may be incomplete or retrospective and does not establish accounting treatment, contractual performance, legitimacy, or payment approval; systems represent services differently','AP can prepare a consistent exception when service obligation, period or milestone, evidence, requester authority, missing facts, and approval responsibility are explicit',[sources.gao,sources.occ,sources.nist]),
];
