export type ResearchPost = {slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;keywords:string[];body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];cta:string};
const source={label:'NIST — Access Control',href:'https://csrc.nist.gov/glossary/term/least_privilege'};
const topics=[
['ap-outsourcing-scope-benchmark','AP outsourcing scope benchmark: what to hand off first','A practical benchmark for separating repeatable AP preparation from approvals, bank changes, and payment release.'],
['invoice-intake-control-research','Invoice intake controls for distributed AP teams','Research on the minimum intake fields and review trail a remote AP support lane should capture.'],
['three-way-match-exception-research','Three-way match exception handling: a workflow study','How teams can measure match exceptions without turning an assistant into the final accounting approver.'],
['ap-approval-separation-research','AP approval separation and role design','A source-backed look at separating preparation, review, approval, and payment release.'],
['vendor-bank-change-control-research','Vendor bank-change controls for outsourced AP','Why changed payment details need a distinct escalation path and employee verification step.'],
['ap-aging-handoff-research','AP aging handoff research for finance managers','A simple model for turning aging data into an owner-led review queue.'],
['month-end-ap-capacity-research','Month-end AP capacity planning for support teams','Use volume, exception rate, and review time to plan a safer first outsourced AP lane.'],
['ap-quality-review-scorecard-research','AP quality review scorecard research','Observable quality measures for invoice packets, exception notes, and handoffs.'],
['philippines-ap-support-role-research','Philippines AP support role design research','A role-design brief for teams considering Philippines-based accounts-payable support.'],
['ap-outsourcing-onboarding-research','AP outsourcing onboarding: first-30-day evidence','What to document before expanding a support role beyond its first controlled queue.']
] as const;
export const researchBatch:ResearchPost[]=topics.map(([slug,title,excerpt])=>({slug,title,excerpt,published:'2026-08-07',modified:'2026-08-07',thumbnail:`/research-thumbnails/${slug}.svg`,keywords:['accounts payable outsourcing','AP controls','Philippines AP support'],body:[`This report examines ${title.toLowerCase()} for a finance team considering outsourced accounts-payable support. The unit of analysis is a reviewable work packet: source records, prepared fields, exception notes, and a named owner. That keeps recommendations separate from any company-specific approval policy.`,`The first finding is that repeatability matters more than volume. A support role can sort an AP inbox, compare records, prepare a draft packet, and request missing evidence when inputs and stop conditions are written down. Approval, vendor-master changes, bank-detail changes, and payment release remain employee decisions.`,`Useful measures include the share of packets that arrive complete, the share that stop for a documented reason, correction count, and time to owner response. Review a sample against the original invoice, purchase order, receipt, approval trail, or vendor communication. Do not use output volume alone as a quality signal.`,`Least privilege is the implementation guardrail: grant only the system access needed for the starting lane, record who can approve or release money, and review permissions when scope changes. For a Philippines-based team, document schedule overlap, escalation timing, communication channel, and the employee who owns unresolved exceptions.`,`Recommended next step: pilot one queue for two weeks, retain representative complete and stopped examples, and ask the finance owner to sign off on the boundary before adding another AP lane. This creates evidence for staffing and makes a later handoff safer than starting with a broad promise to manage AP.`],citations:[source,{label:'NIST — Role Based Access Control',href:'https://csrc.nist.gov/projects/role-based-access-control'}],internalLinks:[{label:'AP services',href:'/services'},{label:'AP inbox management',href:'/services/ap-inbox-management'},{label:'Blog guides',href:'/blog'}],cta:'Map this research to a controlled AP staffing plan.'}));
