import type {ResearchPost} from './research-batch';

// This date is the expected first-publication date for the October 2 combined release.
// The sole integrator must reconcile it to the actual UTC live-verification date before push.
export const oct2ResearchPublicationDate='2026-10-02';
const checked='October 2, 2026';

const controlSources=[
  {label:`U.S. GAO, Standards for Internal Control in the Federal Government (2025), checked ${checked}`,href:'https://www.gao.gov/greenbook'},
  {label:`NIST SP 800-53 Rev. 5, Security and Privacy Controls, checked ${checked}`,href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'}
];

const promptPaymentSource={label:`Federal Acquisition Regulation 32.9, Prompt Payment, checked ${checked}`,href:'https://www.acquisition.gov/far/subpart-32.9'};
const electronicEvidenceSource={label:`DFARS 232.70, Electronic Submission and Processing of Payment Requests and Receiving Reports, checked ${checked}`,href:'https://www.acquisition.gov/dfars/subpart-232.70-electronic-submission-and-processing-payment-requests-and-receiving-reports'};

const discountEligibility:ResearchPost={
  slug:'invoice-prompt-payment-discount-eligibility-research',
  title:'Prompt-payment discount eligibility: an AP evidence method',
  excerpt:'Research on reconstructing discount terms, valid invoice receipt, acceptance, disputes, and the decision boundary before a payment proposal.',
  published:oct2ResearchPublicationDate,modified:oct2ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-payment-calendar-control-research.svg',
  keywords:['prompt payment discount review','invoice discount evidence','accounts payable research'],
  cta:'Design a controlled payment-preparation lane.',
  internalLinks:[
    {label:'Payment run preparation',href:'/services/payment-run-preparation'},
    {label:'Invoice data capture',href:'/services/invoice-data-capture'},
    {label:'AP services',href:'/services'}
  ],
  serviceHandoff:{heading:'Prepare discount evidence without releasing payment',body:'A Philippines-based AP support role can assemble the term, invoice, acceptance, dispute, and calendar evidence. An authorized company owner decides whether the discount is valid and releases funds.',href:'/services/payment-run-preparation',label:'Review payment run preparation'},
  citations:[promptPaymentSource,electronicEvidenceSource,...controlSources],
  body:[
    `A prompt-payment discount is not established merely because an invoice displays “2/10, net 30.” The operational question is whether the offer applies to the purchase, whether the discount clock started, whether the goods or services were accepted, whether a dispute paused or displaced normal processing, and whether an authorized payment can reach the supplier under the agreed method in time. This study develops a reproducible evidence method for that question. It treats the invoice term as one input rather than an instruction to accelerate payment. The output is a review packet that allows a finance owner to accept, reject, or investigate the opportunity. It does not permit a preparer to change contractual terms, waive a dispute, alter a due date, select a bank account, approve an exception, or release funds. That distinction is central for an outsourced accounts-payable lane because a seemingly helpful effort to “capture savings” can bypass purchasing, receiving, cash-management, or approval controls when the underlying dates are uncertain.`,
    `The method starts with a frozen population of invoices that contain an early-payment term, reference a contract with such a term, or were tagged by the approved system as possible discount candidates. The extract records the stable invoice key, supplier key, legal entity, purchase-order or contract reference, invoice date, system receipt timestamp, business receipt channel, acceptance evidence, dispute status, approval status, stated gross amount, proposed discount, proposed net amount, scheduled payment date, and source-system timestamps. Credit notes, rebills, partial invoices, progress billings, and invoices already included in a payment proposal remain visible. Excluding awkward records would make the apparent capture rate look better while hiding the cases most likely to need owner judgment. The cutoff and timezone are stated. Original files remain in the approved repository, and the working register points to them instead of copying sensitive attachments into ordinary email or chat.`,
    `Term reconstruction follows an explicit source hierarchy chosen by the company. A signed contract, accepted purchase order, approved supplier agreement, and invoice may not say the same thing. The preparer transcribes each term without deciding which document legally controls, records its effective date and version, and flags contradictions for the commercial owner. A handwritten invoice note or supplier email is not silently promoted to an amendment. The Federal Acquisition Regulation’s prompt-payment framework is useful primary evidence for concepts such as a proper invoice, acceptance, payment due dates, and discount periods in federal procurement. It is not a universal rule for private companies and does not rewrite their contracts. The research therefore borrows the discipline of identifying the triggering record and date, while leaving contract interpretation and policy choices to authorized owners.`,
    `Clock reconstruction is a chronology, not a single calculated field. The packet shows invoice creation, arrival at each controlled channel, successful ingestion, completeness review, receipt or service acceptance, dispute opening, corrected-document receipt, approval, proposed payment transmission, and expected settlement. Every date carries its source, timezone, and confidence. If a shared mailbox received a message on Monday but the attachment failed malware screening until Tuesday, both events remain visible. If goods arrived in stages, the packet does not assume one receipt starts the clock for every line. If a corrected invoice keeps the original invoice number, the chronology links both versions and states which one the system treats as current. Calendar calculations disclose weekends, holidays, bank cutoff assumptions, and whether “payment” means file release, bank acceptance, or supplier receipt under the governing agreement.`,
    `The calculation layer is deliberately reversible. It records the gross eligible base, excluded taxes or charges if the controlling term says so, discount rate, discount amount, net candidate amount, first possible authorized payment date, last qualifying date, and the exact expression used. Rounding follows the company’s approved currency rule and remains separate from a supplier’s displayed arithmetic. Partial payments receive their own rows because an offer may apply differently to accepted and disputed portions. A credit memo is not netted merely to make a deadline appear achievable. The preparer can reproduce arithmetic and surface anomalies, but the owner decides whether the term applies and whether liquidity, dispute posture, fraud checks, or other obligations support early payment. A calculated positive return is analysis, not authority to move cash.`,
    `A challenge set tests the method against materially different failures: an invoice received before the purchase order was issued; a valid invoice held for missing receipt evidence; a service accepted in milestones; a supplier correction that changes the amount but not the date; two invoice copies arriving through different channels; a discount expressed on the purchase order but omitted from the invoice; a credit memo linked after approval; and a payment file rejected by the bank on the last qualifying day. The method passes when another reviewer can reconstruct the same candidate window from retained sources and identify every unresolved decision. It fails when the register overwrites the first receipt timestamp, selects the most favorable term without recording conflicts, treats system approval as proof of acceptance, or labels a missed opportunity without testing whether an authorized payment could actually have settled.`,
    `Queue design should distinguish “evidence complete,” “owner decision needed,” “commercial term conflict,” “receipt or acceptance missing,” “invoice correction pending,” “approval incomplete,” “banking verification hold,” and “window expired.” Each item has one next question and one owner. A Philippines-based AP assistant may gather approved documents, enter sourced dates, reproduce arithmetic, monitor deadlines, and request missing non-sensitive evidence through verified channels. The role should not negotiate terms, confirm that a supplier’s new banking instruction is genuine, suppress a control to meet a deadline, decide acceptance, approve the invoice, or release the payment. NIST least-privilege principles support restricting system actions to the assigned preparation function. GAO’s control framework supports clear responsibility, quality information, documented control activity, and monitoring; neither source assigns business authority by itself.`,
    `Measurement must resist the seductive but weak headline “discounts captured.” Useful counts include candidates identified, candidates with a complete term source, unresolved term conflicts, missing acceptance evidence, owner decisions received before the deadline, authorized discounts taken, candidates declined, windows expired before evidence completion, and later reversals or supplier disputes. Every rate states its numerator, denominator, entity scope, currency treatment, period, and exclusions. Monetary totals separate offered, evidence-qualified, owner-authorized, paid, and finally accepted amounts. A high offered amount does not prove available savings, and a low capture rate does not prove poor AP execution; the mix may include disputed, fraudulent, cash-constrained, or contractually ineligible items. Trend comparisons are meaningful only when the population, settlement definition, and term hierarchy stay consistent.`,
    `Limitations are substantial. The source population may omit terms stored in procurement systems, side letters, portal messages, or regional contracts. Receipt timestamps can reflect forwarding rather than first arrival. Acceptance may occur outside AP, and settlement timing depends on banking rails the preparer cannot observe completely. Federal prompt-payment rules illustrate a documented framework but do not govern every reader. This method cannot establish contract enforceability, guarantee supplier acceptance, quantify the cost of capital, or prove that an earlier payment was optimal. Its defensible conclusion is narrower: a discount candidate becomes reviewable when the governing-term conflict, triggering events, eligible base, calendar assumptions, approval status, and retained owner decision can be reconstructed. The reader outcome is a decision-ready packet, not a promise of savings.`,
    `A useful operating handoff contains the candidate identifier, governing-term sources, unresolved conflicts, clock start alternatives, last qualifying date under each alternative, gross and eligible bases, arithmetic, approval state, proposed settlement path, and one named decision owner. It also records the time at which the packet was last refreshed because a late acceptance, hold, or bank cutoff can change the answer. The owner’s disposition should use a controlled reason such as authorized, contract term not established, acceptance incomplete, dispute open, liquidity decision, security hold, or window expired. Free text can explain context but should not replace the reason. Retaining declined and expired candidates is necessary for later review of the method; deleting them would turn the register into a success-only record and make process improvement unreliable.`
  ]
};

const partialReceiptAllocation:ResearchPost={
  slug:'partial-receipt-invoice-allocation-research',
  title:'Partial-receipt invoice allocation: evidence before matching',
  excerpt:'A line-level method for relating one supplier invoice to staggered receipts without inventing quantities, acceptance, or accounting outcomes.',
  published:oct2ResearchPublicationDate,modified:oct2ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-receipt-evidence-research.svg',
  keywords:['partial receipt invoice','three way match evidence','accounts payable research'],
  cta:'Define a line-level matching support scope.',
  internalLinks:[
    {label:'Three-way match support',href:'/services/three-way-match-support'},
    {label:'Purchase order reconciliation',href:'/services/purchase-order-reconciliation'},
    {label:'Invoice data capture',href:'/services/invoice-data-capture'}
  ],
  serviceHandoff:{heading:'Build a reviewable partial-receipt packet',body:'Support can align source lines and preserve gaps; company receiving, purchasing, and finance owners retain acceptance, tolerance, coding, and payment decisions.',href:'/services/three-way-match-support',label:'Review three-way match support'},
  citations:[electronicEvidenceSource,...controlSources],
  body:[
    `When one invoice covers goods received in several deliveries, a green header-level match can conceal unresolved line evidence. The invoice may combine accepted units, goods still in transit, rejected quantities, substitutions, freight, tax, or a service component that never creates a warehouse receipt. This study asks how an accounts-payable preparer can relate invoice lines to purchase-order and receiving records without manufacturing a match. The proposed output is a line-level allocation map whose links can be reproduced by a reviewer. It is not a determination that delivery occurred, a receiving correction, a tolerance override, an accounting allocation, or payment approval. The practical buyer question is whether a remote support lane can prepare this evidence safely. It can, when source identities, quantities, units, chronology, residuals, and stop conditions are explicit and when operational owners answer the exceptions.`,
    `The evidence population begins with the original invoice and every referenced order, release, receipt, return, rejection, and approved order change as of a named cutoff. For each source, the register retains its stable system key, source version, entity, supplier key, location, currency, line number, item or service description, supplier item reference, ordered quantity, unit of measure, unit price, receipt quantity, receipt status, event timestamp, and source link. The invoice image and extracted data are both preserved so an OCR value never replaces the supplier’s record. Cancelled and reversed receipts remain in the chronology. Open order balances are evidence about the system state, not proof that goods are due or that an invoice is valid. The scoped total reconciles to included plus excluded lines, and every excluded charge carries a reason and owner.`,
    `Alignment occurs in layers. First, deterministic keys such as purchase-order number, release, line, shipment notice, or receiving reference are tested exactly. Second, the preparer may compare supplier item references, descriptions, dates, locations, quantities, and units, but records the strength and ambiguity of each relation. Fuzzy text similarity never becomes an automatic match. A supplier’s “case” may equal twelve units, twenty-four units, or an undefined pack; conversion requires an approved source with an effective date. Split delivery does not justify splitting an invoice quantity proportionally merely because the totals fit. The map shows one-to-one, one-to-many, many-to-one, and unresolved relations separately. A residual column makes unallocated invoice and receipt quantities visible instead of burying them in a header variance.`,
    `Chronology is essential because the same quantity can appear valid or duplicated depending on reversals and corrections. For every candidate relation, the packet orders the purchase commitment, change order, shipment, physical or service receipt, rejection, return, receipt reversal, corrected receipt, invoice arrival, and invoice correction. A receipt entered after the invoice date is not automatically invalid; it may represent delayed system entry. Nor is it automatically acceptable. The receiving owner must explain the event. The preparer records event time and entry time when both exist, the actor or system, and the source status. If a receipt is reversed and recreated, both identifiers remain linked. This prevents a current-state report from counting only the replacement while losing evidence that a previous match or payment proposal used the reversed record.`,
    `The allocation table keeps quantity and value analyses separate. Quantity columns display the invoice unit, source unit, approved conversion, converted amount, cumulative accepted quantity, prior invoiced quantity, current proposed quantity, and remaining order balance. Value columns display unit prices, line extensions, freight, tax, discounts, and currency without forcing unlike charges onto product units. Rounding residuals are shown, not silently assigned to the final line. Service milestones use their approved acceptance evidence rather than a fictional goods quantity. If a line cannot be allocated because the purchase order is closed, the receipt location differs, or prior invoices consumed the apparent balance, the result is an exception with a bounded owner question. The analyst does not reopen the order, move a receipt, or edit the invoice to make the ledger balance.`,
    `The reproduction test includes an invoice spanning three deliveries; a receipt later reversed for damaged goods; a unit-of-measure conversion with a changed pack size; a blanket order release; freight billed once across several lines; an invoice line that references two purchase-order lines; a substitute item accepted under an approved change; a duplicate receiving entry; and a service fee with milestone evidence. A second reviewer starts from frozen sources and should reach the same allocations, residuals, and unresolved questions. Exact agreement is expected only where deterministic evidence exists. Ambiguity is a valid outcome. The method fails if reviewers can reach the same total through different undocumented line assignments, if a reversal disappears, if the current open balance is mistaken for historical availability, or if an unsupported conversion is introduced merely to clear the queue.`,
    `Control boundaries follow the evidence. An outsourced AP support role may locate approved records, transcribe source fields, create the relation map, reproduce calculations, flag duplicates, maintain residuals, and request missing receipt references. Receiving personnel confirm delivery, condition, and acceptance. Purchasing owners interpret order scope and approve changes. Finance owners decide accounting treatment, tolerances, exceptions, and payment readiness. The support role may not create or backdate a receipt, substitute an item, alter a purchase order, approve a tolerance, decide that a service milestone is complete, change coding to absorb a variance, or release a payment. Electronic receiving and payment records discussed in DFARS illustrate why linked source documents matter, but those federal rules do not impose a private company’s workflow. GAO and NIST provide control-design principles rather than transactional authority.`,
    `Metrics should describe evidence health rather than reward cleared invoices. Useful measures include scoped invoice lines, deterministically linked lines, ambiguous relations, missing receipt references, reversed-receipt cases, unsupported unit conversions, unallocated quantities, items awaiting each owner, and allocations reproduced by a second reviewer. Value measures report currencies separately unless a stated approved conversion is used. A high match percentage can be unsafe if the process uses header totals or generous fuzzy matching; a lower rate can reflect proper stopping on ambiguous evidence. Aging begins from a disclosed event—invoice receipt, exception creation, or owner assignment—and should not mix those clocks. Sampling retains complete, unresolved, and later-corrected cases so the review does not examine only successful allocations.`,
    `This method cannot observe goods that were delivered but never recorded, determine physical condition, interpret every contract, or prove that a system user had authority. Supplier descriptions may be too vague, legacy systems may overwrite receipt histories, and integrations may reuse line identifiers. Multi-currency taxes and landed costs can require specialist treatment outside the packet. Within those limits, the research supports a narrow conclusion: partial-receipt matching is defensible when every allocation is traceable to source keys and approved conversions, chronology preserves reversals, residuals remain visible, and named owners resolve acceptance and accounting questions. The reader should leave with a practical design test: if a second person cannot reproduce which receipt quantity supports each invoiced quantity, the record is not ready to be treated as a clean match.`,
    `The final review packet should be economical despite the depth of the analysis. Its cover sheet identifies the invoice, order versions, receiving locations, affected lines, currencies, total residual quantity and value, and each owner question. Behind it sits the immutable line map, conversion sources, event chronology, and links to originals. Owner responses are appended with the respondent, authority, time, and resulting approved action. A corrected receipt or purchase order never erases the source state that caused the exception. This structure gives a finance reviewer a fast route to the unresolved point while preserving enough evidence for another person to reproduce the work. It also lets managers distinguish a recurring master-data or receiving problem from a single unusual shipment instead of treating every mismatch as an AP productivity failure.`
  ]
};

const invoiceResubmissionIdentity:ResearchPost={
  slug:'invoice-resubmission-identity-research',
  title:'Invoice resubmission identity: separating copies from corrections',
  excerpt:'Research on determining whether repeated invoice arrivals are duplicates, corrected versions, or distinct claims while preserving source history.',
  published:oct2ResearchPublicationDate,modified:oct2ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-invoice-duplicate-signals-research.svg',
  keywords:['invoice resubmission','corrected invoice version','duplicate invoice evidence'],
  cta:'Create a controlled invoice-intake review.',
  internalLinks:[
    {label:'Invoice data capture',href:'/services/invoice-data-capture'},
    {label:'Duplicate invoice review',href:'/services/duplicate-invoice-review'},
    {label:'AP inbox management',href:'/services/ap-inbox-management'}
  ],
  serviceHandoff:{heading:'Keep repeated invoices visible and reviewable',body:'Support can preserve arrivals, compare versions, and route conflicts. A named company owner decides cancellation, replacement, posting, and payment treatment.',href:'/services/duplicate-invoice-review',label:'Review duplicate invoice support'},
  citations:[...controlSources],
  body:[
    `A repeated invoice attachment is not necessarily a duplicate payable, and a changed attachment is not necessarily a valid correction. Suppliers resend documents after status inquiries, mailbox failures, portal rejection, price disputes, tax corrections, or internal requests. They may retain the original invoice number, append “REV,” issue a credit and rebill, or send an identical PDF through a second channel. This research defines an identity method that preserves those possibilities until evidence supports an owner decision. The objective is a version family with a transparent chronology and field-level differences. It is not permission to delete an arrival, replace a posted document, infer supplier intent, cancel an obligation, or choose which version gets paid. For a company considering outsourced AP support, the method separates a repeatable evidence task from accounting and commercial authority.`,
    `Population design starts at intake rather than at the current payable ledger. Every arrival from approved email, portal, scan, electronic data interchange, or internal upload receives a stable intake identifier, source channel, sender or submitting account, received timestamp and timezone, original filename, file size, cryptographic content hash, malware-screen result, extraction version, and link to the retained original. The register also captures stated supplier identity, invoice number, invoice date, purchase reference, currency, amount, remit-to details, page count, and any message that accompanied the file. Failed ingestions and quarantined files remain represented without exposing unsafe content. This approach prevents the current ERP record from becoming the whole population, because an overwritten attachment or rejected upload can be precisely the missing evidence needed to explain a later duplicate signal.`,
    `Candidate families are created from several independent signals. Exact file hashes establish byte-identical copies but do not prove that only one business claim exists. Normalized invoice numbers, supplier keys, legal names, purchase references, dates, amounts, line patterns, and image fingerprints can surface near copies. Each normalization is documented and the original value remains visible. Removing punctuation from “INV-10” may help comparison; dropping meaningful prefixes across supplier entities may create false relations. A reused invoice number in a new year, a credit note sharing a base number, and two entities trading under one brand require different handling. The preparer records why documents were grouped and a confidence classification, while ungrouped but suspicious arrivals stay in an exception queue.`,
    `Within a family, the comparison is field-by-field and page-aware. The record states whether supplier identity, invoice number, date, currency, total, tax, bank details, purchase references, line quantities, prices, service periods, attachments, and terms are identical, added, removed, or changed. A changed PDF creation timestamp alone does not establish a substantive correction. Conversely, a one-digit bank-account change may be consequential even when every invoice field is identical. Visual differences are linked to source coordinates or page images when the system supports them. Extraction differences are distinguished from document differences by re-running both originals through the same approved extractor. The resulting delta explains what changed without claiming why it changed or whether the change is acceptable.`,
    `Chronology records each arrival, acknowledgement, validation failure, supplier contact, dispute, owner request, credit issuance, cancellation notice, posting, approval, payment proposal, and payment result. Messages are attributed to their actual source; an internal note that “vendor confirmed” is not equivalent to retained communication through a verified supplier channel. If an AP team asked for a corrected tax total, the packet links that request to the later file but does not assume the response supersedes every earlier version. If an invoice was already posted or paid, that state is prominent. The chronology uses append-only corrections so a mistaken grouping can be undone without erasing the earlier reasoning. This is especially important when one document entered two entity queues or two suppliers use a shared billing platform.`,
    `The challenge set includes a byte-identical resend after a status request; a PDF with only a new filename; a corrected quantity under the same invoice number; a credit-and-rebill pair; a document with changed beneficiary details; two legal entities using the same invoice sequence; an OCR extraction that drops a decimal; a portal rejection followed by email submission; and a previously paid invoice resent with a new purchase-order reference. A second reviewer should reproduce exact-copy findings and material deltas from the frozen evidence. The test passes when ambiguous business identity remains ambiguous and is routed with a specific question. It fails when a hash match is called fraud, when the latest file silently replaces the original, when supplier-name similarity overrides legal-entity evidence, or when changed payment instructions travel in the ordinary correction path.`,
    `Operational states need plain meanings. “Exact copy” means the retained bytes match. “Near copy” means specified content signals match within a disclosed rule. “Corrected candidate” means a later source contains a material change and a possible relation; it does not mean the supplier or company approved replacement. “Distinct claim” is an owner disposition supported by recorded reasoning. “Suppressed” describes queue behavior, not deletion. A support specialist may capture arrivals, compute hashes, compare fields, link correspondence, flag risky changes, and prepare the family. The specialist may not decide supplier intent, accept altered banking, void or post an invoice, change a legal entity, remove an audit record, approve an exception, or release payment. Sensitive changes leave the ordinary queue for independent verification.`,
    `Quality measures include total arrivals, byte-identical resends, near-copy candidates, families with material deltas, banking or identity changes, cross-entity collisions, unlinked corrections, items already posted or paid, owner dispositions, and second-review agreement. Counts distinguish files, arrivals, families, and business claims; treating them as interchangeable produces misleading duplicate rates. Time measures state whether they begin at first arrival, family creation, or owner assignment. A falling duplicate count might reflect a narrower search, not better supplier behavior. A rising correction count may follow improved capture rather than worse quality. Review samples include false positives, false negatives discovered later, paid cases, and complex families. GAO’s emphasis on quality information and monitoring supports this transparent design, while NIST integrity, audit, and least-privilege concepts support preserved originals and bounded actions.`,
    `Limitations prevent overclaiming. Content hashes do not identify business meaning; OCR and image comparison can miss or invent differences; email sender fields can be spoofed; portals can transform files; and a supplier’s correction practice may be governed by contract, tax law, or jurisdiction-specific rules outside this study. The method cannot prove fraud, establish an enforceable cancellation, or determine which liability belongs in the accounts. Its supported conclusion is operational: repeated invoice arrivals become safer to review when each original remains intact, similarity rules are explicit, material field changes are visible, chronology connects requests and responses, high-risk changes follow an independent route, and an authorized owner records the final disposition. The reader outcome is a durable version family that explains why an item stopped or proceeded.`,
    `Disposition design closes the loop. The company should define who may label an arrival informational, exact resend, supplier correction accepted, credit-and-rebill linked, distinct invoice, suspected duplicate stopped, or unresolved. The record captures the decision, rationale, supporting source, affected ERP document, and any follow-up verification. If the chosen version is posted, the family links to that posting while the rejected versions remain retained under policy. If the family was grouped incorrectly, a logged split restores separate records without changing their original intake identities. A later supplier dispute reopens the evidence question without rewriting the prior decision. This disciplined ending matters because most harm does not arise from finding two similar files; it arises when an unexplained suppression, replacement, or second posting is no longer traceable to the person and evidence behind it.`
  ]
};

const unappliedPayment:ResearchPost={
  slug:'supplier-statement-unapplied-payment-research',
  title:'Unapplied supplier-statement payments: a reconstruction method',
  excerpt:'A source-led approach to tracing statement payments that do not clearly map to company invoices, credits, entities, or remittance records.',
  published:oct2ResearchPublicationDate,modified:oct2ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-vendor-statement-reconciliation-research.svg',
  keywords:['unapplied supplier payment','vendor statement reconciliation','remittance evidence'],
  cta:'Structure a statement-reconciliation support lane.',
  internalLinks:[
    {label:'Vendor statement reconciliation',href:'/services/vendor-statement-reconciliation'},
    {label:'Payment run preparation',href:'/services/payment-run-preparation'},
    {label:'AP inbox management',href:'/services/ap-inbox-management'}
  ],
  serviceHandoff:{heading:'Reconstruct unapplied items without rewriting ledgers',body:'Support can gather statement, remittance, payment, invoice, and credit evidence. Company treasury, accounting, and supplier owners decide allocation, correction, recovery, and posting.',href:'/services/vendor-statement-reconciliation',label:'Review statement reconciliation'},
  citations:[promptPaymentSource,...controlSources],
  body:[
    `A supplier statement may show a payment as unapplied even when the buyer’s ledger shows the payment completed and the related invoices closed. The difference can arise from missing remittance advice, a combined payment, a short pay, withholding, bank fees, value-date timing, a payment sent under another legal entity, an incorrect supplier account, a reversed transaction, or the supplier’s own posting delay. This research asks how AP support can reconstruct the disagreement without declaring either ledger correct. The output is a two-sided evidence map and a bounded question for the proper owner. It is not authority to tell a supplier how to allocate cash, reopen an invoice, move balances between entities, post a credit, initiate a recovery, or release a replacement payment. That boundary protects against turning a reconciliation task into an unreviewed accounting or treasury action.`,
    `The population is defined from statement lines, not only from buyer exceptions. Each supplier-statement payment or unapplied-cash entry within the stated period receives the supplier account, statement date, statement currency, displayed reference, amount, value date, status, and link to the original statement. The buyer side includes payment proposal, payment instruction, bank acceptance or rejection, settlement reference, amount, currency, company entity, supplier master key, remittance record, included invoices and credits, and later reversals. Invoices missing from one side remain explicit. Opening balances are separated from period activity. The register states cutoff, timezone, entities, bank accounts, supplier accounts, and excluded transactions. Originals stay in controlled systems, and the working map avoids exposing full bank details or sensitive payment files.`,
    `Reconstruction begins with exact identifiers: bank trace, end-to-end payment reference, remittance identifier, supplier account, payment amount, and currency. Secondary evidence includes value date, invoice set, credit set, deduction amount, payer name, and message history. A same-amount same-day observation is a candidate, not a match. One buyer payment may cover many supplier invoices; one supplier receipt may represent netted payments from several company entities; and a bank can aggregate or split records. The analyst states each relation as one-to-one, one-to-many, many-to-one, or unresolved and records which evidence supports it. Currency conversion is never inferred solely because converted totals appear close. When a supplier statement omits remittance references, that absence becomes the next evidence request rather than an excuse to force allocation.`,
    `A chronology distinguishes instruction, bank processing, settlement, remittance transmission, supplier receipt, supplier posting, statement issuance, inquiry, reversal, and correction. The date a payment left the buyer’s bank is not necessarily the date the supplier could identify it. Likewise, a statement generated before remittance processing may legitimately display an item later resolved. The packet retains timestamps, timezone, source system, and status at each event. A payment marked successful in the ERP but rejected downstream is not treated as settled. If a payment was recalled or returned, the original and reversing events remain linked. The preparer may ask the bank or treasury owner for a trace through approved channels, but does not claim access to evidence that was unavailable.`,
    `The difference table reconciles four quantities independently: cash instructed, cash settled, remittance described, and supplier-applied amount. For each candidate relation it shows invoices, credits, deductions, taxes withheld, fees, foreign exchange, and residuals without choosing an accounting treatment. A residual can be real, timing-related, or the result of an incomplete population. The table cross-foot checks totals within each currency and identifies any conversion source used for presentation. It never nets balances across company entities simply because the supplier does so on a statement. If an unapplied amount equals several possible invoice combinations, all credible combinations remain visible until the supplier or accountable company owner supplies distinguishing evidence.`,
    `Challenge cases include a bulk payment lacking remittance; a supplier account shared by two buyer entities; an amount reduced by withholding; a bank fee deducted in transit; a credit memo omitted from the remittance; a rejected file still marked paid in the ERP; a returned payment followed by a reissue; a supplier that posted cash after statement cutoff; and two identical payments on consecutive days. A second reviewer should reproduce confirmed identifiers, cross-foots, chronology, and residuals. The method passes when it narrows each disagreement to a specific missing source or owner decision. It fails when amount-and-date proximity is presented as proof, when one entity’s credit is moved to another without authority, when a later clean statement causes the earlier discrepancy record to be deleted, or when a replacement payment is proposed before settlement status is established.`,
    `The queue should separate “trace needed,” “remittance missing,” “supplier account mismatch,” “entity conflict,” “deduction or withholding question,” “return or reversal,” “supplier posting pending,” and “owner disposition required.” Every state has a named next owner and a due date that describes follow-up, not a promise of resolution. An outsourced AP specialist may obtain approved statements, gather remittance and invoice evidence, maintain the map, draft a factual supplier inquiry, and record responses. The role may not direct cash application, change the vendor master, disclose protected banking data, admit liability, approve a write-off, post a journal entry, initiate recovery, or issue replacement payment. Treasury confirms settlement; accounting decides treatment; procurement or relationship owners address commercial deductions; payment release stays with authorized company staff.`,
    `Measures distinguish identification from resolution. Useful counts include scoped statement entries, entries with exact payment traces, entries linked only by secondary evidence, missing remittances, cross-entity conflicts, currency or deduction questions, returned items, supplier-confirmed applications, owner-approved corrections, and unexplained residuals. Aging states its start event and pauses only under a disclosed rule. Monetary totals remain by currency, entity, and evidence status. A high unresolved value can be concentrated in one recent bulk payment; a low value can hide many recurring process failures. Neither the supplier statement nor buyer ledger is used as the denominator of “accuracy” without independent evidence. Samples include resolved and unresolved items, later reversals, and supplier disagreements so monitoring tests the method rather than only the clean outcomes.`,
    `This study cannot see the supplier’s internal subledger, bank data outside granted access, private contracts, or all jurisdiction-specific withholding rules. Supplier statements may be incomplete, payment messages truncated, and bank timestamps inconsistent. Federal prompt-payment material offers useful distinctions around invoice and payment timing but does not decide private cash application. GAO and NIST support documented, limited, reviewable processes; they do not settle a balance. The defensible conclusion is therefore modest: an unapplied payment becomes decision-ready when cash movement, remittance content, invoice and credit composition, entity, currency, timing, and residual uncertainty are shown side by side, and when a named owner records the disposition. The reader outcome is evidence sufficient to ask the right party the smallest unresolved question, without rewriting either ledger to make it disappear.`,
    `A closure record should state the supplier account, buyer entity, currencies, payment and statement identifiers, confirmed settlement evidence, remittance evidence, invoice and credit composition, residual before and after the decision, approving owner, action taken, and verification source. Possible outcomes stay distinct: supplier posted as instructed, supplier applied differently with owner acceptance, buyer remittance corrected, bank trace disproved settlement, payment returned, accounting correction approved, recovery opened, or difference left unresolved with a next review date. The preparer records the outcome but does not invent one to meet an aging target. When the next statement arrives, it is tested against the retained closure rather than assumed to confirm it. This turns supplier-statement reconciliation into a controlled feedback loop and exposes recurring failures in remittance delivery, entity mapping, payment references, or supplier-account maintenance.`
  ]
};

const poCancellationChronology:ResearchPost={
  slug:'purchase-order-cancellation-invoice-chronology-research',
  title:'Purchase-order cancellation after invoicing: chronology research',
  excerpt:'Research on reconstructing orders, commitments, receipts, cancellations, invoices, and credits before deciding what an AP item means.',
  published:oct2ResearchPublicationDate,modified:oct2ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-purchase-order-reconciliation-research.svg',
  keywords:['cancelled purchase order invoice','purchase order chronology','AP exception research'],
  cta:'Define a purchase-order reconciliation lane.',
  internalLinks:[
    {label:'Purchase order reconciliation',href:'/services/purchase-order-reconciliation'},
    {label:'Three-way match support',href:'/services/three-way-match-support'},
    {label:'AP inbox management',href:'/services/ap-inbox-management'}
  ],
  serviceHandoff:{heading:'Reconstruct the event sequence before clearing the exception',body:'Support can assemble order versions, receipts, correspondence, invoice, and credit evidence. Purchasing, receiving, legal, and finance owners retain commitment, acceptance, accounting, and payment decisions.',href:'/services/purchase-order-reconciliation',label:'Review purchase order reconciliation'},
  citations:[electronicEvidenceSource,...controlSources],
  body:[
    `An invoice referencing a cancelled purchase order is often routed as a simple mismatch, yet “cancelled” describes a current system state rather than the history of the commitment. Goods may have shipped before cancellation, services may have been performed, a line may have been partially received, the supplier may never have accepted a change, or the order may have been administratively closed after a replacement was issued. This study provides a chronology method for preparing that exception. The output is a source-linked event record and a set of unresolved owner questions. It is not a legal conclusion about obligation, permission to reopen or recreate an order, acceptance of goods or services, approval of a non-PO payment, accounting direction, or payment authorization. The method is designed for buyers deciding which evidence tasks can safely sit with outsourced AP support.`,
    `The population includes every invoice line tied directly or indirectly to an order or release that is now cancelled, closed, superseded, or unavailable in the processing system. Source collection covers the original requisition, approvals, all purchase-order versions, supplier transmission and acknowledgement, change orders, cancellation request and effective record, shipment or service evidence, receipts and reversals, returns, invoice arrivals, disputes, credits, replacement orders, and current ledger status. Each source keeps a stable key, version, actor or system, event timestamp, entry timestamp when different, entity, supplier, currency, line, quantity, value, and source link. Missing versions are named as gaps. A report of the current order is never presented as the historical record if the platform can supply an audit trail or archived document.`,
    `Chronology is built from evidence events rather than a narrative written from memory. The register distinguishes request, approval, transmission, supplier acknowledgement, performance, shipment, physical receipt, service acceptance, cancellation decision, system status change, invoice receipt, credit, and payment activity. Effective time and recorded time remain separate. An order cancelled in the system on Friday may reflect a decision made Tuesday, while a supplier shipment on Wednesday raises a different question depending on notice and terms. The analyst does not decide that question; the timeline makes it reviewable. Conflicting timestamps retain their sources and confidence. Email headers, portal logs, audit history, and signed documents carry different evidentiary weight under company policy, and a meeting recollection is labeled as such.`,
    `Line analysis prevents a header cancellation from flattening mixed outcomes. Each ordered line shows original and amended quantities, price, required date, cancellation status, shipped quantity, accepted receipt, rejected or returned quantity, invoiced amount, credited amount, and unresolved residual. A line cancelled before any activity differs from a line partially fulfilled and then reduced. Blanket order releases, substitutions, milestones, and freight receive their own evidence paths. The packet links a replacement purchase order without assuming that it transfers every prior obligation. It also shows whether prior invoices consumed quantity or value. Arithmetic is reproduced, but unsupported allocations are not introduced just to fit the invoice to an open balance. Every unresolved difference becomes a specific question for purchasing, receiving, the business owner, or finance.`,
    `Communication evidence is organized by decision, not dumped as an email chain. The preparer identifies the message that transmitted the order, any acknowledgement, the request to cancel, proof of its delivery, supplier response, shipment notice, return instruction, dispute, and credit commitment. Sender identity and channel are preserved. A buyer’s internal cancellation approval does not prove supplier notice; a supplier salesperson’s “okay” may not meet the company’s contractual standard; and an automated portal status may not establish that a human reviewed the change. The record therefore distinguishes observed fact from inference. Sensitive or privileged correspondence is referenced only within approved access boundaries and routed to the responsible legal or commercial owner rather than copied into the AP work queue.`,
    `A rigorous challenge set includes cancellation before supplier acknowledgement; goods shipped between request and confirmed cancellation; partial receipt with the remaining order cancelled; service performed before the system order existed; a replacement order with overlapping lines; a receipt reversed after a return; a cancellation entered against the wrong entity; an invoice received after a supplier promised credit; and a system migration that lost the original order version. A second reviewer reconstructs the event order and line residuals from frozen sources. The method passes when both reviewers can identify which facts are established, which conflict, and who must decide next. It fails when the current “cancelled” flag is treated as proof that nothing is owed, when a receipt is treated as contractual acceptance without the owner, or when a replacement order is backfilled to bypass approval.`,
    `The support boundary is precise. An outsourced AP specialist may retrieve approved sources, index order versions, assemble timestamps, compare line quantities and values, preserve correspondence, maintain the exception, and request a missing source from a named owner. The specialist may not reopen, recreate, or backdate a purchase order; instruct a supplier to ship or stop work; confirm legal cancellation; create a receipt; accept goods or services; choose a non-PO override; decide a provision or accrual; negotiate a settlement; approve the invoice; or release payment. Purchasing owns commitment and supplier communication under company policy. Receiving or the service owner confirms performance. Finance decides accounting and payment treatment. Legal review is escalated when contractual interpretation exceeds the written operating rule.`,
    `Queue states should expose the actual uncertainty: “order version missing,” “supplier notice unconfirmed,” “shipment timing question,” “receipt or acceptance unresolved,” “partial cancellation allocation,” “replacement-order overlap,” “credit promised,” “credit received,” and “owner disposition recorded.” Closure requires retained evidence of the disposition and any approved system changes, not merely movement of the invoice out of the exception list. Metrics include scoped cases, complete order histories, notice gaps, pre-cancellation activity, partial-fulfillment cases, replacement-order conflicts, expected credits, owner decisions, repeated exceptions by root cause, and second-review reproducibility. Monetary totals remain by entity and currency. A low open count can reflect premature clearing, while a high count can reflect transparent discovery. Measures therefore pair volume with evidence completeness and later rework.`,
    `The method has unavoidable limits. Systems may overwrite versions, supplier acknowledgements may be informal, physical activity may lack timestamps, and contracts may define cancellation, acceptance, or termination differently. Access to legal advice, logistics platforms, or supplier records may be restricted. Electronic receiving requirements in federal acquisition guidance illustrate the value of connected records but do not govern every private purchase. GAO’s control principles and NIST’s access and audit concepts support a documented, bounded process; they do not determine liability. Within these limits, the supported conclusion is that a cancelled-order invoice should be treated as a chronology problem before it is treated as a coding problem. A decision-ready file shows the commitment, communication, performance, cancellation, invoice, credit, and residual evidence without filling gaps through assumption. That is the useful outcome for the finance owner.`,
    `Closure should connect the owner’s decision to the system result without letting the system result stand in for the decision. The record names whether the invoice was rejected, held, credited, matched to an approved replacement, processed under an authorized exception, or left open; it links the supporting approval and the actor who executed each permitted change. Subsequent receipt, credit, or supplier dispute events are appended. Root-cause coding remains factual: late cancellation entry, notice gap, shipment timing conflict, order-version loss, incorrect entity, replacement overlap, or another evidenced cause. Managers can then decide whether procurement practice, receiving discipline, supplier communication, system configuration, or AP intake needs attention. The support team supplies the reconstructable record; accountable company leaders decide the process correction and any commercial response.`
  ]
};

export const oct2ResearchBatch:ResearchPost[]=[
  discountEligibility,
  partialReceiptAllocation,
  invoiceResubmissionIdentity,
  unappliedPayment,
  poCancellationChronology
];
