import type {ResearchPost} from './research-batch';
const date='2026-08-23';
const links=[{label:'AP services',href:'/services'},{label:'AP inbox management',href:'/services/ap-inbox-management'},{label:'Research library',href:'/research'}];
const gao={label:'GAO: Green Book Internal Control Standards',href:'https://www.gao.gov/greenbook'};
const nist={label:'NIST: Least Privilege Glossary',href:'https://csrc.nist.gov/glossary/term/least_privilege'};
const cisa={label:'CISA: Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'};
const sba={label:'SBA: Manage Your Business Finances',href:'https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances'};
const irs={label:'IRS: About Form W-9',href:'https://www.irs.gov/forms-pubs/about-form-w-9'};
type Seed={slug:string;title:string;excerpt:string;citations:{label:string;href:string}[];body:string[];thumbnail:string};
const seed=(x:Seed):ResearchPost=>({...x,published:date,modified:date,keywords:['accounts payable outsourcing','AP research','finance operations'],internalLinks:links,cta:'Use this research to define a controlled AP support lane.'});
const common=(question:string,topic:string,method:string,findings:string[],test:string,limits:string,conclusion:string)=>[
`Research question: ${question} This matters in outsourced accounts-payable support because ${topic} can look complete while hiding a missing source, an unresolved exception, or a decision that belongs to an employee owner. The question is about reviewability, not about transferring approval or payment authority.`,
`Methodology and evidence scope: ${method} The cited sources support control principles and record discipline; they do not provide a market benchmark, guaranteed result, staffing ratio, or universal accounting answer. The analysis below distinguishes those sourced principles from workflow recommendations.`,
...findings,
`Evidence classification: Facts should remain tied to a source field, document, timestamp, or recorded response. Analysis explains how those facts relate to the research question. A recommendation describes a safer next step for the workflow. Keeping these layers separate prevents an AP support note from presenting a judgment as though it came from an invoice or an external authority.`,
`Role and access boundary: A Philippines-based AP specialist can organize records, compare fields, request missing evidence, draft a factual follow-up, and route a stopped item. The specialist should not approve spend, change vendor master data, decide tax or accounting treatment, promise payment, or release funds unless the organization has separately authorized and controlled that action. Least privilege should be reviewed when the queue, entity, system, or responsibility changes.`,
`Operational implication: The smallest useful handoff names the population reviewed, the source records checked, the exact observation, the unresolved decision, the next owner, and the next review date. A queue label alone is not a handoff. If the source is unavailable, say so; if a reply conflicts with the record, preserve both; if the item is ordinary, retain the same minimum evidence so the process remains consistent across shifts.`,
`What this does not prove: A complete preparation packet does not prove an invoice is payable, a supplier is trustworthy, a term is contractual, a tax treatment is correct, or a payment should be released. Those conclusions belong to the organization’s policy owners. Research is useful here because it exposes the information needed for their decision without pretending to make it.`,
`Implementation detail: Keep the source document linked rather than copying sensitive content into a broad chat or personal spreadsheet. Give the queue a stable identifier, retain the received and reviewed dates, and record corrections without erasing the earlier value. A manager should be able to inspect a stopped item during the next review window and understand whether the blocker is missing evidence, conflicting evidence, or a decision waiting on an owner. This is particularly important when work crosses schedules and the person receiving the handoff is not the person who prepared the comparison.`,
`Decision ownership: The support lane can make a decision easier by narrowing the question and presenting the relevant records in order. It cannot make the question disappear by choosing a default, sending an unsupported assurance, or treating silence as approval. When the owner gives a disposition, retain the disposition with the source and distinguish the owner’s conclusion from the preparer’s earlier observation. That distinction supports later quality review without turning quality review into a second, undocumented approval.`,
`Research test: ${test} Record the population, source fields, reviewer disagreements, and owner disposition. Measure whether another reviewer can reproduce the preparation and find the evidence, not whether every item receives a convenient status. Keep the original records and do not test the process by editing production data or releasing a payment.`,
`Limitations: ${limits} This report does not provide legal, tax, accounting, fraud, or contractual advice. A support packet can make a question smaller and clearer, but it cannot establish a conclusion that the organization’s authorized owner has not made.`,
`Evidence-led conclusion: ${conclusion} For outsourced AP support, the useful result is a traceable preparation record, an explicit stop condition, and a named next decision owner.`
];
export const aug23ResearchBatch:ResearchPost[]=[
seed({slug:'ap-invoice-approval-evidence-chain-research',title:'What evidence chain lets an AP approval survive review?',excerpt:'A bounded study of the records that connect invoice intake, review, approval, and payment preparation in outsourced accounts payable.',citations:[gao,nist,cisa],thumbnail:'/research-thumbnails/ap-invoice-approval-evidence-chain-research.svg',body:common('What evidence chain lets a finance reviewer reconstruct an AP approval without relying on memory or an unverified message?','an approval event can be mistaken for a complete approval record','This qualitative desk study maps GAO internal-control standards, NIST least-privilege guidance, and CISA phishing guidance to one invoice packet: source invoice, intake record, prepared fields, matching evidence, approval event, exception history, and payment handoff.',[
'An approval button or email reply shows that someone acted, but a later reviewer also needs invoice identity, legal entity, amount, supporting records, and the rule under which the item was routed. GAO’s emphasis on documented control activities supports preserving the prepared comparison rather than treating final status as the whole record.',
'NIST’s least-privilege principle keeps the boundary visible. A support specialist can collect the invoice, compare purchase-order and receipt fields, identify missing approval evidence, and route a factual question. The specialist should not approve the invoice, alter vendor banking data, override a mismatch, or release payment because the packet appears complete. The employee owner’s approval remains a separate event with identity and timestamp.',
'CISA’s independent-verification guidance matters when a message asks for sensitive changes or uses urgency. A bank-detail request must not become evidence of its own authorization. Retain the request, record the stop condition, and show the independent verification or owner disposition. A missing callback is a control gap, not proof that a vendor acted improperly.',
'A useful packet therefore has chronology: receipt, preparation, questions, responses, approval, and payment-run handoff. Each entry should identify the source and person responsible. “Approved” without the underlying evidence forces the next reviewer to reconstruct the decision from private mail or memory, which is exactly the failure this research question tests.'
],'Use one controlled queue containing ordinary, incomplete, and suspicious invoices. Ask a second reviewer to locate the source, identify what the preparer checked, name the unresolved decision, and find the approval record without private explanation.','Systems may overwrite versions, vendors may resend attachments, and time zones can alter apparent chronology. The study does not test a platform, retention rule, accounting treatment, fraud conclusion, or payment authorization.','The most defensible AP approval record is a chain, not a status label. Preserve source identity, preparation checks, exception history, independent verification where needed, and employee approval as distinct evidence.')}),
seed({slug:'ap-vendor-statement-reconciliation-evidence-research',title:'When does a vendor statement match become evidence?',excerpt:'Research on separating statement lines, ledger records, credits, timing differences, and owner decisions in outsourced AP reconciliation.',citations:[gao,sba],thumbnail:'/research-thumbnails/ap-vendor-statement-reconciliation-evidence-research.svg',body:common('When does a vendor-statement match provide enough evidence for an AP reviewer to close an open item?','a near match can hide a missing invoice, unapplied credit, duplicate payment, or timing difference','The study compares a supplier statement, invoice register, payment report, credit-memo record, and follow-up correspondence, using GAO control principles and SBA financial-record guidance. The unit is a dated statement line, classified as matched, missing, or ambiguous. A Treasury context source is not needed to claim a reconciliation result, so the report does not use market statistics.',[
'A statement is evidence of what the supplier lists for its stated period; it is not automatic evidence that every listed amount is owed. Preserve statement date, period, page, currency, line reference, and retrieval date separately. Compare each line with internal records using supplier, document number, amount, date, currency, and source location.',
'Use explicit states that lead to different actions: matched invoice, missing internal invoice, missing supplier credit, timing difference, disputed line, duplicate candidate, and owner review. Support can transcribe, link, compare, request a missing document, and carry forward an unresolved line. Finance decides write-off, dispute settlement, credit application, posting, and acceptable differences.',
'Chronology matters in remote AP work. Keep the original statement period and each follow-up date. A later supplier reply may explain a line without changing what the earlier statement showed. Replacing the old note with “resolved” loses evidence. The history should state source checked, factual result, missing evidence, next question, owner, and review date.',
'A concise open-item index improves handoff when it carries forward unresolved lines with their original statement date. Aging should not erase the first evidence, and a matched amount should not conceal a missing credit. The preparation record should report what was compared, not claim that the vendor balance is settled.'
],'Select one statement containing ordinary invoices, a credit, a payment near the period boundary, and an incomplete identifier. Ask an independent reviewer to reproduce proposed matches from controlled sources and count only measured results from the declared population.','Supplier statements differ in layout and completeness; ERP posting dates vary; credits may be negotiated outside the invoice file; and policy may define acceptable differences. The report does not set materiality, a retention period, or a balance decision.','A vendor-statement match becomes useful evidence when the relationship is reproducible from dated source records and remaining uncertainty is explicit. Keep statement facts, internal comparisons, and finance decisions distinct.')}),
seed({slug:'ap-payment-terms-conflict-research',title:'Which AP payment term should a reviewer trust?',excerpt:'A source-led study of conflicting invoice, purchase-order, vendor-master, and agreement terms before an outsourced AP payment run.',citations:[gao,nist,sba],thumbnail:'/research-thumbnails/ap-payment-terms-conflict-research.svg',body:common('Which payment-term field should an AP reviewer trust when invoice, purchase order, vendor master, and agreement records disagree?','a preparer may select the date that keeps a queue moving','The method maps invoice, purchase order, vendor master, and approved agreement records to a review packet. GAO supports documented information, NIST supports restricting edits and decision authority, and SBA provides financial-record context. No cited source supplies a priority order for every organization; preserve each value, source owner, effective date, and calculation basis instead.',[
'A printed due date is not the same as a payment term. A date may be calculated from invoice receipt, service acceptance, statement date, or a contract rule. Record exact wording and the source date. If an invoice says net 30 while the purchase order differs, keep both values visible and do not silently overwrite master data.',
'The newest source is not automatically the authoritative source. A record may be newer but unauthorized, or authorized but unrelated to the entity and purchase. Identify supplier, legal entity, invoice, purchase order, agreement, currency, source date, and owner. Support flags early-payment language, missing terms, unusual urgency, or conflicts; finance or procurement decides which approved rule applies.',
'Stop when terms conflict, the due date depends on unclear acceptance, a request asks for accelerated payment, or someone asks the preparer to edit master data without an approved change record. The next action should name missing evidence and owner, not merely say “hold.” Keep the item in a controlled exception queue.',
'A term discrepancy is an AP control question, not a processing inconvenience. Recording both source values protects the payment-run reviewer from an undocumented default and makes later master-data changes attributable to the right employee.'
],'Test ordinary terms, a conflict, a missing purchase order, and an urgent request. Have two reviewers record source values and the decision question independently, then compare whether they preserve the same fields and stop in the same cases.','Terms can depend on contracts, jurisdiction, acceptance records, credit arrangements, and policy changes outside the queue. The report does not provide legal advice, calculate interest, or recommend a payment calendar.','The trustworthy AP payment-term record preserves conflicting evidence and routes interpretation to the right owner. Outsourced support improves control by making the discrepancy reviewable, not by selecting a convenient date.')}),
seed({slug:'ap-invoice-entity-routing-evidence-research',title:'Can AP intake evidence identify the right legal entity?',excerpt:'A bounded study of entity clues in invoices, purchase orders, tax records, and inbox routes for distributed AP support.',citations:[gao,irs,nist],thumbnail:'/research-thumbnails/ap-invoice-entity-routing-evidence-research.svg',body:common('Can an AP intake packet identify the responsible legal entity without relying on vendor familiarity or a prior invoice?','one inbox or portal may receive documents for several entities','The method compares legal name, billing address, tax identifier, purchase-order entity, contract reference, receiving record, and intake channel. GAO supports documenting decision information, IRS Form W-9 material shows why taxpayer-identification data needs controlled handling, and NIST supports least-privilege access. The method is a field comparison, not an entity-assignment algorithm.',[
'Entity clues can disagree for legitimate reasons. A supplier may use a shared billing address, a parent may appear on correspondence, or a purchase order may name a subsidiary. Preserve exact values and source locations. Mark missing separately from conflicting because they ask different questions of the owner.',
'A preparer can collect a requested tax form, identify missing fields, compare a document with the approved request, and link the controlled source. The preparer should not infer tax treatment, accept a taxpayer identifier, create a vendor, or change the accounting entity without the authorized process.',
'A route packet should include invoice identity, supplier, stated bill-to, purchase-order entity, service or receipt location where relevant, tax-document reference, inbox source, exact conflict, next owner, and evidence needed. “Wrong entity” is conclusory; “invoice names X while purchase order names Y” is reviewable.',
'Stopping an unsupported assignment before approval is the key control. A support role can route the question and preserve a rejected or redirected attempt, while finance, procurement, or tax confirms the entity decision and any resulting master-data action.'
],'Sample clean invoices, shared-address invoices, cross-entity purchase orders, and documents with missing tax fields. Ask another reviewer to identify the evidence and explain why each item is routed or stopped, recording disagreement by field.','Entity structures, registrations, contracts, and receiving arrangements vary. The study does not determine liability, tax treatment, intercompany accounting, or vendor-master correctness. Sensitive identifiers belong in approved systems.','AP intake evidence can make entity routing reviewable, but it cannot turn ambiguous clues into authority. Capture conflicts, preserve documents, and route the question to the responsible owner.')}),
seed({slug:'ap-duplicate-invoice-signal-research',title:'Which signals make an AP duplicate candidate worth review?',excerpt:'Research on combining invoice identifiers, amounts, dates, attachments, and supplier context without treating a candidate as a confirmed duplicate.',citations:[gao,nist,sba],thumbnail:'/research-thumbnails/ap-duplicate-invoice-signal-research.svg',body:common('Which combination of AP invoice signals makes a duplicate candidate worth a human review?','a matching invoice number or amount is not proof that two obligations are the same','The proposed comparison uses supplier, legal entity, invoice number, invoice date, service period, currency, amount, purchase order, attachment content, and source channel as separate signals. GAO informs traceable review, NIST informs access and approval boundaries, and SBA provides records context. The sources do not establish a detection rate or matching threshold.',[
'Several independent signals can warrant a side-by-side packet: same supplier, number, amount, and purchase order. The same amount with a different service period may be a recurring charge. A replacement invoice may keep the number while correcting a tax field. Preserve both documents and describe differences rather than deleting the apparent copy.',
'Context changes interpretation. Shared invoice numbers across entities may be normal; recurring invoices may repeat amounts; credits and corrected documents can resemble originals; and an attachment filename may be copied without the same content. Entity and service-period fields often distinguish a true repeat from a legitimate recurrence.',
'Support can search a defined period, prepare a comparison, link sources, identify a resubmission, and place a candidate in an exception queue. It cannot reject an invoice, accuse a supplier, remove a hold, merge records, or approve payment based on a flag. The owner decides disposition from the original documents.',
'A candidate comparison should state what the signals show and what they do not show. That distinction prevents an operational label from becoming an unsupported fraud allegation or an automatic payment stop. A documented question is a valid research result when evidence is incomplete.'
],'Create a dated sample of non-duplicates, legitimate corrections, recurring invoices, and unresolved pairs. Ask two reviewers to identify candidates using the same search fields and compare explanations and false alarms. Record search window and excluded sources.','The study does not use a live population, evaluate OCR, set fraud thresholds, or determine retention. Procurement, receiving, tax, legal, or supplier-owner context may be unavailable to AP support. No flag establishes intent.','Duplicate review is strongest when it exposes independent signals, preserves both sources, and states the unresolved decision. Test legitimate repeats as well as suspicious pairs and let the authorized owner decide.')})
];
