type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-09-01';
const links=[{label:'Daily AP queue reconciliation routine',href:'/blog/ap-daily-queue-reconciliation-routine'},{label:'Payment batch readiness checklist',href:'/blog/ap-payment-batch-readiness-checklist'},{label:'Invoice rejection reason register',href:'/blog/ap-invoice-rejection-reason-register'}];
const serviceHandoff={heading:'Turn the evidence model into a bounded AP role',body:'Define source records, preparation steps, exception states, review timing, and retained employee decisions before granting system access.',href:'/contact-us',label:'Scope an AP support role'};
const sources={nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},gao:{label:'GAO Green Book',href:'https://www.gao.gov/greenbook'},cisa:{label:'CISA: Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'},fbi:{label:'FBI: Business Email Compromise',href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'},coso:{label:'COSO Internal Control resources',href:'https://www.coso.org/internal-control'}};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,evidence:string,boundary:string,test:string,citations:Post['citations']):Post=>({slug,title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks:links,serviceHandoff,body:[
`This review examines ${question}. It translates public control guidance into an accounts payable operating model; it does not claim a universal benchmark, legal conclusion, or guaranteed result. The method compares guidance on evidence quality, attributable action, access, and review.`,
`The relevant evidence set is ${evidence}. Each item needs a stable source reference and timestamp so a later reviewer can distinguish original records, operator observations, supplier responses, and company decisions.`,
`The strongest planning signal is reproducibility across systems and people. A count or status label is useful only when a reviewer can identify its population, cutoff, exclusions, checks, conflicts, current owner, and required response.`,
`For an outsourced AP model, ${boundary}. Approval, accounting judgment, master-data authority, and payment release remain separate, attributable events performed by authorized company employees.`,
`A practical control test should ${test}. Run the test with ordinary, incomplete, conflicting, and urgent cases; preserve both the initial evidence and subsequent corrections instead of overwriting history.`,
`The synthesis supports a bounded preparation role with least-privilege access, retained sources, explicit exception states, and scheduled owner review. Each organization must set its own approval, retention, materiality, and access rules.`,
]});
export const sep1ResearchBatch:Post[]=[
make('ap-cross-system-queue-reconciliation-research','Cross-system AP queue reconciliation: an evidence review','Research on population cutoffs, stable identifiers, and exception ownership when invoices move across AP systems.','/research-thumbnails/ap-inbox-triage-research.svg','how teams can detect invoices lost or duplicated between inbox, workflow, and ledger populations','named system extracts, extraction times, stable invoice references, inclusion rules, state comparisons, differences, owners, and resolution evidence','support may extract approved reports, match stable fields, document differences, and maintain an exception queue','prove that a received invoice, a duplicate reference, and a deliberately omitted workflow item each produce an explainable result',[sources.gao,sources.nist,sources.coso]),
make('ap-supplier-refund-control-research','Supplier refund controls in accounts payable: a research synthesis','A source-backed review of refund evidence, role separation, and settlement tracking after supplier credits or overpayments.','/research-thumbnails/ap-credit-memo-reconciliation-research.svg','which records make a supplier refund request and settlement independently reviewable','the originating invoice and payment, duplicate or credit evidence, authorized request, supplier response, expected amount, bank receipt, ledger application, and reviewers','support may prepare the claim, maintain follow-up chronology, and compare expected with received funds','trace a documented overpayment from discovery through an authorized request, actual cash receipt, and accounting application',[sources.gao,sources.coso,sources.nist]),
make('ap-approval-reminder-governance-research','Governance for AP approval reminders and escalations','Research on reminder cadence, accountable ownership, and evidence preservation for pending invoice approvals.','/research-thumbnails/ap-invoice-approval-aging-research.svg','how reminder workflows can reduce ambiguity without becoming shadow approval channels','the invoice record, approval matrix source, original request, due date, reminder events, replies, delegation evidence, escalation rule, and final decision','support may send approved reminders and report aging but must not infer approval from silence, urgency, or an informal reply','show that absence, an invalid delegate, and a disputed invoice each route to the correct named owner without changing approval status',[sources.gao,sources.nist,sources.coso]),
make('ap-vendor-contact-integrity-research','Vendor contact integrity for AP verification workflows','A research review of trusted contact sources, change history, and segregation in supplier verification.', '/research-thumbnails/vendor-bank-change-control-research.svg','how AP teams can keep routine vendor contacts separate from trusted verification routes','contact purpose, source, supplier identity, approved address or number, verification status, effective dates, proposed changes, reviewers, and use history','support may log requests and use approved channels but cannot validate a new verification channel using information supplied in the same change request','demonstrate that an email-address change and a bank-detail request cannot update or bypass the independently controlled verification route',[sources.fbi,sources.cisa,sources.nist]),
make('ap-document-quality-gates-research','Document quality gates for AP invoice intake','A source-backed analysis of readability, completeness, provenance, and correction history before invoice entry.','/research-thumbnails/invoice-intake-control-research.svg','what evidence an AP intake quality gate should retain before extracted invoice data enters downstream processing','the original delivery event, immutable file reference, format and page count, readability result, invoice identifiers, extraction output, omissions, corrections, and reviewers','support may inspect document quality, capture observable fields, and request a better source while coding and acceptance decisions stay with company owners','use a missing page, unreadable total, mismatched attachment, and corrected resubmission to verify that the gate retains chronology',[sources.nist,sources.gao,sources.cisa]),
];
