import type {ResearchPost} from './research-batch';

// Expected first-publication date for the October 5 combined release. The Blog
// integrator must reconcile this to the actual UTC live date before the sole push.
export const oct5ResearchPublicationDate='2026-10-05';
const checked='October 5, 2026';
const gao={label:`U.S. GAO, Standards for Internal Control in the Federal Government (2025), checked ${checked}`,href:'https://www.gao.gov/greenbook'};
const nist={label:`NIST SP 800-53 Rev. 5, Security and Privacy Controls, checked ${checked}`,href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'};
const fbi={label:`FBI, Business Email Compromise, checked ${checked}`,href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'};
const irs={label:`IRS Publication 463 (2025), Travel, Gift, and Car Expenses, checked ${checked}`,href:'https://www.irs.gov/publications/p463'};

const nonPoException:ResearchPost={
  slug:'non-po-invoice-exception-authority-research',
  title:'Non-PO invoice exceptions: evidence before approval',
  excerpt:'A research method for separating missing purchase-order evidence from authorized non-PO treatment, coding, receipt, and payment decisions.',
  published:oct5ResearchPublicationDate,modified:oct5ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-approval-matrix-research.svg',
  keywords:['non-PO invoice review','invoice exception authority','accounts payable outsourcing research'],
  cta:'Define a controlled invoice-exception preparation lane.',
  internalLinks:[{label:'Invoice data capture',href:'/services/invoice-data-capture'},{label:'Purchase order reconciliation',href:'/services/purchase-order-reconciliation'},{label:'Accounts payable services',href:'/services'}],
  serviceHandoff:{heading:'Prepare non-PO evidence without inventing authority',body:'AP support can assemble the source packet and route the precise exception. Company owners retain purchasing, receipt, coding, approval, and payment decisions.',href:'/services/invoice-data-capture',label:'Review invoice data capture'},
  citations:[gao,nist],
  body:[
    `A missing purchase-order number does not prove that an invoice is invalid, and a familiar supplier does not prove that the charge is authorized. This study asks what evidence an accounts-payable preparer should assemble before a company owner decides how a non-PO invoice will be handled. The practical problem is common in subscriptions, utilities, professional services, emergency purchases, taxes, and approved categories that may follow a different procurement path. It also appears when a purchase order should exist but was never created, was issued to another entity, or cannot be found. The method deliberately separates those conditions. Its output is a decision packet that identifies the commitment, benefit, policy path, accounting question, and approving owner. It is not permission to create a retrospective order, choose a bypass code, assert that services were received, assign an expense account, approve a policy exception, or release payment. That boundary lets outsourced AP support make the queue clearer without converting incomplete evidence into apparent authorization.`,
    `The population begins with every invoice entering the declared workflow without a valid order reference at a fixed UTC cutoff. The register keeps the original document, intake channel and timestamp, invoice and supplier identifiers, legal entity, amount and currency, service or delivery period, contract or request references, submitter, proposed cost owner, and every system search performed. It distinguishes no order cited, cited order not found, cited order closed, cited order belongs to another entity, order exists but the line is absent, and category designated by policy as non-PO. Those are facts about the available record. Calling the invoice an approved exception is a conclusion that requires an authoritative rule and owner disposition. Exclusions remain reconciled to the intake total so that a tidy review set does not hide credits, zero-value invoices, disputed duplicates, or records already routed elsewhere. Sensitive attachments remain in approved systems; the working file uses stable links and controlled identifiers.`,
    `Commitment reconstruction starts before coding. The preparer searches the approved contract repository, requisition history, correspondence retained in the business record, supplier master, recurring-charge register, and prior invoices only within the assigned access. A prior payment can suggest where evidence may exist, but it does not authorize the current charge. A signed agreement can establish terms without proving that the billed milestone occurred. An employee email may identify a requester without establishing purchasing authority. The packet states what each source shows, its version, effective period, and any conflict. If the company has a policy listing permitted non-PO categories, the exact category and current policy version are cited. If the invoice falls outside it, the result is “policy path unresolved,” not an improvised category chosen because it resembles a previous transaction. This keeps fact, comparison, inference, and decision visibly separate.`,
    `Benefit and receipt evidence require a second track. Goods may have arrived at a site that cannot create a system receipt; a service owner may need to confirm a deliverable; a utility statement may cover an active company account; or a subscription roster may show use without proving contractual acceptance. The preparer records the named recipient, source event, date, quantity or period, location, and unresolved variance. It does not copy the invoice description into a receipt field and call that confirmation. When an employee attests to performance, the packet retains the attestation, identity, time, scope, and authority under company policy. Partial or disputed performance remains split from the undisputed portion. A later confirmation is appended rather than backdated. That chronology allows the approver to see what was known when the invoice first entered review and prevents a successful later resolution from making the initial control gap disappear.`,
    `The authority map tests four separate questions: who may confirm the business need, who may confirm receipt or service performance, who may decide accounting treatment, and who may approve the financial commitment or exception. One person may hold more than one role under company policy, but the packet should not assume that job title alone grants all four. Thresholds are tested against the correct entity, currency rule, cumulative commitment, and effective delegation date. A requestor's approval cannot cure a missing authority if the policy assigns the decision elsewhere. Technical ability to change workflow status also does not create business authority. GAO's 2025 Green Book supports documented control activities, quality information, and clear responsibility, while NIST least-privilege and audit-record concepts support bounded access and attributable actions. These public frameworks guide method design; they do not dictate a private company's purchasing or approval policy.`,
    `A challenge set makes the method falsifiable. Cases include an emergency repair with an authorized retrospective process; a recurring software invoice after the contract owner left; legal services with a matter reference but no order; an invoice citing another entity's order; a supplier that omitted a valid order from the document; a closed order with remaining service evidence; a duplicate candidate submitted as non-PO; and an employee request above their limit. A second reviewer receives the frozen sources and independently identifies the missing evidence, available policy path, and next authorized owner. Agreement is expected about source facts and calculation, not about decisions that policy reserves to management. The method fails if the reviewers can clear the invoice only by relying on oral history, if the route changes without retained evidence, or if “non-PO approved” hides whether commitment, receipt, coding, and payment approval were actually distinct.`,
    `Queue states should name the unresolved question: order reference missing, order search incomplete, authorized non-PO category evidenced, commitment owner needed, receipt or service confirmation needed, entity conflict, accounting review needed, threshold escalation, duplicate review, supplier correction requested, or owner disposition recorded. Each state has one current owner and one last evidence event. Metrics count the full population, source-complete packets, policy-path gaps, owner response states, later order creation, duplicate candidates, entity corrections, and second-review reproducibility. They should not reward support staff merely for converting invoices to an approved status. A falling exception count could reflect better procurement, but it could also reflect broad bypass coding or premature closure. Any rate therefore discloses numerator, denominator, scope, cutoff, exclusions, and policy version. Monetary totals remain separated by entity and currency rather than being combined into a misleading headline.`,
    `Limitations are explicit. Repository searches can miss informal commitments, system migrations can break links, policy language can be ambiguous, and the preparer may not have access to legal, procurement, or accounting records. The cited federal control frameworks do not make a non-PO invoice allowable, determine contract enforceability, assign tax or accounting treatment, or identify the correct private-company approver. A bounded exception sample cannot estimate fraud, savings, or outsourcing performance. The supported conclusion is narrower: a non-PO invoice becomes decision-ready when its intake source, commitment evidence, benefit or receipt record, applicable policy path, entity, amount, authority questions, and owner disposition are reconstructable. Outsourced AP can organize and monitor that evidence. Accountable employees decide whether the charge is accepted, how it is recorded, whether an exception is authorized, and whether payment may proceed.`,
    `The final handoff should be brief enough to act on but complete enough to audit. It names the invoice, declared exception type, strongest commitment source, benefit evidence, unresolved conflict, applicable policy version, amount and entity, current owner, and requested decision. It also links the full chronology and states the cutoff. If a retrospective order is later created, the record should distinguish that corrective event from the original condition. Preserving both states lets procurement leaders identify recurring intake failures without asking AP support to conceal them. The reader outcome is therefore not a faster bypass. It is a bounded decision request whose facts can be checked and whose eventual disposition can be traced back to the evidence available at the time.`
  ]
};

const accrualMatch:ResearchPost={
  slug:'invoice-accrual-reversal-match-research',
  title:'Matching an AP accrual reversal to the later invoice',
  excerpt:'Research on connecting a prior-period AP accrual, its reversal, and a later supplier invoice without concealing scope, timing, or amount differences.',
  published:oct5ResearchPublicationDate,modified:oct5ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-accrual-support-research.svg',
  keywords:['AP accrual reversal match','month-end invoice research','accounts payable close support'],
  cta:'Build a reviewable month-end AP evidence lane.',
  internalLinks:[{label:'Month-end AP close support',href:'/services/month-end-ap-close-support'},{label:'Invoice data capture',href:'/services/invoice-data-capture'},{label:'Aging report preparation',href:'/services/aging-report-preparation'}],
  serviceHandoff:{heading:'Link close evidence without posting the conclusion',body:'Support can build the bridge among estimate, reversal, invoice, and source records. Company accounting owners retain period, account, estimate, adjustment, and posting decisions.',href:'/services/month-end-ap-close-support',label:'Review month-end AP close support'},
  citations:[gao,nist],
  body:[
    `A later supplier invoice may resemble a prior-period accrual without being the transaction that the accrual estimated. This research asks how AP support can build a reproducible bridge among an accrual, its reversal, the underlying goods or services, and a subsequently received invoice. The reader's decision is not simply whether two amounts match. It is whether the source population supports a proposed relationship and clearly displays residual scope, timing, currency, tax, and accounting questions for an authorized close owner. The method treats an accrual journal, automatic reversal, purchase record, acceptance evidence, and invoice as separate events. It does not let the preparer decide that an estimate was correct, move expense between periods, select an account, post or reverse a journal, absorb a difference, or approve the invoice. This matters in an outsourced lane because a clean one-to-one match can be cosmetically attractive while masking partial services, multiple invoices, credits, foreign-exchange effects, or an estimate built at a different level.`,
    `The study population starts with a frozen list of AP-related accrual lines selected under the company's close procedure and all reversals tied to them. For each line the register records entity, period, journal and line identifiers, preparation source, description, supplier or counterparty if known, purchase-order or contract reference, service or delivery window, quantity basis, currency, entered amount, functional amount, exchange-rate source, account, cost center, preparer, approver, posting time, reversal method, and reversal event. It then links candidate invoices, credits, receipts, milestones, and owner confirmations received through the declared research cutoff. Unmatched and multiply matched items remain visible. The population total reconciles to linked, partially linked, contradicted, and unresolved categories. The working record points to controlled source documents; it does not reproduce confidential contracts or journal support into an ordinary spreadsheet merely to make review convenient.`,
    `Relationship testing proceeds from identity and scope, not amount proximity. Strong evidence can include a stable order line, contract milestone, service ticket, shipment, location, period, and supplier reference. An equal dollar amount is only one feature and may reflect a recurring estimate, standard monthly entry, or coincidence. Conversely, the eventual invoice may legitimately differ because the accrual covered a partial period, excluded tax, used an estimate, or spanned several suppliers. The preparer records each field-level agreement and conflict and labels the proposed relation one-to-one, one-to-many, many-to-one, partial, superseded, or unresolved. No confidence label is used unless the company has an approved method with defined inputs. The packet never edits the invoice description to echo the accrual memo or overwrites the original estimate with actual values; doing so would destroy the evidence needed to evaluate estimate quality.`,
    `Chronology protects the cutoff. The bridge orders service performance, goods receipt, estimate preparation, approval, journal posting, period close, automatic or manual reversal, invoice creation, invoice receipt, correction, approval, and any later adjustment. Event time and system-entry time are retained separately when available. A document received after close can inform later accounting without becoming evidence that it was available to the original preparer. A reversal dated on the first day of the next period may post later because of system processing; both dates matter. If the source estimate changed during review, every version and approval remains connected. The result lets a reviewer reconstruct the information set at close and the information added afterward, rather than judging the estimate with hindsight or treating a later invoice as retroactive proof of the original period.`,
    `The quantitative bridge is reversible. It begins with gross accrued amount, shows the reversal, then displays candidate invoice bases, taxes, freight, credits, retainage, foreign-exchange components, prior invoices, and residuals. Quantities and service periods are reconciled independently of currency values. If one accrual covers a quarter but the invoice covers a month, the packet states the allocation source instead of prorating by days without authority. If the ledger reversal is automatic and an invoice posts before or after it, the bridge reports both effects but does not recommend a journal. Differences receive sourced explanations or an unresolved label. A zero net ledger effect does not prove that the correct period or account was used. Likewise, an open residual does not prove error; it may represent service not yet invoiced, a revised estimate, or scope outside the candidate invoice.`,
    `Challenge cases include an estimate covering two milestones followed by one invoice; a blanket-order accrual later billed across three invoices; a credit issued after an overestimate; a foreign-currency invoice with a rate difference; a service period crossing month-end; an invoice posted before the reversal; a cancelled service with a stale accrual; and two suppliers with similar descriptions and values. A second reviewer starts with the retained sources and reproduces proposed relationships, arithmetic, and residual questions. The method passes when source-based links and gaps are the same, even if the accounting owner has not decided the treatment. It fails when the relation depends on the preparer's memory, when later documents overwrite the cutoff packet, when a residual is forced into the closest invoice, or when the current ledger balance is offered as the only history.`,
    `The support boundary is narrow but useful. A Philippines-based AP specialist may collect approved records, index journal and invoice identifiers, compare scope and chronology, build the mathematical bridge, maintain unresolved-item ownership, and request missing operational evidence. The role may not determine whether an accrual is required, choose a period or account, approve an estimate, post or reverse a journal, decide materiality, assign foreign-exchange treatment, alter invoice coding, or close a residual. Accounting and business owners retain those decisions. GAO's Green Book provides relevant principles for quality information, documented transactions, responsibility, and monitoring. NIST controls support least privilege and attributable audit records for system actions. Neither publication supplies generally accepted accounting conclusions or replaces the company's close policy and professional judgment.`,
    `Measurements should illuminate the bridge rather than manufacture a reconciliation rate. Useful counts include scoped accrual lines, complete source packets, deterministic links, partial relationships, unresolved service periods, amount and currency conflicts, stale accrual candidates, missing reversals, owner decisions, later adjustments, and sampled relations reproduced by a second reviewer. Amounts stay by entity and currency, with both entered and functional values when relevant. “Matched” must mean a defined evidence state, not merely an equal amount. Trend reports retain the same cutoff and population rules. Limitations include incomplete purchasing data, estimates prepared outside the system, inaccessible journal support, bundled supplier billing, and management judgments that cannot be inferred from public sources. The defensible outcome is a bridge showing what the original estimate covered, how it reversed, which later documents may relate, what remains unexplained, and who is authorized to decide the accounting response.`,
    `Closure evidence should state the accounting owner's decision without rewriting the research record. The owner may determine that the invoice consumes the accrual fully, consumes only a defined portion, belongs to a different estimate, requires an adjustment, or provides insufficient evidence. The support register links that disposition, the resulting journal or workflow reference, and any residual follow-up. Subsequent credits and corrected invoices append to the chain. This design supports a later estimate-quality review: analysts can compare original assumptions with outcomes while respecting the information available at each cutoff. It also reveals whether repeated residuals come from late invoices, weak service confirmations, blanket-order design, or another evidenced process issue. Those patterns inform management action, but they do not authorize the preparer to correct accounting entries independently.`,
  ]
};

const expenseOverlap:ResearchPost={
  slug:'corporate-card-reimbursement-overlap-research',
  title:'Corporate-card and employee-reimbursement overlap research',
  excerpt:'A transaction-level method for identifying when the same business expense may appear in a card feed and an employee reimbursement request.',
  published:oct5ResearchPublicationDate,modified:oct5ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-expense-report-review-controls-research.svg',
  keywords:['corporate card duplicate reimbursement','expense report review research','AP expense evidence'],
  cta:'Define a controlled expense-review support lane.',
  internalLinks:[{label:'Expense report review',href:'/services/expense-report-review'},{label:'Duplicate invoice review',href:'/services/duplicate-invoice-review'},{label:'Accounts payable services',href:'/services'}],
  serviceHandoff:{heading:'Surface overlap without accusing or adjudicating',body:'Support can compare controlled card and reimbursement records and prepare a neutral exception. Authorized company owners decide business purpose, repayment, payroll, discipline, accounting, and approval.',href:'/services/expense-report-review',label:'Review expense report support'},
  citations:[irs,gao,nist],
  body:[
    `The same restaurant, hotel, subscription, or transport expense can appear once in a corporate-card feed and again in an employee reimbursement claim. Similarity is not proof of duplicate payment: one record may be a temporary authorization, a reversed charge, a deposit, a split bill, a personal card used after the corporate card failed, or a reimbursement claim that discloses a company-paid portion. This study develops a neutral evidence method for identifying overlap candidates without accusing an employee or deciding recovery, tax, payroll, disciplinary, or accounting treatment. The output is a transaction packet that shows both payment channels, documentary support, employee explanation, system history, and approving owner. Outsourced AP support can prepare that packet and monitor the exception. It must not label conduct as fraud, reject a claim based on resemblance alone, change a card record, deduct pay, net a future reimbursement, or decide whether an expense has an adequate business purpose.`,
    `The population combines a frozen corporate-card extract and reimbursement submissions for the same declared entities and date window. Each source retains its stable transaction or report identifier, employee and cardholder identifiers, merchant name and location, authorization date, posted date, transaction and billing currencies, original and converted amounts, card status, expense-report line, receipt reference, business-purpose field, attendee or trip reference where policy permits, reimbursement status, approver, and source timestamps. Pending authorizations are separated from posted transactions. Credits and reversals remain linked to their original charge. Cash advances, per diem, mileage, and centrally billed travel are classified before comparison because they do not behave like ordinary receipt-backed charges. The study reconciles every included and excluded record to its source totals and keeps personal data in approved systems, exposing only the minimum identifiers required for the assigned review.`,
    `Candidate generation uses layered tests. Exact references, receipt-image hashes, merchant transaction identifiers, booking numbers, dates, currencies, and amounts can provide strong signals. Normalized merchant text, nearby dates, converted values, and similar descriptions provide weaker signals and must not be called matches. A hotel may split room, tax, and incidentals; a restaurant may post a tip adjustment; a ride service may issue several same-day charges; and an employee can legitimately share an expense with colleagues. The register records why each pair was surfaced, which fields agree, which conflict, and whether one record has already been reversed or disclosed. It preserves separate source amounts rather than converting them solely to make a pair appear equal. A company-approved exchange-rate comparison can support analysis, but only the original currencies show whether the sources actually describe the same charge.`,
    `Documentary review follows the money path. A receipt may show the purchase but not the funding source. A card statement may show funding but not the business purpose. An expense report may contain an employee certification, while a travel platform may show that the company paid centrally. The packet links each assertion to its source. If an employee notes that the corporate card failed, the preparer checks for a later captured card transaction and retains both authorization and posting history. If a merchant refunded one channel and charged another, the full chain stays visible. The IRS's 2025 Publication 463 explains accountable-plan concepts such as business connection, adequate accounting, and return of excess reimbursement for U.S. tax contexts. It does not decide a particular claim, apply globally, or authorize AP to interpret payroll and tax consequences.`,
    `The chronology begins with purchase or booking and ends only after card settlement, reimbursement payment, credit, repayment, or owner disposition. It includes submission, approval, edits, rejected attempts, feed refresh, and employee responses. Event time is not silently replaced by entry time. A card charge posted after reimbursement approval is a later fact, not proof that the reviewer ignored visible evidence. Conversely, a pending authorization known during review should remain in the packet even if it later disappears. This time-aware method supports fair review because it shows what each participant could see. It also prevents a later credit from erasing the fact that two outflows may have occurred temporarily. Status labels such as candidate, employee explanation pending, source conflict, credit pending, owner decision pending, and resolved with evidence are preferable to “duplicate” until the relationship is established.`,
    `Challenge cases include a hotel deposit on the company card and balance on a personal card; a restaurant tip posted separately; the same receipt attached to two reports; a card charge reversed after reimbursement; foreign-currency travel with different conversion dates; a centrally billed airfare plus employee-paid seat fee; a shared meal divided between employees; and a subscription accidentally charged to both cards. Two reviewers independently classify the relationship and identify the next evidence needed. Reproducibility does not require them to infer intent. It requires the same source facts, signal strength, cash-flow possibilities, and unresolved owner question. The method fails if a normalized merchant name is treated as identity, if credits vanish from the population, if an employee response is summarized without the original record, or if a support analyst clears the case by editing one system to agree with another.`,
    `Roles remain explicit. Support may collect approved sources, run documented comparisons, preserve transaction histories, request a missing receipt or explanation through approved channels, and assemble an exception packet. The employee supplies required evidence. A manager determines business purpose and approval under policy. Finance, payroll, tax, card administration, human resources, or legal owners decide recovery, wage treatment, discipline, accounting, and card actions as applicable. NIST least privilege supports restricting the support role from card administration and payroll actions, while audit-record concepts support attributable changes. GAO principles support reliable information, clear responsibility, and monitoring. Neither framework establishes employee misconduct. Access design should prevent the convenience of overlap review from becoming broad visibility into unrelated travel, personal information, or complete card accounts.`,
    `Metrics report candidates and evidence states, not allegations or “fraud caught.” They can include records compared, exact-reference pairs, receipt-hash pairs, weak similarity candidates, later reversals, employee explanations, confirmed dual outflows, credits or repayments evidenced, unresolved owner decisions, false positives by signal, and second-review agreement. Denominators, date windows, currency treatment, and feed timing are disclosed. A rising candidate count may reflect better coverage or a changed travel pattern rather than worse behavior. Limitations include delayed card feeds, truncated merchant data, missing receipts, shared purchases, privacy constraints, and policy differences across jurisdictions. The method cannot establish intent, taxability, deductibility, employment consequences, or final accounting treatment. Its supported conclusion is that a suspected overlap becomes reviewable when both channels, their timing, funding evidence, documents, explanations, and authorized disposition remain linked without premature accusation.`,
    `A fair employee-facing handoff avoids loaded language. It states that two records may refer to the same expense, lists the fields that prompted review, identifies the missing fact, and gives an approved response channel. It does not demand sensitive personal account data when a receipt, card record, or merchant credit can answer the question. The final disposition records whether the sources described different expenses, one charge was reversed, an amount was disclosed and netted under policy, a dual outflow occurred, or evidence remained insufficient. Any recovery or payroll event receives its own authorized record. Keeping false positives and their causes improves the comparison rules and reduces repeated inconvenience without hiding real exceptions. The operational reader outcome is a respectful, reproducible review process, not a surveillance score.`,
  ]
};

const bankEffectiveTime:ResearchPost={
  slug:'vendor-bank-change-payment-proposal-timing-research',
  title:'Vendor bank-change timing inside a payment proposal',
  excerpt:'Research on preserving which bank instruction, verification event, and payment-proposal version existed at each decision cutoff.',
  published:oct5ResearchPublicationDate,modified:oct5ResearchPublicationDate,
  thumbnail:'/research-thumbnails/vendor-bank-change-control-research.svg',
  keywords:['vendor bank change timing','payment proposal bank account','AP fraud control research'],
  cta:'Define a bounded payment-preparation control lane.',
  internalLinks:[{label:'Payment run preparation',href:'/services/payment-run-preparation'},{label:'Vendor onboarding administration',href:'/services/vendor-onboarding-administration'},{label:'Accounts payable services',href:'/services'}],
  serviceHandoff:{heading:'Preserve bank-detail chronology without changing or releasing funds',body:'Support can assemble proposal versions, change records, and verification evidence. Authorized company owners control vendor-master changes, exceptions, payment approval, file creation, and release.',href:'/services/payment-run-preparation',label:'Review payment run preparation'},
  citations:[fbi,gao,nist],
  body:[
    `A bank-detail change received near a payment cutoff creates two linked questions: whether the new instruction was validly verified and which instruction a particular payment proposal actually used. This study focuses on chronology because a current vendor-master screen cannot prove what was selected when the proposal was created, reviewed, approved, exported, or released. The research output is a reconstruction of change request, independent verification, master-data versions, proposal versions, exclusions, and downstream events. It does not validate ownership of an account, decide that a callback was sufficient, edit supplier banking, select the old or new instruction, waive a hold, approve an exception, create a payment file, or release funds. The distinction matters for outsourced AP support: staff can make the evidence chain visible, but convenience and deadline pressure must not convert a preparation role into vendor-master or treasury authority.`,
    `The source population begins with every vendor-bank change whose request, effective date, approval, or system update overlaps a declared payment-preparation window. It also includes every proposal line for those suppliers, whether paid, excluded, held, rejected, or rolled forward. The register records entity, supplier identifier, change case, request channel, received time, requested values represented only by controlled references, verification method and independently sourced contact, verifier, approver, master-data version, effective time, proposal identifier and version, invoice keys, amount and currency, selected payment-method token, holds, export time, file identifier, bank response, and final disposition. Sensitive bank values never enter an ordinary audit sheet. Masked fingerprints or secure system references are enough to test version relationships. Shared suppliers across entities remain separate because one entity's verified instruction may not govern another entity or payment method.`,
    `Request provenance is evaluated before timing. The FBI's current business-email-compromise guidance warns that messages may appear to come from known sources and advises verifying changes in account number or payment procedures through independently obtained contact information. That is risk guidance, not proof that any request is fraudulent or a complete private-company procedure. The preparer records observable features: sender, channel, attachments, urgency, differences from approved records, and the source of the verification contact. It does not use the phone number supplied in the same change message as independent evidence unless company policy explicitly defines and controls that path. A supplier confirmation establishes what the contacted person said; authorized company owners still decide whether the verification and documentation meet policy and whether the master may change.`,
    `The central timeline separates requested effective date, verification time, approval time, system-entry time, master effective time, proposal creation, proposal refresh, approval, export, transmission, acceptance, rejection, cancellation, and settlement evidence. These events may occur in different systems and timezones. A proposal created before a bank change can refresh afterward. A master update approved before cutoff can fail to reach the payment engine. A rejected file may be regenerated after the instruction changes. The packet preserves every version and the rule or system behavior used to select details. It never assumes that the latest screen retroactively governed an earlier export. Where a platform does not retain versions, the research records the evidence gap and available compensating sources instead of manufacturing certainty from a screenshot taken after the event.`,
    `Proposal-line reconstruction uses stable identifiers and protected account fingerprints. For each version, the reviewer can see the supplier record, payment method, masked destination token, invoice population, hold state, and actor or process that refreshed it. A difference matrix identifies lines added, removed, altered, or unchanged. The packet distinguishes a master-data change from a proposal override and an override from a bank-file transformation. If an authorized employee decides to retain an old instruction for a specific payment, that disposition and its authority are linked; the support analyst does not implement or infer it. If a bank rejection triggers resubmission, the rejected file, response code, correction decision, and new file remain chained. Reusing a proposal number does not permit the previous version to disappear.`,
    `Challenge cases include a verified change approved after proposal creation; a request for one entity mistakenly visible to another; a supplier with separate domestic and foreign-currency accounts; a change entered in the master but not synchronized; an urgent invoice paired with a bank request; a file rejected and rebuilt after the change; a callback made to a number from the request; and a proposal refreshed without a clear audit event. Two reviewers reconstruct which bank-detail token each proposal stage used and identify unresolved verification or authority questions. The method passes when the same chronology and gaps emerge. It fails when current master data is treated as historical evidence, when masked values cannot be related safely across sources, when an unsuccessful file is discarded, or when deadline language is accepted as permission to bypass a required hold.`,
    `Access and separation are critical. AP support may index requests, gather approved verification records, compare masked tokens, preserve proposal histories, maintain holds already authorized by policy, and route precise exceptions. It may not amend vendor banking, obtain verification through an unapproved channel, approve the change, remove a security hold, override proposal details, create or modify bank files, approve payments, or release funds. Vendor management, finance, treasury, security, and payment approvers retain their assigned decisions. NIST least privilege and audit controls support restricting privileged functions and retaining who did what, when, where, and with what result. GAO's Green Book supports separation of duties, quality information, and documented control activity. The exact workflow remains the company's responsibility.`,
    `Useful measures include in-scope changes, independently sourced verification records, approval states, master versions retained, affected proposals, pre-change and post-change proposal lines, synchronization gaps, holds, overrides, rejected files, owner dispositions, and second-review reproducibility. A fast update is not inherently a good result, and a held payment is not inherently a failure. Reports should never expose bank data or rank staff by how quickly they clear security exceptions. Limitations include system histories that overwrite values, external bank processing outside the company's visibility, supplier organizational changes, shared-service configurations, and inaccessible verification recordings. This research cannot determine legal account ownership, prove or disprove fraud, define bank liability, or authorize payment. Its supported conclusion is that the risk becomes governable when every requested and approved change, effective-time decision, proposal version, masked destination, hold, export, and final owner action can be reconstructed without relying on the latest screen or oral memory.`,
    `The handoff to the authorized payment owner should show one compact lineage for each affected line: verified supplier identity reference, approved master version, proposal version, masked destination token, security holds, invoice population, and latest bank response. It explicitly says whether the proposed destination changed after an earlier approval and whether the workflow requires renewed review. The owner records the chosen action and reason; the support role only preserves it. After transmission, settlement or rejection evidence is appended without treating bank acceptance as proof that the supplier ultimately received or allocated funds. If the supplier later disputes receipt, the same lineage supports investigation while keeping the original verification and release decisions intact. This end-to-end record is more useful than a screenshot of a successful status because it exposes every controlled transition. A separate exception note records any unavailable system event, the compensating evidence used, and the person accountable for resolving the gap. Reviewers can then distinguish confirmed chronology from an inference instead of allowing a plausible narrative to harden into fact.`,
  ]
};

const delegationExpiry:ResearchPost={
  slug:'invoice-approval-delegation-expiry-research',
  title:'Did invoice approval occur before delegation expired?',
  excerpt:'A time-aware study of delegated invoice authority, workflow events, amount thresholds, and superseding decisions.',
  published:oct5ResearchPublicationDate,modified:oct5ResearchPublicationDate,
  thumbnail:'/research-thumbnails/ap-approval-separation-research.svg',
  keywords:['invoice approval delegation expiry','AP approval evidence','delegated authority research'],
  cta:'Build an attributable approval-evidence workflow.',
  internalLinks:[{label:'Accounts payable services',href:'/services'},{label:'Invoice data capture',href:'/services/invoice-data-capture'},{label:'Aging report preparation',href:'/services/aging-report-preparation'}],
  serviceHandoff:{heading:'Reconstruct approval authority without deciding validity',body:'Support can align policy, delegation, invoice, and workflow events. Authorized company owners decide whether approval was valid, must be repeated, or requires escalation.',href:'/services',label:'Review accounts payable services'},
  citations:[gao,nist],
  body:[
    `An invoice can display “approved” even when the business authority behind that status is uncertain. A delegate may have approved moments after a temporary assignment expired, the invoice may have crossed a threshold after tax or currency conversion, or a workflow may have recorded action after the delegator returned. This study asks how to reconstruct authority at the precise time of approval. The method does not decide that an approval is legally valid, infer intent, extend a delegation, change a workflow record, accept an invoice, approve an exception, or release payment. Its output is a time-aware evidence packet connecting the invoice version, applicable policy, delegation record, user identity, approval event, amount basis, and any superseding action. That gives a finance owner enough evidence to decide whether the approval stands, needs ratification, must be repeated, or should be escalated, while keeping outsourced AP support inside an evidence-preparation role.`,
    `The population includes invoice approvals performed by delegates during or near a declared delegation window, plus approvals affected by later invoice changes. Each record retains entity, invoice key and version, supplier, amount and currency, tax and freight components, converted threshold amount if policy uses one, approval step, required role, delegator, delegate, delegation identifier, scope, start and end times with timezone, creation and revocation events, authentication identity, action timestamp, system outcome, later edits, payment status, and owner disposition. The register includes rejected, returned, reassigned, auto-approved, and superseded events rather than selecting only successful approvals. Delegations for another entity, cost center, category, or amount remain visible as scope conflicts. Access to personnel and identity records stays controlled; the working packet uses only the minimum fields needed to test the event.`,
    `Policy reconstruction identifies the version effective when the action occurred. The preparer records whether thresholds apply to invoice subtotal, tax-inclusive total, cumulative commitment, purchase-order value, payment amount, or another approved basis. Currency conversion uses the policy's source and effective time, not today's rate. Scope is tested across entity, department, account, project, supplier class, and exception type only where the policy actually defines those dimensions. The existence of a delegation does not establish that it covered every approval held by the delegator. Conversely, an expired delegation does not by itself decide the fate of an invoice; the company may have a documented fallback or ratification process. The evidence packet states the rule and conflict without writing a new rule to resolve an awkward case.`,
    `Time reconstruction distinguishes when the delegate clicked or submitted, when the workflow accepted the event, when an asynchronous rule evaluated it, and when the status became visible. It also records delegation creation, approval, activation, modification, revocation, scheduled expiry, and any system synchronization. If systems use different timezones, UTC and original display values are retained. A click before expiry with processing afterward is not silently treated the same as a click after expiry; the policy and system owner must define which event governs. A delegation revoked while an invoice was open creates another bounded question. Later ratification is appended with its own authority and time rather than backdating the original event. This approach preserves what happened instead of editing history until the workflow appears internally consistent.`,
    `Invoice version matters because authority can change with amount and scope. The packet hashes or otherwise identifies the document and structured record seen at approval, then compares later corrections, tax changes, currency updates, coding changes, added lines, credits, and purchase-order links. A delegate authorized below a threshold may have acted on an earlier value before a corrected invoice exceeded it. A small value reduction after approval may still require reapproval if policy says any material source change resets the chain. Support records the difference and current workflow behavior; it does not decide materiality or whether the old approval transfers. Approval comments are evidence of what the actor stated, not a substitute for the controlled source version. A current “approved” badge cannot prove which amount or attachment the user reviewed.`,
    `Challenge cases include an approval seconds before scheduled expiry; a late system timestamp after a timely user action; revocation during an open task; an invoice corrected above the delegate's limit; foreign-currency conversion crossing a threshold; a delegation restricted to one cost center; overlapping delegates; an auto-escalation that failed; and ratification after payment preparation began. A second reviewer receives frozen sources and reconstructs policy version, scope, invoice version, event times, and unresolved decision. Agreement is expected on those facts and calculations. The method fails if current roles replace historical access evidence, if timezone conversion is undocumented, if only the final invoice is retained, if ratification overwrites the original approval, or if the analyst assumes a system status is equivalent to authorized business consent.`,
    `An outsourced AP specialist may gather approved policy and workflow records, normalize timestamps, compare invoice versions and thresholds, maintain the exception queue, and request a decision from the designated owner. The specialist must not create or extend delegations, assign approver roles, change historical events, determine policy validity, ratify an approval, approve the invoice, override workflow, or release payment. Management owns authority design; system administrators own controlled configuration; finance owners decide invoice and exception outcomes. NIST access-control and audit-record concepts support least privilege, unique identity, and attributable event content. GAO's Green Book supports documented responsibility, appropriate control activities, quality information, and monitoring. These sources are control frameworks, not the company's approval matrix and not a legal opinion about agency or contractual authority.`,
    `Queue labels should describe evidence: policy version missing, delegation record missing, scope conflict, event-time conflict, threshold calculation needed, invoice version changed, identity attribution unresolved, ratification decision pending, reapproval required by owner, or disposition retained. Metrics include scoped approval events, complete delegation records, timestamp conflicts, invoice-version changes, threshold crossings, scope exceptions, later ratifications, repeated workflow defects, and second-review reproducibility. Counting “invalid approvals” would overstate what an evidence study can prove. Limitations include overwritten workflow histories, shared or migrated identities, unclear policy language, clock drift, asynchronous processing, and decisions made outside controlled systems. The defensible conclusion is narrower: an approval becomes reviewable when another person can identify the exact invoice version, authority source, delegation scope, amount basis, action and processing times, subsequent changes, and accountable disposition without relying on oral explanation or a current status badge.`,
    `The final owner packet should not bury the decision beneath workflow exports. A summary states the approval event, delegation window and scope, policy threshold calculation, invoice version reviewed, later changes, and exact conflict. It then asks one bounded question: retain, repeat, ratify, reject, or escalate under the company's defined options. The response is linked to the responsible identity and timestamp. If reapproval occurs, the new event supplements rather than replaces the disputed one. If no action is needed, the reason is retained so a later reviewer can distinguish an evaluated exception from an unnoticed defect. Aggregated findings can reveal timezone configuration, role provisioning, or workflow synchronization problems, but management owns those remedies. Support supplies the reproducible evidence and keeps the queue current; it does not convert recurring practice into unofficial policy. The packet also identifies any downstream proposal or payment state reached before the authority question was resolved. That fact changes urgency and escalation ownership, but it does not give the preparer permission to reverse, release, or otherwise alter the transaction.`
  ]
};

export const oct5ResearchBatch:ResearchPost[]=[nonPoException,accrualMatch,expenseOverlap,bankEffectiveTime,delegationExpiry];
