type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-09-11';
const sources={gao:{label:'GAO 2025 Green Book',href:'https://www.gao.gov/greenbook'},nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},occ:{label:'OCC Accounts Payable Operations',href:'https://www.occ.treas.gov/publications-and-resources/publications/comptrollers-handbook/files/accounts-payable/index-accounts-payable.html'},cisa:{label:'CISA Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'},irs:{label:'IRS Taxpayer Identification Number Matching',href:'https://www.irs.gov/tax-professionals/taxpayer-identification-number-tin-matching'}};
const internalLinks=[{label:'Rush payment request intake',href:'/blog/ap-rush-payment-request-intake'},{label:'Payment-file transfer log',href:'/blog/ap-payment-file-transfer-log'},{label:'Vendor name alias register',href:'/blog/ap-vendor-name-alias-register'}];
const serviceHandoff={heading:'Turn the study into a bounded AP routine',body:'Name the population, approved sources, preparer access, reviewer, exception owner, retention rule, and retest trigger before assigning the work.',href:'/contact-us',label:'Discuss an AP support scope'};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,population:string,method:string,boundaries:string,limitations:string,conclusion:string,citations:Post['citations']):Post=>({slug,title:'September 11 study: '+title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks,serviceHandoff,body:[
`Research question and scope: ${question}. The scope is a declared accounts payable population and period. This report applies public control guidance to workflow design. It does not provide legal, tax, accounting, cybersecurity, or fraud assurance.`,
`Evidence population: ${population}. Before sampling, record the entity, systems, cutoff, inclusion rules, exclusions, unavailable records, and source hierarchy. Keep system facts, document contents, operator notes, supplier claims, reviewer judgments, and management decisions distinct.`,
`Methodology: ${method}. Preserve the original chronology and have a second reviewer reproduce each classification from the same evidence. Counts and rates describe only the declared population.`,
`Inference boundaries: ${boundaries}. The GAO Green Book supplies a framework for responsibility, documentation, quality information, and monitoring. NIST SP 800-53 supplies relevant access and audit concepts. The remaining sources narrow the operating question but do not decide a case.`,
`Limitations: ${limitations}. Report absent evidence as missing or excluded rather than converting it into a positive or negative finding. Do not generalize results outside the tested policies, workflow, systems, access model, entities, and period.`,
`Conclusion: ${conclusion}. Management retains policy, access, materiality, accounting treatment, vendor-master approval, payment release, remediation, and the decision to retest.`,
]});
export const sep11ResearchBatch:Post[]=[
make('returned-payment-evidence-boundaries-research','What returned supplier payments can and cannot tell an AP team','A reproducible study of bank return events, reason codes, verification, retries, and final ledger treatment.','/research-thumbnails/ap-payment-calendar-control-research.svg','which retained evidence supports useful classifications of returned supplier payments','payment proposals, approval records, bank submissions, return events and codes, original instructions, verification records, supplier correspondence, master-data events, retries, fees, and ledger outcomes','include every return first recorded in the period; reconcile it to the bank and ledger; stratify by reason, age, entity, currency, and outcome; then replay all ambiguous or repeated returns','a bank code does not establish supplier fault, fraudulent intent, the correct replacement instruction, or permission to retry payment','bank wording may be truncated; processors map codes differently; partial returns, fees, batch rejections, and later corrections can obscure the original event','return analysis becomes useful when the bank event, verification, change authority, retry approval, cash result, and accounting closure remain separate',[sources.gao,sources.occ,sources.nist]),
make('urgent-payment-control-observations-research','Rush payment requests: an evidence study of urgency and control','Research on request timing, stated reasons, approval gaps, bank-change signals, repeat requesters, and payment outcomes.','/research-thumbnails/ap-fraud-escalation-queue-research.svg','what a bounded review can learn from invoices routed outside the normal payment calendar','request timestamps, stated deadlines and reasons, invoice and receipt evidence, terms, approval state, requester identity, supplier contact, bank-change events, escalation, payment decision, and outcome','select every request marked urgent or routed outside the standard calendar; define the label before counting; compare evidence available at intake with the final disposition; independently replay exceptions','urgency labels do not prove business impact, supplier pressure, fraud, invoice validity, or a control failure; correlation between a requester and an outcome does not establish cause','teams may record urgency inconsistently; rejected requests can disappear from payment data; verbal escalation and local holidays may be missing','the useful output is a transparent intake record and exception path, not an automatic rule that approves or rejects urgent work',[sources.gao,sources.cisa,sources.occ]),
make('recurring-billing-gap-evidence-research','Finding gaps in recurring invoice intake without inventing accruals','A scoped comparison of expected billing events, received invoices, service periods, follow-up, and close decisions.','/research-thumbnails/ap-close-open-items-research.svg','which records help AP detect a missing recurring invoice while respecting the boundary between follow-up and accounting judgment','approved contracts or expectation lists, supplier and entity, billing cadence, expected period, intake channels, received invoices and credits, cancellations, renewals, follow-up, accrual decisions, and later resolution','declare eligible recurring arrangements; create expected events from approved records; compare them with intake through the cutoff; classify gaps and late arrivals; replay cancelled, variable, and disputed examples','an expectation does not prove that a liability exists, that service occurred, that the amount is material, or that an accrual should be recorded','contract lists can be stale; variable bills resist exact matching; invoices may arrive through unobserved channels; later receipts can make an earlier gap look resolved','AP may flag and document a missing billing event, while the contract owner and accounting owner decide service status and financial treatment',[sources.gao,sources.occ,sources.nist]),
make('supplier-alias-match-boundaries-research','Vendor name aliases and the limits of automated matching','Research on legal names, trading names, payment descriptors, tax identifiers, master records, and uncertain supplier matches.','/research-thumbnails/ap-1099-vendor-records-research.svg','what evidence lets a reviewer connect an observed supplier name to a vendor record without merging distinct organizations','invoice headers, approved master records, legal and trading names, entity and address data, taxpayer information where authorized, bank descriptors, contracts, change history, match proposals, reviews, and rejected matches','build candidates from observed names; compare only approved fields; stratify exact, normalized, corroborated, conflicting, and unresolved matches; have a second reviewer replay every proposed merge or alias','name similarity alone does not establish legal identity, common ownership, tax status, bank ownership, or authority to change a vendor master','names vary by language and system; corporate events and shared addresses create ambiguity; taxpayer data may be restricted; rejected candidates may be under-recorded','an alias register is defensible when it retains the observed value, approved master identity, corroborating sources, conflicts, reviewer, effective dates, and revocation path',[sources.irs,sources.gao,sources.nist]),
make('invoice-attachment-integrity-observations-research','Invoice file integrity at the AP intake boundary','A bounded review of attachment completeness, readability, mismatches, safe handling, replacement requests, and downstream corrections.','/research-thumbnails/invoice-intake-control-research.svg','which observable file and message facts support consistent AP intake decisions before invoice data entry','inbound message metadata, approved channel, sender, attachment names and types, page counts, readability checks, invoice identifiers, duplicate signals, mismatch notes, security routing, replacement requests, intake status, and corrections','sample all attachments or a declared random sample from approved intake channels; apply a written checklist without opening prohibited content; record exclusions; replay every mismatch, unreadable file, and security escalation','file appearance does not prove authenticity, safety, supplier authority, or invoice validity; AP review is not malware analysis and should not bypass security controls','encrypted or corrupted files may be uninspectable; forwarded messages lose metadata; image quality affects observations; separate channels can make the population incomplete','intake improves when staff record what they can observe, stop on defined conditions, use the approved security path, and retain the replacement and disposition history',[sources.cisa,sources.nist,sources.gao]),
];
