type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-09-08';
const sources={gao:{label:'GAO Green Book',href:'https://www.gao.gov/greenbook'},nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},occ:{label:'OCC: Accounts Payable Operations',href:'https://www.occ.treas.gov/publications-and-resources/publications/comptrollers-handbook/files/accounts-payable/index-accounts-payable.html'},irs:{label:'IRS: Taxpayer Identification Number Matching',href:'https://www.irs.gov/tax-professionals/taxpayer-identification-number-tin-matching'},fbi:{label:'FBI: Business Email Compromise',href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'}};
const internalLinks=[{label:'Invoice version control log',href:'/blog/ap-invoice-version-control-log'},{label:'Payment-file transmission log',href:'/blog/ap-payment-file-transmission-log'},{label:'Queue reassignment handoff note',href:'/blog/ap-queue-reassignment-handoff-note'}];
const serviceHandoff={heading:'Turn the finding into a bounded AP handoff',body:'Name the source records, permitted preparation, access, reviewer, exception owner, and retained employee decisions before assigning the queue.',href:'/contact-us',label:'Discuss an AP support scope'};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,population:string,method:string,limits:string,finding:string,citations:Post['citations']):Post=>({slug,title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks,serviceHandoff,body:[
`Research question and scope: ${question}. This evidence review applies public guidance to a bounded accounts payable workflow. It is not legal, tax, accounting, cybersecurity, or fraud assurance, and it does not establish a universal performance benchmark.`,
`Evidence population: ${population}. The population, entities, systems, period, cutoff, inclusion rule, exclusions, and missing records are declared before review. Source facts remain separate from operator notes, external statements, reviewer inference, and management decisions.`,
`Methodology: ${method}. Routine and awkward cases are included, original chronology is retained, and a second reviewer attempts to reproduce each classification from the same packet. Counts are descriptive of this declared sample only.`,
`Control basis: the GAO Green Book addresses documentation, quality information, responsibility, and monitoring; NIST SP 800-53 addresses least privilege and attributable action. The additional cited sources narrow the operating question but do not decide any individual case.`,
`Inference limits and limitations: ${limits}. Missing evidence is reported as missing or excluded, not silently imputed. Findings cannot be generalized beyond the named population, workflow, access, policy, and observation period.`,
`Bounded conclusion: ${finding}. Management retains policy, access, materiality, retention, accounting treatment, approval, vendor-master change, and payment-release authority and should retest after material system or workflow changes.`,
]});
export const sep8ResearchBatch:Post[]=[
make('ap-invoice-revision-patterns-research','What invoice revisions reveal—and what they do not','An evidence study of corrected invoices, replacement files, changed fields, workflow timing, and decision boundaries.','/research-thumbnails/invoice-intake-control-research.svg','which retained records allow a reviewer to distinguish an unchanged resend, a corrected invoice, and an unsupported replacement','original and later files, cryptographic hashes, message or portal events, invoice identifiers, field-level comparisons, workflow states, linked credits, supplier explanations, reviewer decisions, and posting outcomes','select every multi-version invoice in the period plus a declared sample of single-version invoices; compare stable fields and changed fields; trace timing; and blind the replay reviewer to the first classification','a file difference does not prove supplier intent or fraud; image rendering, OCR, portal replacement behavior, incomplete retention, and corrections outside the period can obscure history','version comparison is a useful exception signal when originals, changes, chronology, and authorized disposition remain separately inspectable',[sources.gao,sources.nist,sources.fbi]),
make('ap-credit-memo-resolution-evidence-research','Credit memo resolution evidence across AP queues','Research on references, open-item matching, partial applications, refunds, and accountable accounting decisions.','/research-thumbnails/ap-credit-memo-reconciliation-research.svg','what evidence supports the movement of a supplier credit from receipt to an independently reviewable resolution','credit documents, supplier and entity, currency, referenced invoices, open-item extracts at defined cutoffs, statements, correspondence, proposals, approvals, postings, refunds, residuals, and later corrections','stratify credits by exact reference, partial use, no reference, cross-entity suggestion, refund request, and unresolved status; then reconcile proposed and final outcomes to dated source extracts','an apparent match is not accounting authority; later ledger extracts can hide the information available at the decision date; supplier statements may omit timing or entity detail','resolution is reproducible when receipt, matching evidence, preparer proposal, owner decision, posting or cash event, and remaining balance are not collapsed into one status',[sources.gao,sources.occ,sources.nist]),
make('ap-supplier-tax-identifier-review-research','Supplier tax-identifier review as a controlled evidence process','A bounded synthesis of source collection, matching responses, discrepancy handling, privacy, and vendor-master authority.','/research-thumbnails/ap-tax-document-collection-research.svg','how AP support can prepare supplier identifier evidence without making tax status or vendor-master decisions','approved supplier submissions, legal names, identifier fields, entity and system records, access logs, authorized matching responses where available, discrepancy queues, owner decisions, and change history','declare permissible sources and users; sample exact, missing, changed, formatted, and discrepant records; record only the minimum result needed; and replay routing without exposing identifiers in the workpaper','matching availability and rules vary; a response does not establish tax classification, ownership, legitimacy, or payment eligibility; sensitive identifiers require company-approved handling and retention','administrative review can improve traceability, but authorized tax and master-data owners must resolve discrepancies and control sensitive-data access',[sources.irs,sources.nist,sources.gao]),
make('ap-payment-file-chain-of-custody-research','Payment-file chain of custody from proposal to bank','Research on file identity, approvals, transmission events, acknowledgments, replacements, and separation of duties.','/research-thumbnails/ap-payment-run-preparation-research.svg','which evidence connects an approved payment proposal to the file accepted by a bank without granting the preparer release authority','proposal versions, approval events, export configuration, file hashes, item counts and totals, transmitter identity, secure-channel events, bank acknowledgments, rejections, replacement files, release decisions, and reconciliation results','select successful, rejected, retransmitted, cancelled, and partially accepted runs; compare identifiers and control totals at each transition; and have an independent reviewer reconstruct the sequence','bank and ERP logs differ in granularity and retention; a matching total does not prove identical beneficiaries; the review does not test cryptography, bank controls, or transaction legitimacy','a chain is reviewable when each transition has attributable evidence and preparation, approval, transmission, release, and reconciliation responsibilities remain explicit',[sources.nist,sources.gao,sources.occ]),
make('ap-work-queue-continuity-research','AP work-queue continuity during staff transitions','An evidence review of ownership changes, open promises, aging context, access gaps, and acceptance of handoffs.','/research-thumbnails/ap-aging-handoff-research.svg','what information lets a successor continue an AP queue without relying on the departing operator’s memory','queue snapshots, item identifiers, source links, status history, supplier and approver correspondence, outstanding promises, aging, exception reasons, next actions, ownership events, access records, acceptance checks, and closure outcomes','observe declared transitions, sample open items across age and exception type, freeze the pre-handoff snapshot, compare it with successor actions, and independently replay items that stalled or changed status','small or planned transitions may not represent urgent departures; private conversations and missing system history may make context unavailable; later closure does not prove the handoff itself was complete','continuity improves when source evidence, last action, outstanding commitment, next owner, required access, and acceptance are explicit before the former owner leaves the queue',[sources.gao,sources.nist,sources.occ]),
];
