import type {ResearchPost} from './research-batch';

const gao={label:'GAO: Green Book Internal Control Standards',href:'https://www.gao.gov/greenbook'};
const nist={label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'};
const least={label:'NIST: Least Privilege Glossary',href:'https://csrc.nist.gov/glossary/term/least_privilege'};
const cisa={label:'CISA: Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'};
const sba={label:'SBA: Manage Your Business Finances',href:'https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances'};
const irs={label:'IRS: About Form W-9',href:'https://www.irs.gov/forms-pubs/about-form-w-9'};
const links=[{label:'AP services',href:'/services'},{label:'AP inbox management',href:'/services/ap-inbox-management'},{label:'Research library',href:'/research'}];
const date='2026-08-18' as const;
type Seed={slug:string;title:string;excerpt:string;citations:ResearchPost['citations'];body:string[]};

// Keep the date and evidence contract visible in this route-specific source file.
// The release gate uses these records to verify each accepted identity independently.
const aug18ResearchPublicationDates:Record<string,string>={
  'ap-invoice-source-completeness-research':'2026-08-18',
  'ap-invoice-queue-aging-cause-research':'2026-08-18',
  'ap-approval-evidence-chain-research':'2026-08-18',
  'ap-vendor-inquiry-boundary-research':'2026-08-18',
  'ap-credit-application-evidence-research':'2026-08-18',
  'ap-entity-routing-evidence-research':'2026-08-18',
  'ap-payment-due-date-evidence-research':'2026-08-18',
  'ap-receipt-gap-routing-research':'2026-08-18',
  'ap-invoice-currency-exception-research':'2026-08-18',
  'ap-close-cutoff-exception-research':'2026-08-18'
};

const routeEvidence:Record<string,string>= {
  'ap-invoice-source-completeness-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final, and https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances. The evidence is used to frame traceability and record discipline, not to claim that any one source defines a universal AP packet.',
  'ap-invoice-queue-aging-cause-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final, and https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances. They inform the distinction between observed queue events and unsupported performance claims.',
  'ap-approval-evidence-chain-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final, and https://csrc.nist.gov/glossary/term/least_privilege. They support accountability and separation concepts, not a legal conclusion about any approval.',
  'ap-vendor-inquiry-boundary-research':'Sources consulted for this route include https://www.cisa.gov/secure-our-world/recognize-and-report-phishing, https://www.gao.gov/greenbook, and https://csrc.nist.gov/glossary/term/least_privilege. They support cautious routing and independent verification boundaries.',
  'ap-credit-application-evidence-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances, and https://csrc.nist.gov/glossary/term/least_privilege. They do not prescribe a ledger or tax treatment.',
  'ap-entity-routing-evidence-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://www.irs.gov/forms-pubs/about-form-w-9, and https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final. They frame evidence and authority without deciding an entity obligation.',
  'ap-payment-due-date-evidence-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances, and https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final. They do not establish a payment promise or term for a particular supplier.',
  'ap-receipt-gap-routing-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances, and https://csrc.nist.gov/glossary/term/least_privilege. They support preserving evidence while leaving acceptance to the owner.',
  'ap-invoice-currency-exception-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances, and https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final. They do not select an exchange-rate policy or accounting treatment.',
  'ap-close-cutoff-exception-research':'Sources consulted for this route include https://www.gao.gov/greenbook, https://www.sba.gov/business-guide/manage-your-business/manage-your-business-finances, and https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final. They support retained chronology and control ownership, not a close conclusion.'
};

const sharedResearchDepth=`Evidence interpretation for outsourced accounts payable requires more than recording a status. For each observation, preserve the source location, the date it was inspected, the person or system that supplied it, and the question that remains open. A packet should distinguish a fact copied from an invoice, a comparison made by the preparation role, an inference offered for review, and a decision made by the authorized finance owner. That distinction is useful during ordinary invoice intake, exception follow-up, close preparation, and later reconstruction. It also prevents a support lane from turning a plausible explanation into a posted value or an approval.

The research design should test difficult examples rather than only clean invoices. Include a record with a missing attachment, a conflicting identifier, a late correction, and a request that falls outside the written lane. Ask an independent reviewer to work from the retained packet and identify what can be accepted as fact, what needs evidence, and who must decide. Record disagreements and exclusions. A small, dated sample can show where the handoff is unclear, but it cannot establish a universal accuracy rate, staffing benchmark, savings claim, or compliance result. External control guidance supplies principles; the organization must still choose its authoritative systems, retention rules, approval policy, and escalation owners.

This boundary is especially important when work is performed by an outsourced AP support role. The role may sort incoming records, compare visible fields, request a missing document, maintain factual status, and prepare a concise question. It should not invent evidence, certify receipt, change a vendor master record, decide tax or entity treatment, waive an approval rule, promise payment, or release funds. Access should follow the smallest useful scope, with review when the queue, entity, or tool changes. The evidence-led conclusion for this report is therefore operational: a well-designed lane makes the next finance decision easier to see and safer to make, while leaving judgment and authority where the organization assigned them. Limitations remain material: the method does not prove the underlying transaction, resolve legal obligations, or replace accounting advice.`;
const seeds:Seed[]=[
{slug:'ap-invoice-source-completeness-research',title:'Invoice-source completeness in outsourced AP research',excerpt:'Which source fields let an AP support lane prepare a reviewable invoice packet without guessing what the finance owner needs?',citations:[gao,nist,sba],body:[
'Research question: what makes an invoice packet complete enough for a finance owner to review? This report treats completeness as evidence coverage, not as a filled-in form. The packet must preserve the invoice as received, identify the supplier and billed entity, show the amount and currency, connect any order or receipt evidence, and state what remains unresolved. A support role can collect and compare those elements. It cannot make an absent approval, receipt, tax determination, or accounting conclusion appear complete. The central test is whether another reviewer can understand the item from the packet without relying on the preparer’s memory.',
'Methodology and evidence scope: we mapped the control principles in the GAO Green Book, NIST access and accountability guidance, and SBA finance-record guidance to a bounded AP preparation scenario. The sources describe control objectives and record discipline; they do not prescribe one software layout or prove a universal invoice standard. We therefore distinguish sourced principles from operational recommendations. The proposed test sample should include ordinary invoices, credit documents, invoices with missing pages, non-purchase-order items, and records crossing an entity boundary. Findings describe that sample only.',
'The first evidence layer is provenance. Retain the original attachment, the message or intake record that supplied it, and the date received. Use a stable identifier that connects the file to the queue record. If the attachment was replaced, preserve the earlier copy and explain why the replacement arrived. A filename such as “final invoice” is not enough to establish which document was reviewed. The support lane should flag unreadable pages, duplicate attachments, and conflicting versions instead of silently selecting the easiest one.',
'The second layer is comparison. Compare the supplier name, invoice number, invoice date, billed entity, currency, amount, purchase order or contract reference, and receipt or service evidence when applicable. Record “not present” separately from “not applicable.” That distinction matters because a missing receipt may require a request while a service that does not use receiving evidence may follow a different approved rule. Similar names and matching totals are useful signals, not proof of obligation or approval.',
'The third layer is ownership. Every unresolved field needs a named question and an owner who can answer it. The preparer may request a receipt from the requester, route an entity conflict to finance, or identify an approval gap. The preparer should not choose a substitute entity, certify delivery, approve an exception, or infer that a manager’s silence means acceptance. A dated next-review event keeps the issue visible when the owner cannot answer immediately.',
'A useful pilot measures packet reconstruction rather than speed alone. Ask a second reviewer to classify a sample as complete, missing evidence, conflicting evidence, or outside the lane. Record which source was needed to resolve each disagreement and how often the same field was absent. Do not turn the result into a promised accuracy rate or a comparison between teams without accounting for invoice mix, system differences, and review difficulty.',
'Access design follows the evidence boundary. The support worker needs intake and document access appropriate to the assigned queue, plus permission to add notes or request information. They do not need payment-release authority, unrestricted vendor-master editing, or the ability to approve their own preparation. Review temporary access after the pilot and remove permissions that the final lane does not require. This is a control recommendation grounded in least-privilege principles, not a claim about a particular company’s system.',
'Limitations are material. A complete packet does not prove the invoice is valid, the work was performed, the tax treatment is correct, or the organization should pay it. The external sources support control design, not a legal or accounting opinion. Local retention, privacy, tax, and approval policies still govern. The sample cannot establish that one field set works for every entity, supplier, or spend category.',
'Evidence-led conclusion: an outsourced AP lane is safest when “complete” means traceable source, explicit comparisons, visible gaps, and a named decision owner. Build the packet so the finance reviewer can accept, reject, request, or escalate based on preserved evidence. Do not measure preparation success by how many invoices disappear from the inbox; measure whether the next decision is understandable and authorized.'
]},
{slug:'ap-invoice-queue-aging-cause-research',title:'Cause-based aging of outsourced AP queues',excerpt:'How to separate waiting time caused by missing evidence, owner delay, and policy review in an AP support queue.',citations:[gao,nist,sba],body:[
'Research question: what does an aging AP queue actually tell a finance manager? An age number is useful only when its clock and cause are visible. This study separates elapsed time since intake from time waiting for a requester, approver, supplier, system correction, or policy decision. A support role can maintain those observations and route the next question. It should not close an old item simply to improve a dashboard or promise a payment date based on age alone.',
'Methodology: we translate control and recordkeeping principles from the GAO Green Book, NIST accountability guidance, and SBA finance guidance into an observation model for one AP queue. The evidence scope is a dated sample of open and recently closed invoices. We recommend preserving intake time, each status transition, owner assignment, evidence request, response, and close reason. This model is not a benchmark for response time and cannot establish that a particular delay is caused by an individual or department.',
'Use at least two clocks. The queue clock begins when the invoice enters the approved intake path. The active-owner clock begins when a named reviewer receives a complete question. A third clock can capture time waiting on external evidence. Showing these separately prevents a supplier delay from looking like preparation delay and prevents an internal approval delay from being hidden inside a broad “pending” label.',
'Cause categories should describe the next decision, not assign blame. Examples include missing receipt, missing approval, entity conflict, duplicate signal, vendor response pending, policy interpretation, system correction, and finance review. Each category needs a definition and a stop condition. If an item can sit in “finance review” for months with no owner or next date, the label is not managing the risk; it is only renaming inactivity.',
'Sample construction changes the answer. Include new invoices, near-due invoices, returned items, exceptions that changed owners, and items closed after a long wait. Compare the source queue with the current report so records that were reclassified or removed remain explainable. A median can hide a long tail, while a maximum can be dominated by one unusual dispute. Report the distribution with the evidence boundaries attached.',
'The support lane can update factual status, preserve correspondence, ask for missing records, and notify the documented owner when a review date arrives. It should not change a due date, approve an invoice, waive a control, or declare an exception resolved because a vendor stopped replying. A status note should state what was observed, when it was observed, and what authority is needed next.',
'A two-week trial can test whether cause labels improve handoffs. Measure the percentage of sampled items for which a reviewer can identify the current owner, evidence gap, and next event. Also count reclassification and reopened items. Those measures show whether the queue tells the truth; they do not prove productivity, service quality, or a staffing ratio. Keep sample size and exclusions visible.',
'Limitations: aging may reflect seasonal volume, unusual disputes, system outages, or a policy change. External control guidance does not define an AP response target. The method also cannot tell a finance owner whether a payment is economically wise or legally required. Those questions remain outside preparation and require the organization’s own policy and evidence.',
'Conclusion: cause-based aging turns an old invoice into a reviewable question. The best handoff names the clock, the waiting condition, the evidence held, and the authorized owner. A support team should make delay legible and actionable while leaving acceptance, exception disposition, and payment decisions with finance.'
]},
{slug:'ap-approval-evidence-chain-research',title:'Approval evidence chains for outsourced AP',excerpt:'A research model for proving which invoice evidence an approver saw without converting preparation into approval.',citations:[gao,nist,least],body:[
'Research question: when can a later reviewer tell what an invoice approver actually reviewed? An approval evidence chain connects the source invoice, prepared comparisons, exception notes, approver identity, decision time, and any conditions attached to the decision. A green status alone does not answer the question. This report studies the chain as a traceability problem for an outsourced AP preparation lane, where the support role prepares context but the authorized employee owns the decision.',
'Methodology and scope: the model maps GAO control objectives to NIST accountability and least-privilege concepts. It examines one approved queue and a sample containing ordinary approvals, returned invoices, delegated coverage, and changed packets. The sources support traceability and separation principles, not a prescribed approval application. We label recommendations as design choices and do not claim that the sample proves compliance or that every organization should use the same approval fields.',
'Start with version identity. The packet should show the exact invoice file, the preparation timestamp, the fields compared, and the source links used. If a correction arrives after approval, keep the pre-correction packet distinct and route the new version under the organization’s rule. A mutable attachment or overwritten note can make a valid approval impossible to reconstruct, even when the system still displays an approved status.',
'Next show the decision context. The record should identify the billed entity, amount, currency, order or contract evidence, receipt evidence where relevant, and the exception state. A preparer can summarize what agrees and what does not, but the summary must link back to the source. Do not use a short note such as “looks good” to stand in for missing evidence or an approval scope.',
'Approval identity is more than a name. Preserve the account or role used, the decision time, the applicable threshold or delegation reference, and any conditions or requested follow-up. An out-of-office message may explain why coverage was needed, but it does not itself prove authority. If the approval matrix and system route disagree, stop and route the authority question instead of selecting the more convenient record.',
'A review pilot should test reconstruction. Give a second reviewer a sample of approved and rejected items without the preparer’s verbal explanation. Ask what source was approved, what exception was accepted, and who could reverse or clarify the decision. Record ambiguity and missing links. Do not use the result as a universal approval-quality score because the sample, policy complexity, and reviewer experience affect it.',
'Role boundaries are practical. The support lane can assemble the packet, highlight contradictions, request missing documents, and route an approval task. It should not approve its own preparation, edit an approver’s decision, add authority by changing a threshold, or communicate that approval guarantees payment. Finance retains the authority to accept the evidence, reject it, or ask for more work.',
'Limitations: an evidence chain shows what was recorded, not whether the underlying goods or services were actually received. It does not settle tax, legal, accounting, or fraud questions. Retention and privacy requirements may limit what should be copied into a working packet. The organization’s policy determines the authoritative system and retention period.',
'Conclusion: approval becomes reviewable when source identity, prepared analysis, authority, decision, and later changes remain connected. Outsourced AP support can improve that chain by preserving context and exposing gaps. It must never improve the dashboard by filling an evidence gap or borrowing the decision that belongs to the finance owner.'
]},
{slug:'ap-vendor-inquiry-boundary-research',title:'Vendor inquiry boundaries in AP support research',excerpt:'What an AP support lane can answer about invoice status while protecting approval, bank-change, and payment-release boundaries.',citations:[cisa,gao,least],body:[
'Research question: which vendor questions can an AP support lane answer from records, and which require an authorized finance response? The distinction matters because a factual status update can become an accidental payment promise. This report separates observable intake, document, and workflow facts from decisions about acceptance, release, bank details, disputes, and timing. The support role should answer only from the approved record and should route everything that changes risk or authority.',
'Methodology: we mapped CISA phishing guidance, GAO internal-control principles, and NIST least-privilege concepts to common AP inquiries. The evidence scope is a sample of invoice-status, missing-document, remittance, and bank-detail questions. These sources support caution, authentication, and role separation; they do not define a company’s customer-service script, payment terms, or legal obligations. Those must come from the organization’s own records and policy.',
'A factual response can identify whether an invoice was received, whether a document is missing, whether an approval task is open, or whether a statement request was routed. The message should include the date or system status observed and avoid implying that the status will change. If the record is incomplete, say that the record is incomplete. A confident answer built from a search result or memory is not controlled evidence.',
'A decision response is different. “Can you pay this Friday?”, “Can you change the bank account?”, “Can you waive the receipt?”, and “Can you apply this credit?” all ask for authority. A support worker can preserve the request and route it to the owner; they should not answer yes, change master data, or select a payment run. The escalation record should capture the original request and the owner who must decide.',
'CISA’s warnings about urgency, unusual requests, and message-directed action are relevant when a vendor inquiry changes payment details or asks to bypass the normal channel. They do not prove a message is fraudulent. Use an independent, approved verification path and keep the request separate from the routine status queue. Never treat a reply to the requesting message as independent confirmation.',
'A pilot can review a dated sample of outbound and inbound messages. Classify whether each answer was factual, conditional, or a routed decision request. Check whether the source record, responder, timestamp, and escalation were retained. Measure ambiguity and unauthorized promises, not only response speed. A short response that creates a correction later is not a successful control outcome.',
'Access should match the communication task. The support role may need read access to invoice status and approved message templates, but not payment release or unrestricted vendor-master editing. Keep sensitive bank information out of ordinary correspondence when it is not needed. Review access when the queue or schedule changes and remove temporary permission after the assignment ends.',
'Limitations: external guidance does not determine the truth of a particular vendor’s claim or the organization’s contractual payment obligation. A recorded status can become stale between lookup and sending. Policies may require employee review of certain messages. This research offers a boundary model, not legal advice or a promise of response time.',
'Conclusion: the safest vendor answer is narrow, sourced, and explicit about what remains undecided. Outsourced AP support should reduce search and route questions quickly while leaving payment, bank, dispute, and exception decisions with the authorized owner. That boundary protects both the record and the relationship.'
]},
{slug:'ap-credit-application-evidence-research',title:'AP credit-application evidence research',excerpt:'How to compare open credits with candidate invoices without silently changing a vendor balance or accounting outcome.',citations:[gao,sba,least],body:[
'Research question: what evidence supports a candidate application of an AP credit, and what remains a finance decision? A credit memo can look easy to net, but the source may represent a return, pricing correction, tax adjustment, service dispute, or unapplied overpayment. This report treats matching as preparation evidence, not accounting authorization. The support lane can identify candidate relationships and preserve the record; the finance owner decides whether and how the credit is applied.',
'Methodology and scope: we mapped GAO control and evidence principles, SBA record guidance, and NIST least-privilege concepts to a sample of open credit memos and vendor statements. The sources do not prescribe a ledger treatment or tax policy. The sample should include credits with clear references, credits without invoice numbers, partial credits, multiple currencies, and credits near close. Findings describe evidence quality in that sample only.',
'Begin with provenance. Preserve the credit memo, the supplier message, the statement line, and the date received. Keep the original amount, currency, entity, and stated reason exactly as shown. A candidate invoice number from an email is not proof that the credit belongs there. If the supplier later replaces the document, retain the earlier version and make the change visible.',
'Matching requires more than amount. Compare supplier identity, entity, currency, reference, date, purchase context, and the related invoice or order. A partial amount may be correct, but it needs a source explanation. A credit that matches two invoices equally is unresolved. Record candidate matches separately from confirmed applications and do not net a balance in a working spreadsheet just to make the statement agree.',
'Age can prioritize research but cannot authorize treatment. Define whether the clock begins at issue, receipt, or posting according to policy. Separate an old credit waiting for a vendor response from one waiting for a finance decision. The support role can show the age and missing evidence, request clarification, and maintain the queue. It should not promise a refund, apply the credit, or tell the vendor the balance is final.',
'The pilot should test reconstruction by a second reviewer. Can they see why the candidate was selected, what evidence conflicts, and who owns the final decision? Record false candidates and credits that were resolved through a source other than the initial statement. Do not translate the sample into a recovery rate or claim that an aging band predicts a financial result.',
'Access design matters because credit work touches vendor balances and potentially sensitive records. Grant read access and note permissions needed for the preparation lane. Keep ledger posting, vendor-master editing, payment release, and tax decisions separate. When a temporary reviewer covers the queue, document the period and remove access when coverage ends.',
'Limitations: the evidence set cannot prove the supplier’s legal obligation, the accounting treatment, or the tax effect of a credit. Statement data may be incomplete or delayed. External control sources describe discipline and separation, not the organization’s own policy. Finance, tax, procurement, and legal owners may need to resolve the same item from different perspectives.',
'Conclusion: a credit application is ready for decision when the source, candidate match, conflicts, and owner are visible. A controlled outsourced AP lane makes those facts easier to review without silently editing the balance. The final application remains an authorized finance action, supported by the evidence the preparer preserved.'
]},
{slug:'ap-entity-routing-evidence-research',title:'Entity-routing evidence for multi-company AP',excerpt:'A source-led study of invoice entity conflicts when one supplier serves multiple companies or business units.',citations:[gao,irs,nist],body:[
'Research question: how can AP support expose an entity conflict without assigning an obligation to the wrong company? Supplier familiarity is not enough when a group has multiple legal entities, shared procurement, or centralized receiving. The preparation lane should compare the billed entity, order or contract, service location or recipient, vendor record, tax documentation where relevant, and intended approver. It should route a conflict rather than silently rewriting the invoice.',
'Methodology: the evidence model draws on GAO internal-control principles, IRS W-9 source-document guidance, and NIST accountability concepts. The scope is one multi-entity invoice queue sampled across ordinary and conflicting records. These sources support source comparison and role separation; they do not decide legal ownership, intercompany treatment, withholding, or tax classification. Those questions require the responsible finance or tax owner.',
'Preserve exact names and identifiers. A shortened business name may conceal the distinction between entities. Record the supplier name as shown, the billed-to field, the purchase-order entity, and any approved vendor-record identifier. If a tax form is present, link to it without treating it as a complete answer to accounting ownership. If a field is absent, mark it absent instead of selecting the most common entity.',
'Compare context as well as labels. A purchase order may identify one entity while a service receipt names another. A centralized buyer may place an order for several companies. Currency, contract, cost center, and approval route can provide useful clues but do not independently prove who owes the invoice. Keep agreeing fields and conflicting fields in separate notes so the owner can see why the route is uncertain.',
'The support role can request clarification from the requester, link the source records, and prepare candidate routes with their evidence. It should not move an invoice to make the queue cleaner, create a substitute vendor record, change tax fields, or approve an intercompany interpretation. If the source conflict could change payment or reporting, the item should remain visibly stopped until the owner decides.',
'A pilot should include recurring suppliers and one-off invoices. Record which source resolved each conflict, how often a supplier used multiple entity names, and whether the same intake field was missing. Segment the findings by invoice type and entity count. This describes the sampled operating problem; it is not a claim about a supplier’s quality or a universal routing rule.',
'Access must cover only the records required for comparison. Read access to invoices, orders, receipts, and approved vendor references may be sufficient. Keep vendor-master editing, tax configuration, ledger posting, and approval separate. Least privilege also improves attribution: the record shows who prepared the comparison and which owner made the accounting decision.',
'Limitations are important. A document set may not contain the legal or contractual evidence needed to decide ownership. W-9 materials are source documents, not tax advice. Shared services and intercompany arrangements can require specialized policy. External guidance cannot replace the organization’s chart of entities, accounting policy, or professional review.',
'Conclusion: multi-entity routing is a comparison task before it is a workflow task. A useful packet shows exact source values, the conflict, candidate interpretations, and the owner who can decide. Outsourced AP support should make ambiguity visible and preserve the record; it should never turn a plausible guess into a posting or payment.'
]},
{slug:'ap-payment-due-date-evidence-research',title:'Payment due-date evidence in AP preparation',excerpt:'How to distinguish invoice terms, receipt timing, disputes, and proposed payment dates before preparing a payment review.',citations:[sba,gao,least],body:[
'Research question: what evidence supports an AP due-date observation without turning it into a payment promise? Due date, invoice date, receipt date, approved terms, dispute status, and scheduled run are related but different facts. The preparation lane should show which source produced each date and which owner can resolve a conflict. A due date is not authority to release funds, and an urgency request is not evidence that terms changed.',
'Methodology and scope: we map SBA finance-record guidance, GAO control principles, and NIST least-privilege concepts to a payment-review packet. The sample should include ordinary invoices, changed terms, partial receipts, credits, disputed items, and invoices crossing a cutoff. External sources support evidence discipline and separation, not a particular organization’s terms or a guaranteed payment schedule.',
'Record the source date and the calculation basis. If terms come from an approved vendor record, link that record and preserve its effective period. If the invoice states different terms, flag the conflict. Do not treat a prior payment as proof of current terms, and do not copy a vendor email into master data without the approved change process.',
'A proposal can show due date, amount, currency, approval state, exception state, and recommended review priority. Label a proposed date as proposed. If the invoice is disputed or lacks approval, retain it in the exception population even when its due date has passed. Removing it from the report may make the calendar look orderly while hiding the decision that matters.',
'Cascading changes need their own evidence. A credit, corrected invoice, term amendment, or entity correction can change the review context. Preserve the prior packet and identify the changed field. The support worker can refresh the calculation and route the difference; finance decides whether the source is authoritative and whether the item belongs in a run.',
'A two-cycle sample can test whether a reviewer can reproduce the date. Record calculation disagreements, stale vendor records, missing receipt dates, and items whose proposed payment date changed. Report counts with sample boundaries. Do not claim that a small sample proves on-time payment performance or that an aging number predicts cash needs.',
'Access should allow preparation without release. The support lane may read invoice and approved terms records, prepare a list, and add factual notes. It should not approve invoices, alter vendor terms, verify bank changes by itself, or execute a payment run. A named finance owner reviews the proposal and records the disposition under the organization’s control process.',
'Limitations: payment terms may be contractual, jurisdiction-specific, or affected by disputes and credits. External guidance does not decide a contractual obligation or cash policy. System timestamps can differ from business events. This research describes a reviewable evidence model and does not provide legal, accounting, or treasury advice.',
'Conclusion: a payment calendar is trustworthy when every important date has a source, every exception stays visible, and proposed timing is clearly separated from authorized release. Outsourced AP support can prepare that evidence efficiently while keeping the decision and movement of funds with the finance owner.'
]},
{slug:'ap-receipt-gap-routing-research',title:'Receipt-gap routing in invoice review research',excerpt:'How to study missing receiving evidence without allowing an AP preparer to certify delivery or close the exception.',citations:[gao,nist,sba],body:[
'Research question: what should happen when an invoice has no receiving evidence, and what may an AP support role conclude? A missing receipt is an evidence gap, not proof that goods were not delivered and not permission to certify delivery. This report examines how to identify the gap, route a factual request, retain the response, and keep approval with the authorized owner. The niche problem is especially important when invoice preparation is separated from receiving and finance.',
'Methodology: we translate GAO control principles, NIST accountability concepts, and SBA record guidance into a bounded sample of purchase-order invoices. Include complete matches, services without conventional receipts, partial deliveries, returned goods, and invoices where the receipt is stored in another system. The sources support traceability and separation, not an organization’s receiving policy. Classify recommendations as recommendations rather than external facts.',
'First distinguish absence from mismatch. “No receipt found” means the search did not locate the record; “receipt quantity differs” means two known records conflict; “service evidence required” means another approved form may apply. A broad “receipt issue” label hides the next question. Record systems searched, search date, reference used, and the person or team who can provide the missing evidence.',
'The support lane can compare invoice quantity, order quantity, receipt quantity, dates, and unit context when the records are available. It can draft a request to the requester or receiver and preserve the reply. It cannot certify delivery, edit the receipt, approve an exception, or infer that payment is safe because an employee says the service was performed in an informal message.',
'Partial deliveries need separate treatment. The invoice may cover a shipment, milestone, subscription period, or combined service. Matching only the total amount can hide a quantity or timing issue. Keep the source documents connected and ask the owner to decide whether the invoice is payable, should be held, or needs a corrected document. The preparation note should describe the discrepancy without choosing the outcome.',
'A pilot can measure how often the original intake contained the evidence, how often it was found elsewhere, and how often the owner required a new source. Include reopened exceptions and items closed after an owner decision. These measurements identify intake and handoff weaknesses in the sample; they do not establish receiving performance or a universal three-way-match tolerance.',
'Permissions should reflect the lane. Read access to purchase orders, invoices, and approved receipt records may be needed. Edit rights to receiving, ledger, approval, and payment systems should remain separate unless the organization explicitly defines a controlled role. Review temporary access and retain the final owner decision with the source evidence.',
'Limitations: some services use evidence other than a warehouse receipt, and local policy may define acceptable substitutes. External guidance cannot determine whether work was actually performed. A completed receipt in a system may itself contain an error. This research is a process-design aid, not an accounting conclusion or an instruction to bypass a control.',
'Conclusion: a receipt gap is useful when it becomes a precise, owned question. Outsourced AP support can find and document that question, protect the source trail, and keep the queue moving toward review. It should never convert a missing document into a delivery assertion or an approval.'
]},
{slug:'ap-invoice-currency-exception-research',title:'Invoice-currency exception research for AP support',excerpt:'How to expose currency, entity, and terms conflicts while leaving conversion and payment decisions with finance.',citations:[gao,sba,nist],body:[
'Research question: what can AP support establish when an invoice currency differs from the purchase order, vendor record, or payment proposal? Currency is not merely a display field. It affects amount comparison, terms, tax context, approval thresholds, and cash planning. The preparation role can identify the conflict and preserve the source values; it should not choose a conversion rate, rewrite the invoice, or approve the resulting obligation.',
'Methodology and evidence scope: the model maps GAO internal-control principles, SBA financial-record guidance, and NIST accountability and access concepts to a sample of multi-currency AP records. The sources support source preservation and role separation, not a specific accounting policy or exchange-rate source. Include invoices in the expected currency, invoices with a changed currency, credit notes, and invoices crossing an entity boundary.',
'Preserve original values before calculating anything. Record invoice currency, amount, order currency, vendor-record currency, entity, invoice date, proposed rate source if policy allows a calculation, and the date used. A converted amount without the source currency and rate basis cannot be reconstructed. Avoid rounding in a working note unless the policy defines it, and do not overwrite the supplier’s stated amount.',
'A currency mismatch may be legitimate or may signal a wrong entity, wrong order, amended terms, or source error. Compare the contract or approved terms when available, but treat every agreement as evidence to be reviewed rather than a shortcut. If two sources conflict, keep both visible and route the question to finance, procurement, or tax as appropriate.',
'The support lane may calculate a draft comparison using the approved rate source and label it draft. It should not change master data, approve a threshold exception, promise a settlement amount, or release a payment. The owner decides which date and rate apply, whether the invoice is accepted, and whether a correction is required.',
'A pilot should compare the calculated result with the authoritative system outcome for a dated sample. Record missing rates, stale terms, rounding differences, and rework caused by entity conflicts. Analyze by currency and invoice type because a small sample dominated by routine transactions can hide unusual risk. Do not present the result as a forecast of foreign-exchange exposure.',
'Access should be limited to records and calculation tools needed for preparation. Keep vendor-master, ledger, bank, payment, and tax configuration permissions separate. If a support worker handles sensitive financial records, review access and retention under the organization’s policy. The goal is attribution and reviewability, not maximum system reach.',
'Limitations: exchange-rate rules, tax treatment, contracts, and statutory records can vary. External guidance cannot determine the correct accounting treatment. A draft calculation may become stale as rates change, and a matching currency does not prove the invoice is valid. Finance and tax owners retain the final interpretation.',
'Conclusion: currency exceptions become manageable when source amounts, rate basis, effective date, and owner decision are separated. An outsourced AP lane can prepare a transparent comparison and surface the risk. It should leave conversion authority, accounting treatment, and payment release with the authorized finance process.'
]},
{slug:'ap-close-cutoff-exception-research',title:'AP close-cutoff exception research',excerpt:'A research method for carrying late invoices and unresolved AP evidence into month-end close without hiding them in a checklist.',citations:[gao,sba,nist],body:[
'Research question: what evidence should a month-end close owner see when an AP item arrives near or after cutoff? A cutoff list is not just a checklist of received invoices. It should distinguish source date, receipt date, service period, approval state, exception reason, and owner disposition. The support role can assemble and reconcile that population; the finance owner decides close treatment and accounting effect.',
'Methodology and scope: this report maps GAO control principles, SBA finance-record guidance, and NIST accountability concepts to one close cycle. Sample ordinary invoices, late invoices, credit memos, unapproved items, and items reopened after a correction. External sources support evidence and ownership, not a universal cutoff time or accounting policy. Keep the policy and selected sample explicit so the finding is not overstated.',
'Record three moments separately: when the supplier issued the document, when the organization received it, and when the service or goods period occurred. A late receipt can relate to an earlier service period, while an invoice date can be backdated or corrected. Do not infer close treatment from one date. Preserve the source and route the difference to the named close owner.',
'The exception queue should show what is known, what is missing, and what decision is due. Examples include received after cutoff, service period unclear, approval pending, receipt missing, duplicate signal, and credit not applied. A single “late invoice” status can hide several different owners and actions. Use a dated next-review event so the item survives the close handoff.',
'A close packet benefits from reconciliation. Compare intake records, mailbox or portal records, open purchase orders, vendor statements, and prior exception queues where approved. Reconciliation is a comparison, not permission to create an accrual, post an entry, or remove an item. The support note should point to the source population and show exclusions so a reviewer can understand what was not tested.',
'A pilot across two closes can measure completeness of the handoff: source linked, period stated, exception coded, owner named, and disposition retained. Record reopened items and changes after the initial handoff. These are evidence-quality measures for the tested cycle, not a close-accuracy claim or a benchmark for another organization with different systems and policies.',
'The support role can gather records, maintain the late-item queue, request missing evidence, and route questions. It should not decide accruals, alter cutoff dates, approve invoices, or tell a supplier that a late item will be paid. Access to the ledger and close controls should be read-only or otherwise limited to the documented lane.',
'Limitations: close treatment is governed by accounting policy, materiality, contracts, tax rules, and professional judgment. External control sources do not answer those questions. A complete close packet cannot prove that no unrecorded obligation exists. It can show what population was searched, what evidence was found, and where judgment remains.',
'Conclusion: a controlled AP close handoff makes late evidence visible without pretending the support lane can make the accounting decision. The useful outcome is a traceable population, explicit gaps, and a named finance owner for each disposition. That is stronger than a clean checklist with no source trail.',
'The close owner should also document what happens after the first decision. If an invoice is held for a missing receipt, show whether the next review returns to the same owner or moves to a different queue. If a source arrives after close, preserve its arrival and connect it to the original exception rather than treating it as a new, unrelated invoice. If the item is excluded from the tested population, state the reason and who approved the exclusion. These details keep a close handoff from becoming a one-day snapshot. They also make later research possible: the team can examine whether late evidence reflects supplier timing, intake design, approval coverage, or a recurring system problem. A support role can maintain that chronology and prepare the questions. The close owner still determines the accounting treatment, materiality, and final disposition under the organization’s policy.'
]},
{slug:'ap-sensitive-document-access-research',title:'Sensitive AP document access research',excerpt:'How to design an outsourced AP document lane that preserves evidence while limiting exposure to payment and vendor data.',citations:[least,nist,gao],body:[
'Research question: what access does an AP support role need to prepare invoice packets without exposing unnecessary vendor, bank, employee, or payment information? The answer begins with the lane’s inputs and outputs, not with a broad job title. This report examines document classification, least privilege, temporary coverage, access review, and evidence retention for a finance team using outsourced AP support.',
'Methodology and evidence scope: we map NIST least-privilege and access-control guidance to GAO internal-control principles, then test the model against invoice intake, statement reconciliation, exception follow-up, and payment-preparation scenarios. The sources support access discipline and accountability, not a particular application role or legal retention schedule. The analysis separates facts from recommendations and does not claim an organization is compliant merely because it follows this model.',
'List the records required for the starting queue. Invoice files, order or receipt evidence, approved vendor references, and status history may be necessary. Bank details, employee tax data, payment credentials, and unrelated entity records may not be. Minimize copies and avoid placing sensitive values in email or ad hoc spreadsheets when the approved system can hold the source. The role should see the evidence needed for its decision boundary, not everything available to finance.',
'Permissions should follow actions. Read access supports comparison; note access supports factual preparation; routing access supports escalation. Approval, ledger posting, vendor-master editing, bank-detail changes, payment release, and deletion are distinct authorities. If a system bundles them, use workflow controls or a narrower operational process. A convenient shared account weakens attribution and makes later review harder.',
'Temporary access deserves the same attention as standing access. Document the assignment, scope, start date, end date, and approving owner. Review whether the user still needs access when the queue expands or changes. Remove coverage permissions promptly after the window. A worker who changes roles should not retain access because the original group or system default left it in place.',
'A pilot can test both usability and exposure. Ask whether the preparer can complete representative tasks with the minimum role and whether a reviewer can identify who opened, changed, or routed the record. Record blocked tasks, workarounds, and unnecessary data visible in the interface. Do not solve friction by granting broad access without documenting the new risk and owner approval.',
'Evidence retention must not become uncontrolled duplication. Preserve the authoritative source and link it from the work record. If a working copy is required, label it, restrict access, and follow the organization’s retention and deletion rules. Never create a private archive of bank details or vendor identity documents for convenience. A complete packet must also be a governed packet.',
'Limitations: access risk depends on application configuration, identity controls, endpoint security, privacy rules, and the organization’s contracts. NIST and GAO guidance are not a substitute for a security review. The model cannot establish that a role is safe without inspecting actual permissions, logs, and process behavior.',
'Conclusion: outsourced AP access should be designed around a small, observable lane with explicit stop conditions and reviewable ownership. Least privilege is not merely a security slogan; it keeps preparation separate from approval and limits the impact of a mistake. The finance owner should approve the boundary and revisit it when scope changes.'
]},
{slug:'ap-w9-document-collection-research',title:'W-9 document collection boundaries in AP research',excerpt:'What AP support can collect and compare about W-9 records while keeping tax classification and vendor acceptance with the responsible owner.',citations:[irs,gao,least],body:[
'Research question: how can an AP support lane collect a missing W-9 without turning document intake into tax advice or vendor acceptance? A tax form is a source record with sensitive identifiers, not a simple checkbox. The support role can request the approved document, check whether required fields appear present, preserve the source, and route discrepancies. The responsible tax or finance owner decides classification, withholding, and acceptance.',
'Methodology and scope: the analysis uses IRS information about Form W-9, GAO internal-control principles, and NIST least-privilege concepts. The evidence scope is a sample of vendor records with complete forms, missing forms, changed names, and conflicting tax identifiers. IRS guidance is authoritative for the form’s purpose, but this report is not tax advice and does not infer a vendor’s correct classification from a visual check.',
'Collection starts with the approved request channel. Record who requested the form, the vendor or payee identity used, the date sent, the response date, and the location of the returned document. Avoid asking vendors to send sensitive tax data through an unapproved channel. If a form arrives from an unexpected address or with an urgent bank-change request, preserve the message and route it through the organization’s verification process.',
'A preparation review can check whether the form is legible, signed or otherwise completed under the organization’s rule, and associated with the intended vendor record. It can compare names and identifiers for obvious mismatch and flag blank or contradictory fields. It should not decide whether a classification is correct, alter the form, copy sensitive numbers into a new file, or activate a vendor.',
'Conflicts need distinct routing. A name difference may reflect a legal-name update, a trade name, a merger, or an error. A tax identifier mismatch may require a direct owner review. A missing signature may be a form-completion problem. Combining all of these into “W-9 issue” hides the action and can cause a preparer to resolve a tax question by guesswork.',
'A pilot should sample complete and stopped records and ask an authorized reviewer to reconstruct what was collected, what was compared, and what decision remains. Measure missing source, unclear association, duplicate copies, and owner rework. Do not report a completion percentage as proof of tax compliance. The sample and the organization’s tax process determine what the result means.',
'Access should be tightly limited because W-9 records contain sensitive information. The support worker needs only the approved intake and vendor-record views required for the lane. Keep tax configuration, vendor activation, bank changes, payment release, and final acceptance separate. Review retention and deletion under the organization’s privacy and records rules.',
'Limitations: the IRS form and instructions do not resolve every tax or vendor-governance question. A legible form may still contain incorrect information. External control guidance cannot establish legal identity or withholding treatment. Escalate uncertainty to the responsible owner and preserve the exact question rather than offering a tax conclusion.',
'Conclusion: W-9 support is a controlled collection and evidence task. Outsourced AP can improve follow-up and traceability by keeping requests, responses, and mismatches visible. It must leave classification, acceptance, activation, and tax decisions with the authorized finance or tax process.'
]},
{slug:'ap-duplicate-signal-review-boundaries-research',title:'Duplicate-signal review boundaries in AP research',excerpt:'How to investigate repeated invoice signals without treating a similarity match as proof of fraud, error, or rejection.',citations:[gao,nist,cisa],body:[
'Research question: what can a duplicate-invoice signal establish before an authorized reviewer examines the source? Matching vendor, invoice number, amount, date, currency, attachment, or purchase order can identify a candidate relationship. It cannot by itself prove a duplicate, fraud, or an invoice should be rejected. This report defines a reviewable investigation lane for outsourced AP preparation and keeps the final disposition with finance.',
'Methodology: the model maps GAO control principles, NIST accountability and access concepts, and CISA caution around suspicious requests to a dated sample of invoice records. Include true repeats, credit-and-rebill pairs, partial invoices, recurring charges, corrected documents, and close vendor names. The external sources support evidence preservation and escalation, not a universal matching algorithm or fraud conclusion.',
'Preserve the signal inputs. Record the records compared, the fields that matched, the fields that differed, the search date, and the source files. A system score without its underlying fields is difficult to review. Do not overwrite a candidate record with a “duplicate” label before the owner sees the evidence. Keep the original invoice and any correction linked but distinct.',
'Context changes interpretation. The same invoice number may recur across entities or years. An identical amount may represent a subscription or installment. A credit memo can resemble a negative invoice, while a replacement invoice may intentionally reuse a reference. Compare entity, service period, order, receipt, currency, and document type before recommending a route. Similarity is a prompt for questions, not a decision.',
'The support role can assemble candidate pairs, preserve suspicious correspondence, request confirmation from the documented owner, and stop an item under the approved rule. It should not reject an invoice, accuse a supplier, delete a record, approve a payment, or mark a signal harmless because one field differs. If a request uses urgency or asks to bypass a control, route it independently rather than relying on the sender’s explanation.',
'A pilot should measure investigation quality. For a sample of high and low signals, ask a second reviewer whether the evidence supports the candidate, what remains unknown, and who decided. Record false positives, reopened items, and signals discovered after approval. Do not turn those counts into a fraud rate or claim that a detector works equally across systems and vendor populations.',
'Access should permit comparison but not the authority to erase or release. Read access to invoices and related records, plus note and routing permissions, may be sufficient. Keep vendor-master editing, ledger posting, approval, bank changes, and payment release separate. Preserve audit events and review temporary access after any investigation assignment ends.',
'Limitations: no document comparison can prove intent. External guidance cannot establish fraud, contractual breach, or a required accounting outcome. Data quality and field normalization affect signals. The organization’s fraud response and escalation policy governs the next action, while this research only defines what evidence a preparation lane can assemble.',
'Conclusion: duplicate review is strongest when the candidate relationship, differences, source files, and decision owner are visible. Outsourced AP support can reduce search time and preserve suspicious evidence without making an accusation or taking an approval shortcut. The result is a better question for finance, not an automatic verdict.'
]}
];

const supplements:Record<string,string[]>= {
 'ap-invoice-source-completeness-research':[
  'For implementation, make the packet fields answer the questions a reviewer actually asks: what arrived, what was compared, what is missing, and who can resolve it. A field should have a source location or an explicit not-found note. Avoid forcing the preparer to choose from values that imply approval, such as “valid,” “payable,” or “accepted.” Better labels are “source located,” “comparison prepared,” and “owner decision pending.” This vocabulary preserves the distinction between preparation and judgment while still making queue status useful.',
  'When evidence comes through several channels, the intake record should identify the authoritative copy. A portal attachment, forwarded email, scanner image, and supplier correction may all describe the same invoice. Keep their relationship visible and do not let a late correction erase the first version. The finance reviewer can then determine whether the change is administrative, substantive, or a reason to request a new approval. The support lane’s contribution is a clean chronology, not a conclusion about materiality.',
  'The practical control test is a blind handoff. Remove the preparer from the conversation and ask another reviewer to locate the invoice, explain the comparison, identify the open question, and name the next owner. If the reviewer has to ask where a file came from or whether a missing field was searched, the packet is not yet complete. Repeat the test after changing the intake instructions and preserve both examples so process improvement is evidence-led.'
 ],
 'ap-invoice-queue-aging-cause-research':[
  'A cause taxonomy should be small enough to use consistently but specific enough to trigger action. Test each label against five prompts: what started the wait, what evidence is absent, who can answer, when should the item be reviewed, and what closes the condition? If a label fails one of these prompts, revise it before publishing an aging report. Keep a free-text factual note for unusual cases rather than expanding the taxonomy every time an invoice is different.',
  'Queue reports should show movement as well as age. A record that moved from requester follow-up to finance review has a different operating story from one that sat untouched in an unassigned inbox. Preserve status-transition timestamps and the reason for each transfer. Do not reset the original intake clock when ownership changes. A new owner needs context, and a manager needs to know whether the queue is aging because of demand, evidence quality, or authority.',
  'Use the result to improve the handoff, not to create a contest over the lowest age. Review outliers with the named owner and retain representative examples. If one missing field repeatedly creates long waits, change the intake requirement or the source request. If approvals are the bottleneck, the finance owner may need a policy or coverage decision. The support lane can reveal the pattern, but only the responsible owner can change the governing rule.'
 ],
 'ap-approval-evidence-chain-research':[
  'An approval packet should make later changes legible. If a corrected invoice arrives, link the correction to the original, state which fields changed, and identify whether the prior approval remains applicable under policy. Do not copy the old approval onto the new document. A reviewer must be able to distinguish “approved version one,” “correction received,” and “new decision required.” This is especially important when the amount, entity, service period, or supplier identity changes.',
  'Delegation evidence deserves a separate field from the approver’s name. Record the effective period, scope, source of authority, and any threshold or entity limits. A backup reviewer may be available without being authorized for every decision. If the system route is broader than the written delegation, preserve the conflict and escalate. Convenience is not evidence that an approval path was valid.',
  'Review the chain after an item is paid as well as before approval. The purpose is not to reopen settled decisions automatically; it is to learn whether the source and decision remain reconstructable. Sample ordinary items and exceptions, document missing links, and ask the finance owner which record is authoritative. Findings can improve system configuration and packet design without turning the support role into a retroactive auditor.'
 ],
 'ap-vendor-inquiry-boundary-research':[
  'Use a response matrix with three columns: observable record, safe wording, and escalation trigger. “We received the invoice on [date]” is factual when the source supports it. “We are reviewing the approval status” is conditional and should identify that no payment decision is being made. “Please confirm these new bank details” is a trigger for independent verification, not a routine reply. The matrix should be approved by the organization and updated when systems or policies change.',
  'A response can create risk even when every sentence is technically true. A vendor may read “approved” as “payment released,” or “scheduled” as a commitment if the message omits the owner’s conditions. Keep approval, proposed timing, and release status separate. If the record cannot distinguish them, route the inquiry rather than improvising language. Preserve the final message with the source status used at the time it was sent.',
  'Sample messages at the boundary, not only easy status requests. Include urgent requests, repeated follow-ups, a changed remittance instruction, an invoice with no approval, and a request to bypass the portal. Ask a reviewer whether the response exposed the source, avoided an unsupported promise, and routed the decision correctly. The most valuable finding may be a missing template or a need for employee review.'
 ],
 'ap-credit-application-evidence-research':[
  'The candidate-match note should explain both the attraction and the doubt. State which identifiers agree, which amounts or periods align, and which facts prevent confirmation. If the credit could apply to several invoices, list the candidates without ranking them unless policy authorizes a ranking method. This allows the finance owner to apply judgment with the source in view and prevents a preparer’s guess from becoming a ledger outcome.',
  'Statement reconciliation can help locate an open credit but does not replace the credit memo or owner decision. Preserve the statement period, retrieval date, and supplier references separately. A supplier statement may omit a recent transaction or contain a balance that includes disputed items. If the statement and ledger disagree, record the disagreement and route it. Never delete the credit from the work queue because a later statement happens to show a zero balance.',
  'Close the research loop with a disposition record: applied, refunded, disputed, carried forward, corrected, or unresolved, using the organization’s approved vocabulary. Record the deciding owner and date, and link the source that supports the disposition. A closed status without the decision evidence is not a complete result. Review a sample of closed credits later to ensure the packet still explains what happened.'
 ],
 'ap-entity-routing-evidence-research':[
  'Candidate routes should be presented as alternatives with evidence, not as a hidden correction. For each candidate, state the source that supports it and the fact that remains unresolved. This makes the finance owner’s question concrete: confirm entity A, confirm entity B, request a corrected invoice, or apply a documented intercompany rule. The support lane can reduce the search burden without crossing into legal-entity judgment.',
  'Recurring supplier patterns deserve a master-data conversation, not a shortcut. If one vendor routinely sends invoices with ambiguous entity names, collect examples and show the cost of repeated clarification. The owner may decide to improve the purchase-order instruction, create a controlled vendor-record distinction, or change the intake form. Until that decision is documented, a support worker should continue to surface each invoice’s own evidence rather than relying on precedent.',
  'The audit trail should retain the owner’s response in the same place as the comparison. A chat message may be useful context, but the approved record must identify who decided and when. If the decision is temporary, record its effective period. A later reviewer should not have to infer from a previously routed invoice that the same treatment applies today.'
 ],
 'ap-payment-due-date-evidence-research':[
  'A due-date review benefits from a source hierarchy approved by finance. The hierarchy might distinguish contract terms, approved vendor terms, invoice terms, and an exception decision, but this report does not select the hierarchy for the organization. Once approved, use it consistently and record which source won when records disagree. Do not let the most recent email silently override the authoritative terms.',
  'Keep the payment proposal reversible until the owner signs off. Show included and excluded records, the reason for each exclusion, and the extraction time. If the queue changes after preparation, record the refresh rather than editing the original proposal without explanation. This protects the reviewer from approving a population that no longer matches the evidence and gives treasury a clear boundary around the preparer’s work.',
  'Review urgent vendor requests as a separate risk population. A request to pay early, change terms, or bypass an approval may be legitimate, but urgency is not proof. Preserve the request, verify through the approved channel, and route the policy decision. The support lane can identify the requested action and its source; it should not convert urgency into a due date or a payment commitment.'
 ],
 'ap-receipt-gap-routing-research':[
  'Requests for missing receipts should be precise and neutral. Identify the invoice, order line or service period, quantity or amount in question, and the evidence needed. Do not ask the requester to confirm “everything is correct” when the actual question is whether a particular delivery occurred. A narrow question produces a more useful response and makes the owner’s later decision easier to defend.',
  'When a substitute document is acceptable under policy, record the rule and the source that qualifies it. A signed email, service report, milestone certificate, or receiving record may answer different questions. Do not create a substitute because it is convenient. The owner should decide whether the source meets the organization’s requirement, and the packet should retain the exact evidence used.',
  'Exception aging should preserve the original receipt gap even after a response arrives. Mark the response received, identify the document, and route the item for the next decision. If the owner rejects the substitute, keep the reason visible rather than returning the item to a generic pending state. This history shows whether intake instructions, receiving practice, or finance review needs attention.'
 ],
 'ap-invoice-currency-exception-research':[
  'A currency comparison should be reproducible by a second person. Record the rate source, timestamp, effective date, precision, and rounding rule used for any draft calculation. If the policy forbids a preparer from calculating a conversion, record the source values and leave the calculation to finance. A transparent blank is safer than a precise number with an unapproved basis.',
  'Watch for currency conflicts that are really identity conflicts. A foreign-currency invoice may have been sent to the wrong entity, linked to an old purchase order, or generated after a contract amendment. Compare the surrounding facts before treating the issue as a rate problem. The best escalation names the competing explanations and points to the source that would resolve each one.',
  'After the owner decides, retain both the preparation comparison and the authoritative outcome. If a rate or term changes, show the reason and effective date. Review repeated exceptions by supplier, entity, and transaction type; recurring patterns may justify an intake or master-data change. They do not justify applying a local workaround to every future invoice.'
 ],
 'ap-close-cutoff-exception-research':[
  'A close handoff should include exclusions as well as included items. State which intake sources, dates, entities, and document types were searched, then list the known gaps. An empty result can mean no items were found or that the search did not reach the relevant source. Preserve search evidence and owner sign-off so the finance reviewer can distinguish those possibilities.',
  'Late invoices need a chronology, not a blame label. Show issue date, receipt date, service period, approval state, and the request or event that brought the item into the queue. If a supplier delayed a document, record that fact without concluding why. If internal review delayed it, identify the open authority question. The support lane documents the chronology and routes the judgment.',
  'Carry unresolved items into the next review with their original identity. Do not create a fresh record that resets age or loses the prior owner’s question. When the close owner decides, retain the disposition and source. A durable handoff makes the next close faster because the team can see what was already established and what remains open. Note whether the item was included in the close population, excluded pending evidence, or transferred to another owner. That small distinction prevents a later reviewer from mistaking a carried item for a newly discovered obligation. It also lets the team compare recurring cutoff problems without changing the underlying record.'
 ]
};
const finalReview=(title:string)=>`A final review of ${title.toLowerCase()} should be performed against real source records, but it should remain a bounded review rather than an informal audit. Select examples before the queue is cleaned up, include at least one item that stopped and one that proceeded, and record the selection rule. Ask the reviewer to locate the source, explain the preparation, identify the unresolved decision, and name the person authorized to make it. Capture disagreements as findings instead of correcting the sample silently. This approach helps a finance team distinguish a missing instruction from a missing document, a system limitation from a permission problem, and a policy question from ordinary follow-up. It also makes a proposed outsourced lane easier to supervise because the owner can see what the preparer was expected to notice and what the preparer was explicitly not allowed to decide. The result should identify a next experiment, such as changing an intake field, narrowing a permission, clarifying a status, or adding an escalation route. Do not present the experiment as a guarantee of lower cost, faster payment, fewer exceptions, or better vendor outcomes. Those outcomes require their own measures, time period, comparison design, and owner interpretation. Revisit the evidence after the agreed trial window, because a control that works for a clean sample may fail during close, staff coverage, or an unusual supplier request. Keep the original examples available so later improvements can be compared with the same evidence. The evidence-led value of this report is narrower: it gives the AP team a way to preserve facts, expose uncertainty, and hand a decision to the right role.`;
export const aug18ResearchBatch:ResearchPost[]=seeds.slice(0,10).map(s=>({...s,body:[`Publication date: August 18, 2026. ${s.body[0]}`,routeEvidence[s.slug],...s.body.slice(1),...(supplements[s.slug]||[]),sharedResearchDepth,finalReview(s.title)],published:aug18ResearchPublicationDates[s.slug],modified:aug18ResearchPublicationDates[s.slug],thumbnail:'/research-thumbnails/aug18-research.svg',keywords:['accounts payable outsourcing','AP research','finance operations'],internalLinks:links,cta:'Use this research to define a controlled AP support lane.'}));
