type Post={slug:string;title:string;excerpt:string;published:string;modified:string;thumbnail:string;body:string[];citations:{label:string;href:string}[];internalLinks:{label:string;href:string}[];serviceHandoff:{heading:string;body:string;href:string;label:string}};
const date='2026-08-31';
const links=[{label:'Invoice intake completeness gate',href:'/blog/ap-invoice-intake-completeness-gate'},{label:'AP quality correction loop',href:'/blog/ap-quality-sample-correction-loop'},{label:'AP close owner map',href:'/blog/ap-close-open-item-owner-map'}];
const serviceHandoff={heading:'Translate evidence into a controlled role',body:'Define the source records, preparation tasks, exception states, review cadence, and employee decisions before granting access.',href:'/contact-us',label:'Scope an AP support role'};
const sources={nist:{label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},cisa:{label:'CISA: Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'},gao:{label:'GAO Green Book',href:'https://www.gao.gov/greenbook'},fbi:{label:'FBI: Business Email Compromise',href:'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'},coso:{label:'COSO Internal Control resources',href:'https://www.coso.org/internal-control'}};
const make=(slug:string,title:string,excerpt:string,thumbnail:string,question:string,evidence:string,boundary:string,citations:Post['citations']):Post=>({slug,title,excerpt,published:date,modified:date,thumbnail,citations,internalLinks:links,serviceHandoff,body:[
`This review asks ${question}. It synthesizes public control guidance into an accounts payable workflow and does not claim a universal benchmark, legal conclusion, or guaranteed outcome. The method compares guidance on source integrity, accountable access, documented transactions, and timely review.`,
`Across the cited guidance, reliable control depends on attributable actions and information another reviewer can inspect. For this topic, the useful evidence set is ${evidence}. A copied value without a link to its source remains an observation, not a resolved decision.`,
`The central planning signal is reproducibility. A reviewer should be able to identify scope, source timestamps, checks performed, conflicts found, the current owner, and the exact response needed. Totals and generic pending labels cannot provide that trail by themselves.`,
`In an outsourced AP model, ${boundary}. Approval, vendor-master authority, accounting judgment, and payment release remain with specifically authorized company employees and should be recorded as separate events.`,
`Implementation should begin with a small queue, named accounts, stable identifiers, explicit exception states, and a fixed review cadence. Test an ordinary case, an incomplete case, a conflicting case, and a case that creates pressure to bypass the written route.`,
`The evidence supports a bounded preparation role with retained sources and attributable escalation. Each organization still needs to set retention, access, materiality, and approval rules for its own systems and obligations.`,
]});
export const aug31ResearchBatch:Post[]=[
make('ap-invoice-data-provenance-research','AP invoice data provenance: a control-oriented research review','A source-backed review of why invoice fields need traceable origins, timestamps, and correction history in outsourced AP workflows.','/research-thumbnails/invoice-intake-control-research.svg','how invoice data can keep a traceable origin as it moves from receipt into an accounting workflow','the original message or portal record, receipt time, stable file reference, extracted fields, corrections, and reviewer identities','support may capture fields, link sources, identify omissions, and maintain exception status',[sources.nist,sources.cisa,sources.gao]),
make('ap-payment-change-verification-research','Payment change verification in AP: evidence and role boundaries','Research on verification channels, segregation of duties, and retained evidence for supplier payment-detail changes.','/research-thumbnails/vendor-bank-change-control-research.svg','which evidence and role boundaries make supplier payment-detail changes reviewable','the incoming request, existing supplier record, changed fields, known contact route, verification result, employee approval, system action, and payment decision','support may log and hold the request, prepare a comparison, and initiate the approved verification route',[sources.fbi,sources.cisa,sources.nist]),
make('ap-exception-ownership-research','AP exception ownership: research on queues, evidence, and escalation','A research synthesis for designing AP exception states that expose the missing decision and accountable owner.','/research-thumbnails/ap-exception-aging-research.svg','what makes a distributed AP exception queue governable','the original source, reason code, first-seen date, requests, responses, next action, decision owner, and exit evidence','support may classify observable gaps, collect documents, send approved follow-ups, and maintain chronology',[sources.gao,sources.nist,sources.coso]),
make('ap-close-evidence-continuity-research','AP close evidence continuity across reporting cutoffs','Research on cutoff timestamps, open-item history, and reproducible AP close handoffs.','/research-thumbnails/ap-close-evidence-handoff-research.svg','how AP records can preserve what was known at cutoff while showing evidence received later','report scope and timestamp, entity, document identity, amount, source, first-seen date, unresolved question, later evidence, and employee decision','support may prepare reports, obtain documents, reconcile statements, and maintain open-item history',[sources.gao,sources.coso,sources.nist]),
make('ap-least-privilege-work-design-research','Least-privilege work design for outsourced AP support','A source-backed review of access scope, role separation, and recertification for outsourced accounts payable work.','/research-thumbnails/ap-outsourced-ap-access-review-research.svg','how least privilege can shape outsourced AP work from onboarding through offboarding','each permission, its named task and owner, account identity, authentication method, start and end dates, activity evidence, and recertification','support should receive only the queue visibility, document preparation, and factual-status access required for its defined lane',[sources.nist,sources.cisa,sources.gao]),
];
