import type {ResearchPost} from './research-batch';

const gao={label:'GAO: Green Book Internal Control Standards',href:'https://www.gao.gov/greenbook'};
const nist={label:'NIST SP 800-53 Rev. 5',href:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'};
const least={label:'NIST: Least Privilege Glossary',href:'https://csrc.nist.gov/glossary/term/least_privilege'};
const cisa={label:'CISA: Recognize and Report Phishing',href:'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'};
const irs={label:'IRS: About Form W-9',href:'https://www.irs.gov/forms-pubs/about-form-w-9'};
const links=[{label:'AP services',href:'/services'},{label:'AP inbox management',href:'/services/ap-inbox-management'},{label:'Research library',href:'/research'}];

type Seed={slug:string;title:string;excerpt:string;focus:string;analysis:string[];citations:ResearchPost['citations'];thumbnail:string;date:'2026-08-17';modified?:string;serviceHandoff?:ResearchPost['serviceHandoff']};
const seeds:Seed[]=[
{slug:'ap-invoice-exception-reason-coding-research',title:'Invoice exception-reason coding research',excerpt:'How AP teams can classify invoice exceptions without hiding the evidence gap behind a broad status label.',focus:'invoice exception-reason coding',date:'2026-08-17',thumbnail:'ap-exception-aging-research',citations:[gao,nist],analysis:[
'Research question: does an exception code help a finance owner decide what to do, or does it merely make the queue easier to count? A useful code identifies the evidence problem, such as missing receipt, conflicting entity, approval delay, duplicate signal, or owner policy question. “Other” may be necessary, but it should trigger a description rather than become the permanent destination for unclear work.',
'The code belongs beside the source, not in place of it. Keep the invoice identifier, the document or field that caused the stop, the date the issue was found, and the person who can answer it. Two records may share a code while requiring different owners. A missing receipt belongs with a receiver or requester; a payment-detail concern needs an authorized verification path.',
'Test the taxonomy on a dated sample of complete and stopped invoices. Count code changes after owner review because a frequent reclassification may show that the labels do not match the real decisions. Do not use the counts as a performance ranking without accounting for queue mix, source quality, and the amount of review each class requires.',
'A code should have a defined stop condition and a next action. If “approval pending” can remain open with no owner or review date, the label describes inactivity rather than control. If a code implies that an invoice is safe to pay, it exceeds the preparation role and should be rewritten as an observation.',
'A stable code set can reveal where intake instructions or source records need improvement. It cannot prove that the underlying vendor, buyer, or accounting process is at fault. Review recurring categories with the process owner and retain the source examples that led to the proposed change.',
'The AP support lane may select a code from an approved list, add a factual note, and route the item. The finance owner decides whether to accept an exception, request a correction, or leave the invoice stopped. That boundary keeps reporting useful without turning classification into approval.'
]},
{slug:'ap-vendor-statement-cutoff-evidence-research',title:'Vendor-statement cutoff evidence research',excerpt:'A bounded comparison of statement period, retrieval date, and open-item evidence for AP reconciliation.',focus:'vendor-statement cutoff evidence',date:'2026-08-17',modified:'2026-08-25',thumbnail:'ap-vendor-statement-reconciliation-research',citations:[gao,least],analysis:[
'Research question: which dates make a vendor statement reconciliation reviewable? The statement period, the date the statement was issued, and the date the AP team retrieved it answer different questions. Record them separately. A retrieval date cannot establish that a statement is complete through that date, and a statement date does not prove when the organization received it.',
'Preserve the full statement and its page count when the source provides one. List invoices, credits, payments, and unexplained lines with the identifiers shown by the supplier. Missing pages and truncated attachments are evidence gaps, not zero balances. A support role should request a complete statement rather than reconstructing the missing section from memory or a prior month.',
'Match candidates using more than supplier name and amount. Reference, date, currency, entity, and document type can distinguish a credit from an invoice or a repeated charge from a correction. Keep unmatched lines visible until the owner decides whether they are timing differences, disputes, duplicates, or obligations.',
'A two-week observation around one statement cycle can show where reconciliation stalls. Segment the result by statement format and vendor group. The sample cannot establish that a supplier’s balance is wrong or that one matching rule is suitable for every entity.',
'The packet should distinguish “matched to source,” “candidate match,” and “unresolved.” A candidate pair is not a confirmed reconciliation. The finance owner may ask the supplier, inspect the ledger, or apply an approved policy. The support role records that answer and does not net open items to make the statement agree.',
'Access should cover the statement and relevant AP records but not payment release or vendor-master editing. If a statement includes changed remittance instructions, preserve the message and route it through the independent verification path. Reconciliation and bank-change review are related evidence problems, not the same authority.'
],serviceHandoff:{heading:'Plan vendor statement reconciliation support',body:'A Philippines-based support role can request statements, compare open items, and keep missing evidence visible. Your finance owner still decides disputes, credit treatment, accounting entries, and payment action.',label:'Explore vendor statement reconciliation support',href:'/services/vendor-statement-reconciliation'}},
{slug:'ap-approval-threshold-drift-research',title:'Invoice approval-threshold drift research',excerpt:'How to detect when invoice routing no longer reflects the approved threshold or delegated authority.',focus:'invoice approval-threshold drift',date:'2026-08-17',thumbnail:'ap-approval-separation-research',citations:[gao,nist],analysis:[
'Research question: how can AP support identify approval-threshold drift without deciding who should approve an invoice? Compare the invoice amount, entity, currency, purchase context, and routing rule that was in force when the item entered the queue. A mismatch is a review signal, not permission to choose a more convenient approver.',
'Threshold evidence needs a source and effective period. A copied approval matrix may be old, while a system route may reflect a temporary delegation. Retain the policy reference or approved system record used for the comparison. If the sources disagree, stop and name the owner who can resolve the authority question.',
'Review a dated sample across ordinary amounts and near-threshold amounts. Include invoices that were rerouted, split, returned, or approved during a delegation window. The result can show where the process needs a clearer rule. It cannot prove that every invoice above or below a threshold should follow one route across entities.',
'Do not treat a manager’s availability as evidence of delegated authority. An out-of-office message, copied email, or prior approval may provide context but may not change the organization’s rule. The support note should state what was observed and ask the authorized owner to confirm the route.',
'Threshold drift may come from currency conversion, entity configuration, a changed policy, or an invoice that was divided across records. Keep those reasons separate. Combining them into “routing issue” hides whether the answer belongs to finance policy, system administration, procurement, or the approver.',
'The support lane can compare fields, flag the mismatch, and keep the approval state visible. It should not lower a threshold, add an approver, approve its own preparation, or promise that a rerouted invoice will be paid. Those actions require the owner named by the organization.'
]},
{slug:'ap-payment-run-exclusion-evidence-research',title:'Payment-run exclusion evidence research',excerpt:'What an AP payment proposal should retain when approved invoices are held out of a run.',focus:'payment-run exclusion evidence',date:'2026-08-17',thumbnail:'ap-payment-calendar-control-research',citations:[gao,least],analysis:[
'Research question: when is an excluded invoice understandable to the payment-run reviewer? The record should show the invoice, the source status, the exclusion reason, the owner, and the next review event. “Not in this run” is not enough because it does not distinguish a hold, a missing approval, a duplicate signal, a bank verification stop, or a scheduling choice.',
'Build the exclusion population from the approved queue and the run’s defined cutoff. Record the extraction time because the queue can change while the proposal is prepared. Do not add an invoice because a vendor requests urgency or remove one to make a total convenient.',
'A two-week sample can compare proposed exclusions with the eventual owner dispositions. Classify changes caused by missing evidence, changed instructions, approval delay, credit activity, or policy choice. This describes the tested run and period. It is not a promise that every future run will have the same exception mix.',
'The support packet should preserve the source amount and currency, due-date evidence, approval state, exception history, and owner response. If a payment date is proposed, label it as proposed. A support worker should not turn a due date into a commitment or communicate a release decision without authority.',
'A reviewer needs to see both included and excluded records. Reviewing only what entered the run can hide a stopped invoice that later becomes urgent. Reviewing only exclusions can make the ordinary control path invisible. The two populations answer different questions and should remain distinguishable.',
'Preparation can include assembling the proposal, reconciling exclusions, and routing questions. Approval, bank-detail verification, and payment release remain with authorized employees. Least privilege supports this separation because the report can be prepared without granting the ability to move money.'
]},
{slug:'ap-recurring-invoice-baseline-research',title:'Recurring AP invoice baseline research',excerpt:'How to compare recurring invoices with their own approved history without turning a pattern into automatic approval.',focus:'recurring AP invoice baselines',date:'2026-08-17',thumbnail:'ap-invoice-duplicate-signals-research',citations:[gao,nist],analysis:[
'Research question: when does a recurring invoice pattern provide useful review evidence? A baseline should describe the selected vendor, entity, service, period, source fields, and approved comparison population. Similarity is a prompt for inspection. It is not proof that the current invoice is valid, complete, or approved.',
'Define the comparison window before looking at the current invoice. A six-month history may be useful for one recurring service, while a seasonal or amended contract needs a different population. Preserve the history used and state which fields were compared: amount, period, description, order or contract reference, and approval record.',
'A change in amount can reflect scope, tax, currency, timing, a credit, or a source error. Do not create a tolerance that hides those causes. Route the specific difference to the service owner or finance reviewer and keep the original and current records together.',
'The pilot should include stable invoices and known changes. Record false alerts as well as useful alerts. A high alert count may reflect a weak baseline, but a low count may reflect a narrow comparison that never sees the real exceptions. The sample is a design test, not a vendor-performance score.',
'Recurring work needs a refresh rule. If the contract, vendor record, entity, or service period changes, the old baseline may no longer be the right evidence. The support role can flag that condition. The owner decides whether a new approved reference is needed.',
'The support lane may prepare a comparison and label a candidate outlier. It should not auto-approve a matching invoice, edit source data, or tell a supplier that the expected pattern guarantees payment. A repeated pattern reduces search effort but does not remove the approval boundary.'
]},
{slug:'ap-credit-memo-aging-research',title:'AP credit-memo aging research',excerpt:'A source-led way to distinguish old credits, missing applications, and unresolved vendor decisions.',focus:'AP credit-memo aging',date:'2026-08-17',thumbnail:'ap-credit-memo-reconciliation-research',citations:[gao,least],analysis:[
'Research question: what does the age of an AP credit memo tell a finance owner? It shows how long the credit has remained open under the chosen start event. It does not prove that the credit is valid, refundable, applicable to the oldest invoice, or ready to net against a payment.',
'Define the clock using the credit date, receipt date, or system-posted date according to the organization’s policy, and keep the selected basis visible. A credit can appear old because the source arrived late or because the related invoice is disputed. Separate those causes instead of treating age as a single risk score.',
'The evidence packet should link the credit memo, supplier statement, candidate invoices, correspondence, and any owner decision. Preserve amounts and currencies as shown. If a candidate application is only a possibility, label it that way. Do not alter the ledger or vendor balance to make an aging report tidy.',
'A two-week sample can segment credits by age band, source completeness, owner, and candidate status. The result can show where follow-up is slow or documentation is missing. It cannot establish a market norm or authorize a policy that applies to every vendor.',
'Aged credits may require procurement, AP, treasury, tax, or finance review. The support role can identify the open question and route it. It should not promise a refund, apply a credit, or tell a vendor that a balance has been accepted without documented authority.',
'Review closed credits separately from open credits. A closed status without the source decision is not enough evidence for a quality sample. Retain the disposition and the date so a later reviewer can distinguish a resolved credit from one that disappeared from the queue.'
]},
{slug:'ap-vendor-bank-callback-evidence-research',title:'Vendor bank-callback evidence research',excerpt:'How to document independent verification of payment-detail changes without relying on the requesting message.',focus:'vendor bank-callback evidence',date:'2026-08-17',thumbnail:'vendor-bank-change-control-research',citations:[cisa,gao,least],analysis:[
'Research question: what makes a vendor bank-detail callback independently useful? The record should identify the change request, the trusted contact path used for verification, the person who completed the check, the date, and the authorized decision. The requesting email cannot serve as its own independent confirmation.',
'Preserve the original message and the current approved vendor record. Compare the changed field without copying unnecessary sensitive information into extra files. If the contact path came from the request itself, stop and escalate because the verification path is not independent.',
'CISA’s phishing guidance supports caution around urgency, unusual requests, and messages that direct a recipient to act quickly. Its use here is bounded: it informs the reason for a second channel. It does not prove that a particular message is malicious or replace the organization’s fraud and vendor-change policy.',
'A dated pilot can classify requests by channel, reason, verification outcome, and owner response time. Include legitimate changes and stopped requests. Do not use the result as a fraud rate or claim that one channel is safe in all situations. The purpose is to test whether the evidence path is complete.',
'The support role can hold the change, assemble the request, and route the callback task. It should not edit bank data, approve the vendor change, or release a payment. The authorized owner records the decision and keeps the change within the approved master-data process.',
'Access should be limited because bank details and vendor records are sensitive. Remove temporary access after the tested task ends and preserve the verification decision according to retention rules. A callback log without the underlying source and owner is an incomplete control record.'
]},
{slug:'ap-ap-queue-ownership-transfer-research',title:'AP queue ownership-transfer research',excerpt:'A research model for moving an invoice exception between reviewers without losing the source, history, or decision owner.',focus:'AP queue ownership transfers',date:'2026-08-17',thumbnail:'ap-outsourced-ap-access-review-research',citations:[gao,nist,least],analysis:[
'Research question: what evidence is needed when an AP exception changes hands? Record the prior owner, new owner, transfer date, reason, current status, source packet, and next action. A reassignment should not reset the age of the underlying exception or erase the question that caused the stop.',
'Distinguish temporary coverage from a permanent scope change. An out-of-office message may explain timing but does not by itself prove approval authority. A documented delegation or owner confirmation should identify the period and the decisions included.',
'Sample ordinary transfers, urgent transfers, and transfers that cross a close or payment-run cutoff. Measure whether the new owner received the source and whether the next action remained visible. The sample describes handoff quality in the selected queue, not an ideal response time for all AP teams.',
'The support role can update status within approved permissions, link the existing record, and request a response from the documented owner. It should not create a new invoice, close the exception to clear the queue, or infer that a backup reviewer can approve every decision the primary reviewer handled.',
'A good transfer note states what is known, what is missing, and what decision is needed. It should not repeat a long history when the source packet is available, but it must preserve enough context for the receiving owner to avoid restarting the search.',
'Access reviews should include temporary coverage. When the window ends, remove stale permission and return the item to its normal authority path. A transfer is complete when ownership and evidence are clear, not merely when the queue field changes.'
]},
{slug:'ap-multi-entity-invoice-routing-research',title:'Multi-entity invoice-routing research',excerpt:'How to compare entity evidence and route invoices without silently assigning an obligation to the wrong company.',focus:'multi-entity invoice routing',date:'2026-08-17',thumbnail:'ap-invoice-coding-control-research',citations:[gao,nist,irs],analysis:[
'Research question: what can AP support establish before routing an invoice across entities? Compare the billed entity, purchase-order entity, receiving or service entity, vendor record, tax documentation where applicable, and intended approver. A familiar supplier name is not evidence that the same company owes every invoice.',
'Keep the exact source names and identifiers. Shared addresses, centralized procurement, and group vendors can be legitimate, but they do not eliminate the need to show which record supports the routing choice. If the entity field is absent, mark it absent and ask the owner rather than choosing the most common entity.',
'A two-week sample should separate single-entity invoices from cross-entity exceptions. Record the source that resolved each exception and whether the same supplier or request pattern recurred. Recurrence may indicate an intake issue or master-data question, but it does not authorize a support role to edit the source.',
'Tax documents can provide relevant fields, but Form W-9 is a source document and not tax advice. Questions about classification, withholding, intercompany treatment, or legal ownership belong with the responsible finance or tax owner. The support packet should preserve the question and document location.',
'The handoff should show what agrees, what conflicts, and which owner can decide. Do not rewrite an invoice or move it to another entity to make a queue route clean. An unresolved entity question is safer as a visible stop than as a silent correction.',
'Access should cover the records needed for comparison, with edit and approval permissions kept separate. A route is a preparation outcome until the authorized owner confirms the accounting and approval consequences.'
]},
{slug:'ap-invoice-document-retention-evidence-research',title:'AP invoice-document retention evidence research',excerpt:'What a reviewable AP packet should preserve when source documents, corrections, and owner decisions must remain traceable.',focus:'AP invoice-document retention evidence',date:'2026-08-17',thumbnail:'ap-document-retention-research',citations:[gao,nist,least],analysis:[
'Research question: which invoice records must remain together for a later reviewer to understand what happened? The answer begins with the original invoice and expands to the source message, related order or receipt, prepared comparison, exception note, owner decision, and material correction. A retention copy should preserve provenance, not just a final summary.',
'Keep original and corrected files distinguishable. A replacement invoice may be legitimate, but overwriting the first file erases the reason the record changed. Record who supplied the correction, when it arrived, and which field changed. The finance owner decides the accounting or approval effect.',
'A sample can test whether a second reviewer can reconstruct selected closed and stopped items from the approved system. Record missing sources, broken links, ambiguous filenames, and decisions stored outside the packet. These findings describe the tested population and should not be presented as proof of universal retention compliance.',
'Retention must follow the organization’s legal, tax, privacy, security, and records policy. This research does not set a retention period. It identifies the evidence a reviewer may need and the boundary around the support role’s handling of it.',
'The support lane can file records in the approved system, link related evidence, and flag a missing source. It should not create unofficial archives containing sensitive vendor or payment data, delete a record to reduce clutter, or decide that an exception no longer matters because the invoice was paid.',
'Least privilege matters after processing as well as during it. Give the role access to the records needed for its assigned lane and review that access when the lane or retention rule changes. A complete packet is useful only when the right people can inspect it under the approved policy.'
]}
];

export const aug17ResearchBatch:ResearchPost[]=seeds.map(s=>({...s,published:s.date,modified:s.modified??s.date,thumbnail:`/research-thumbnails/${s.thumbnail}.svg`,keywords:['accounts payable outsourcing','AP research','finance operations'],body:s.analysis,internalLinks:links,cta:'Use this research to define a controlled AP support lane.'}));
